msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2016-04-21 06:53+0000\n"
"PO-Revision-Date: 2023-08-03 10:57\n"
"Last-Translator: \n"
"Language-Team: Esperanto\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2023-08-03 10:16+0000\n"
"X-Generator: Launchpad (build d80dbb5bdc9110f3a64cc968928033472d5e0509)\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-Language: eo\n"
"X-Crowdin-File: /main/jammy/en_GB/nova_locale_nova-be.po\n"
"X-Crowdin-File-ID: 347\n"
"Language: eo_UY\n"

#: nova/block_device.py:102
msgid "Some fields are invalid."
msgstr ""

#: nova/block_device.py:112
msgid "Some required fields are missing"
msgstr ""

#: nova/block_device.py:128 nova/block_device.py:203
msgid "Boot index is invalid."
msgstr ""

#: nova/block_device.py:171
msgid "Unrecognized legacy format."
msgstr ""

#: nova/block_device.py:189
msgid "Invalid source_type field."
msgstr ""

#: nova/block_device.py:192
msgid "Invalid device UUID."
msgstr ""

#: nova/block_device.py:196
msgid "Missing device UUID."
msgstr ""

#: nova/block_device.py:208
msgid "Mapping image to local is not supported."
msgstr ""

#: nova/block_device.py:399
msgid "Device name empty or too long."
msgstr ""

#: nova/block_device.py:403
msgid "Device name contains spaces."
msgstr ""

#: nova/block_device.py:416
msgid "Invalid volume_size."
msgstr ""

#: nova/servicegroup/drivers/mc.py:44
msgid "memcached_servers not defined"
msgstr ""

#: nova/cache_utils.py:137
msgid "old style configuration can use only dictionary or memcached backends"
msgstr ""

#: nova/context.py:109
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: nova/crypto.py:143
msgid "failed to generate fingerprint"
msgstr ""

#: nova/crypto.py:128
#, python-format
msgid "failed to generate X509 fingerprint. Error message: %s"
msgstr ""

#: nova/exception.py:102
msgid "An unknown exception occurred."
msgstr ""

#: nova/exception.py:143
#, python-format
msgid "Failed to encrypt text: %(reason)s"
msgstr ""

#: nova/exception.py:147
#, python-format
msgid "Failed to decrypt text: %(reason)s"
msgstr ""

#: nova/exception.py:174
#, python-format
msgid "Failed to revoke certificate for %(project_id)s"
msgstr ""

#: nova/exception.py:151
msgid "Virtual Interface creation failed"
msgstr ""

#: nova/exception.py:155
msgid "Creation of virtual interface with unique mac address failed"
msgstr ""

#: nova/exception.py:187
msgid "Virtual interface plugin failed"
msgstr ""

#: nova/exception.py:191
#, python-format
msgid "Connection to glance host %(server)s failed: %(reason)s"
msgstr ""

#: nova/exception.py:196
#, python-format
msgid "Connection to cinder host failed: %(reason)s"
msgstr ""

#: nova/exception.py:166
msgid "Not authorized."
msgstr ""

#: nova/exception.py:171
msgid "User does not have admin privileges"
msgstr ""

#: nova/exception.py:175
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: nova/exception.py:214
msgid "Volume resource quota exceeded"
msgstr ""

#: nova/exception.py:182
#, python-format
msgid "Image %(image_id)s is not active."
msgstr ""

#: nova/exception.py:186
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: nova/exception.py:190
msgid "Unacceptable parameters."
msgstr ""

#: nova/exception.py:195
msgid "Block Device Mapping is Invalid."
msgstr ""

#: nova/exception.py:199
#, python-format
msgid "Block Device Mapping is Invalid: failed to get snapshot %(id)s."
msgstr ""

#: nova/exception.py:204
#, python-format
msgid "Block Device Mapping is Invalid: failed to get volume %(id)s."
msgstr ""

#: nova/exception.py:248
#, python-format
msgid "Block Device Mapping is Invalid: %(auth_method)s is unsupported."
msgstr ""

#: nova/exception.py:209
#, python-format
msgid "Block Device Mapping is Invalid: failed to get image %(id)s."
msgstr ""

#: nova/exception.py:214
msgid "Block Device Mapping is Invalid: Boot sequence for the instance and image/block device mapping combination is not valid."
msgstr ""

#: nova/exception.py:221
msgid "Block Device Mapping is Invalid: You specified more local devices than the limit allows"
msgstr ""

#: nova/exception.py:227
msgid "Ephemeral disks requested are larger than the instance type allows."
msgstr ""

#: nova/exception.py:232
msgid "Swap drive requested is larger than instance type allows."
msgstr ""

#: nova/exception.py:236
#, python-format
msgid "Block Device Mapping is Invalid: %(details)s"
msgstr ""

#: nova/exception.py:241
msgid "Block Device Mapping cannot be converted to legacy format. "
msgstr ""

#: nova/exception.py:290
#, python-format
msgid "Block Device %(id)s is not bootable."
msgstr ""

#: nova/exception.py:246
#, python-format
msgid "Attribute not supported: %(attr)s"
msgstr ""

#: nova/exception.py:302
#, python-format
msgid "Volume %(volume_id)s could not be attached. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:255
#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr ""

#: nova/exception.py:312
#, python-format
msgid "Volume %(volume_id)s did not finish being created even after we waited %(seconds)s seconds or %(attempts)s attempts. And its status is %(volume_status)s."
msgstr ""

#: nova/exception.py:318
#, python-format
msgid "Volume encryption is not supported for %(volume_type)s volume %(volume_id)s"
msgstr ""

#: nova/exception.py:266
#, python-format
msgid "Keypair data is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:270
msgid "The request is invalid."
msgstr ""

#: nova/exception.py:274
#, python-format
msgid "Invalid input received: %(reason)s"
msgstr ""

#: nova/exception.py:279
#, python-format
msgid "Invalid volume: %(reason)s"
msgstr ""

#: nova/exception.py:341
#, python-format
msgid "Invalid volume access mode: %(access_mode)s"
msgstr ""

#: nova/exception.py:287
#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr ""

#: nova/exception.py:291
#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr ""

#: nova/exception.py:296
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr ""

#: nova/exception.py:300
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr ""

#: nova/exception.py:304
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: nova/exception.py:366
#, python-format
msgid "API Version String %(version)s is of invalid format. Must be of format MajorNum.MinorNum."
msgstr ""

#: nova/exception.py:371
#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr ""

#: nova/exception.py:375
#, python-format
msgid "Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s and maximum is %(max_ver)s."
msgstr ""

#: nova/exception.py:380
#, python-format
msgid "Version of %(name) %(min_ver) %(max_ver) intersects with another versions."
msgstr ""

#: nova/exception.py:320
#, python-format
msgid "%(err)s"
msgstr ""

#: nova/exception.py:397
#, python-format
msgid "Cannot add host to aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:402
#, python-format
msgid "Cannot remove host from aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:407
#, python-format
msgid "Cannot update aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:412
#, python-format
msgid "Cannot update metadata of aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:329
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:333 nova/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr ""

#: nova/exception.py:425
#, python-format
msgid "Invalid datetime string: %(reason)s"
msgstr ""

#: nova/exception.py:429
#, python-format
msgid "An invalid 'name' value was provided. The name must be: %(reason)s"
msgstr ""

#: nova/exception.py:337
#, python-format
msgid "Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while the instance is in this state."
msgstr ""

#: nova/exception.py:342
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr ""

#: nova/exception.py:346
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr ""

#: nova/exception.py:350
#, python-format
msgid "Instance %(instance_id)s cannot be rescued: %(reason)s"
msgstr ""

#: nova/exception.py:354
#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr ""

#: nova/exception.py:358
#, python-format
msgid "Failed to suspend instance: %(reason)s"
msgstr ""

#: nova/exception.py:362
#, python-format
msgid "Failed to resume instance: %(reason)s"
msgstr ""

#: nova/exception.py:366
#, python-format
msgid "Failed to power on instance: %(reason)s"
msgstr ""

#: nova/exception.py:370
#, python-format
msgid "Failed to power off instance: %(reason)s"
msgstr ""

#: nova/exception.py:374
#, python-format
msgid "Failed to reboot instance: %(reason)s"
msgstr ""

#: nova/exception.py:378
#, python-format
msgid "Failed to terminate instance: %(reason)s"
msgstr ""

#: nova/exception.py:382
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr ""

#: nova/exception.py:386
#, python-format
msgid "Failed to launch instances: %(reason)s"
msgstr ""

#: nova/exception.py:390
msgid "Service is unavailable at this time."
msgstr ""

#: nova/exception.py:394
#, python-format
msgid "Insufficient compute resources: %(reason)s."
msgstr ""

#: nova/exception.py:398
#, python-format
msgid "Connection to the hypervisor is broken on host: %(host)s"
msgstr ""

#: nova/exception.py:402
#, python-format
msgid "Compute service of %(host)s is unavailable at this time."
msgstr ""

#: nova/exception.py:406
#, python-format
msgid "Compute service of %(host)s is still in use."
msgstr ""

#: nova/exception.py:410
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""

#: nova/exception.py:415
msgid "The supplied hypervisor type of is invalid."
msgstr ""

#: nova/exception.py:520
#, python-format
msgid "This compute node's hypervisor is older than the minimum supported version: %(version)s."
msgstr ""

#: nova/exception.py:419
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr ""

#: nova/exception.py:530
#, python-format
msgid "This service is older (v%(thisver)i) than the minimum (v%(minver)i) version of the rest of the deployment. Unable to continue."
msgstr ""

#: nova/exception.py:424
#, python-format
msgid "The supplied disk path (%(path)s) already exists, it is expected not to exist."
msgstr ""

#: nova/exception.py:429
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr ""

#: nova/exception.py:433
#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr ""

#: nova/exception.py:438
#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr ""

#: nova/exception.py:442
#, python-format
msgid "Unacceptable CPU info: %(reason)s"
msgstr ""

#: nova/exception.py:446
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr ""

#: nova/exception.py:450
#, python-format
msgid "VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""

#: nova/exception.py:456
#, python-format
msgid "vSwitch which contains the port group %(bridge)s is not associated with the desired physical adapter. Expected vSwitch is %(expected)s, but the one associated is %(actual)s."
msgstr ""

#: nova/exception.py:463
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr ""

#: nova/exception.py:579
#, python-format
msgid "Disk info file is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:583
#, python-format
msgid "Failed to read or write disk info file: %(reason)s"
msgstr ""

#: nova/exception.py:467
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:591
#, python-format
msgid "Request of image %(image_id)s got BadRequest response: %(response)s"
msgstr ""

#: nova/exception.py:471
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:475
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr ""

#: nova/exception.py:479
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: nova/exception.py:483
#, python-format
msgid "Invalid ID received %(id)s."
msgstr ""

#: nova/exception.py:487
msgid "Constraint not met."
msgstr ""

#: nova/exception.py:492
msgid "Resource could not be found."
msgstr ""

#: nova/exception.py:497
#, python-format
msgid "No agent-build associated with id %(id)s."
msgstr ""

#: nova/exception.py:501
#, python-format
msgid "Agent-build with hypervisor %(hypervisor)s os %(os)s architecture %(architecture)s exists."
msgstr ""

#: nova/exception.py:507
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: nova/exception.py:636
msgid "Undefined Block Device Mapping root: BlockDeviceMappingList contains Block Device Mappings from multiple instances."
msgstr ""

#: nova/exception.py:641
#, python-format
msgid "No Block Device Mapping with id %(id)s."
msgstr ""

#: nova/exception.py:511
#, python-format
msgid "No volume Block Device Mapping with id %(volume_id)s."
msgstr ""

#: nova/exception.py:649
#, python-format
msgid "Block Device Mapping %(volume_id)s is a multi-attach volume and is not valid for this operation."
msgstr ""

#: nova/exception.py:654
#, python-format
msgid "No volume Block Device Mapping at path: %(path)s"
msgstr ""

#: nova/exception.py:658
#, python-format
msgid "Device detach failed for %(device)s: %(reason)s)"
msgstr ""

#: nova/exception.py:662
#, python-format
msgid "Device '%(device)s' not found."
msgstr ""

#: nova/exception.py:516
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: nova/exception.py:520
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: nova/exception.py:524
#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr ""

#: nova/exception.py:528
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: nova/exception.py:532
#, python-format
msgid "Requested image %(image)s has automatic disk resize disabled."
msgstr ""

#: nova/exception.py:537
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: nova/exception.py:541
msgid "The current driver does not support preserving ephemeral partitions."
msgstr ""

#: nova/exception.py:547
#, python-format
msgid "Image %(image_id)s could not be found. The nova EC2 API assigns image ids dynamically when they are listed for the first time. Have you listed image ids since adding this image?"
msgstr ""

#: nova/exception.py:554
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:558
msgid "Cannot find SR to read/write VDI."
msgstr ""

#: nova/exception.py:713
#, python-format
msgid "Instance %(uuid)s has no mapping to a cell."
msgstr ""

#: nova/exception.py:562
#, python-format
msgid "Network %(network_id)s is duplicated."
msgstr ""

#: nova/exception.py:721
#, python-format
msgid "Failed to release IP %(address)s with MAC %(mac_address)s"
msgstr ""

#: nova/exception.py:566
#, python-format
msgid "Network %(network_id)s is still in use."
msgstr ""

#: nova/exception.py:729
#, python-format
msgid "Network set host failed for network %(network_id)s."
msgstr ""

#: nova/exception.py:570
#, python-format
msgid "%(req)s is required to create a network."
msgstr ""

#: nova/network/manager.py:1052
msgid "Maximum allowed length for 'label' is 255."
msgstr ""

#: nova/exception.py:741
#, python-format
msgid "%(key)s must be an integer."
msgstr ""

#: nova/exception.py:745
#, python-format
msgid "%(cidr)s is not a valid IP network."
msgstr ""

#: nova/exception.py:749
#, python-format
msgid "%(address)s is not a valid IP address."
msgstr ""

#: nova/exception.py:753
#, python-format
msgid "%(address)s is not within %(cidr)s."
msgstr ""

#: nova/exception.py:1189
#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr ""

#: nova/exception.py:762
#, python-format
msgid "Requested cidr (%(cidr)s) conflicts with existing cidr (%(other)s)"
msgstr ""

#: nova/exception.py:768
#, python-format
msgid "Network must be disassociated from project %(project_id)s before it can be deleted."
msgstr ""

#: nova/exception.py:574
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr ""

#: nova/exception.py:578
#, python-format
msgid "Port id %(port_id)s could not be found."
msgstr ""

#: nova/exception.py:582
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr ""

#: nova/exception.py:586
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr ""

#: nova/exception.py:590
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr ""

#: nova/exception.py:594
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr ""

#: nova/exception.py:598
msgid "No networks defined."
msgstr ""

#: nova/exception.py:602
msgid "No more available networks."
msgstr ""

#: nova/exception.py:606
#, python-format
msgid "Either network uuid %(network_uuid)s is not present or is not assigned to the project %(project_id)s."
msgstr ""

#: nova/exception.py:810
msgid "More than one possible network found. Specify network ID(s) to select which one(s) to connect to."
msgstr ""

#: nova/exception.py:616
#, python-format
msgid "Network %(network_uuid)s requires a subnet in order to boot instances on."
msgstr ""

#: nova/exception.py:820
#, python-format
msgid "It is not allowed to create an interface on external network %(network_uuid)s"
msgstr ""

#: nova/exception.py:825
#, python-format
msgid "Physical network is missing for network %(network_uuid)s"
msgstr ""

#: nova/exception.py:829
#, python-format
msgid "vhostuser_sock_path not present in vif_details for vif %(vif_id)s"
msgstr ""

#: nova/exception.py:834
#, python-format
msgid "Parameters %(missing_params)s not present in vif_details for vif %(vif_id)s. Check your Neutron configuration to validate that the macvtap parameters are correct."
msgstr ""

#: nova/exception.py:841
#, python-format
msgid "OVS configuration failed with: %(inner_exception)s."
msgstr ""

#: nova/exception.py:621
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr ""

#: nova/exception.py:625
#, python-format
msgid "Port %(port_id)s is still in use."
msgstr ""

#: nova/exception.py:629
#, python-format
msgid "Port %(port_id)s requires a FixedIP in order to be used."
msgstr ""

#: nova/exception.py:633
#, python-format
msgid "Port %(port_id)s not usable for instance %(instance)s."
msgstr ""

#: nova/exception.py:861
#, python-format
msgid "Port %(port_id)s not usable for instance %(instance)s. Value %(value)s assigned to dns_name attribute does not match instance's hostname %(hostname)s"
msgstr ""

#: nova/exception.py:637
#, python-format
msgid "No free port available for instance %(instance)s."
msgstr ""

#: nova/exception.py:871
#, python-format
msgid "Binding failed for port %(port_id)s, please check neutron logs for more information."
msgstr ""

#: nova/exception.py:876
#, python-format
msgid "Fixed IP %(address)s already exists."
msgstr ""

#: nova/exception.py:645
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr ""

#: nova/exception.py:884
#, python-format
msgid "Fixed IP not found for address %(address)s."
msgstr ""

#: nova/exception.py:888
#, python-format
msgid "Instance %(instance_uuid)s has zero fixed IPs."
msgstr ""

#: nova/exception.py:892
#, python-format
msgid "Network host %(host)s has zero fixed IPs in network %(network_id)s."
msgstr ""

#: nova/exception.py:897
#, python-format
msgid "Instance %(instance_uuid)s doesn't have fixed IP '%(ip)s'."
msgstr ""

#: nova/exception.py:666
#, python-format
msgid "Fixed IP address (%(address)s) does not exist in network (%(network_uuid)s)."
msgstr ""

#: nova/exception.py:906
#, python-format
msgid "Fixed IP associate failed for network: %(net)s."
msgstr ""

#: nova/exception.py:671
#, python-format
msgid "Fixed IP address %(address)s is already in use on instance %(instance_uuid)s."
msgstr ""

#: nova/exception.py:915
#, python-format
msgid "More than one instance is associated with fixed IP address '%(address)s'."
msgstr ""

#: nova/exception.py:681
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr ""

#: nova/exception.py:925
#, python-format
msgid "No fixed IP addresses available for network: %(net)s"
msgstr ""

#: nova/exception.py:929
msgid "Zero fixed IPs could be found."
msgstr ""

#: nova/exception.py:933
#, python-format
msgid "Floating IP %(address)s already exists."
msgstr ""

#: nova/exception.py:938
#, python-format
msgid "Floating IP not found for ID %(id)s."
msgstr ""

#: nova/exception.py:703
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr ""

#: nova/exception.py:946
#, python-format
msgid "Floating IP not found for address %(address)s."
msgstr ""

#: nova/exception.py:950
#, python-format
msgid "Floating IP not found for host %(host)s."
msgstr ""

#: nova/exception.py:954
#, python-format
msgid "Multiple floating IPs are found for address %(address)s."
msgstr ""

#: nova/exception.py:958
msgid "Floating IP pool not found."
msgstr ""

#: nova/exception.py:963
msgid "Zero floating IPs available."
msgstr ""

#: nova/exception.py:969
#, python-format
msgid "Floating IP %(address)s is associated."
msgstr ""

#: nova/exception.py:973
#, python-format
msgid "Floating IP %(address)s is not associated."
msgstr ""

#: nova/exception.py:977
msgid "Zero floating IPs exist."
msgstr ""

#: nova/exception.py:743
#, python-format
msgid "Interface %(interface)s not found."
msgstr ""

#: nova/exception.py:986
msgid "Floating IP allocate failed."
msgstr ""

#: nova/exception.py:990
#, python-format
msgid "Floating IP %(address)s association has failed."
msgstr ""

#: nova/exception.py:995
msgid "The floating IP request failed with a BadRequest"
msgstr ""

#: nova/exception.py:1000 nova/api/openstack/compute/floating_ips.py:84
#: nova/api/openstack/compute/floating_ips.py:177
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:73
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:156
msgid "Cannot disassociate auto assigned floating IP"
msgstr ""

#: nova/exception.py:753
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr ""

#: nova/exception.py:757
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: nova/exception.py:761
#, python-format
msgid "Service with host %(host)s binary %(binary)s exists."
msgstr ""

#: nova/exception.py:765
#, python-format
msgid "Service with host %(host)s topic %(topic)s exists."
msgstr ""

#: nova/exception.py:769
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: nova/exception.py:773
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr ""

#: nova/exception.py:1029
#, python-format
msgid "Compute host %(name)s needs to be created first before updating."
msgstr ""

#: nova/exception.py:777
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: nova/exception.py:781
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: nova/exception.py:785
#, python-format
msgid "Change would make usage less than 0 for the following resources: %(unders)s"
msgstr ""

#: nova/exception.py:1047
#, python-format
msgid "Wrong quota method %(method)s used on resource %(res)s"
msgstr ""

#: nova/exception.py:790
msgid "Quota could not be found"
msgstr ""

#: nova/exception.py:794
#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s"
msgstr ""

#: nova/exception.py:799
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: nova/exception.py:803
#, python-format
msgid "Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:808
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:812
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: nova/exception.py:816
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:820
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: nova/exception.py:824
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: nova/exception.py:828
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr ""

#: nova/exception.py:832
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""

#: nova/exception.py:837
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr ""

#: nova/exception.py:842
#, python-format
msgid "Security group %(security_group_name)s already exists for project %(project_id)s."
msgstr ""

#: nova/exception.py:847
#, python-format
msgid "Security group %(security_group_id)s is already associated with the instance %(instance_id)s"
msgstr ""

#: nova/exception.py:852
#, python-format
msgid "Security group %(security_group_id)s is not associated with the instance %(instance_id)s"
msgstr ""

#: nova/exception.py:857
#, python-format
msgid "Security group default rule (%rule_id)s not found."
msgstr ""

#: nova/exception.py:861
msgid "Network requires port_security_enabled and subnet associated in order to apply security groups."
msgstr ""

#: nova/exception.py:867
#, python-format
msgid "Rule already exists in group: %(rule)s"
msgstr ""

#: nova/exception.py:871
msgid "No Unique Match Found."
msgstr ""

#: nova/exception.py:876
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: nova/exception.py:880
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: nova/exception.py:1146
#, python-format
msgid "Migration %(migration_id)s not found for instance %(instance_id)s"
msgstr ""

#: nova/exception.py:1151
#, python-format
msgid "Migration %(migration_id)s state of instance %(instance_uuid)s is %(state)s. Cannot %(method)s while the migration is in this state."
msgstr ""

#: nova/exception.py:1157
#, python-format
msgid "Console log output could not be retrieved for instance %(instance_id)s. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:885
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr ""

#: nova/exception.py:889
#, python-format
msgid "Console pool with host %(host)s, console_type %(console_type)s and compute_host %(compute_host)s already exists."
msgstr ""

#: nova/exception.py:895
#, python-format
msgid "Console pool of type %(console_type)s for compute host %(compute_host)s on proxy host %(host)s not found."
msgstr ""

#: nova/exception.py:901
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr ""

#: nova/exception.py:905
#, python-format
msgid "Console for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1186
msgid "Guest does not have a console available."
msgstr ""

#: nova/exception.py:909
#, python-format
msgid "Console for instance %(instance_uuid)s in pool %(pool_id)s could not be found."
msgstr ""

#: nova/exception.py:914
#, python-format
msgid "Invalid console type %(console_type)s"
msgstr ""

#: nova/exception.py:918
#, python-format
msgid "Unavailable console type %(console_type)s."
msgstr ""

#: nova/exception.py:922
#, python-format
msgid "The console port range %(min_port)d-%(max_port)d is exhausted."
msgstr ""

#: nova/exception.py:927
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr ""

#: nova/exception.py:931
#, python-format
msgid "Flavor with name %(flavor_name)s could not be found."
msgstr ""

#: nova/exception.py:935
#, python-format
msgid "Flavor access not found for %(flavor_id)s / %(project_id)s combination."
msgstr ""

#: nova/exception.py:1221
#, python-format
msgid "Flavor %(id)s extra spec cannot be updated or created after %(retries)d retries."
msgstr ""

#: nova/exception.py:940
#, python-format
msgid "Cell %(cell_name)s doesn't exist."
msgstr ""

#: nova/exception.py:944
#, python-format
msgid "Cell with name %(name)s already exists."
msgstr ""

#: nova/exception.py:948
#, python-format
msgid "Inconsistency in cell routing: %(reason)s"
msgstr ""

#: nova/exception.py:952
#, python-format
msgid "Service API method not found: %(detail)s"
msgstr ""

#: nova/exception.py:956
msgid "Timeout waiting for response from cell"
msgstr ""

#: nova/exception.py:960
#, python-format
msgid "Cell message has reached maximum hop count: %(hop_count)s"
msgstr ""

#: nova/exception.py:964
msgid "No cells available matching scheduling criteria."
msgstr ""

#: nova/exception.py:968
msgid "Cannot update cells configuration file."
msgstr ""

#: nova/exception.py:972
#, python-format
msgid "Cell is not known for instance %(instance_uuid)s"
msgstr ""

#: nova/exception.py:976
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: nova/exception.py:980
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(extra_specs_key)s."
msgstr ""

#: nova/exception.py:985
#, python-format
msgid "Metric %(name)s could not be found on the compute host node %(host)s.%(node)s."
msgstr ""

#: nova/exception.py:990
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: nova/exception.py:998
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""

#: nova/exception.py:1003
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr ""

#: nova/exception.py:1007
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: nova/exception.py:1293
#, python-format
msgid "Instance %(instance_id)s has no tag '%(tag)s'"
msgstr ""

#: nova/exception.py:1019
msgid "Rotation param is required for backup image_type"
msgstr ""

#: nova/exception.py:1024 nova/tests/compute/test_keypairs.py:144
#, python-format
msgid "Key pair '%(key_name)s' already exists."
msgstr ""

#: nova/exception.py:1028
#, python-format
msgid "Instance %(name)s already exists."
msgstr ""

#: nova/exception.py:1032
#, python-format
msgid "Flavor with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1036
#, python-format
msgid "Flavor with ID %(flavor_id)s already exists."
msgstr ""

#: nova/exception.py:1040
#, python-format
msgid "Flavor access already exists for flavor %(flavor_id)s and project %(project_id)s combination."
msgstr ""

#: nova/exception.py:1045
#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr ""

#: nova/exception.py:1049
#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr ""

#: nova/exception.py:1331
#, python-format
msgid "Storage error: %(reason)s"
msgstr ""

#: nova/exception.py:1053
#, python-format
msgid "Migration error: %(reason)s"
msgstr ""

#: nova/exception.py:1057
#, python-format
msgid "Migration pre-check error: %(reason)s"
msgstr ""

#: nova/exception.py:1343
#, python-format
msgid "Migration select destinations error: %(reason)s"
msgstr ""

#: nova/exception.py:1061
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: nova/exception.py:1067
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: nova/exception.py:1071
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: nova/exception.py:1075
msgid "When resizing, instances must change flavor!"
msgstr ""

#: nova/exception.py:1079
#, python-format
msgid "Resize error: %(reason)s"
msgstr ""

#: nova/exception.py:1083
#, python-format
msgid "Server disk was unable to be resized because: %(reason)s"
msgstr ""

#: nova/exception.py:1087
msgid "Flavor's memory is too small for requested image."
msgstr ""

#: nova/exception.py:1377
msgid "The created instance's disk would be too small."
msgstr ""

#: nova/exception.py:1381
#, python-format
msgid "Flavor's disk is too small for requested image. Flavor disk is %(flavor_size)i bytes, image is %(image_size)i bytes."
msgstr ""

#: nova/exception.py:1386
#, python-format
msgid "Flavor's disk is smaller than the minimum size specified in image metadata. Flavor disk is %(flavor_size)i bytes, minimum size is %(image_min_disk)i bytes."
msgstr ""

#: nova/exception.py:1392
#, python-format
msgid "Volume is smaller than the minimum size specified in image metadata. Volume size is %(volume_size)i bytes, minimum size is %(image_min_disk)i bytes."
msgstr ""

#: nova/exception.py:1095
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""

#: nova/exception.py:1099
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: nova/exception.py:1406
#, python-format
msgid "Exceeded maximum number of retries. %(reason)s"
msgstr ""

#: nova/exception.py:1104
#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr ""

#: nova/exception.py:1420
#, python-format
msgid "Quota exceeded for %(overs)s: Requested %(req)s, but already used %(used)s of %(allowed)s %(overs)s"
msgstr ""

#: nova/exception.py:1425
msgid "Maximum number of floating IPs exceeded"
msgstr ""

#: nova/exception.py:1429
msgid "Maximum number of fixed IPs exceeded"
msgstr ""

#: nova/exception.py:1124
#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr ""

#: nova/exception.py:1128
msgid "Personality file limit exceeded"
msgstr ""

#: nova/exception.py:1132
msgid "Personality file path too long"
msgstr ""

#: nova/exception.py:1136
msgid "Personality file content too long"
msgstr ""

#: nova/exception.py:1140 nova/tests/compute/test_keypairs.py:155
msgid "Maximum number of key pairs exceeded"
msgstr ""

#: nova/exception.py:1145
msgid "Maximum number of security groups or rules exceeded"
msgstr ""

#: nova/exception.py:1149
msgid "Maximum number of ports exceeded"
msgstr ""

#: nova/exception.py:1153
#, python-format
msgid "Aggregate %(aggregate_id)s: action '%(action)s' caused an error: %(reason)s."
msgstr ""

#: nova/exception.py:1158
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr ""

#: nova/exception.py:1162
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr ""

#: nova/exception.py:1166
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr ""

#: nova/exception.py:1170
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:1175
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr ""

#: nova/exception.py:1179
msgid "Unable to create flavor"
msgstr ""

#: nova/exception.py:1183
#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr ""

#: nova/exception.py:1199
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: nova/exception.py:1203
#, python-format
msgid "Info cache for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1509
msgid "Invalid association."
msgstr ""

#: nova/exception.py:1216
#, python-format
msgid "Marker %(marker)s could not be found."
msgstr ""

#: nova/exception.py:1517
#, python-format
msgid "Invalid id: %(instance_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1522
#, python-format
msgid "Invalid id: %(volume_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1225
#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr ""

#: nova/exception.py:1229
#, python-format
msgid "Could not upload image %(image_id)s"
msgstr ""

#: nova/exception.py:1233
#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr ""

#: nova/exception.py:1237
#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr ""

#: nova/exception.py:1241
#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr ""

#: nova/exception.py:1245
#, python-format
msgid "Invalid value for Config Drive option: %(option)s"
msgstr ""

#: nova/exception.py:1551
#, python-format
msgid "Config drive format '%(format)s' is not supported."
msgstr ""

#: nova/exception.py:1249
#, python-format
msgid "Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr ""

#: nova/exception.py:1254
#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr ""

#: nova/exception.py:1565
#, python-format
msgid "Instance %(instance_uuid)s requires config drive, but it does not exist."
msgstr ""

#: nova/exception.py:1570
#, python-format
msgid "Failed to attach network adapter device to %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1575
#, python-format
msgid "No specific network was requested and none are available for project '%(project_id)s'."
msgstr ""

#: nova/exception.py:1580
#, python-format
msgid "Failed to detach network adapter device from %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1267
#, python-format
msgid "User data too large. User data must be no larger than %(maxsize)s bytes once base64 encoded. Your data is %(length)d bytes"
msgstr ""

#: nova/exception.py:1273
msgid "User data needs to be valid base 64."
msgstr ""

#: nova/exception.py:1595
#, python-format
msgid "Conflict updating instance %(instance_uuid)s. Expected: %(expected)s. Actual: %(actual)s"
msgstr ""

#: nova/exception.py:1600
#, python-format
msgid "Conflict updating instance %(instance_uuid)s, but we were unable to determine the cause"
msgstr ""

#: nova/exception.py:1286
#, python-format
msgid "Action for request_id %(request_id)s on instance %(instance_uuid)s not found"
msgstr ""

#: nova/exception.py:1291
#, python-format
msgid "Event %(event)s not found for action id %(action_id)s"
msgstr ""

#: nova/exception.py:1300
#, python-format
msgid "The CA file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1304
#, python-format
msgid "The CRL file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1308
msgid "Instance recreate is not supported."
msgstr ""

#: nova/exception.py:1317
#, python-format
msgid "%(binary)s attempted direct database access which is not allowed by policy"
msgstr ""

#: nova/exception.py:1322
#, python-format
msgid "Virtualization type '%(virt)s' is not supported by this compute driver"
msgstr ""

#: nova/exception.py:1327
#, python-format
msgid "Requested hardware '%(model)s' is not supported by the '%(virt)s' virt driver"
msgstr ""

#: nova/exception.py:1332
#, python-format
msgid "Invalid Base 64 data for file %(path)s"
msgstr ""

#: nova/exception.py:1336
#, python-format
msgid "Build of instance %(instance_uuid)s aborted: %(reason)s"
msgstr ""

#: nova/exception.py:1340
#, python-format
msgid "Build of instance %(instance_uuid)s was re-scheduled: %(reason)s"
msgstr ""

#: nova/exception.py:1345
#, python-format
msgid "Shadow table with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1350
#, python-format
msgid "Instance rollback performed due to: %s"
msgstr ""

#: nova/exception.py:1360
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""

#: nova/exception.py:1368
#, python-format
msgid "Object action %(action)s failed because: %(reason)s"
msgstr ""

#: nova/exception.py:1372
#, python-format
msgid "Core API extensions are missing: %(missing_apis)s"
msgstr ""

#: nova/exception.py:1376
#, python-format
msgid "Error during following call to agent: %(method)s"
msgstr ""

#: nova/exception.py:1380
#, python-format
msgid "Unable to contact guest agent. The following call timed out: %(method)s"
msgstr ""

#: nova/exception.py:1385
#, python-format
msgid "Agent does not support the call: %(method)s"
msgstr ""

#: nova/exception.py:1389
#, python-format
msgid "Instance group %(group_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1393
#, python-format
msgid "Instance group %(group_uuid)s already exists."
msgstr ""

#: nova/exception.py:1402
#, python-format
msgid "Instance group %(group_uuid)s has no member with id %(instance_id)s."
msgstr ""

#: nova/exception.py:1407
#, python-format
msgid "Instance group %(group_uuid)s has no policy %(policy)s."
msgstr ""

#: nova/exception.py:1715
#, python-format
msgid "%(field)s should not be part of the updates."
msgstr ""

#: nova/exception.py:1411
#, python-format
msgid "Number of retries to plugin (%(num_retries)d) exceeded."
msgstr ""

#: nova/exception.py:1415
#, python-format
msgid "There was an error with the download module %(module)s. %(reason)s"
msgstr ""

#: nova/exception.py:1420
#, python-format
msgid "The metadata for this location will not work with this module %(module)s.  %(reason)s."
msgstr ""

#: nova/exception.py:1425
#, python-format
msgid "The method %(method_name)s is not implemented."
msgstr ""

#: nova/exception.py:1429
#, python-format
msgid "The module %(module)s is misconfigured: %(reason)s."
msgstr ""

#: nova/exception.py:1741
#, python-format
msgid "Signature verification for the image failed: %(reason)s."
msgstr ""

#: nova/exception.py:1433
#, python-format
msgid "Error when creating resource monitor: %(monitor)s"
msgstr ""

#: nova/exception.py:1437
#, python-format
msgid "The PCI address %(address)s has an incorrect format."
msgstr ""

#: nova/exception.py:1754
#, python-format
msgid "Invalid PCI Whitelist: The PCI address %(address)s has an invalid %(field)s."
msgstr ""

#: nova/exception.py:1759
msgid "Invalid PCI Whitelist: The PCI whitelist can specify devname or address, but not both"
msgstr ""

#: nova/exception.py:1441
#, python-format
msgid "PCI device %(id)s not found"
msgstr ""

#: nova/exception.py:1445
#, python-format
msgid "PCI Device %(node_id)s:%(address)s not found."
msgstr ""

#: nova/exception.py:1449
#, python-format
msgid "PCI device %(compute_node_id)s:%(address)s is %(status)s instead of %(hopestatus)s"
msgstr ""

#: nova/exception.py:1779
#, python-format
msgid "Not all Virtual Functions of PF %(compute_node_id)s:%(address)s are free."
msgstr ""

#: nova/exception.py:1785
#, python-format
msgid "Physical Function %(compute_node_id)s:%(address)s, related to VF %(compute_node_id)s:%(vf_address)s is %(status)s instead of %(hopestatus)s"
msgstr ""

#: nova/exception.py:1455
#, python-format
msgid "PCI device %(compute_node_id)s:%(address)s is owned by %(owner)s instead of %(hopeowner)s"
msgstr ""

#: nova/exception.py:1798
#, python-format
msgid "PCI device request %(requests)s failed"
msgstr ""

#: nova/exception.py:1466
#, python-format
msgid "Attempt to consume PCI device %(compute_node_id)s:%(address)s from empty pool"
msgstr ""

#: nova/exception.py:1472
#, python-format
msgid "Invalid PCI alias definition: %(reason)s"
msgstr ""

#: nova/exception.py:1476
#, python-format
msgid "PCI alias %(alias)s is not defined"
msgstr ""

#: nova/exception.py:1481
#, python-format
msgid "Not enough parameters: %(reason)s"
msgstr ""

#: nova/exception.py:1486
#, python-format
msgid "Invalid PCI devices Whitelist config %(reason)s"
msgstr ""

#: nova/exception.py:1500
#, python-format
msgid "Failed to prepare PCI device %(id)s for instance %(instance_uuid)s: %(reason)s"
msgstr ""

#: nova/exception.py:1505
#, python-format
msgid "Failed to detach PCI device %(dev)s: %(reason)s"
msgstr ""

#: nova/exception.py:1509
#, python-format
msgid "%(type)s hypervisor does not support PCI devices"
msgstr ""

#: nova/exception.py:1513
#, python-format
msgid "Key manager error: %(reason)s"
msgstr ""

#: nova/exception.py:1850
#, python-format
msgid "Failed to remove volume(s): (%(reason)s)"
msgstr ""

#: nova/exception.py:1517
#, python-format
msgid "Provided video model (%(model)s) is not supported."
msgstr ""

#: nova/exception.py:1521
#, python-format
msgid "The provided RNG device path: (%(path)s) is not present on the host."
msgstr ""

#: nova/exception.py:1526
#, python-format
msgid "The requested amount of video memory %(req_vram)d is higher than the maximum allowed by flavor %(max_vram)d."
msgstr ""

#: nova/exception.py:1531
#, python-format
msgid "Provided watchdog action (%(action)s) is not supported."
msgstr ""

#: nova/exception.py:1872
msgid "Live migration of instances with config drives is not supported in libvirt unless libvirt instance path and drive data is shared across compute nodes."
msgstr ""

#: nova/exception.py:1878
msgid "Live migration with API v2.25 requires all the Mitaka upgrade to be complete before it is available."
msgstr ""

#: nova/exception.py:1883
#, python-format
msgid "No live migration URI configured and no default available for \"%(virt_type)s\" hypervisor virtualization type."
msgstr ""

#: nova/exception.py:1888
#, python-format
msgid "Error during unshelve instance %(instance_id)s: %(reason)s"
msgstr ""

#: nova/exception.py:1892
#, python-format
msgid "Image vCPU limits %(sockets)d:%(cores)d:%(threads)d exceeds permitted %(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1897
#, python-format
msgid "Image vCPU topology %(sockets)d:%(cores)d:%(threads)d exceeds permitted %(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1902
#, python-format
msgid "Requested vCPU limits %(sockets)d:%(cores)d:%(threads)d are impossible to satisfy for vcpus count %(vcpus)d"
msgstr ""

#: nova/exception.py:1907
#, python-format
msgid "Architecture name '%(arch)s' is not recognised"
msgstr ""

#: nova/exception.py:1911
msgid "CPU and memory allocation must be provided for all NUMA nodes"
msgstr ""

#: nova/exception.py:1916
#, python-format
msgid "Image property '%(name)s' is not permitted to override NUMA configuration set against the flavor"
msgstr ""

#: nova/exception.py:1921
msgid "Asymmetric NUMA topologies require explicit assignment of CPUs and memory to nodes in image or flavor"
msgstr ""

#: nova/exception.py:1926
#, python-format
msgid "CPU number %(cpunum)d is larger than max %(cpumax)d"
msgstr ""

#: nova/exception.py:1930
#, python-format
msgid "CPU number %(cpunum)d is assigned to two nodes"
msgstr ""

#: nova/exception.py:1934
#, python-format
msgid "CPU number %(cpuset)s is not assigned to any node"
msgstr ""

#: nova/exception.py:1938
#, python-format
msgid "%(memsize)d MB of memory assigned, but expected %(memtotal)d MB"
msgstr ""

#: nova/exception.py:1943
#, python-format
msgid "Invalid characters in hostname '%(hostname)s'"
msgstr ""

#: nova/exception.py:1947
#, python-format
msgid "Instance %(instance_uuid)s does not specify a NUMA topology"
msgstr ""

#: nova/exception.py:1951
#, python-format
msgid "Instance %(instance_uuid)s does not specify a migration context."
msgstr ""

#: nova/exception.py:1956
#, python-format
msgid "Not able to acquire a free port for %(host)s"
msgstr ""

#: nova/exception.py:1960
#, python-format
msgid "Not able to bind %(host)s:%(port)d, %(error)s"
msgstr ""

#: nova/exception.py:1964
#, python-format
msgid "Number of serial ports '%(num_ports)s' specified in '%(property)s' isn't valid."
msgstr ""

#: nova/exception.py:1969
msgid "Forbidden to exceed flavor value of number of serial ports passed in image meta."
msgstr ""

#: nova/exception.py:1974
#, python-format
msgid "Maximum number of serial port exceeds %(allowed)d for %(virt_type)s"
msgstr ""

#: nova/exception.py:1979
#, python-format
msgid "Image's config drive option '%(config_drive)s' is invalid"
msgstr ""

#: nova/exception.py:1983
#, python-format
msgid "Hypervisor virtualization type '%(hv_type)s' is not recognised"
msgstr ""

#: nova/exception.py:1988
#, python-format
msgid "Virtual machine mode '%(vmmode)s' is not recognised"
msgstr ""

#: nova/exception.py:1992
#, python-format
msgid "The token '%(token)s' is invalid or has expired"
msgstr ""

#: nova/console/websocketproxy.py:75
msgid "Invalid Connection Info"
msgstr ""

#: nova/exception.py:2000
#, python-format
msgid "Quiescing is not supported in instance %(instance_id)s"
msgstr ""

#: nova/exception.py:2004
msgid "QEMU guest agent is not enabled"
msgstr ""

#: nova/exception.py:2008
msgid "Set admin password is not supported"
msgstr ""

#: nova/exception.py:2012
#, python-format
msgid "Invalid memory page size '%(pagesize)s'"
msgstr ""

#: nova/exception.py:2016
#, python-format
msgid "Page size %(pagesize)s forbidden against '%(against)s'"
msgstr ""

#: nova/exception.py:2020
#, python-format
msgid "Page size %(pagesize)s is not supported by the host."
msgstr ""

#: nova/exception.py:2024
#, python-format
msgid "CPU pinning is not supported by the host: %(reason)s"
msgstr ""

#: nova/exception.py:2029
#, python-format
msgid "Cannot pin/unpin cpus %(requested)s from the following pinned set %(pinned)s"
msgstr ""

#: nova/exception.py:2034
#, python-format
msgid "CPU set to pin/unpin %(requested)s must be a subset of known CPU set %(cpuset)s"
msgstr ""

#: nova/exception.py:2039
msgid "Image property 'hw_cpu_policy' is not permitted to override CPU pinning policy set against the flavor"
msgstr ""

#: nova/exception.py:2044
msgid "Image property 'hw_cpu_thread_policy' is not permitted to override CPU thread pinning policy set against the flavor"
msgstr ""

#: nova/exception.py:2049
#, python-format
msgid "ServerGroup policy is not supported: %(reason)s"
msgstr ""

#: nova/exception.py:2053
#, python-format
msgid "Cell %(uuid)s has no mapping."
msgstr ""

#: nova/exception.py:2057
msgid "Host does not support guests with NUMA topology set"
msgstr ""

#: nova/exception.py:2061
msgid "Host does not support guests with custom memory page sizes"
msgstr ""

#: nova/exception.py:2065
#, python-format
msgid "%(typename)s in %(fieldname)s is not an instance of Enum"
msgstr ""

#: nova/exception.py:2069
#, python-format
msgid "%(fieldname)s missing field type"
msgstr ""

#: nova/exception.py:2073
#, python-format
msgid "Invalid image format '%(format)s'"
msgstr ""

#: nova/exception.py:2077
#, python-format
msgid "Image model '%(image)s' is not supported"
msgstr ""

#: nova/exception.py:2081
#, python-format
msgid "Host '%(name)s' is not mapped to any cell"
msgstr ""

#: nova/exception.py:2085
msgid "Cannot set realtime policy in a non dedicated cpu pinning policy"
msgstr ""

#: nova/exception.py:2090
msgid "Cannot set cpu thread pinning policy in a non dedicated cpu pinning policy"
msgstr ""

#: nova/exception.py:2095
#, python-format
msgid "RequestSpec not found for instance %(instance_uuid)s"
msgstr ""

#: nova/exception.py:2099
msgid "UEFI is not supported"
msgstr ""

#: nova/exception.py:2103
msgid "Triggering crash dump is not supported"
msgstr ""

#: nova/exception.py:2107
msgid "Requested CPU control policy not supported by host"
msgstr ""

#: nova/exception.py:2111
msgid "Realtime policy not supported by hypervisor"
msgstr ""

#: nova/exception.py:2115
msgid "Realtime policy needs vCPU(s) mask configured with at least 1 RT vCPU and 1 ordinary vCPU. See hw:cpu_realtime_mask or hw_cpu_realtime_mask"
msgstr ""

#: nova/exception.py:2121
#, python-format
msgid "No configuration information found for operating system %(os_name)s"
msgstr ""

#: nova/exception.py:2126
#, python-format
msgid "BuildRequest not found for instance %(uuid)s"
msgstr ""

#: nova/exception.py:2130
#, python-format
msgid "Attaching interfaces is not supported for instance %(instance)s."
msgstr ""

#: nova/hooks.py:80
msgid "Wrong type of hook method. Only 'pre' and 'post' type allowed"
msgstr ""

#: nova/rpc.py:317
#, python-format
msgid "%(event_type)s is not a versioned notification and not whitelisted. See ./doc/source/notification.rst"
msgstr ""

#: nova/service.py:338
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: nova/service.py:423
msgid "serve() can only be called once"
msgstr ""

#: nova/signature_utils.py:108
#, python-format
msgid "Invalid signature key type: %s"
msgstr ""

#: nova/signature_utils.py:202
#, python-format
msgid "Required image properties for signature verification do not exist. Cannot verify signature. Missing property: %s"
msgstr ""

#: nova/signature_utils.py:222
msgid "Error occurred while creating the verifier"
msgstr ""

#: nova/signature_utils.py:236
msgid "The signature data was not properly encoded using base64"
msgstr ""

#: nova/signature_utils.py:251
#, python-format
msgid "Invalid signature hash method: %s"
msgstr ""

#: nova/signature_utils.py:275
#, python-format
msgid "Invalid public key type for signature key type: %s"
msgstr ""

#: nova/signature_utils.py:305
#, python-format
msgid "Unable to retrieve certificate with ID: %s"
msgstr ""

#: nova/signature_utils.py:310
#, python-format
msgid "Invalid certificate format: %s"
msgstr ""

#: nova/signature_utils.py:337
#, python-format
msgid "Certificate is not valid before: %s UTC"
msgstr ""

#: nova/signature_utils.py:341
#, python-format
msgid "Certificate is not valid after: %s UTC"
msgstr ""

#: nova/openstack/common/processutils.py:154
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: nova/utils.py:270
#, python-format
msgid "%(desc)r\n"
"command: %(cmd)r\n"
"exit code: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"
msgstr ""

#: nova/utils.py:279
#, python-format
msgid "%r failed. Not Retrying."
msgstr ""

#: nova/openstack/common/processutils.py:199
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: nova/utils.py:388
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: nova/utils.py:391
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: nova/utils.py:457
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: nova/utils.py:990
msgid "The input is not a string or unicode"
msgstr ""

#: nova/utils.py:966
#, python-format
msgid "%s is not a string or unicode"
msgstr ""

#: nova/utils.py:970
#, python-format
msgid "%(name)s has a minimum character requirement of %(min_length)s."
msgstr ""

#: nova/utils.py:975
#, python-format
msgid "%(name)s has more than %(max_length)s characters."
msgstr ""

#: nova/utils.py:985
#, python-format
msgid "%(value_name)s must be an integer"
msgstr ""

#: nova/utils.py:991
#, python-format
msgid "%(value_name)s must be >= %(min_value)d"
msgstr ""

#: nova/utils.py:997
#, python-format
msgid "%(value_name)s must be <= %(max_value)d"
msgstr ""

#: nova/wsgi.py:84
msgid "The backlog must be more than 0"
msgstr ""

#: nova/wsgi.py:152 nova/openstack/common/sslutils.py:50
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: nova/wsgi.py:156 nova/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: nova/wsgi.py:160 nova/openstack/common/sslutils.py:56
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: nova/wsgi.py:164 nova/openstack/common/sslutils.py:59
msgid "When running server in SSL mode, you must specify both a cert_file and key_file option value in your configuration file"
msgstr ""

#: nova/wsgi.py:311
msgid "You must implement __call__"
msgstr ""

#: nova/api/auth.py:132
msgid "Invalid service catalog json."
msgstr ""

#: nova/api/ec2/ec2utils.py:252
#, python-format
msgid "Unacceptable attach status:%s for ec2 API."
msgstr ""

#: nova/api/ec2/ec2utils.py:255
msgid "Request must include either Timestamp or Expires, but cannot contain both"
msgstr ""

#: nova/api/metadata/handler.py:136 nova/api/metadata/handler.py:192
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: nova/api/metadata/handler.py:154
msgid "X-Instance-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:188
msgid "X-Instance-ID-Signature header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:156
msgid "X-Tenant-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:158
msgid "Multiple X-Instance-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:160
msgid "Multiple X-Tenant-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:267
msgid "X-Forwarded-For is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:271
msgid "X-Metadata-Provider is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:183
msgid "Invalid proxy request signature."
msgstr ""

#: nova/api/sizelimit.py:53 nova/api/sizelimit.py:62 nova/api/sizelimit.py:76
#: nova/api/metadata/password.py:62
msgid "Request is too large."
msgstr ""

#: nova/api/openstack/__init__.py:190
msgid "Must specify an ExtensionManager class"
msgstr ""

#: nova/api/openstack/api_version_request.py:151
#, python-format
msgid "'%(other)s' should be an instance of '%(cls)s'"
msgstr ""

#: nova/api/openstack/common.py:299
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: nova/api/openstack/common.py:314
msgid "Image metadata limit exceeded"
msgstr ""

#: nova/api/openstack/common.py:322
msgid "Image metadata key cannot be blank"
msgstr ""

#: nova/api/openstack/common.py:325
msgid "Image metadata key too long"
msgstr ""

#: nova/api/openstack/common.py:328
msgid "Invalid image metadata"
msgstr ""

#: nova/api/openstack/common.py:372
#, python-format
msgid "Cannot '%(action)s' instance %(server_id)s while it is in %(attr)s %(state)s"
msgstr ""

#: nova/api/openstack/common.py:378
#, python-format
msgid "Instance %(server_id)s is in an invalid state for '%(action)s'"
msgstr ""

#: nova/api/openstack/common.py:479
msgid "Instance snapshots are not permitted at this time."
msgstr ""

#: nova/api/openstack/common.py:534
msgid "The requested functionality is not supported."
msgstr ""

#: nova/api/openstack/extensions.py:495
#, python-format
msgid "Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.\n"
"%s"
msgstr ""

#: nova/api/openstack/wsgi.py:228 nova/api/openstack/wsgi.py:644
msgid "cannot understand JSON"
msgstr ""

#: nova/api/openstack/wsgi.py:649
msgid "too many body keys"
msgstr ""

#: nova/api/openstack/wsgi.py:957
msgid "Unsupported Content-Type"
msgstr ""

#: nova/api/openstack/wsgi.py:930
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:933 nova/api/openstack/wsgi.py:960
#: nova/api/openstack/compute/server_metadata.py:57
#: nova/api/openstack/compute/server_metadata.py:75
#: nova/api/openstack/compute/server_metadata.py:100
#: nova/api/openstack/compute/server_metadata.py:126
#: nova/api/openstack/compute/contrib/evacuate.py:45
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:58
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:73
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:95
msgid "Malformed request body"
msgstr ""

#: nova/api/openstack/wsgi.py:692
#, python-format
msgid "Action: '%(action)s', calling method: %(meth)s, body: %(body)s"
msgstr ""

#: nova/api/openstack/wsgi.py:969
#, python-format
msgid "Malformed request URL: URL's project_id '%(project_id)s' doesn't match Context's project_id '%(context_project_id)s'"
msgstr ""

#: nova/api/openstack/compute/servers.py:1271
#: nova/api/openstack/compute/plugins/v3/admin_password.py:56
msgid "Unable to set password on instance"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:191
#: nova/api/openstack/compute/contrib/aggregates.py:195
#: nova/api/openstack/compute/plugins/v3/aggregates.py:189
#: nova/api/openstack/compute/plugins/v3/aggregates.py:193
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/attach_interfaces.py:81
#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:80
#, python-format
msgid "Instance %(instance)s does not have a port with id %(port)s"
msgstr ""

#: nova/api/openstack/compute/attach_interfaces.py:108
#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:105
msgid "Must not input both network_id and port_id"
msgstr ""

#: nova/api/openstack/compute/attach_interfaces.py:111
#: nova/api/openstack/compute/legacy_v2/contrib/attach_interfaces.py:108
msgid "Must input network_id when request IP address"
msgstr ""

#: nova/api/openstack/compute/baremetal_nodes.py:67
#: nova/api/openstack/compute/legacy_v2/contrib/baremetal_nodes.py:65
#, python-format
msgid "Command Not supported. Please use Ironic command %(cmd)s to perform this action."
msgstr ""

#: nova/api/openstack/compute/baremetal_nodes.py:113
#: nova/api/openstack/compute/legacy_v2/contrib/baremetal_nodes.py:119
#, python-format
msgid "Node %s could not be found."
msgstr ""

#: nova/api/openstack/compute/servers.py:881
msgid "Using different block_device_mapping syntaxes is not allowed in the same request."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/cells.py:187
#, python-format
msgid "Cell %s doesn't exist."
msgstr ""

#: nova/api/openstack/compute/contrib/certificates.py:59
#: nova/api/openstack/compute/plugins/v3/certificates.py:49
msgid "Only root certificate can be retrieved."
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe.py:150
msgid "Unable to claim IP for VPN instances, ensure it isn't running, and try again in a few minutes"
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe_update.py:40
#, python-format
msgid "Unknown action %s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:40
msgid "token not provided"
msgstr ""

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:40
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:45
msgid "Token not found"
msgstr ""

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:46
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:51
msgid "The requested console type details are not accessible"
msgstr ""

#: nova/api/openstack/compute/contrib/disk_config.py:42
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:61
#: nova/api/openstack/compute/plugins/v3/evacuate.py:67
msgid "admin password can't be changed on existing disk"
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:71
#: nova/api/openstack/compute/plugins/v3/evacuate.py:77
#, python-format
msgid "Compute host %s not found."
msgstr ""

#: nova/api/openstack/compute/evacuate.py:108
#: nova/api/openstack/compute/legacy_v2/contrib/evacuate.py:93
msgid "The target host can't be the same one."
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:39
#, python-format
msgid "Fixed IP %s has been deleted"
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:72
#, python-format
msgid "Fixed IP %s not found"
msgstr ""

#: nova/api/openstack/compute/fixed_ips.py:104
#, python-format
msgid "Fixed IP %s not valid"
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:99
#: nova/api/openstack/compute/plugins/v3/flavor_access.py:61
msgid "Access list not available for public flavors."
msgstr ""

#: nova/api/openstack/compute/flavor_access.py:112
msgid "Can not add access to a public flavor."
msgstr ""

#: nova/api/openstack/compute/flavor_manage.py:89
#: nova/api/openstack/compute/legacy_v2/contrib/flavormanage.py:92
msgid "Not all flavors have been migrated to the API database"
msgstr ""

#: nova/api/openstack/compute/flavors.py:107
#: nova/api/openstack/compute/plugins/v3/flavors.py:70
#, python-format
msgid "Invalid is_public filter [%s]"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/flavors.py:94
#, python-format
msgid "Invalid min_ram filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:138
#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr ""

#: nova/api/openstack/common.py:259 nova/api/openstack/compute/flavors.py:146
#: nova/api/openstack/compute/servers.py:604
#: nova/api/openstack/compute/plugins/v3/flavors.py:110
#: nova/api/openstack/compute/plugins/v3/servers.py:281
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:82
#: nova/api/openstack/compute/server_metadata.py:79
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:92
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:84
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:77
msgid "Request body and URI mismatch"
msgstr ""

#: nova/api/openstack/compute/flavors_extraspecs.py:112
#: nova/api/openstack/compute/flavors_extraspecs.py:133
#: nova/api/openstack/compute/legacy_v2/contrib/flavorextraspecs.py:124
#: nova/api/openstack/compute/legacy_v2/contrib/flavorextraspecs.py:142
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(key)s."
msgstr ""

#: nova/api/openstack/compute/floating_ip_dns.py:122
msgid "you can not pass project if the scope is private"
msgstr ""

#: nova/api/openstack/compute/floating_ip_dns.py:125
msgid "you can not pass av_zone if the scope is public"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:222
msgid "DNS entries not found."
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:105
#: nova/api/openstack/compute/floating_ips.py:162
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:93
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:144
#, python-format
msgid "Floating IP not found for ID %s"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:135
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:119
#, python-format
msgid "No more floating IPs in pool %s."
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:137
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:121
msgid "No more floating IPs available."
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:141
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:125
#, python-format
msgid "IP allocation over quota in pool %s."
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:143
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:127
msgid "IP allocation over quota."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:225
msgid "No nw_info cache associated with instance"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:209
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:194
msgid "No fixed IPs associated to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:241
msgid "Specified fixed address not assigned to instance"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:227
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:213
#, python-format
msgid "Unable to associate floating IP %(address)s to any fixed IPs for instance %(id)s. Instance has no fixed IPv4 addresses to associate."
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:242
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:228
msgid "floating IP is already associated"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:245
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:231
msgid "l3driver call to add floating IP failed"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:250
#: nova/api/openstack/compute/floating_ips.py:280
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:234
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:269
msgid "floating IP not found"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:255
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:239
#, python-format
msgid "Unable to associate floating IP %(address)s to fixed IP %(fixed_address)s for instance %(id)s. Error: %(error)s"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:295
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:284
msgid "Floating IP is not associated"
msgstr ""

#: nova/api/openstack/compute/floating_ips.py:299
#: nova/api/openstack/compute/legacy_v2/contrib/floating_ips.py:288
#, python-format
msgid "Floating IP %(address)s is not associated with instance %(id)s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:120
#: nova/api/openstack/compute/contrib/services.py:173
#: nova/api/openstack/compute/plugins/v3/services.py:124
msgid "Unknown action"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:148
#: nova/cmd/manage.py:413
#, python-format
msgid "/%s should be specified as single address(es) not in cidr format"
msgstr ""

#: nova/api/openstack/compute/contrib/fping.py:52
msgid "fping utility is not found."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:193
#: nova/api/openstack/compute/contrib/hypervisors.py:205
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:93
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:105
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:140
#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:229
#: nova/api/openstack/compute/contrib/hypervisors.py:239
#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:35
#: nova/api/openstack/compute/images.py:141
#: nova/api/openstack/compute/images.py:157
msgid "Image not found."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:117
msgid "Invalid metadata key"
msgstr ""

#: nova/api/openstack/compute/images.py:162
msgid "You are not allowed to delete the image."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/instance_actions.py:73
#, python-format
msgid "Action %s not found"
msgstr ""

#: nova/api/openstack/compute/contrib/instance_usage_audit_log.py:56
#, python-format
msgid "Invalid timestamp for date %s"
msgstr ""

#: nova/api/openstack/compute/ips.py:90
#: nova/api/openstack/compute/plugins/v3/ips.py:60
msgid "Instance is not a member of specified network"
msgstr ""

#: nova/api/openstack/compute/contrib/keypairs.py:104
#: nova/api/openstack/compute/plugins/v3/keypairs.py:88
msgid "Quota exceeded, too many key pairs."
msgstr ""

#: nova/api/ec2/cloud.py:1279 nova/api/openstack/compute/servers.py:919
#: nova/api/openstack/compute/plugins/v3/multiple_create.py:64
msgid "min_count must be <= max_count"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:40
#: nova/api/openstack/compute/contrib/networks_associate.py:56
#: nova/api/openstack/compute/contrib/networks_associate.py:74
#: nova/api/openstack/compute/contrib/os_networks.py:78
#: nova/api/openstack/compute/contrib/os_networks.py:93
#: nova/api/openstack/compute/contrib/os_networks.py:104
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:110
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:135
msgid "Network not found"
msgstr ""

#: nova/api/openstack/compute/quota_sets.py:53
#, python-format
msgid "Quota limit %(limit)s for %(resource)s must be -1 or greater."
msgstr ""

#: nova/api/openstack/compute/quota_sets.py:62
#: nova/api/openstack/compute/legacy_v2/contrib/quotas.py:85
#, python-format
msgid "Quota limit %(limit)s for %(resource)s must be greater than or equal to already used and reserved %(minimum)s."
msgstr ""

#: nova/api/openstack/compute/quota_sets.py:68
#: nova/api/openstack/compute/legacy_v2/contrib/quotas.py:91
#, python-format
msgid "Quota limit %(limit)s for %(resource)s must be less than or equal to %(maximum)s."
msgstr ""

#: nova/api/openstack/compute/rescue.py:49
#: nova/api/openstack/compute/legacy_v2/contrib/rescue.py:43
msgid "Invalid rescue_image_ref provided."
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:127
#: nova/api/openstack/compute/contrib/security_groups.py:371
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:131
msgid "This default rule already exists."
msgstr ""

#: nova/api/openstack/compute/security_groups.py:110
#: nova/api/openstack/compute/legacy_v2/contrib/security_groups.py:134
msgid "The request body can't be empty"
msgstr ""

#: nova/api/openstack/compute/security_groups.py:114
#: nova/api/openstack/compute/legacy_v2/contrib/security_groups.py:138
#, python-format
msgid "Missing parameter %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:379
#, python-format
msgid "Bad prefix for network in cidr %s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:216
#: nova/api/openstack/compute/contrib/floating_ips.py:280
#: nova/api/openstack/compute/contrib/security_groups.py:457
msgid "Missing parameter dict"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:460
msgid "Security group not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:464
msgid "Security group name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:130
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:103
msgid "No instances found for any event"
msgstr ""

#: nova/api/openstack/compute/server_groups.py:147
#: nova/api/openstack/compute/legacy_v2/contrib/server_groups.py:203
msgid "Quota exceeded, too many server groups."
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:37
#: nova/api/openstack/compute/server_metadata.py:122
#: nova/api/openstack/compute/server_metadata.py:174
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:41
msgid "Server does not exist"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:154
#: nova/api/openstack/compute/server_metadata.py:165
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:141
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:153
msgid "Metadata item was not found"
msgstr ""

#: nova/api/openstack/compute/server_migrations.py:120
#, python-format
msgid "In-progress live migration %(id)s is not found for server %(uuid)s."
msgstr ""

#: nova/api/openstack/compute/server_migrations.py:125
#, python-format
msgid "Migration %(id)s for server %(uuid)s is not live-migration."
msgstr ""

#: nova/api/openstack/compute/server_migrations.py:132
#, python-format
msgid "Live migration %(id)s for server %(uuid)s is not in progress."
msgstr ""

#: nova/api/openstack/compute/server_tags.py:51
#, python-format
msgid "Server %(server_id)s has no tag '%(tag)s'"
msgstr ""

#: nova/api/openstack/compute/server_tags.py:78
#, python-format
msgid "Tag '%(tag)s' is invalid. It must be a string without characters '/' and ','. Validation error message: %(err)s"
msgstr ""

#: nova/api/openstack/compute/server_tags.py:89
#, python-format
msgid "The number of tags exceeded the per-server limit %d"
msgstr ""

#: nova/api/openstack/compute/server_tags.py:94
#, python-format
msgid "Tag '%(tag)s' is too long. Maximum length of a tag is %(length)d"
msgstr ""

#: nova/api/openstack/compute/server_tags.py:129
#, python-format
msgid "Tags '%s' are invalid. Each tag must be a string without characters '/' and ','."
msgstr ""

#: nova/api/openstack/compute/server_tags.py:135
#, python-format
msgid "The number of tags exceeded the per-server limit %(max)d. The number of tags in request is %(count)d."
msgstr ""

#: nova/api/openstack/compute/server_tags.py:144
#, python-format
msgid "Tags %(tags)s are too long. Maximum length of a tag is %(length)d"
msgstr ""

#: nova/api/openstack/compute/servers.py:552
#: nova/api/openstack/compute/contrib/cells.py:423
#: nova/api/openstack/compute/plugins/v3/cells.py:331
msgid "Invalid changes-since value"
msgstr ""

#: nova/api/openstack/compute/servers.py:571
#: nova/api/openstack/compute/plugins/v3/servers.py:235
msgid "Only administrators may list deleted instances"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:343
msgid "Unknown argument: port"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:351
#, python-format
msgid "Specified Fixed IP '%(addr)s' cannot be used with port '%(port)s': port already has a Fixed IP allocated."
msgstr ""

#: nova/api/openstack/compute/servers.py:691
#: nova/api/openstack/compute/plugins/v3/servers.py:362
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:715
#: nova/api/openstack/compute/plugins/v3/servers.py:377
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr ""

#: nova/api/openstack/compute/servers.py:721
#: nova/api/openstack/compute/plugins/v3/servers.py:383
#, python-format
msgid "Bad network format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:724
#: nova/api/openstack/compute/servers.py:825
#: nova/api/openstack/compute/plugins/v3/servers.py:386
msgid "Bad networks format"
msgstr ""

#: nova/api/openstack/compute/servers.py:841
#: nova/api/openstack/compute/servers.py:969
msgid "Invalid flavorRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:966
#: nova/api/openstack/compute/plugins/v3/servers.py:503
msgid "Can not find requested image"
msgstr ""

#: nova/api/openstack/compute/servers.py:972
#: nova/api/openstack/compute/plugins/v3/servers.py:509
msgid "Invalid key_name provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:975
#: nova/api/openstack/compute/plugins/v3/servers.py:512
msgid "Invalid config_drive provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:626
#: nova/api/openstack/compute/servers.py:773
#: nova/api/openstack/compute/servers.py:1079
#: nova/api/openstack/compute/servers.py:1199
#: nova/api/openstack/compute/servers.py:1380
#: nova/api/openstack/compute/plugins/v3/servers.py:622
#: nova/api/openstack/compute/plugins/v3/servers.py:734
#: nova/api/openstack/compute/plugins/v3/servers.py:853
msgid "Instance could not be found"
msgstr ""

#: nova/api/openstack/compute/servers.py:1094
#: nova/api/openstack/compute/servers.py:1113
#: nova/api/openstack/compute/plugins/v3/servers.py:633
#: nova/api/openstack/compute/plugins/v3/servers.py:649
msgid "Instance has not been resized."
msgstr ""

#: nova/api/openstack/compute/servers.py:1116
#: nova/api/openstack/compute/plugins/v3/servers.py:652
msgid "Flavor used by the instance could not be found."
msgstr ""

#: nova/api/openstack/compute/servers.py:1180
#: nova/api/openstack/compute/plugins/v3/servers.py:715
msgid "You are not authorized to access the image the instance was started with."
msgstr ""

#: nova/api/openstack/compute/servers.py:1184
#: nova/api/openstack/compute/plugins/v3/servers.py:719
msgid "Image that the instance was started with could not be found."
msgstr ""

#: nova/api/openstack/compute/servers.py:1188
#: nova/api/openstack/compute/plugins/v3/servers.py:723
msgid "Invalid instance image."
msgstr ""

#: nova/api/openstack/compute/servers.py:1220
msgid "Invalid imageRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:1211
msgid "Missing imageRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1386
#: nova/api/openstack/compute/plugins/v3/servers.py:859
msgid "Cannot find image for rebuild"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:202
#: nova/api/openstack/compute/plugins/v3/services.py:152
msgid "Missing disabled reason field"
msgstr ""

#: nova/api/openstack/compute/services.py:136
msgid "Missing forced_down field"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:146
#: nova/api/openstack/compute/plugins/v3/services.py:99
#, python-format
msgid "Service %s not found."
msgstr ""

#: nova/api/openstack/compute/simple_tenant_usage.py:192
#: nova/api/openstack/compute/legacy_v2/contrib/simple_tenant_usage.py:193
msgid "Datetime is in invalid format"
msgstr ""

#: nova/api/openstack/compute/contrib/simple_tenant_usage.py:238
msgid "Invalid start time. The start time cannot occur after the end time."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:161
msgid "Requested network does not contain enough (2+) usable hosts"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:168
msgid "Address could not be converted."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:176
msgid "Quota exceeded, too many networks."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:189
msgid "Create networks failed"
msgstr ""

#: nova/api/openstack/compute/virtual_interfaces.py:65
#: nova/api/openstack/compute/legacy_v2/contrib/virtual_interfaces.py:55
msgid "Listing virtual interfaces is not supported by this cloud."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:362
#: nova/api/openstack/compute/contrib/volumes.py:517
#, python-format
msgid "Instance %s is not attached."
msgstr ""

#: nova/api/openstack/compute/volumes.py:288
#: nova/api/openstack/compute/volumes.py:452
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:279
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:396
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:443
#, python-format
msgid "volume_id not found: %s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:98
msgid "The volume was either invalid or not attached to the instance."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:526
#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:201
msgid "Can't detach root device volume"
msgstr ""

#: nova/api/openstack/compute/flavors.py:131
#, python-format
msgid "Invalid minRam filter [%s]"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:78
msgid "Incorrect request body format"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:85
#: nova/api/openstack/compute/server_metadata.py:83
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:95
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:87
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:81
msgid "Request body contains too many items"
msgstr ""

#: nova/api/openstack/compute/limits.py:161
#, python-format
msgid "Only %(value)s %(verb)s request(s) can be made to %(uri)s every %(unit_string)s."
msgstr ""

#: nova/api/openstack/compute/limits.py:287
msgid "This request was rate-limited."
msgstr ""

#: nova/api/openstack/compute/legacy_v2/server_metadata.py:58
#: nova/api/openstack/compute/legacy_v2/server_metadata.py:105
msgid "Malformed request body. metadata must be object"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/server_metadata.py:78
msgid "Malformed request body. meta item must be object"
msgstr ""

#: nova/api/openstack/compute/servers.py:657
#, python-format
msgid "Bad personality format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:660
msgid "Bad personality format"
msgstr ""

#: nova/api/openstack/compute/servers.py:663
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:681
#: nova/api/openstack/compute/plugins/v3/servers.py:346
#, python-format
msgid "Bad port format: port uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:678
msgid "Unknown argument : port"
msgstr ""

#: nova/api/openstack/compute/servers.py:702
#: nova/api/openstack/compute/plugins/v3/servers.py:335
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:755
msgid "accessIPv4 is not proper IPv4 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:760
msgid "accessIPv6 is not proper IPv6 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:750
msgid "Userdata content cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/servers.py:415
msgid "block_device_mapping must be a list"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/servers.py:440
msgid "block_device_mapping_v2 must be a list"
msgstr ""

#: nova/api/openstack/compute/servers.py:789
#: nova/api/openstack/compute/plugins/v3/servers.py:427
msgid "Server name is not defined"
msgstr ""

#: nova/api/validation/validators.py:61
#, python-format
msgid "Invalid input for field/attribute %(path)s. Value: %(value)s. %(message)s"
msgstr ""

#: nova/api/openstack/compute/servers.py:1064
msgid "HostId cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:1068
msgid "Personality cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:1132
#: nova/api/openstack/compute/plugins/v3/servers.py:666
msgid "Argument 'type' for reboot must be a string"
msgstr ""

#: nova/api/openstack/compute/servers.py:1138
#: nova/api/openstack/compute/plugins/v3/servers.py:672
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr ""

#: nova/api/openstack/compute/servers.py:1142
#: nova/api/openstack/compute/plugins/v3/servers.py:676
msgid "Missing argument 'type' for reboot"
msgstr ""

#: nova/api/openstack/compute/servers.py:1169
#: nova/api/openstack/compute/plugins/v3/servers.py:704
msgid "Unable to locate requested flavor."
msgstr ""

#: nova/api/openstack/compute/servers.py:1172
#: nova/api/openstack/compute/plugins/v3/servers.py:707
msgid "Resize requires a flavor change."
msgstr ""

#: nova/api/openstack/compute/servers.py:1250
msgid "Missing flavorRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1263
msgid "No adminPass was specified"
msgstr ""

#: nova/api/openstack/compute/servers.py:1280
msgid "Unable to parse metadata key/value pairs."
msgstr ""

#: nova/api/openstack/compute/servers.py:1293
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1296
msgid "Resize requests require 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1316
msgid "Could not parse imageRef from request."
msgstr ""

#: nova/api/openstack/compute/servers.py:1419
msgid "createImage entity requires name attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1428
#: nova/api/openstack/compute/contrib/admin_actions.py:286
#: nova/api/openstack/compute/plugins/v3/create_backup.py:85
#: nova/api/openstack/compute/plugins/v3/servers.py:899
msgid "Invalid metadata"
msgstr ""

#: nova/api/openstack/compute/servers.py:1486
msgid "Invalid adminPass"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:63
#: nova/api/openstack/compute/contrib/admin_actions.py:88
#: nova/api/openstack/compute/contrib/admin_actions.py:113
#: nova/api/openstack/compute/contrib/admin_actions.py:135
#: nova/api/openstack/compute/contrib/admin_actions.py:176
#: nova/api/openstack/compute/contrib/admin_actions.py:195
#: nova/api/openstack/compute/contrib/admin_actions.py:214
#: nova/api/openstack/compute/contrib/admin_actions.py:233
#: nova/api/openstack/compute/contrib/admin_actions.py:386
#: nova/api/openstack/compute/contrib/multinic.py:43
#: nova/api/openstack/compute/contrib/rescue.py:44
#: nova/api/openstack/compute/contrib/shelve.py:43
msgid "Server not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:263
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:267
msgid "Malformed createBackup entity"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:323
#: nova/api/openstack/compute/plugins/v3/migrate_server.py:80
msgid "host, block_migration and disk_over_commit must be specified for live migration."
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:355
#, python-format
msgid "Live migration of instance %s to another host failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:358
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:376
#: nova/api/openstack/compute/plugins/v3/admin_actions.py:83
#, python-format
msgid "Desired state must be specified.  Valid states are: %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/agents.py:88
#: nova/api/openstack/compute/legacy_v2/contrib/agents.py:151
#: nova/api/openstack/compute/legacy_v2/contrib/cloudpipe_update.py:56
#, python-format
msgid "Invalid request body: %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/aggregates.py:41
msgid "Only host parameter can be specified"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/aggregates.py:44
msgid "Host parameter must be specified"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:158
#, python-format
msgid "Aggregates does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:162
#: nova/api/openstack/compute/contrib/flavormanage.py:55
#: nova/api/openstack/compute/contrib/keypairs.py:86
#: nova/api/openstack/compute/plugins/v3/aggregates.py:46
#: nova/api/openstack/compute/plugins/v3/aggregates.py:82
#: nova/api/openstack/compute/plugins/v3/aggregates.py:120
#: nova/api/openstack/compute/plugins/v3/aggregates.py:205
msgid "Invalid request body"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/aggregates.py:199
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/aggregates.py:204
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: host exists"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/aggregates.py:225
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/aggregates.py:229
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: invalid"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/aggregates.py:248
msgid "The value of metadata must be a dict"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:215
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:117
#: nova/api/openstack/compute/contrib/attach_interfaces.py:150
#: nova/api/openstack/compute/contrib/attach_interfaces.py:173
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:161
msgid "Network driver does not support this function."
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:121
msgid "Failed to attach interface"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/baremetal_nodes.py:44
msgid "Ironic client unavailable, cannot access Ironic."
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:252
#, python-format
msgid "Cell %(id)s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:285
#: nova/api/openstack/compute/plugins/v3/cells.py:192
msgid "Cell name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/cells.py:195
msgid "Cell name cannot contain '!', '.' or '@'"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:296
#: nova/api/openstack/compute/plugins/v3/cells.py:203
msgid "Cell type must be 'parent' or 'child'"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/cells.py:237
msgid "rpc_port must be integer"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:352
#: nova/api/openstack/compute/contrib/cells.py:376
#: nova/api/openstack/compute/plugins/v3/cells.py:259
#: nova/api/openstack/compute/plugins/v3/cells.py:282
msgid "No cell information in request"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:357
#: nova/api/openstack/compute/plugins/v3/cells.py:264
msgid "No cell name in request"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:411
#: nova/api/openstack/compute/plugins/v3/cells.py:319
msgid "Only 'updated_since', 'project_id' and 'deleted' are understood."
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:50
msgid "os-getConsoleOutput malformed or missing from request body"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:61
msgid "Length in request body must be an integer value"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:69
msgid "Unable to get console"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:74
#: nova/api/openstack/compute/plugins/v3/console_output.py:55
msgid "Unable to get console log, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:50
msgid "Instance not yet ready"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:52
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:59
msgid "Unable to get vnc console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:76
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:89
msgid "Unable to get spice console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:101
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:122
msgid "Unable to get rdp console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/consoles.py:140
msgid "Unable to get serial console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/evacuate.py:61
msgid "host must be specified."
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/evacuate.py:68
msgid "onSharedStorage must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:111
msgid "No request body"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/flavor_access.py:115
#: nova/api/openstack/compute/legacy_v2/contrib/flavor_access.py:140
msgid "Missing tenant parameter"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:55
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:42
msgid "No Request Body"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/flavorextraspecs.py:45
msgid "Bad extra_specs provided"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/flavorextraspecs.py:51
msgid "Fail to validate provided extra specs keys. Expected string"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/flavormanage.py:57
msgid "A valid name parameter is required"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/flavormanage.py:63
msgid "A valid ram parameter is required"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/flavormanage.py:68
msgid "A valid vcpus parameter is required"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/flavormanage.py:73
msgid "A valid disk parameter is required"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/floating_ip_dns.py:94
msgid "Unable to get dns domain"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/floating_ip_dns.py:134
msgid "Unable to create dns domain"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/floating_ip_dns.py:156
msgid "Unable to delete dns domain"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/floating_ip_dns.py:188
msgid "Unable to get dns entry"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/floating_ip_dns.py:229
msgid "Unable to create dns entry"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/floating_ip_dns.py:249
msgid "Unable to delete dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:219
#: nova/api/openstack/compute/contrib/floating_ips.py:283
msgid "Address not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:183
#: nova/api/openstack/compute/plugins/v3/hosts.py:128
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:186
#: nova/api/openstack/compute/plugins/v3/hosts.py:131
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:188
#: nova/api/openstack/compute/plugins/v3/hosts.py:133
#, python-format
msgid "Invalid mode: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:190
#: nova/api/openstack/compute/plugins/v3/hosts.py:135
msgid "'status' or 'maintenance_mode' needed for host update"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:212
#: nova/api/openstack/compute/plugins/v3/hosts.py:158
msgid "Virt driver does not implement host maintenance mode."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:234
#: nova/api/openstack/compute/plugins/v3/hosts.py:181
msgid "Virt driver does not implement host disabled status."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:250
#: nova/api/openstack/compute/plugins/v3/hosts.py:199
msgid "Virt driver does not implement host power management."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:213
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:113
msgid "Virt driver does not implement uptime function."
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:54
msgid "Missing 'networkId' argument for addFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:70
msgid "Missing 'address' argument for removeFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:43
msgid "Disassociate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:59
msgid "Disassociate project is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:77
msgid "Associate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:81
msgid "Disassociate network is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:116
msgid "Missing network in body"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:120
msgid "Network label is required"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:124
msgid "Network cidr or cidr_v6 is required"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/os_networks.py:169
#, python-format
msgid "%s is not a valid IP network"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:150
msgid "VLAN support must be enabled"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:155
msgid "No CIDR requested"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:165
msgid "CIDR is malformed."
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/quota_classes.py:86
msgid "quota_class_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:163
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:139
#, python-format
msgid "Bad key(s) %s in quota_set"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/quotas.py:76
#, python-format
msgid "Quota limit %(limit)s for %(resource)s must be in the range of -1 and %(max)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:140
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:118
msgid "quota_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/scheduler_hints.py:37
#: nova/api/openstack/compute/plugins/v3/scheduler_hints.py:39
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:156
msgid "security group default rule not found"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/server_diagnostics.py:44
msgid "Unable to get diagnostics, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:102
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:75
#, python-format
msgid "Invalid event status `%s'"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/server_external_events.py:65
#, python-format
msgid "Invalid event name %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:92
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:65
#, python-format
msgid "event entity requires key %(key)s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:96
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:69
#, python-format
msgid "event entity contains unsupported items: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:173
msgid "Conflicting policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:178
#, python-format
msgid "Invalid policies: %s"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/server_groups.py:94
msgid "Duplicate policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:183
msgid "the body is invalid."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:192
#, python-format
msgid "'%s' is either missing or empty."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:198
#, python-format
msgid "Invalid format for name: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:206
#, python-format
msgid "'%s' is not a list"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:210
#, python-format
msgid "unsupported fields: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:292
#: nova/api/openstack/compute/contrib/console_output.py:44
#: nova/api/openstack/compute/contrib/server_diagnostics.py:48
#: nova/api/openstack/compute/contrib/server_start_stop.py:40
#: nova/virt/hyperv/vmops.py:353
msgid "Instance not found"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:192
msgid "The string containing the reason for disabling the service contains invalid characters or is too long."
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:200
#: nova/api/openstack/compute/plugins/v3/services.py:150
msgid "Invalid attribute in the request"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:155
msgid "volume not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:383
#, python-format
msgid "Bad volumeId format: volumeId is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:300
#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:357
msgid "volumeAttachment not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:399
#: nova/api/openstack/compute/contrib/volumes.py:460
msgid "volumeId must be specified."
msgstr ""

#: nova/api/openstack/compute/legacy_v2/contrib/volumes.py:549
msgid "snapshot not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:693
#, python-format
msgid "Invalid value '%s' for force."
msgstr ""

#: nova/api/validation/parameter_types.py:126
msgid "printable characters. Can not start or end with whitespace."
msgstr ""

#: nova/api/validation/parameter_types.py:140
msgid "printable characters except !, ., @. Can not start or end with whitespace."
msgstr ""

#: nova/api/validation/parameter_types.py:149
msgid "printable characters except !, ., @, with at least one non space character"
msgstr ""

#: nova/api/validation/parameter_types.py:157
msgid "printable characters with at least one non space character"
msgstr ""

#: nova/cells/messaging.py:339
msgid "No cell given in routing path."
msgstr ""

#: nova/cells/messaging.py:365 nova/cells/messaging.py:373
#, python-format
msgid "destination is %(target_cell)s but routing_path is %(routing_path)s"
msgstr ""

#: nova/cells/messaging.py:385
#, python-format
msgid "Unknown %(cell_type)s when routing to %(target_cell)s"
msgstr ""

#: nova/cells/messaging.py:668
#, python-format
msgid "Unknown method '%(method)s' in compute API"
msgstr ""

#: nova/cmd/idmapshift.py:207
msgid "nova-idmapshift is a tool that properly sets the ownership of a filesystem for use with linux user namespaces.  This tool can only be used with linux lxc containers.  See the man page for details."
msgstr ""

#: nova/cmd/manage.py:210
msgid "The above error may show that the database has not been created.\n"
"Please create a database using 'nova-manage db sync' before running this command."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:72
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:56
#: nova/cmd/manage.py:251
msgid "Quota limit must be -1 or greater."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:76
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:60
#: nova/cmd/manage.py:255
#, python-format
msgid "Quota limit must be greater than %s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:79
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:63
#: nova/cmd/manage.py:258
#, python-format
msgid "Quota limit must be less than %s."
msgstr ""

#: nova/cmd/manage.py:267
#, python-format
msgid "%(key)s is not a valid quota key. Valid options are: %(options)s."
msgstr ""

#: nova/cmd/manage.py:273
msgid "Quota"
msgstr ""

#: nova/cmd/manage.py:274
msgid "Limit"
msgstr ""

#: nova/cmd/manage.py:275
msgid "In Use"
msgstr ""

#: nova/cmd/manage.py:276
msgid "Reserved"
msgstr ""

#: nova/cmd/manage.py:319 nova/cmd/manage.py:394 nova/cmd/manage.py:718
#: nova/cmd/manage.py:732 nova/cmd/manage.py:802
#, python-format
msgid "error: %s"
msgstr ""

#: nova/cmd/manage.py:327
msgid "network"
msgstr ""

#: nova/cmd/manage.py:328
msgid "IP address"
msgstr ""

#: nova/cmd/manage.py:329
msgid "hostname"
msgstr ""

#: nova/cmd/manage.py:330 nova/cmd/manage.py:858
msgid "host"
msgstr ""

#: nova/cmd/manage.py:342 nova/cmd/manage.py:366
msgid "No fixed IP found."
msgstr ""

#: nova/cmd/manage.py:364
#, python-format
msgid "WARNING: fixed IP %s allocated to missing instance"
msgstr ""

#: nova/cmd/manage.py:420
#, python-format
msgid "Too many IP addresses will be generated.  Please increase /%s to reduce the number generated."
msgstr ""

#: nova/cmd/manage.py:471
msgid "No floating IP addresses have been defined."
msgstr ""

#: nova/cmd/manage.py:496
msgid "ERROR: Network commands are not supported when using the Neutron API.  Use python-neutronclient instead."
msgstr ""

#: nova/cmd/manage.py:533 nova/tests/test_nova_manage.py:214
msgid "id"
msgstr ""

#: nova/cmd/manage.py:534 nova/tests/test_nova_manage.py:215
msgid "IPv4"
msgstr ""

#: nova/cmd/manage.py:535 nova/tests/test_nova_manage.py:216
msgid "IPv6"
msgstr ""

#: nova/cmd/manage.py:536 nova/tests/test_nova_manage.py:217
msgid "start address"
msgstr ""

#: nova/cmd/manage.py:537 nova/tests/test_nova_manage.py:218
msgid "DNS1"
msgstr ""

#: nova/cmd/manage.py:538 nova/tests/test_nova_manage.py:219
msgid "DNS2"
msgstr ""

#: nova/cmd/manage.py:539 nova/tests/test_nova_manage.py:220
msgid "VlanID"
msgstr ""

#: nova/cmd/manage.py:540 nova/cmd/manage.py:646
#: nova/tests/test_nova_manage.py:221
msgid "project"
msgstr ""

#: nova/cmd/manage.py:541 nova/tests/test_nova_manage.py:222
msgid "uuid"
msgstr ""

#: nova/cmd/manage.py:548
msgid "No networks found"
msgstr ""

#: nova/cmd/manage.py:567
msgid "Please specify either fixed_range or uuid"
msgstr ""

#: nova/cmd/manage.py:572
msgid "UUID is required to delete Neutron Networks"
msgstr ""

#: nova/cmd/manage.py:575
msgid "Deleting by fixed_range is not supported with the NeutronManager"
msgstr ""

#: nova/cmd/manage.py:638
msgid "instance"
msgstr ""

#: nova/cmd/manage.py:639
msgid "node"
msgstr ""

#: nova/cmd/manage.py:640
msgid "type"
msgstr ""

#: nova/cmd/manage.py:641
msgid "state"
msgstr ""

#: nova/cmd/manage.py:642
msgid "launched"
msgstr ""

#: nova/cmd/manage.py:643
msgid "image"
msgstr ""

#: nova/cmd/manage.py:644
msgid "kernel"
msgstr ""

#: nova/cmd/manage.py:645
msgid "ramdisk"
msgstr ""

#: nova/cmd/manage.py:647
msgid "user"
msgstr ""

#: nova/cmd/manage.py:648 nova/cmd/manage.py:859
msgid "zone"
msgstr ""

#: nova/cmd/manage.py:649
msgid "index"
msgstr ""

#: nova/cmd/manage.py:898
msgid "Must supply a positive value for max_rows"
msgstr ""

#: nova/cmd/manage.py:755
#, python-format
msgid "max rows must be <= %(max_value)d"
msgstr ""

#: nova/cmd/manage.py:761
msgid "Table"
msgstr ""

#: nova/cmd/manage.py:762
msgid "Number of Rows Archived"
msgstr ""

#: nova/cmd/manage.py:764
msgid "Nothing was archived."
msgstr ""

#: nova/cmd/manage.py:780
#, python-format
msgid "Deleted %(records)d records from table '%(table_name)s'."
msgstr ""

#: nova/cmd/manage.py:784
#, python-format
msgid "There are %(records)d records in the '%(table_name)s' table where the uuid or instance_uuid column is NULL. Run this command again with the --delete option after you have backed up any necessary data."
msgstr ""

#: nova/cmd/manage.py:792
msgid "There were no records found where instance_uuid was NULL."
msgstr ""

#: nova/cmd/manage.py:802
#, python-format
msgid "Error attempting to run %(method)s"
msgstr ""

#: nova/cmd/manage.py:807
#, python-format
msgid "%(total)i rows matched query %(meth)s, %(done)i migrated"
msgstr ""

#: nova/cmd/manage.py:828
msgid "Must supply a positive value for max_number"
msgstr ""

#: nova/cmd/manage.py:833
#, python-format
msgid "Running batches of %i until complete"
msgstr ""

#: nova/cmd/manage.py:1091
#, python-format
msgid "Hypervisor: %s"
msgstr ""

#: nova/cmd/manage.py:1140
#, python-format
msgid "Line %(linenum)d : %(line)s"
msgstr ""

#: nova/cmd/manage.py:1143
msgid "No errors in logfiles!"
msgstr ""

#: nova/cmd/manage.py:1157
msgid "Unable to find system log file!"
msgstr ""

#: nova/cmd/manage.py:1161
#, python-format
msgid "Last %s nova syslog entries:-"
msgstr ""

#: nova/cmd/manage.py:1170
msgid "No nova entries in syslog!"
msgstr ""

#: nova/cmd/manage.py:1011
#, python-format
msgid "Invalid broker_hosts value: %s. It should be in hostname:port format"
msgstr ""

#: nova/cmd/manage.py:1017
#, python-format
msgid "Invalid port value: %s. It should be an integer"
msgstr ""

#: nova/cmd/manage.py:1030
#, python-format
msgid "Invalid port value: %s. Should be an integer"
msgstr ""

#: nova/cmd/manage.py:1189
msgid "No hosts found to map to cell, exiting."
msgstr ""

#: nova/cmd/manage.py:1200
#, python-format
msgid "Host %(host)s is already mapped to cell %(uuid)s"
msgstr ""

#: nova/cmd/manage.py:1211
msgid "All hosts are already mapped to cell(s), exiting."
msgstr ""

#: nova/cmd/baremetal_manage.py:158 nova/cmd/manage.py:1327
#, python-format
msgid "Could not read %s. Re-running with sudo"
msgstr ""

#: nova/cmd/baremetal_manage.py:162 nova/cmd/manage.py:1331
msgid "sudo failed, continuing as if nothing happened"
msgstr ""

#: nova/cmd/baremetal_manage.py:164 nova/cmd/manage.py:1333
msgid "Please re-run nova-manage as root."
msgstr ""

#: nova/cmd/manage.py:1367
#, python-format
msgid "Missing arguments: %s"
msgstr ""

#: nova/compute/api.py:366
msgid "Cannot run any more instances of this type."
msgstr ""

#: nova/compute/api.py:373
#, python-format
msgid "Can only run %s more instances of this type."
msgstr ""

#: nova/compute/api.py:410
msgid "Metadata type should be dict."
msgstr ""

#: nova/compute/api.py:438
msgid "Metadata property key greater than 255 characters"
msgstr ""

#: nova/compute/api.py:441
msgid "Metadata property value greater than 255 characters"
msgstr ""

#: nova/compute/api.py:738
#, python-format
msgid "The volume cannot be assigned the same device name as the root device %s"
msgstr ""

#: nova/compute/api.py:667
msgid "Cannot attach one or more volumes to multiple instances"
msgstr ""

#: nova/compute/api.py:856
#, python-format
msgid "Invalid image metadata. Error: %s"
msgstr ""

#: nova/compute/api.py:1031
msgid "Quota exceeded, too many servers in group"
msgstr ""

#: nova/compute/api.py:1121
msgid "Server group scheduler hint must be a UUID."
msgstr ""

#: nova/compute/api.py:1080
msgid "Images with destination_type 'volume' need to have a non-zero size specified"
msgstr ""

#: nova/compute/api.py:1347
msgid "Blank volumes (source: 'blank', dest: 'volume') need to have non-zero size"
msgstr ""

#: nova/compute/api.py:1107
msgid "More than one swap drive requested."
msgstr ""

#: nova/compute/api.py:1272
#: nova/tests/api/openstack/compute/test_servers.py:3112
#: nova/tests/api/openstack/compute/plugins/v3/test_servers.py:2460
msgid "Unable to launch multiple instances with a single configured port ID. Please launch your instance one by one with different ports."
msgstr ""

#: nova/compute/api.py:1530
msgid "max_count cannot be greater than 1 if an fixed_ip is specified."
msgstr ""

#: nova/compute/api.py:711
msgid "The requested availability zone is not available"
msgstr ""

#: nova/compute/api.py:2018
#, python-format
msgid "snapshot for %s"
msgstr ""

#: nova/compute/api.py:2649
msgid "Resize to zero disk flavor is not allowed."
msgstr ""

#: nova/compute/api.py:2557
msgid "Cannot rescue a volume-backed instance"
msgstr ""

#: nova/compute/api.py:2808
msgid "Old volume is attached to a different instance."
msgstr ""

#: nova/compute/api.py:2811
msgid "New volume must be detached in order to swap."
msgstr ""

#: nova/compute/api.py:2814
msgid "New volume must be the same size or larger."
msgstr ""

#: nova/compute/api.py:3863
msgid "Host aggregate is not empty"
msgstr ""

#: nova/compute/api.py:3887
#, python-format
msgid "Aggregate %s does not support empty named availability zone"
msgstr ""

#: nova/compute/api.py:3899
#, python-format
msgid "One or more hosts already in availability zone(s) %s"
msgstr ""

#: nova/compute/api.py:3919
#, python-format
msgid "Unexpected aggregate action %s"
msgstr ""

#: nova/compute/api.py:3442 nova/tests/compute/test_keypairs.py:135
msgid "Keypair name contains unsafe characters"
msgstr ""

#: nova/compute/api.py:4005
msgid "Keypair name must be string and between 1 and 255 characters long"
msgstr ""

#: nova/compute/api.py:3534
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr ""

#: nova/compute/api.py:3545
#, python-format
msgid "Value (%(value)s) for parameter Group%(property)s is invalid. Content limited to '%(allowed)s'."
msgstr ""

#: nova/compute/api.py:3569
msgid "Quota exceeded, too many security groups."
msgstr ""

#: nova/compute/api.py:3584
#, python-format
msgid "Security group %s already exists"
msgstr ""

#: nova/compute/api.py:3597
#, python-format
msgid "Unable to update system group '%s'"
msgstr ""

#: nova/compute/api.py:3659
#, python-format
msgid "Unable to delete system group '%s'"
msgstr ""

#: nova/compute/api.py:3664
msgid "Security group is still in use"
msgstr ""

#: nova/compute/api.py:3753 nova/compute/api.py:3827
#, python-format
msgid "Rule (%s) not found"
msgstr ""

#: nova/compute/api.py:3769
msgid "Quota exceeded, too many security group rules."
msgstr ""

#: nova/compute/api.py:4344
#, python-format
msgid "Security group %(name)s added %(protocol)s ingress (%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:4359
#, python-format
msgid "Security group %(name)s removed %(protocol)s ingress (%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:3834
msgid "Security group id should be integer"
msgstr ""

#: nova/compute/claims.py:153
msgid "memory"
msgstr ""

#: nova/compute/claims.py:162
msgid "disk"
msgstr ""

#: nova/compute/claims.py:179
msgid "vcpu"
msgstr ""

#: nova/compute/claims.py:177 nova/compute/claims.py:249
msgid "Claim pci failed."
msgstr ""

#: nova/compute/claims.py:219
msgid "Requested instance NUMA topology together with requested PCI devices cannot fit the given host NUMA topology"
msgstr ""

#: nova/compute/claims.py:223
msgid "Requested instance NUMA topology cannot fit the given host NUMA topology"
msgstr ""

#: nova/compute/claims.py:212
#, python-format
msgid "Free %(type)s %(free).02f %(unit)s < requested %(requested)d %(unit)s"
msgstr ""

#: nova/compute/flavors.py:115
msgid "Flavor names can only contain printable characters and horizontal spaces."
msgstr ""

#: nova/compute/flavors.py:119
msgid "id cannot contain leading and/or trailing whitespace(s)"
msgstr ""

#: nova/compute/flavors.py:129
msgid "Flavor id can only contain letters from A-Z (both cases), periods, dashes, underscores and spaces."
msgstr ""

#: nova/compute/flavors.py:150
#, python-format
msgid "'rxtx_factor' argument must be a float between 0 and %g"
msgstr ""

#: nova/compute/flavors.py:161
msgid "is_public must be a boolean"
msgstr ""

#: nova/compute/flavors.py:327
msgid "Key Names can only contain alphanumeric characters, periods, dashes, underscores, colons and spaces."
msgstr ""

#: nova/compute/manager.py:512
msgid "Instance event failed"
msgstr ""

#: nova/compute/manager.py:610
#, python-format
msgid "%s is not a valid node managed by this compute host."
msgstr ""

#: nova/compute/manager.py:1242
msgid "Anti-affinity instance group policy was violated."
msgstr ""

#: nova/compute/manager.py:1467
msgid "Affinity instance group policy was violated."
msgstr ""

#: nova/compute/manager.py:2080
#, python-format
msgid "Failed to allocate the network(s) with error %s, not rescheduling."
msgstr ""

#: nova/compute/manager.py:1944 nova/compute/manager.py:1981
msgid "Failed to allocate the network(s), not rescheduling."
msgstr ""

#: nova/compute/manager.py:1190 nova/compute/manager.py:1918
msgid "Success"
msgstr ""

#: nova/compute/manager.py:2007
msgid "Failure prepping block device."
msgstr ""

#: nova/compute/manager.py:2443
msgid "Invalid state of instance files on shared storage"
msgstr ""

#: nova/compute/manager.py:3286
#, python-format
msgid "instance %s is not running"
msgstr ""

#: nova/compute/manager.py:2860
msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""

#: nova/compute/manager.py:2880
msgid "error setting admin password"
msgstr ""

#: nova/compute/manager.py:2965
#, python-format
msgid "Driver Error: %s"
msgstr ""

#: nova/compute/manager.py:3288
msgid "Instance has no source host"
msgstr ""

#: nova/compute/manager.py:4369
#, python-format
msgid "Port %s is not attached"
msgstr ""

#: nova/compute/manager.py:4940
#, python-format
msgid "Instance %s not found"
msgstr ""

#: nova/compute/manager.py:4945
msgid "In ERROR state"
msgstr ""

#: nova/compute/manager.py:4952
#, python-format
msgid "In states %(vm_state)s/%(task_state)s, not RESIZED/None"
msgstr ""

#: nova/compute/manager.py:5510
#, python-format
msgid "Unrecognized value '%s' for CONF.running_deleted_instance_action"
msgstr ""

#: nova/compute/resource_tracker.py:664
#, python-format
msgid "Missing keys: %s"
msgstr ""

#: nova/compute/rpcapi.py:58
msgid "No compute host specified"
msgstr ""

#: nova/compute/rpcapi.py:60
#, python-format
msgid "Unable to find host for Instance %s"
msgstr ""

#: nova/compute/stats.py:42
msgid "Unexpected type adding stats"
msgstr ""

#: nova/conductor/manager.py:714
msgid "No valid host found for cold migrate"
msgstr ""

#: nova/conductor/manager.py:231
msgid "No valid host found for resize"
msgstr ""

#: nova/conductor/manager.py:493
#, python-format
msgid "Unshelve attempted but the image %s cannot be found."
msgstr ""

#: nova/conductor/tasks/live_migrate.py:113
#, python-format
msgid "Unable to migrate %(instance_uuid)s to %(dest)s: Lack of memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""

#: nova/conductor/tasks/live_migrate.py:160
#, python-format
msgid "Timeout while checking if we can live migrate to host: %s"
msgstr ""

#: nova/conductor/tasks/live_migrate.py:177
#, python-format
msgid "Exceeded max scheduling retries %(max_retries)d for instance %(instance_uuid)s during live migration"
msgstr ""

#: nova/conf/cloudpipe.py:24
msgid "Image ID used when starting up a cloudpipe vpn server"
msgstr ""

#: nova/cloudpipe/pipelib.py:47
msgid "Flavor for vpn instances"
msgstr ""

#: nova/cloudpipe/pipelib.py:50
msgid "Template for cloudpipe instance boot script"
msgstr ""

#: nova/cloudpipe/pipelib.py:53
msgid "Network to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:56
msgid "Netmask to push into openvpn config"
msgstr ""

#: nova/conf/cloudpipe.py:44
msgid "Suffix to add to project name for vpn key and secgroups"
msgstr ""

#: nova/crypto.py:54
msgid "Filename of root CA"
msgstr ""

#: nova/crypto.py:57
msgid "Filename of private key"
msgstr ""

#: nova/crypto.py:60
msgid "Filename of root Certificate Revocation List"
msgstr ""

#: nova/crypto.py:63
msgid "Where we keep our keys"
msgstr ""

#: nova/crypto.py:66
msgid "Where we keep our root CA"
msgstr ""

#: nova/crypto.py:69
msgid "Should we use a CA for each project?"
msgstr ""

#: nova/crypto.py:73
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: nova/crypto.py:78
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: nova/image/download/file.py:30
msgid "List of file systems that are configured in this file in the image_file_url:<list entry name> sections"
msgstr ""

#: nova/console/websocketproxy.py:50
msgid "No access_url in connection_info. Cannot validate protocol"
msgstr ""

#: nova/console/websocketproxy.py:79
#, python-format
msgid "We do not support scheme '%s' under Python < 2.7.4, please use http or https"
msgstr ""

#: nova/console/websocketproxy.py:119
msgid "Origin header not valid."
msgstr ""

#: nova/console/websocketproxy.py:122
msgid "Origin header does not match this host."
msgstr ""

#: nova/console/websocketproxy.py:125
msgid "Origin header protocol does not match this host."
msgstr ""

#: nova/console/websocketproxy.py:128
#, python-format
msgid "connect info: %s"
msgstr ""

#: nova/console/websocketproxy.py:133
#, python-format
msgid "connecting to: %(host)s:%(port)s"
msgstr ""

#: nova/console/websocketproxy.py:156
#, python-format
msgid "%(host)s:%(port)s: Target closed"
msgstr ""

#: nova/console/xvp.py:203
msgid "Failed to run xvp."
msgstr ""

#: nova/db/sqlalchemy/api.py:258
#: nova/openstack/common/db/sqlalchemy/utils.py:176
#: nova/virt/baremetal/db/sqlalchemy/api.py:60
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: nova/db/sqlalchemy/api.py:990
#, python-format
msgid "Invalid floating IP %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1291 nova/db/sqlalchemy/api.py:1330
#, python-format
msgid "Invalid fixed IP Address %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1465
#, python-format
msgid "Invalid virtual interface address %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1558
#, python-format
msgid "Unknown osapi_compute_unique_server_name_scope value: %s Flag must be empty, \"global\" or \"project\""
msgstr ""

#: nova/db/sqlalchemy/api.py:1717
#, python-format
msgid "Invalid instance id %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1991
#, python-format
msgid "Invalid field name: %s"
msgstr ""

#: nova/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: nova/db/sqlalchemy/api.py:2635
msgid "Sort direction size exceeds sort key size"
msgstr ""

#: nova/db/sqlalchemy/api.py:5244
#, python-format
msgid "Add metadata failed for aggregate %(id)s after %(retries)s retries"
msgstr ""

#: nova/db/sqlalchemy/migration.py:39
#: nova/openstack/common/db/sqlalchemy/migration.py:188
#: nova/virt/baremetal/db/sqlalchemy/migration.py:37
msgid "version should be an integer"
msgstr ""

#: nova/db/sqlalchemy/migration.py:66
#: nova/virt/baremetal/db/sqlalchemy/migration.py:65
msgid "Upgrade DB using Essex release first."
msgstr ""

#: nova/db/sqlalchemy/utils.py:274
#, python-format
msgid "Missing column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:280
#, python-format
msgid "Different types in %(table)s.%(column)s and shadow table: %(c_type)s %(shadow_c_type)s"
msgstr ""

#: nova/db/sqlalchemy/utils.py:289
#, python-format
msgid "Extra column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:310
msgid "Specify `table_name` or `table` param"
msgstr ""

#: nova/db/sqlalchemy/utils.py:313
msgid "Specify only one param `table_name` `table`"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/267_instance_uuid_non_nullable.py:54
#, python-format
msgid "There are %(records)d records in the '%(table_name)s' table where the uuid or instance_uuid column is NULL. These must be manually cleaned up before the migration will pass. Consider running the 'nova-manage db null_instance_uuid_scan' command."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/291_enforce_flavors_migrated.py:30
#, python-format
msgid "There are still %(count)i unmigrated flavor records. Migration cannot continue until all instance flavor records have been migrated to the new format. Please run `nova-manage db migrate_flavor_data' first."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/330_enforce_mitaka_online_migrations.py:19
#, python-format
msgid "There are still %(count)i unmigrated records in the %(table)s table. Migration cannot continue until all records have been migrated."
msgstr ""

#: nova/image/s3.py:396
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: nova/image/s3.py:403
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: nova/image/s3.py:414
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: nova/image/s3.py:426
msgid "Unsafe filenames in image"
msgstr ""

#: nova/image/download/file.py:78
msgid "A unique ID given to each file system.  This is value is set in Glance and agreed upon here so that the operator knowns they are dealing with the same file system."
msgstr ""

#: nova/image/download/file.py:83
msgid "The path at which the file system is mounted."
msgstr ""

#: nova/image/download/file.py:85
#, python-format
msgid "The group %(group_name)s must be configured with an id."
msgstr ""

#: nova/image/download/file.py:110
#, python-format
msgid "The key %s is required in all file system descriptions."
msgstr ""

#: nova/image/download/file.py:120
#, python-format
msgid "The key %(r)s is required in the location metadata to access the url %(url)s."
msgstr ""

#: nova/image/download/file.py:127
#, python-format
msgid "The ID %(id)s is unknown."
msgstr ""

#: nova/image/download/file.py:135
#, python-format
msgid "The mount point advertised by glance: %(glance_mount)s, does not match the URL path: %(path)s"
msgstr ""

#: nova/image/download/file.py:153
#, python-format
msgid "No matching ID for the URL %s was found."
msgstr ""

#: nova/ipv6/account_identifier.py:39 nova/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:41 nova/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:43
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr ""

#: nova/keymgr/barbican.py:62
msgid "User is not authorized to use key manager."
msgstr ""

#: nova/keymgr/barbican.py:67
msgid "Unable to create Barbican Client without project_id."
msgstr ""

#: nova/keymgr/conf_key_mgr.py:58
msgid "keymgr.fixed_key not defined"
msgstr ""

#: nova/keymgr/single_key_mgr.py:60
msgid "cannot store arbitrary keys"
msgstr ""

#: nova/keymgr/single_key_mgr.py:70
msgid "cannot delete non-existent key"
msgstr ""

#: nova/network/api.py:56
msgid "instance is a required argument to use @refresh_cache"
msgstr ""

#: nova/network/ldapdns.py:322
msgid "ldap not installed"
msgstr ""

#: nova/network/ldapdns.py:333
msgid "This driver only supports type 'a' entries."
msgstr ""

#: nova/network/linux_net.py:264
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: nova/network/linux_net.py:1542
#, python-format
msgid "Failed to add bridge: %s"
msgstr ""

#: nova/network/linux_net.py:1568
#, python-format
msgid "Failed to add interface: %s"
msgstr ""

#: nova/network/manager.py:1851
msgid "The sum between the number of networks and the vlan start cannot be greater than 4094"
msgstr ""

#: nova/network/manager.py:2037
msgid "vlan must be an integer"
msgstr ""

#: nova/network/manager.py:2039
msgid "The vlan number cannot be greater than 4094"
msgstr ""

#: nova/network/manager.py:2042
msgid "The vlan number cannot be less than 1"
msgstr ""

#: nova/network/manager.py:1858
#, python-format
msgid "The network range is not big enough to fit %(num_networks)s networks. Network size is %(network_size)s"
msgstr ""

#: nova/network/minidns.py:75 nova/network/minidns.py:106
msgid "Invalid name"
msgstr ""

#: nova/network/minidns.py:78
msgid "This driver only supports type 'a'"
msgstr ""

#: nova/network/model.py:80
#, python-format
msgid "Invalid IP format %s"
msgstr ""

#: nova/network/neutronv2/api.py:107
#, python-format
msgid "Unknown auth plugin: %s"
msgstr ""

#: nova/network/neutronv2/api.py:256
#, python-format
msgid "Fixed IP %(ip)s is not a valid ip address for network %(network_id)s."
msgstr ""

#: nova/network/neutronv2/api.py:263
#, python-format
msgid "Fixed IP %s is already in use."
msgstr ""

#: nova/network/neutronv2/api.py:274
#, python-format
msgid "Multiple security groups found matching '%s'. Use an ID to be more specific."
msgstr ""

#: nova/network/neutronv2/api.py:219
#, python-format
msgid "empty project id for instance %s"
msgstr ""

#: nova/network/neutronv2/api.py:599
msgid "Multiple possible networks found, use a Network ID to be more specific."
msgstr ""

#: nova/network/neutronv2/api.py:813
#, python-format
msgid "Instance hostname %(hostname)s is not a valid DNS name"
msgstr ""

#: nova/network/neutronv2/api.py:935
#, python-format
msgid "Failed to access port %(port_id)s: %(reason)s"
msgstr ""

#: nova/network/neutronv2/api.py:961
msgid "This method needs to be called with either networks=None and port_ids=None or port_ids and networks as not none."
msgstr ""

#: nova/network/neutronv2/api.py:1231
#, python-format
msgid "The number of defined ports: %(ports)d is over the limit: %(quota)d"
msgstr ""

#: nova/network/neutronv2/api.py:907
#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr ""

#: nova/network/security_group/neutron_driver.py:161
#, python-format
msgid "Invalid security group name: %(name)s."
msgstr ""

#: nova/network/security_group/neutron_driver.py:170
msgid "Security group id should be uuid"
msgstr ""

#: nova/network/security_group/neutron_driver.py:405
#: nova/network/security_group/neutron_driver.py:456
#, python-format
msgid "Security group %(name)s is not found for project %(project)s"
msgstr ""

#: nova/network/security_group/neutron_driver.py:421
#: nova/network/security_group/neutron_driver.py:472
#, python-format
msgid "instance_id %s could not be found as device id on any ports"
msgstr ""

#: nova/network/security_group/neutron_driver.py:500
#, python-format
msgid "Security group %(security_group_name)s not associated with the instance %(instance)s"
msgstr ""

#: nova/network/security_group/security_group_base.py:88
msgid "Type and Code must be integers for ICMP protocol type"
msgstr ""

#: nova/network/security_group/security_group_base.py:91
msgid "To and From ports must be integers"
msgstr ""

#: nova/network/security_group/security_group_base.py:134
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: nova/objects/block_device.py:136
msgid "Volume does not belong to the requested instance."
msgstr ""

#: nova/objects/fields.py:101
#, python-format
msgid "Architecture name '%s' is not valid"
msgstr ""

#: nova/objects/fields.py:263
#, python-format
msgid "Hypervisor virt type '%s' is not valid"
msgstr ""

#: nova/objects/fields.py:438
#, python-format
msgid "Virtual machine mode '%s' is not valid"
msgstr ""

#: nova/objects/fields.py:601
#, python-format
msgid "Network \"%(val)s\" is not valid in field %(attr)s"
msgstr ""

#: nova/objects/fields.py:616
#, python-format
msgid "A NetworkModel is required in field %s"
msgstr ""

#: nova/objects/fields.py:637 nova/objects/fields.py:646
#, python-format
msgid "Value must be >= 0 for field %s"
msgstr ""

#: nova/objects/fields.py:656
#, python-format
msgid "Value must match %s"
msgstr ""

#: nova/objects/network.py:87
#, python-format
msgid "IPv6 netmask \"%s\" must be a netmask or integral prefix"
msgstr ""

#: nova/pci/devspec.py:42
#, python-format
msgid "invalid %(property)s %(attr)s"
msgstr ""

#: nova/pci/request.py:116
#, python-format
msgid "Device type mismatch for alias '%s'"
msgstr ""

#: nova/pci/whitelist.py:45
#, python-format
msgid "Invalid entry: '%s'"
msgstr ""

#: nova/pci/whitelist.py:50
#, python-format
msgid "Invalid entry: '%s'; Expecting list or dict"
msgstr ""

#: nova/pci/whitelist.py:56
#, python-format
msgid "Invalid entry: '%s'; Expecting dict"
msgstr ""

#: nova/scheduler/chance.py:55
msgid "Is the appropriate service running?"
msgstr ""

#: nova/scheduler/chance.py:60
msgid "Could not find another compute"
msgstr ""

#: nova/scheduler/chance.py:72 nova/scheduler/filter_scheduler.py:73
msgid "There are not enough hosts available."
msgstr ""

#: nova/scheduler/manager.py:73
#, python-format
msgid "Cannot load scheduler driver from configuration %(conf)s."
msgstr ""

#: nova/scheduler/utils.py:178
#, python-format
msgid "Exceeded max scheduling attempts %(max_attempts)d for instance %(instance_uuid)s. Last exception: %(exc_reason)s"
msgstr ""

#: nova/scheduler/utils.py:312
msgid "ServerGroupAffinityFilter not configured"
msgstr ""

#: nova/scheduler/utils.py:316
msgid "ServerGroupAntiAffinityFilter not configured"
msgstr ""

#: nova/scheduler/utils.py:321
msgid "ServerGroupSoftAffinityWeigher not configured"
msgstr ""

#: nova/scheduler/utils.py:326
msgid "ServerGroupSoftAntiAffinityWeigher not configured"
msgstr ""

#: nova/servicegroup/drivers/db.py:47
msgid "service is a mandatory argument for DB based ServiceGroup driver"
msgstr ""

#: nova/servicegroup/drivers/mc.py:58
msgid "service is a mandatory argument for Memcached based ServiceGroup driver"
msgstr ""

#: nova/virt/diagnostics.py:143
#, python-format
msgid "Invalid type for %s"
msgstr ""

#: nova/virt/diagnostics.py:147
#, python-format
msgid "Invalid type for %s entry"
msgstr ""

#: nova/virt/driver.py:885
msgid "Hypervisor driver does not support post_live_migration_at_source method"
msgstr ""

#: nova/virt/driver.py:1204
msgid "Event must be an instance of nova.virt.event.Event"
msgstr ""

#: nova/virt/event.py:34
msgid "Started"
msgstr ""

#: nova/virt/event.py:35
msgid "Stopped"
msgstr ""

#: nova/virt/event.py:36
msgid "Paused"
msgstr ""

#: nova/virt/event.py:37
msgid "Resumed"
msgstr ""

#: nova/virt/event.py:38
msgid "Suspended"
msgstr ""

#: nova/virt/event.py:110
msgid "Unknown"
msgstr ""

#: nova/virt/cpu.py:82
#, python-format
msgid "No CPUs available after parsing %r"
msgstr ""

#: nova/virt/cpu.py:57 nova/virt/cpu.py:61
#, python-format
msgid "Invalid range expression %r"
msgstr ""

#: nova/virt/cpu.py:70
#, python-format
msgid "Invalid exclusion expression %r"
msgstr ""

#: nova/virt/cpu.py:77
#, python-format
msgid "Invalid inclusion expression %r"
msgstr ""

#: nova/virt/images.py:58
#, python-format
msgid "qemu-img failed to execute on %(path)s : %(exp)s"
msgstr ""

#: nova/virt/images.py:63
#, python-format
msgid "Failed to run qemu-img info on %(path)s : %(error)s"
msgstr ""

#: nova/virt/images.py:98
#, python-format
msgid "Unable to convert image to %(format)s: %(exp)s"
msgstr ""

#: nova/virt/images.py:86
msgid "'qemu-img info' parsing failed."
msgstr ""

#: nova/virt/images.py:92
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: nova/virt/images.py:159
#, python-format
msgid "Unable to convert image to raw: %(exp)s"
msgstr ""

#: nova/virt/images.py:122
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: nova/virt/disk/api.py:285
msgid "image already mounted"
msgstr ""

#: nova/virt/disk/api.py:611
msgid "Not implemented on Windows"
msgstr ""

#: nova/virt/disk/api.py:640
#, python-format
msgid "User %(username)s not found in password file."
msgstr ""

#: nova/virt/disk/api.py:656
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr ""

#: nova/virt/disk/mount/api.py:143
#, python-format
msgid "partition search unsupported with %s"
msgstr ""

#: nova/virt/disk/mount/api.py:159
#, python-format
msgid "partition %s not found"
msgstr ""

#: nova/virt/disk/mount/api.py:160
#, python-format
msgid "Failed to map partitions: %s"
msgstr ""

#: nova/virt/disk/mount/api.py:195
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: nova/virt/disk/mount/loop.py:32
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:65
msgid "nbd unavailable: module not loaded"
msgstr ""

#: nova/virt/disk/mount/nbd.py:59 nova/virt/disk/mount/nbd.py:73
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/mount/nbd.py:90
#, python-format
msgid "qemu-nbd error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:103
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:69
#, python-format
msgid "libguestfs is not installed (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:82
#, python-format
msgid "libguestfs installed but not usable (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:64
#, python-format
msgid "No operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:70
#, python-format
msgid "Multi-boot operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:144
#, python-format
msgid "No mount points found in %(root)s of %(image)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:158
#, python-format
msgid "Error mounting %(device)s to %(dir)s in image %(image)s with libguestfs (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:225
#, python-format
msgid "Error mounting %(image)s with libguestfs (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:45
#, python-format
msgid "File path %s not valid"
msgstr ""

#: nova/virt/hyperv/driver.py:165
msgid "VIF plugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/driver.py:170
msgid "VIF unplugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/hostops.py:160
msgid "Host PowerOn is not supported by the Hyper-V driver"
msgstr ""

#: nova/virt/hyperv/migrationops.py:111 nova/virt/hyperv/migrationops.py:221
#, python-format
msgid "Cannot resize the root disk to a smaller size. Current size: %(curr_root_gb)s GB. Requested size: %(new_root_gb)s GB."
msgstr ""

#: nova/virt/hyperv/pathutils.py:64
#, python-format
msgid "Cannot access \"%(instances_path)s\", make sure the path exists and that you have the proper permissions. In particular Nova-Compute must not be executed with the builtin SYSTEM account or other accounts unable to authenticate on a remote host."
msgstr ""

#: nova/virt/hyperv/vmops.py:113
#, python-format
msgid "VIF driver not found for network_api_class: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:215 nova/virt/hyperv/volumeops.py:229
#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:325
#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s. Please ensure that the host's SAN policy is set to \"OfflineAll\" or \"OfflineShared\""
msgstr ""

#: nova/virt/ironic/client_wrapper.py:100
msgid "Unable to authenticate Ironic client."
msgstr ""

#: nova/virt/ironic/driver.py:370
#, python-format
msgid "Failed to add deploy parameters on node %(node)s when provisioning the instance %(instance)s"
msgstr ""

#: nova/virt/ironic/driver.py:386
#, python-format
msgid "Instance %s provisioning was aborted"
msgstr ""

#: nova/virt/ironic/driver.py:407
#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/ironic/driver.py:694
#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr ""

#: nova/virt/ironic/driver.py:714
#, python-format
msgid "Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: %(power)s)"
msgstr ""

#: nova/virt/ironic/driver.py:824
#, python-format
msgid "Error destroying the instance on node %(node)s. Provision state still '%(state)s'."
msgstr ""

#: nova/virt/ironic/driver.py:1007
#, python-format
msgid "Ironic node: %(id)s virtual to physical interface count  missmatch (Vif count: %(vif_count)d, Pif count: %(pif_count)d)"
msgstr ""

#: nova/virt/ironic/driver.py:1131
#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:145
#, python-format
msgid "Unable to determine disk prefix for %s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:193
#, python-format
msgid "No free disk device names for prefix '%s'"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:294
#, python-format
msgid "Unable to determine disk bus for '%s'"
msgstr ""

#: nova/virt/libvirt/config.py:75
#, python-format
msgid "Root element name should be '%(name)s' not '%(tag)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:662
#, python-format
msgid "Nova requires libvirt version %s or greater."
msgstr ""

#: nova/virt/libvirt/driver.py:668
#, python-format
msgid "Running Nova with parallels virt_type requires libvirt version %s"
msgstr ""

#: nova/virt/libvirt/driver.py:689
#, python-format
msgid "Running Nova with qemu/kvm virt_type on %(arch)s requires libvirt version %(libvirt_ver)s and qemu version %(qemu_ver)s, or greater"
msgstr ""

#: nova/virt/libvirt/driver.py:898
msgid "operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:1208
#, python-format
msgid "Volume sets block size, but the current libvirt hypervisor '%s' does not support custom block size"
msgstr ""

#: nova/virt/libvirt/driver.py:1313
msgid "Swap only supports host devices"
msgstr ""

#: nova/virt/libvirt/driver.py:1800
#, python-format
msgid "Error from libvirt while set password for username \"%(user)s\": [Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1824
#, python-format
msgid "Error from libvirt while quiescing %(instance_name)s: [Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1733
msgid "Found no disk to snapshot."
msgstr ""

#: nova/virt/libvirt/driver.py:1806
#, python-format
msgid "Unknown type: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1811
msgid "snapshot_id required in create_info"
msgstr ""

#: nova/virt/libvirt/driver.py:2125
#, python-format
msgid "Something went wrong when deleting a volume snapshot: rebasing a %(protocol)s network disk using qemu-img has not been fully tested"
msgstr ""

#: nova/virt/libvirt/driver.py:1858
#, python-format
msgid "Libvirt '%s' or later is required for online deletion of volume snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:1865
#, python-format
msgid "Unknown delete_info type %s"
msgstr ""

#: nova/virt/libvirt/driver.py:2223
#, python-format
msgid "Disk with id: %s not found attached to instance."
msgstr ""

#: nova/virt/libvirt/driver.py:2232
msgid "filename cannot be None"
msgstr ""

#: nova/virt/libvirt/driver.py:2261
#, python-format
msgid "no match found for %s"
msgstr ""

#: nova/virt/libvirt/driver.py:2342
#, python-format
msgid "Relative blockcommit support was not detected. Libvirt '%s' or later is required for online deletion of file/network storage-backed volume snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:3225
#, python-format
msgid "%s format is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:2738
#, python-format
msgid "Detaching PCI devices with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:3426
#, python-format
msgid "Detaching SR-IOV ports with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:2897
#, python-format
msgid "Config requested an explicit CPU model, but the current libvirt hypervisor '%s' does not support selecting CPU models"
msgstr ""

#: nova/virt/libvirt/driver.py:2903
msgid "Config requested a custom CPU model, but no model name was provided"
msgstr ""

#: nova/virt/libvirt/driver.py:2907
msgid "A CPU model name should not be set when a host CPU model is requested"
msgstr ""

#: nova/virt/libvirt/driver.py:3559
#, python-format
msgid "Volume sets discard option, but libvirt %(libvirt)s or later is required, qemu %(qemu)s or later is required."
msgstr ""

#: nova/virt/libvirt/driver.py:3701
msgid "Unable to get host UUID: /etc/machine-id does not exist"
msgstr ""

#: nova/virt/libvirt/driver.py:3709
msgid "Unable to get host UUID: /etc/machine-id is empty"
msgstr ""

#: nova/virt/libvirt/driver.py:3900
#, python-format
msgid "Invalid libvirt version %(version)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4989
#, python-format
msgid "Invalid vcpu_pin_set config, one or more of the specified cpuset is not online. Online cpuset(s): %(online)s, requested cpuset(s): %(req)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3748
msgid "Invalid vcpu_pin_set config, out of hypervisor cpu range."
msgstr ""

#: nova/virt/libvirt/driver.py:4221
msgid "Block migration can not be used with shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:5598
#, python-format
msgid "Cannot block migrate instance %(uuid)s with mapped volumes. Selective block device migration feature requires libvirt version %(libvirt_ver)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5608
msgid "Live migration can not be used without shared storage except a booted from volume VM which does not have a local disk."
msgstr ""

#: nova/virt/libvirt/driver.py:4273
#, python-format
msgid "Unable to migrate %(instance_uuid)s: Disk of instance is too large(available on destination host:%(available)s < need:%(necessary)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:4312
#, python-format
msgid "CPU doesn't have compatibility.\n\n"
"%(ret)s\n\n"
"Refer to %(u)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4379
#, python-format
msgid "The firewall filter for %s does not exist"
msgstr ""

#: nova/virt/libvirt/driver.py:5955
msgid "Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag or your destination node does not support retrieving listen addresses.  In order for live migration to work properly, you must configure the graphics (VNC and/or SPICE) listen addresses to be either the catch-all address (0.0.0.0 or ::) or the local address (127.0.0.1 or ::1)."
msgstr ""

#: nova/virt/libvirt/driver.py:5989
msgid "Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag or your destination node does not support retrieving listen addresses.  In order for live migration to work properly you must either disable serial console or upgrade your libvirt version."
msgstr ""

#: nova/virt/libvirt/driver.py:4864
msgid "Unable to resize disk down."
msgstr ""

#: nova/virt/libvirt/driver.py:7175
msgid "Migration is not supported for LVM backed instances"
msgstr ""

#: nova/virt/libvirt/driver.py:7193
#, python-format
msgid "not able to execute ssh command: %s"
msgstr ""

#: nova/virt/libvirt/guest.py:340
msgid "Unable to detach from guest transient domain."
msgstr ""

#: nova/virt/libvirt/guest.py:416
#, python-format
msgid "Error from libvirt while getting domain info for %(instance_name)s: [Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1599
msgid "libvirt error while requesting blockjob info."
msgstr ""

#: nova/virt/libvirt/driver.py:757 nova/virt/libvirt/driver.py:760
#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr ""

#: nova/virt/libvirt/driver.py:576
#, python-format
msgid "Connection to libvirt lost: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:3455
#, python-format
msgid "Error from libvirt while looking up %(instance_id)s: [Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:3476
#, python-format
msgid "Error from libvirt while looking up %(instance_name)s: [Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:852 nova/virt/libvirt/host.py:881
#, python-format
msgid "Invalid usage_type: %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:98
msgid "Incompatible settings: ephemeral storage encryption is supported only for LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:324
#, python-format
msgid "Could not load line %(line)s, got error %(error)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:339
msgid "Attempted overwrite of an existing value."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:387
msgid "clone() is not implemented"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:399
msgid "direct_snapshot() is not implemented"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:364
msgid "You should specify images_volume_group flag to use LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:738
msgid "Instance disk to be encrypted but no context provided"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:479
msgid "You should specify images_rbd_pool flag to use rbd images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:896
msgid "Image is not raw format"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:904
msgid "No image locations are accessible"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:972
#, python-format
msgid "Cannot determine the parent storage pool for %s; cannot determine where to store images"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:1065
#, python-format
msgid "PCS doesn't support images in %s format. You should either set force_raw_images=True in config or upload an image in ploop or raw format."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:632
#, python-format
msgid "Unknown image_type=%s"
msgstr ""

#: nova/virt/libvirt/utils.py:615
msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr ""

#: nova/virt/libvirt/vif.py:341 nova/virt/libvirt/vif.py:597
#: nova/virt/libvirt/vif.py:779
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr ""

#: nova/virt/libvirt/vif.py:385 nova/virt/libvirt/vif.py:617
#: nova/virt/libvirt/vif.py:799
#, python-format
msgid "Unexpected vif_type=%s"
msgstr ""

#: nova/virt/libvirt/vif.py:764
#, python-format
msgid "Plug vif failed because of unexpected vif_type=%s"
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:65
#, python-format
msgid "Insufficient Space on Volume Group %(vg)s. Only %(free_space)db available, but %(size)d bytes required by volume %(lv)s."
msgstr ""

#: nova/virt/libvirt/utils.py:311
#, python-format
msgid "vg %s must be LVM volume group"
msgstr ""

#: nova/virt/libvirt/utils.py:340
#, python-format
msgid "Path %s must be LVM logical volume"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:593
msgid "rbd python libraries not found"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:169
msgid "Not stored in rbd"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:173
msgid "Blank components"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:176
msgid "Not an rbd snapshot"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:229
#, python-format
msgid "no write permission on storage pool %s"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:257
#, python-format
msgid "no usable parent snapshot for volume %s"
msgstr ""

#: nova/virt/libvirt/volume/net.py:86
msgid "Invalid volume source data"
msgstr ""

#: nova/virt/libvirt/volume/net.py:90
msgid "Invalid target_lun"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:90
#, python-format
msgid "The mount %(mount_path)s is not a valid Quobyte volume. Error: %(exc)s"
msgstr ""

#: nova/virt/libvirt/volume.py:1049
msgid "Value required for 'scality_sofs_config'"
msgstr ""

#: nova/virt/libvirt/volume.py:1060
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr ""

#: nova/virt/libvirt/volume.py:1066
msgid "Cannot execute /sbin/mount.sofs"
msgstr ""

#: nova/virt/libvirt/volume.py:1081
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr ""

#: nova/virt/vmwareapi/driver.py:83
msgid "Must specify host_ip, host_username and host_password to use vmwareapi.VMwareVCDriver"
msgstr ""

#: nova/virt/vmwareapi/driver.py:124
#, python-format
msgid "Invalid Regular Expression %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:108
#, python-format
msgid "The specified cluster '%s' was not found in vCenter"
msgstr ""

#: nova/virt/vmwareapi/driver.py:471
msgid "Multiple hosts may be managed by the VMWare vCenter driver; therefore we do not return uptime for just one host."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:150
#, python-format
msgid "Storage policy %s did not match any datastores"
msgstr ""

#: nova/tests/virt/vmwareapi/test_vm_util.py:172
#: nova/virt/vmwareapi/vm_util.py:1116
#, python-format
msgid "Datastore regex %s did not match any datastores"
msgstr ""

#: nova/virt/vmwareapi/error_util.py:25
msgid "No root disk defined."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:29
msgid "Default PBM policy is required if PBM is enabled."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:33
msgid "The default PBM policy doesn't exist on the backend."
msgstr ""

#: nova/virt/vmwareapi/images.py:459
msgid "Extracting vmdk from OVA failed."
msgstr ""

#: nova/virt/vmwareapi/io_util.py:117
#, python-format
msgid "Glance image %s is in killed state"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:125
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr ""

#: nova/virt/vmwareapi/network_util.py:132
msgid "ESX SOAP server returned an empty port group for the host system in its response"
msgstr ""

#: nova/virt/vmwareapi/vif.py:146
#, python-format
msgid "vif type %s not supported"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:74
#, python-format
msgid "Share level '%s' cannot have share configured"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:81
#, python-format
msgid "Share '%s' is not supported"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:392
#, python-format
msgid "%s is not supported."
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:471
msgid "Limits only supported from vCenter 6.0 and above"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:239 nova/virt/vmwareapi/volumeops.py:414
msgid "Unable to find iSCSI Target"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:737
#, python-format
msgid "Only %d SCSI controllers are allowed to be created on this instance."
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1008
msgid "No host available on cluster"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1502
#, python-format
msgid "Rescue device does not exist for instance %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:255
msgid "Image disk size greater than requested disk size"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:578
#, python-format
msgid "disk type '%s' not supported"
msgstr ""

#: nova/virt/hyperv/vmops.py:280 nova/virt/vmwareapi/vmops.py:640
#, python-format
msgid "Invalid config_drive_format \"%s\""
msgstr ""

#: nova/virt/vmwareapi/vmops.py:948
msgid "instance is not powered on"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1065
msgid "pause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1069
msgid "unpause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1087
msgid "instance is powered off and cannot be suspended."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1107
msgid "instance is not in a suspended state"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1327
msgid "Unable to shrink disk."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1757
#, python-format
msgid "No device with interface-id %s exists on VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1769
#, python-format
msgid "No device with MAC address %s exists on the VM"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:336 nova/virt/vmwareapi/volumeops.py:536
#, python-format
msgid "%s does not support disk hotplug."
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:375 nova/virt/vmwareapi/volumeops.py:422
msgid "Unable to find volume"
msgstr ""

#: nova/virt/xenapi/agent.py:452
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: nova/virt/xenapi/driver.py:151
msgid "Must specify connection_url, connection_username (optionally), and connection_password to use compute_driver=xenapi.XenAPIDriver"
msgstr ""

#: nova/virt/xenapi/driver.py:656
msgid "Host startup on XenServer is not supported."
msgstr ""

#: nova/virt/xenapi/fake.py:812
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: nova/virt/xenapi/fake.py:920
#, python-format
msgid "xenapi.fake does not have an implementation for %s or it has been called with the wrong number of arguments"
msgstr ""

#: nova/virt/xenapi/host.py:85
#, python-format
msgid "Aggregate for host %(host)s count not be found."
msgstr ""

#: nova/virt/xenapi/host.py:191
msgid "Failed to parse information about a pci device for passthrough"
msgstr ""

#: nova/virt/xenapi/network_utils.py:29
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:46
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:48
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: nova/virt/xenapi/pool.py:74 nova/virt/xenapi/pool.py:122
msgid "setup in progress"
msgstr ""

#: nova/virt/xenapi/pool.py:75 nova/virt/xenapi/pool.py:123
msgid "aggregate deleted"
msgstr ""

#: nova/virt/xenapi/pool.py:76
msgid "aggregate in error"
msgstr ""

#: nova/virt/xenapi/pool.py:121
msgid "no hosts to remove"
msgstr ""

#: nova/virt/xenapi/pool.py:150
#, python-format
msgid "Unable to eject %s from the pool; pool not empty"
msgstr ""

#: nova/virt/xenapi/pool.py:165
#, python-format
msgid "Unable to eject %s from the pool; No master found"
msgstr ""

#: nova/virt/xenapi/pool.py:185
#, python-format
msgid "Unable to join %s in the pool"
msgstr ""

#: nova/virt/xenapi/vif.py:64
#, python-format
msgid "Failed to create vif %s"
msgstr ""

#: nova/virt/xenapi/vif.py:85
#, python-format
msgid "Failed to unplug vif %s"
msgstr ""

#: nova/virt/xenapi/vif.py:103
#, python-format
msgid "Found no PIF for device %s"
msgstr ""

#: nova/virt/xenapi/vif.py:122
#, python-format
msgid "PIF %(pif_uuid)s for network %(bridge)s has VLAN id %(pif_vlan)d. Expected %(vlan_num)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:234
#, python-format
msgid "Device id %(id)s specified is not supported by hypervisor version %(version)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:444
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:447
#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:458
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:509
#, python-format
msgid "Unable to destroy VDI %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:737
#, python-format
msgid "No primary VDI found for %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:828
#, python-format
msgid "Only file-based SRs (ext/NFS) are supported by this feature.  SR %(uuid)s is of type %(type)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:843
#, python-format
msgid "VDI %(vdi_ref)s is %(virtual_size)d bytes which is larger than flavor size of %(new_disk_size)d bytes."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:970 nova/virt/xenapi/vmops.py:1044
msgid "Can't resize a disk to 0 GB."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1022
msgid "Disk must have only one partition."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1030
#, python-format
msgid "Disk contains a filesystem we are unable to resize: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:916
msgid "The only partition should be partition 1."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1583
#, python-format
msgid "Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d bytes"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1930
msgid "Cannot find SR of content-type ISO"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2120
#, python-format
msgid "VHD coalesce attempts exceeded (%d), giving up..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2155
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2331
msgid "Shrinking the filesystem down with resize2fs has failed, please check if you have enough free space on your disk."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2582
msgid "This domU must be running on the host specified by connection_url"
msgstr ""

#: nova/virt/xenapi/vmops.py:185
msgid "Error: Agent is disabled"
msgstr ""

#: nova/virt/xenapi/vmops.py:525
msgid "Failed to spawn, rolling back"
msgstr ""

#: nova/virt/xenapi/vmops.py:1257
msgid "Unable to find root VBD/VDI for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:790
msgid "Unable to terminate instance."
msgstr ""

#: nova/virt/xenapi/vmops.py:1020
msgid "Can't resize down ephemeral disks."
msgstr ""

#: nova/virt/xenapi/vmops.py:1295
msgid "instance has a kernel or ramdisk but not both"
msgstr ""

#: nova/virt/xenapi/vmops.py:1409
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1837
#, python-format
msgid "Destination host:%s must be in the same aggregate as the source server"
msgstr ""

#: nova/virt/xenapi/vmops.py:1858
msgid "No suitable network for migrate"
msgstr ""

#: nova/virt/xenapi/vmops.py:1864
#, python-format
msgid "PIF %s does not contain IP address"
msgstr ""

#: nova/virt/xenapi/vmops.py:1877
msgid "Migrate Receive failed"
msgstr ""

#: nova/virt/xenapi/vmops.py:1951
msgid "XAPI supporting relax-xsm-sr-check=true required"
msgstr ""

#: nova/virt/xenapi/vmops.py:1962
#, python-format
msgid "assert_can_migrate failed because: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:2022
msgid "Migrate Send failed"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:223 nova/virt/xenapi/volume_utils.py:269
#, python-format
msgid "Unable to obtain target information %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:168
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:171
#, python-format
msgid "VDI not found on SR %(sr)s (vdi_uuid %(vdi_uuid)s, target_lun %(target_lun)s)"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:182
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:204
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:111
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:333
#, python-format
msgid "Unable to find SR from VDI %s"
msgstr ""

#: nova/virt/xenapi/client/session.py:78
#, python-format
msgid "%(vendor)s %(product)s %(version)s"
msgstr ""

#: nova/virt/xenapi/client/session.py:83
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: nova/virt/xenapi/client/session.py:103
#, python-format
msgid "Plugin version mismatch (Expected %(exp)s, got %(got)s)"
msgstr ""

#: nova/virt/xenapi/image/bittorrent.py:49
msgid "Cannot create default bittorrent URL without xenserver.torrent_base_url configuration option set."
msgstr ""

#: nova/volume/cinder.py:319
#, python-format
msgid "volume '%(vol)s' status must be 'in-use'. Currently in '%(status)s' status"
msgstr ""

#: nova/volume/cinder.py:327
#, python-format
msgid "volume '%(vol)s' status must be 'available'. Currently in '%(status)s'"
msgstr ""

#: nova/volume/cinder.py:332
#, python-format
msgid "volume %s already attached"
msgstr ""

#: nova/volume/cinder.py:337
#, python-format
msgid "Instance %(instance)s and volume %(vol)s are not in the same availability_zone. Instance is in %(ins_zone)s. Volume is in %(vol_zone)s"
msgstr ""

#: nova/volume/cinder.py:349
#, python-format
msgid "volume %s already detached"
msgstr ""

#: nova/compute/api.py:2787
msgid "Volume must be attached in order to detach."
msgstr ""

