# Belarusian translation for apport
# Copyright (c) 2007 Rosetta Contributors and Canonical Ltd 2007
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2007.
#
# Alyaksandr Koshal <alyaksandr.koshal@gmail.com>, 2021
# Вася Пупкін, 2021
# Black Beard (blackbeardboy), 2021
# p k (pkuhto), 2021
# Heorhi Puhachou <h.puhachou@gmail.com>, 2021
# Aleh Gardzey, 2021.
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-12-06 21:23+0000\n"
"PO-Revision-Date: 2023-02-24 21:01+0000\n"
"Last-Translator: Ubuntu Belarusian Translators Team <Unknown>\n"
"Language-Team: Belarusian <be@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2023-03-04 10:28+0000\n"
"X-Generator: Launchpad (build 1938a4fd80bdf1a1b1373119ac1ac9e0e65174d6)\n"
"Language: be\n"

#: ../bin/apport-valgrind.py:37 ../debian/tmp/usr/bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Глядзіце падрабязнасці ў старонках man"

#: ../bin/apport-valgrind.py:46 ../debian/tmp/usr/bin/apport-valgrind.py:46
msgid "specify the log file name produced by valgrind"
msgstr "вызначце імя log файлу valgrind"

#: ../bin/apport-valgrind.py:52 ../debian/tmp/usr/bin/apport-valgrind.py:52
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"выкарыстоўваць раней створаны каталог пясочніцы (SDIR) або стварыць яго калі "
"яго не існуе"

#: ../bin/apport-valgrind.py:60 ../debian/tmp/usr/bin/apport-valgrind.py:60
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"не ствараць і не выкарыстоўваць каталог пясочніцы для дадатковых сімвалаў "
"адладкі, а спадзявацца толькі на устаноўленыя сімвалы адладкі."

#: ../bin/apport-valgrind.py:69 ../debian/tmp/usr/bin/apport-valgrind.py:69
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"выкарыстоўваць раней створаны каталог кэша (CDIR) або стварыць яго калі яго "
"не існуе"

#: ../bin/apport-valgrind.py:78 ../debian/tmp/usr/bin/apport-valgrind.py:78
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"паказваць прагрэс загрузкі/ўстаноўкі пры ўсталёўцы пакетаў у пясочніцу"

#: ../debian/tmp/usr/bin/apport-valgrind.py:62 ../bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"выкананы файл, які запускаецца пад кантролем valgrind memcheck для "
"вызначэння уцечак памяці"

#: ../bin/apport-retrace.py:167 ../bin/apport-valgrind.py:97
#: ../debian/tmp/usr/bin/apport-retrace.py:167
#: ../debian/tmp/usr/bin/apport-valgrind.py:97
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"Усталяваць у часовае асяроддзе дадатковы пакет (можа задавацца некалькі "
"разоў)"

#: ../bin/apport-valgrind.py:129 ../debian/tmp/usr/bin/apport-valgrind.py:129
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Памылка: %s - не выканальны файл. Прыпынак."

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Сабраць сістэмную інфармацыю"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Трэба даць права, каб сабраць патрэбныя дадзеныя для справаздачнасці гэтай "
"праблемы"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Справаздачы аб сістэмных памылках"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""
"Калі ласка, увядзіце пароль для доступу да справаздач пра памылкі ў "
"сістэмных праграмах"

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr "Паведаміць аб праблеме..."

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Паведаміць аб недапрацоўцы распрацоўшчыкам"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Файл справаздачы Apport"

#: ../data/general-hooks/ubuntu.py:219
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:219
msgid ""
"An Ubuntu package has a file conflict with a package that is not a genuine "
"Ubuntu package."
msgstr ""
"Пакет Ubuntu канфліктуе з пакетам, які не з'яўляецца сапраўдным пакетам "
"Ubuntu."

#: ../data/general-hooks/ubuntu.py:234
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:234
msgid "You have already encountered this package installation failure."
msgstr "Памылка з усталёўкай гэтага пакета ўжо адбывалася."

#: ../data/general-hooks/ubuntu.py:224
#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:224
msgid ""
"Your system was initially configured with grub version 2, but you have "
"removed it from your system in favor of grub 1 without configuring it.  To "
"ensure your bootloader configuration is updated whenever a new kernel is "
"available, open a terminal and run:\n"
"\n"
"      sudo apt-get install grub-pc\n"
msgstr ""
"Першапачаткова сістэма была настроена на выкарыстанне загрузчыка GRUB версіі "
"2, але быў заменены на GRUB 1 і не настроена. Каб пераканацца ў "
"працаздольнасці загрузніка з новымі параметрамі, адкрыйце тэрмінал і "
"выканайце каманду:\n"
"\n"
"      sudo apt-get install grub-pc\n"

#: ../bin/apport-cli.py:174 ../debian/tmp/usr/bin/apport-cli.py:174
#: ../debian/tmp/usr/share/apport/apport-gtk.py:169
#: ../debian/tmp/usr/share/apport/apport-kde.py:405 ../gtk/apport-gtk.py:169
#: ../kde/apport-kde.py:405
msgid "(binary data)"
msgstr "(двайковыя дадзеныя)"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:185 ../gtk/apport-gtk.py:185
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Выбачайце, прылада %s нечакана прыпынілася."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:188 ../gtk/apport-gtk.py:188
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Выбачайце, %s нечакана зачынілася."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:193
#: ../debian/tmp/usr/share/apport/apport-kde.py:213
#: ../debian/tmp/usr/share/apport/apport-kde.py:265 ../gtk/apport-gtk.py:193
#: ../kde/apport-kde.py:213 ../kde/apport-kde.py:265
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Прабачце, у %s адбылася ўнутраная памылка."

#: ../bin/apport-cli.py:209 ../debian/tmp/usr/bin/apport-cli.py:209
#: ../debian/tmp/usr/share/apport/apport-gtk.py:208
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-kde.py:198 ../gtk/apport-gtk.py:208
#: ../gtk/apport-gtk.ui.h:6 ../kde/apport-kde.py:198
msgid "Send problem report to the developers?"
msgstr "Даслаць распрацоўшчыкам паведамленне аб праблеме?"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14
#: ../debian/tmp/usr/share/apport/apport-kde.py:206 ../gtk/apport-gtk.py:216
#: ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:206
msgid "Send"
msgstr "Даслаць"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:234
#: ../debian/tmp/usr/share/apport/apport-gtk.py:660
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-kde.py:329 ../gtk/apport-gtk.py:234
#: ../gtk/apport-gtk.py:660 ../gtk/apport-gtk.ui.h:11 ../kde/apport-kde.py:329
msgid "Show Details"
msgstr "Паказаць падрабязнасці"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:247
#: ../debian/tmp/usr/share/apport/apport-kde.py:257
#: ../debian/tmp/usr/share/apport/apport-kde.py:275 ../gtk/apport-gtk.py:247
#: ../kde/apport-kde.py:257 ../kde/apport-kde.py:275
msgid "Continue"
msgstr "Працягнуць"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:271 ../gtk/apport-gtk.py:271
#, python-format
msgid "The application %s has stopped responding."
msgstr "Дадатак %s перастаў адказваць."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:275 ../gtk/apport-gtk.py:275
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Праграма \"%s\" перастала адказваць."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:292
#: ../debian/tmp/usr/share/apport/apport-kde.py:221 ../gtk/apport-gtk.py:292
#: ../kde/apport-kde.py:221
#, python-format
msgid "Package: %s"
msgstr "Пакет: %s"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:298
#: ../debian/tmp/usr/share/apport/apport-kde.py:228 ../gtk/apport-gtk.py:298
#: ../kde/apport-kde.py:228
msgid "Sorry, a problem occurred while installing software."
msgstr "Прабачце, пры ўсталяванні адбылася памылка."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:310
#: ../debian/tmp/usr/share/apport/apport-gtk.py:334
#: ../debian/tmp/usr/share/apport/apport-kde.py:237 ../gtk/apport-gtk.py:310
#: ../gtk/apport-gtk.py:334 ../kde/apport-kde.py:237
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "У дадатку %s адбылася ўнутраная памылка."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:316
#: ../debian/tmp/usr/share/apport/apport-kde.py:244 ../gtk/apport-gtk.py:316
#: ../kde/apport-kde.py:244
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Дастасаванне %s нечакана зачынілася."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:347
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7
#: ../debian/tmp/usr/share/apport/apport-kde.py:270 ../gtk/apport-gtk.py:347
#: ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:270
msgid "If you notice further problems, try restarting the computer."
msgstr "Калі праблема з'явіцца зноў, паспрабуйце перазагрузіць кампутар."

#: ../debian/tmp/usr/share/apport/apport-gtk.py:352
#: ../debian/tmp/usr/share/apport/apport-kde.py:277 ../gtk/apport-gtk.py:352
#: ../kde/apport-kde.py:277
msgid "Ignore future problems of this type"
msgstr "Ігнараваць такія праблемы ў будучыні"

#: ../debian/tmp/usr/share/apport/apport-gtk.py:664
#: ../debian/tmp/usr/share/apport/apport-kde.py:326 ../gtk/apport-gtk.py:664
#: ../kde/apport-kde.py:326
msgid "Hide Details"
msgstr "Схаваць падрабязнасці"

#: ../data/apportcheckresume.py:67
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Гэта адбылося падчас папярэдняга сеансу прыпынення працы і прывяло да "
"немагчымасці належнага аднаўлення працы сістэмы."

#: ../data/apportcheckresume.py:72
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:72
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Гэта адбылося падчас папярэдняга сеансу ўсыплення і прывяло да немагчымасці "
"належнага аднаўлення працы сістэмы."

#: ../data/apportcheckresume.py:80
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:80
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Адбылася памылка ў працэсе стварэння справаздачы, бо сам працэс завіс перад "
"сваім завяршэннем; для нармальнага завяршэння ён павінен быў з'явіцца."

#: ../apport/ui.py:167
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:167
msgid "This package does not seem to be installed correctly"
msgstr "Падобна на тое, што гэты пакет усталяваны неправільна"

#: ../apport/ui.py:177
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:177
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""

#: ../apport/ui.py:207
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:207
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"У Вашай сістэме ўсталяваныя састарэўшыя версіі некаторых пакетаў. Абнавіце "
"наступныя пакеты і праверце, ці засталася праблема:\n"
"\n"
"%s"

#: ../apport/ui.py:370
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:370
msgid "unknown program"
msgstr "невядомая праграма"

#: ../apport/ui.py:373
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:373
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Прабачце, праграма «%s» аварыйна завяршыла сваю работу"

#: ../apport/ui.py:376 ../apport/ui.py:1924
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:376
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1924
#, python-format
msgid "Problem in %s"
msgstr "Праблема ў %s"

#: ../apport/ui.py:381
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:381
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"На Вашым кампутары недастаткова вольнай памяці для таго, каб аўтаматычна "
"прааналізаваць няспраўнасць і даслаць справаздачу распрацоўшчыкам."

#: ../apport/ui.py:441 ../apport/ui.py:459 ../apport/ui.py:632
#: ../apport/ui.py:641 ../apport/ui.py:878 ../apport/ui.py:1688
#: ../apport/ui.py:1885 ../apport/ui.py:1890
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:441
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:459
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:632
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:641
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:878
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1688
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1885
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1890
msgid "Invalid problem report"
msgstr "Няправільная справаздача аб памылцы"

#: ../apport/ui.py:442
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:442
msgid "You are not allowed to access this problem report."
msgstr "У Вас не хапае правоў, каб паведамляць аб праблемах."

#: ../apport/ui.py:450
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:450
msgid "Error"
msgstr "Памылка"

#: ../apport/ui.py:452
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:452
msgid "There is not enough disk space available to process this report."
msgstr "Недастаткова месца на дыску для апрацоўкі дадзенай справаздачы."

#: ../apport/ui.py:490
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:490
msgid "No PID specified"
msgstr ""

#: ../apport/ui.py:492
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:492
msgid "You need to specify a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:503 ../apport/ui.py:608
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:503
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:608
msgid "Invalid PID"
msgstr "Памылковы PID"

#: ../apport/ui.py:504
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:504
msgid "The specified process ID does not exist."
msgstr ""

#: ../apport/ui.py:509
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:509
msgid "Not your PID"
msgstr ""

#: ../apport/ui.py:510
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:510
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../apport/ui.py:565
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:565
msgid "No package specified"
msgstr "Не пазначаны пакет"

#: ../apport/ui.py:567
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:567
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Неабходна пазначыць пакет альбо PID. Запусціце праграму з параметрам --help "
"каб атрымаць дадатковую інфармацыю."

#: ../apport/ui.py:595
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:595
msgid "Permission denied"
msgstr "Доступ забаронены"

#: ../apport/ui.py:597
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:597
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Пазначаны працэс запушчэны іншым карыстальнікам. Запусціце дадзеную праграму "
"з правамі ўладальніка працэса альбо адміністратара сістэмы."

#: ../apport/ui.py:610
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:610
msgid "The specified process ID does not belong to a program."
msgstr "Пазначаны PID належыць іншаму працэсу."

#: ../apport/ui.py:634
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:634
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Сімптаматычны скрыпт %s ня можа вызначыць закрануты пакет"

#: ../apport/ui.py:642
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:642
#, python-format
msgid "Package %s does not exist"
msgstr "Пакет %s не існуе"

#: ../apport/ui.py:671 ../apport/ui.py:883 ../apport/ui.py:916
#: ../apport/ui.py:926
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:671
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:883
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:916
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:926
msgid "Cannot create report"
msgstr "Нельга стварыць справаздачу"

#: ../apport/ui.py:686 ../apport/ui.py:745 ../apport/ui.py:763
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:686
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:745
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:763
msgid "Updating problem report"
msgstr "Абнаўленне справаздачы аб праблеме"

#: ../apport/ui.py:688
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:688
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Вы не з'яўляецеся аўтарам альбо атрымальнікам гэтай справаздачы аб праблеме, "
"магчыма яна ўжо існуе ці была зачыненая."

#: ../apport/ui.py:700
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:700
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Вы не з'яўляецеся стваральнікам дадзенай справаздачы. Нашмат прасцей, "
"адзначыць памылку што яна ўжо існуе, чым ствараць свае каментары і ўкладаць "
"іх у новую памылку\n"
"\n"
"Пасля, мы рэкамендуем Вам падаць новае паведамленне аб памылцы выкарыстання "
"\"памылка apport\", і зрабіць заўвагу аб гэтай памылцы ў тым жа файле.\n"
"\n"
"Вы сапраўды хочаце працягнуць?"

#: ../apport/ui.py:746 ../apport/ui.py:764
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:746
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:764
msgid "No additional information collected."
msgstr "Не сабрана ніякай дадатковай інфармацыі."

#: ../apport/ui.py:827
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:827
msgid "What kind of problem do you want to report?"
msgstr "Пра які тып праблемы Вы хочаце паведаміць?"

#: ../apport/ui.py:848
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:848
msgid "Unknown symptom"
msgstr "Невядомы сімптом"

#: ../apport/ui.py:849
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:849
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Сімптом  \"%s\" невядомы."

#: ../apport/ui.py:885
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:885
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""

#: ../apport/ui.py:901
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:901
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Пасля закрыцця гэтага паведамлення, калі ласка, націсніце на вакно "
"прыкладання, каб паведаміць аб праблеме."

#: ../apport/ui.py:918 ../apport/ui.py:927
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:918
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:927
msgid "xprop failed to determine process ID of the window"
msgstr "xprop не ўдалося вызначыць ID працэсу акна"

#: ../apport/ui.py:772
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:772
msgid "%prog <report number>"
msgstr "%prog <нумар справаздачы>"

#: ../apport/ui.py:943
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:943
msgid "Specify package name."
msgstr "Пазначце імя пакета."

#: ../apport/ui.py:950 ../apport/ui.py:1083
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:950
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1083
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""
"Дадаць дадатковы тэг да справаздачы. Можа быць паказаны некалькі разоў."

#: ../apport/ui.py:807
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:807
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [параметры] [прыкмета|pid|пакет|шлях да праграмы|.apport/.crash файл]"

#: ../apport/ui.py:999
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:999
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Запуск у рэжыме адпраўкі справаздачы аб памылцы. Патрабуе параметр --package "
"і неабавязковы --pid, або толькі --pid. Калі параметры не перададзеныя, "
"адлюстроўвае спіс вядомых сімптомаў. (Ужываецца, калі перададзены адзіны "
"параметр.)"

#: ../apport/ui.py:1008
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1008
msgid "Click a window as a target for filing a problem report."
msgstr "Цокніце па намечаным акне каб запоўніць справаздачу аб праблеме."

#: ../apport/ui.py:1017
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1017
msgid "Start in bug updating mode. Can take an optional --package."
msgstr ""
"Запусціць у рэжыме абнаўлення памылкі. Можа прымаць дадатковы ключ - package."

#: ../apport/ui.py:1026
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1026
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Адправіць справаздачу аб памылцы з сімптомам. (Ужываецца, калі назва "
"сімптома перададзена ў якасці адзінага параметра.)"

#: ../apport/ui.py:1035
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1035
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Пазначыць імя пакета ў рэжыме --file-bug. Неабавязкова, калі пазначаны --"
"pid. (Ужываецца, калі імя пакета перададзена ў якасці адзінага праметра.)"

#: ../apport/ui.py:1046
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1046
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Пазначце запушчаную праграму ў рэжыме - file-bug. У гэтым выпадку "
"справаздача аб памылцы будзе ўтрымліваць больш інфармацыі. (Маецца на ўвазе, "
"што пазначаны адзіны аргумент - pid.)"

#: ../apport/ui.py:1054
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1054
msgid "The provided pid is a hanging application."
msgstr "Згаданы ідэнтыфікатар належыць працэсу, які не адказвае."

#: ../apport/ui.py:1062
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1062
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Адправіць дадзеныя аб збоі з азначанага файла .apport або .crash замест "
"ччакаемых у %s. (Ужываецца, калі файл перададзены ў якасці адзінага "
"параметра.)"

#: ../apport/ui.py:1072
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1072
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"У рэжыме збору справаздачы аб памылках, сабраная інфармацыя захоўваецца ў "
"файле замест яе адпраўкі. Гэты файл можна будзе адправіць пазней, ці з "
"іншага кампутара."

#: ../apport/ui.py:1091
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1091
msgid "Print the Apport version number."
msgstr "Раздрукаваць нумар версіі Apport ."

#: ../apport/ui.py:1253
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1253
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Будзе ажыццёўлены запуск «apport-retrace» у акне тэрміналу для праверкі "
"аварыйнага завяршэння працы."

#: ../apport/ui.py:1257
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1257
msgid "Run gdb session"
msgstr "Запусціць сеанс gdb"

#: ../apport/ui.py:1258
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1258
msgid "Run gdb session without downloading debug symbols"
msgstr "Запусціць сеанс gdb, абыходзячы загрузкі адладкавых сімвалаў"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1260
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1260
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Абнавіць %s з поўным адсочваннем сімвалічнага стэку"

#: ../apport/ui.py:1322
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1322
msgid "Can't remember send report status settings"
msgstr ""

#: ../apport/ui.py:1326
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1326
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../apport/ui.py:1408 ../apport/ui.py:1421
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1408
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1421
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "Дадзеная справаздача адносіцца да праграмы, якая не ўсталявана."

#: ../apport/ui.py:1445
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1445
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Праблема ў праграме %s, да якой былі ўнесены змены з моманту аварыйнага "
"завяршэння яе работы."

#: ../apport/ui.py:1506 ../apport/ui.py:1629 ../apport/ui.py:1894
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1506
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1629
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1894
msgid "This problem report is damaged and cannot be processed."
msgstr "Дадзеная справаздача аб непаладцы пашкоджана і не можа апрацоўвацца."

#: ../apport/ui.py:1515
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1515
msgid "This report is about a package that is not installed."
msgstr ""

#: ../apport/ui.py:1523
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1523
msgid "An error occurred while attempting to process this problem report:"
msgstr "Адбылася памылка пры спробе апрацоўкі справаздачы:"

#: ../apport/ui.py:1540
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1540
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""

#: ../apport/ui.py:1545
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1545
#, python-format
msgid "%s snap"
msgstr ""

#: ../apport/ui.py:1546
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1546
#, python-format
msgid "%s deb package"
msgstr ""

#: ../apport/ui.py:1586
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1586
#, python-format
msgid ""
"%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../apport/ui.py:1591
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1591
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../apport/ui.py:1690
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1690
msgid "Could not determine the package or source package name."
msgstr "Немагчыма вызначыць імя пакету альбо крыніцы."

#: ../apport/ui.py:1715
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1715
msgid "Unable to start web browser"
msgstr "Не атрымалася запусціць вэб-браўзэр"

#: ../apport/ui.py:1716
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1716
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Немагчыма запусціць вэб-браўзэр, каб адчыніць %s."

#: ../apport/ui.py:1398
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1398
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""
"Калі ласка, увядзіце інфармацыю аб уліковым запісы для %s  сістэмы сачэння "
"за памылкамі"

#: ../apport/ui.py:1840
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1840
msgid "Network problem"
msgstr "Праблема з сеткай"

#: ../apport/ui.py:1844
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1844
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Не атрымоўваецца падлучыцца да базы дадзеных па збоях, калі ласка, праверце "
"падлучэнне да Інтэрнэту."

#: ../apport/ui.py:1876
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1876
msgid "Memory exhaustion"
msgstr "Нястача памяці"

#: ../apport/ui.py:1878
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1878
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"У сістэме недастаткова памяці для апрацоўкі дадзенай справаздачы аб памылцы."

#: ../apport/ui.py:1929
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1929
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Немагчыма паведаміць аб праблеме:\n"
"\n"
"%s"

#: ../apport/ui.py:1985 ../apport/ui.py:1997
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1985
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1997
msgid "Problem already known"
msgstr "Праблема ўжо вядомая"

#: ../apport/ui.py:1987
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1987
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Аб дадзенай няспраўнасці ўжо вядома. Існуючая справаздача аб ёй адкрыта ў "
"Вашым браўзэры. Калі ласка, праверце, ці можаце Вы дадаць да яе карысную "
"інфармацыю, якая магла бы дапамагчы распрацоўшчыкам."

#: ../apport/ui.py:1999
#: ../debian/tmp/usr/lib/python3.11/dist-packages/apport/ui.py:1999
msgid "This problem was already reported to developers. Thank you!"
msgstr "Аб гэтай праблеме распрацоўнікам ужо вядома. Дзякуй!"

#: ../debian/tmp/usr/bin/apport-unpack.py:22 ../bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Выкарыстанне: %s <справаздача> <тэчка прызначэння>"

#: ../bin/apport-unpack.py:59 ../debian/tmp/usr/bin/apport-unpack.py:59
msgid "Destination directory exists and is not empty."
msgstr "Тэчка прызначэння існуе і яна не пустая."

#: ../data/kernel_oops.py:30 ../debian/tmp/usr/share/apport/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr "Сістэма можа стаць нестабільнай, магчыма спатрэбіцца перазагрузка."

#: ../bin/apport-retrace.py:44 ../debian/tmp/usr/bin/apport-retrace.py:44
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Не дадаваць новыя трасіроўкі ў справаздачу, а адсылаць на стандартны вывад."

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Запусціць інтэрактыўны сеанс gdb з дампам ядра са справаздачы (-o "
"ігнаруецца; справаздача не перазапісваецца)"

#: ../bin/apport-retrace.py:62 ../debian/tmp/usr/bin/apport-retrace.py:62
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Захаваць змененую справаздачу ў файл замест змены арыгінальнай справаздачы"

#: ../bin/apport-retrace.py:72 ../debian/tmp/usr/bin/apport-retrace.py:72
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Выдаліць дамп ядра са справаздачы пасля ўзнаўлення трасіроўкі стэка"

#: ../bin/apport-retrace.py:80 ../debian/tmp/usr/bin/apport-retrace.py:80
msgid "Override report's CoreFile"
msgstr "Замяніць CoreFile у справаздачы"

#: ../bin/apport-retrace.py:86 ../debian/tmp/usr/bin/apport-retrace.py:86
msgid "Override report's ExecutablePath"
msgstr "Замяніць ExecutablePath у справаздачы"

#: ../bin/apport-retrace.py:92 ../debian/tmp/usr/bin/apport-retrace.py:92
msgid "Override report's ProcMaps"
msgstr "Замяніць ProcMaps у справаздачы"

#: ../bin/apport-retrace.py:98 ../debian/tmp/usr/bin/apport-retrace.py:98
msgid "Rebuild report's Package information"
msgstr "Нанава пабудаваць інфармацыю аб пакетах у справаздачы"

#: ../bin/apport-retrace.py:105 ../debian/tmp/usr/bin/apport-retrace.py:105
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Стварыць часавае асяроддзе, затым загрузіць / ўсталяваць у яе неабходныя "
"пакеты і адладкавыя сімвалы; без гэтага параметра прадугледжваецца, што "
"неабходныя пакеты і адладкавыя сімвалы ў сістэме ўжо ўсталяваныя. Аргумент "
"паказвае на базавую тэчку канфігурацыі сістэмы пакетаў; калі Вы паказалі "
"\"system\", будуць выкарыстоўвацца сістэмныя файлы канфігурацыі, але толькі "
"ў выпадку выяўлення аварыйных сітуацый, якія адбыліся ў выпуску сістэмы, які "
"працуе ў дадзены момант."

#: ../bin/apport-retrace.py:119 ../debian/tmp/usr/bin/apport-retrace.py:119
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""

#: ../bin/apport-retrace.py:129 ../debian/tmp/usr/bin/apport-retrace.py:129
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"Паведамляць аб ходзе выканання загрузкі / ўсталёўкі пакетаў у часовае "
"асяроддзе"

#: ../bin/apport-retrace.py:136 ../debian/tmp/usr/bin/apport-retrace.py:136
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"Дадаваць часовыя пазнакі да паведамленняў у часопісе, для групавых аперацый"

#: ../bin/apport-retrace.py:142 ../debian/tmp/usr/bin/apport-retrace.py:142
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Стварэнне і выкарыстанне іншых сховішчаў на аснове зыходных, указаных у "
"справаздачах"

#: ../bin/apport-retrace.py:150 ../debian/tmp/usr/bin/apport-retrace.py:150
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Тэчка для захавання пакетаў, загружаных у часовае асяроддзе"

#: ../bin/apport-retrace.py:156 ../debian/tmp/usr/bin/apport-retrace.py:156
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Дырэкторыя для распакавання пакетаў. Пры наступных запусках ўсё ўжо "
"загружаны пакеты будуць распакоўваць ў гэта ізаляванае асяроддзе."

#: ../bin/apport-retrace.py:174 ../debian/tmp/usr/bin/apport-retrace.py:174
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Шлях да файла з інфармацыяй аб праверцы сапраўднасці базы збояў. "
"Выкарыстоўваецца пры ўказанні ID збою для адпраўкі трасіровак стэка (толькі "
"калі -g, -o ці -s не пазначаныя)"

#: ../bin/apport-retrace.py:184 ../debian/tmp/usr/bin/apport-retrace.py:184
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Адлюстраваць трасіроўкі і запытаць пацверджанне перад іх адпраўкай у базу "
"дадзеных збояў."

#: ../bin/apport-retrace.py:192 ../debian/tmp/usr/bin/apport-retrace.py:192
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Шлях да дублюючай базы дадзеных sqlite (па змаўчанні: без праверкі "
"дублікатаў)"

#: ../bin/apport-retrace.py:200 ../debian/tmp/usr/bin/apport-retrace.py:200
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../bin/apport-retrace.py:213 ../debian/tmp/usr/bin/apport-retrace.py:213
msgid "You cannot use -C without -S. Stopping."
msgstr "Нельга выкарыстоўваць -C без -S. Прыпынак."

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:243 ../debian/tmp/usr/bin/apport-retrace.py:243
msgid "OK to send these as attachments? [y/n]"
msgstr "Адправіць іх як далучэнні? [так/не]"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-kde.py:545
#: ../debian/tmp/usr/share/apport/apport-kde.py:588 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:545 ../kde/apport-kde.py:588
msgid "Apport"
msgstr "Apport"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Скасаваць"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "Добра"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Справаздача аб непаладцы"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Выбачайце, паўстала ўнутраная памылка.</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9 ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Ігнараваць далейшыя збоі ў гэтай версіі праграмы"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12 ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Лакальная праверка"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15 ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Збор інфармацыі аб няспраўнасці</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16 ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"Адбываецца збор інфармацыі, якая можа дапамагчы распрацоўшчыкам выправіць "
"гэтую памылку."

#: ../bin/apport-cli.py:301 ../debian/tmp/usr/bin/apport-cli.py:301
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-kde.py:504 ../gtk/apport-gtk.ui.h:17
#: ../kde/apport-kde.py:504
msgid "Uploading problem information"
msgstr "Перадача інфармацыі аб непаладцы"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18 ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Перадача звестак аб няспраўнасці</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19
#: ../debian/tmp/usr/share/apport/apport-kde.py:506 ../gtk/apport-gtk.ui.h:19
#: ../kde/apport-kde.py:506
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Сабраныя дадзеныя перасылаюцца ў сістэму ўліку памылак. Гэта можа заняць "
"некалькі хвілін."

#: ../debian/tmp/usr/share/apport/apport-kde.py:260 ../kde/apport-kde.py:260
msgid "Leave Closed"
msgstr "Пакінуць зачыненым"

#: ../debian/tmp/usr/share/apport/apport-kde.py:261
#: ../debian/tmp/usr/share/apport/apport-kde.py:425 ../kde/apport-kde.py:261
#: ../kde/apport-kde.py:425
msgid "Relaunch"
msgstr "Перазапусціць"

#: ../debian/tmp/usr/share/apport/apport-kde.py:354 ../kde/apport-kde.py:354
msgid "Username:"
msgstr "Імя карыстальніка:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:355 ../kde/apport-kde.py:355
msgid "Password:"
msgstr "Пароль:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:454 ../kde/apport-kde.py:454
msgid "Collecting Problem Information"
msgstr "Збор інфармацыі аб праблеме"

#: ../bin/apport-cli.py:283 ../debian/tmp/usr/bin/apport-cli.py:283
#: ../debian/tmp/usr/share/apport/apport-kde.py:455 ../kde/apport-kde.py:455
msgid "Collecting problem information"
msgstr "Збор інфармацыі аб праблеме"

#: ../debian/tmp/usr/share/apport/apport-kde.py:457 ../kde/apport-kde.py:457
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Сабраную інфармацыю можна адправіць распрацоўшчыкам, каб палепшыць праграму. "
"Гэта можа заняць некалькі хвілін."

#: ../debian/tmp/usr/share/apport/apport-kde.py:503 ../kde/apport-kde.py:503
msgid "Uploading Problem Information"
msgstr "Перадача інфармацыі аб непаладцы"

#: ../bin/apport-cli.py:84 ../debian/tmp/usr/bin/apport-cli.py:84
msgid "Press any key to continue..."
msgstr "Каб працягнуць, націсніце любую клавішу ..."

#: ../bin/apport-cli.py:91 ../debian/tmp/usr/bin/apport-cli.py:91
msgid "What would you like to do? Your options are:"
msgstr "Што вы жадаеце зрабіць? Магчымыя варыянты:"

#: ../bin/apport-cli.py:104 ../debian/tmp/usr/bin/apport-cli.py:104
#, python-format
msgid "Please choose (%s):"
msgstr "Калі ласка выберыце (%s):"

#: ../bin/apport-cli.py:172 ../debian/tmp/usr/bin/apport-cli.py:172
#, python-format
msgid "(%i bytes)"
msgstr "(%i байт)"

#: ../bin/apport-cli.py:211 ../debian/tmp/usr/bin/apport-cli.py:211
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Пасля таго, як справаздача будзе дасланая, запоўніце\n"
"форму ў акне браўзэра , што адчынілася аўтаматычна."

#: ../bin/apport-cli.py:218 ../debian/tmp/usr/bin/apport-cli.py:218
#, python-format
msgid "&Send report (%s)"
msgstr "&Даслаць паведамленне (%s)"

#: ../bin/apport-cli.py:223 ../debian/tmp/usr/bin/apport-cli.py:223
msgid "&Examine locally"
msgstr "&Локальна перевірка"

#: ../bin/apport-cli.py:227 ../debian/tmp/usr/bin/apport-cli.py:227
msgid "&View report"
msgstr "&Паказаць справаздачу"

#: ../bin/apport-cli.py:230 ../debian/tmp/usr/bin/apport-cli.py:230
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Захаваць файл справаздачы для наступнай адпраўкі альбо капіявання куды-"
"небудзь"

#: ../bin/apport-cli.py:235 ../debian/tmp/usr/bin/apport-cli.py:235
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Адмяніць і &ігнараваць будучыя збоі ў гэтай версіі праграмы"

#: ../bin/apport-cli.py:238 ../bin/apport-cli.py:326 ../bin/apport-cli.py:360
#: ../bin/apport-cli.py:383 ../debian/tmp/usr/bin/apport-cli.py:238
#: ../debian/tmp/usr/bin/apport-cli.py:326
#: ../debian/tmp/usr/bin/apport-cli.py:360
#: ../debian/tmp/usr/bin/apport-cli.py:383
msgid "&Cancel"
msgstr "&Скасаваць"

#: ../bin/apport-cli.py:267 ../debian/tmp/usr/bin/apport-cli.py:267
msgid "Problem report file:"
msgstr "Файл справаздачы аб праблеме:"

#: ../bin/apport-cli.py:273 ../bin/apport-cli.py:278
#: ../debian/tmp/usr/bin/apport-cli.py:273
#: ../debian/tmp/usr/bin/apport-cli.py:278
msgid "&Confirm"
msgstr "&Пацвердзіць"

#: ../bin/apport-cli.py:277 ../debian/tmp/usr/bin/apport-cli.py:277
#, python-format
msgid "Error: %s"
msgstr "Памылка: %s"

#: ../bin/apport-cli.py:285 ../debian/tmp/usr/bin/apport-cli.py:285
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Сабраная інфармацыя можа быць накіравана распрацоўшчыкам для\n"
"паляпшэння праграмы. Гэта можа заняць некалькі хвілін."

#: ../bin/apport-cli.py:303 ../debian/tmp/usr/bin/apport-cli.py:303
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Сабраная інфармацыя накіроўваецца да сістэмы адсочвання памылак.\n"
"Гэта можа заняць некалькі хвілін."

#: ../bin/apport-cli.py:359 ../debian/tmp/usr/bin/apport-cli.py:359
msgid "&Done"
msgstr "&Зроблена"

#: ../bin/apport-cli.py:365 ../debian/tmp/usr/bin/apport-cli.py:365
msgid "none"
msgstr "нічога"

#: ../bin/apport-cli.py:367 ../debian/tmp/usr/bin/apport-cli.py:367
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Абрана: %s. Некалькі варыянтаў:"

#: ../bin/apport-cli.py:384 ../debian/tmp/usr/bin/apport-cli.py:384
msgid "Choices:"
msgstr "Выбар:"

#: ../bin/apport-cli.py:398 ../debian/tmp/usr/bin/apport-cli.py:398
msgid "Path to file (Enter to cancel):"
msgstr "Шлях да файла (Enter — адмена):"

#: ../bin/apport-cli.py:404 ../debian/tmp/usr/bin/apport-cli.py:404
msgid "File does not exist."
msgstr "Файл не існуе."

#: ../bin/apport-cli.py:406 ../debian/tmp/usr/bin/apport-cli.py:406
msgid "This is a directory."
msgstr "Гэта - дырэкторыя."

#: ../bin/apport-cli.py:412 ../debian/tmp/usr/bin/apport-cli.py:412
msgid "To continue, you must visit the following URL:"
msgstr "Каб працягнуць, Вы павінны наведаць наступны адрас:"

#: ../bin/apport-cli.py:415 ../debian/tmp/usr/bin/apport-cli.py:415
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Зараз Вы можаце адкрыць браўзар ці скапіяваць URL у браўзар на іншы кампутар."

#: ../bin/apport-cli.py:421 ../debian/tmp/usr/bin/apport-cli.py:421
msgid "Launch a browser now"
msgstr "Запусціць браўзар"

#: ../bin/apport-cli.py:437 ../debian/tmp/usr/bin/apport-cli.py:437
msgid "No pending crash reports. Try --help for more information."
msgstr "Няма чакаючых паведамленьняў аб збоях. Паспрабуйце ключ --help."
