# Ukrainian translations for PROJECT.
# Copyright (C) 2012 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-19 06:56+0000\n"
"PO-Revision-Date: 2018-05-06 15:31+0000\n"
"Last-Translator: Andrii Prokopenko <Unknown>\n"
"Language-Team: uk <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-03-25 09:32+0000\n"
"X-Generator: Launchpad (build aec24aef7a9042c99ef3e238d8b0ca01df9e1a9f)\n"
"Generated-By: Babel 1.3\n"

#: glance/location.py:101
msgid "Invalid location"
msgstr "Невірне розташування"

#: glance/location.py:333
msgid "Invalid locations"
msgstr "Невірні розташування"

#: glance/store/__init__.py:667
#, python-format
msgid "Original locations is not empty: %s"
msgstr "Початкове розташування не порожнє: %s"

#: glance/location.py:440
msgid "Signature verification failed"
msgstr "Перевірка підпису не виконана."

#: glance/store/__init__.py:739
#, python-format
msgid "Get image %(id)s data failed: %(err)s."
msgstr "Не вдалося отримати дані образу %(id)s: %(err)s."

#: glance/notifier.py:239 glance/api/v1/upload_utils.py:184
#: glance/api/v2/image_data.py:107
#, python-format
msgid "Image storage media is full: %s"
msgstr "На накопичувачі з образом закінчилося вільне місце: %s"

#: glance/notifier.py:243 glance/api/v1/upload_utils.py:193
#: glance/api/v2/image_data.py:128
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr "Недостатні дозволи на носіях даних зображення: %s"

#: glance/notifier.py:248
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr "Неможливо зберегти дані для образу %(image_id)s: %(error)s"

#: glance/notifier.py:254
#, python-format
msgid ""
"Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""
"Неможливо завантажити дублюючу інформацію для образу %(image_id)s: %(error)s"

#: glance/notifier.py:261
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr ""
"Не дозволено завантажити інформацію для образу %(image_id)s: %(error)s"

#: glance/notifier.py:267
#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have been "
"deleted during the upload: %(error)s"
msgstr ""
"Образ %(image_id)s не був знайдений після завантаження. Можливо, образ був "
"вилучений під час завантаження: %(error)s"

#: glance/notifier.py:274
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""
"Неможливо завантажити інформацію про образ %(image_id)s через HTTP помилку: "
"%(error)s"

#: glance/notifier.py:281
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error: "
"%(error)s"
msgstr ""
"Не вдалося завантажити дані образу для образу %(image_id)s з-за внутрішньої "
"помилки: %(error)s"

#: glance/schema.py:58
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr ""
"користувальницькі властивості (%(props)s) конфліктують  з базовими "
"властивостями"

#: glance/scrubber.py:42 glance/store/__init__.py:58
msgid "The amount of time in seconds to delay before performing a delete."
msgstr "Кількість часу (у секундах) до виконання вилучення."

#: glance/scrubber.py:40
msgid ""
"The size of thread pool to be used for scrubbing images. The default is one, "
"which signifies serial scrubbing. Any value above one indicates the max "
"number of images that may be scrubbed in parallel."
msgstr ""
"Розмір пулу потоків, що використовується для чистки образів. Типово один, що "
"означає послідовну чистку. Усі значення більше одного означають максимальну "
"кількість образів, які можуть бути очищені паралельно."

#: glance/store/__init__.py:53
msgid "Turn on/off delayed delete."
msgstr "Увімкнути/вимкнути затримка вилучення"

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr ""
"Роль використовуватись для ідентифікації автентичності користувача з правами "
"адміністратора."

#: glance/scrubber.py:51 glance/registry/client/v1/api.py:34
msgid ""
"Whether to pass through headers containing user and tenant information when "
"making requests to the registry. This allows the registry to use the context "
"middleware without keystonemiddleware's auth_token middleware, removing "
"calls to the keystone auth service. It is recommended that when using this "
"option, secure communication between glance api and glance registry is "
"ensured by means other than auth_token middleware."
msgstr ""
"Чи передавати заголовки, що містять інформацію про користувачів і "
"арендаторів, при відправці запитів до реєстру. Дозволяє реєстру "
"використовувати проміжне проґрамне забезпечення контексту без проміжного "
"проґрамного забезпечення auth_token Keystone, вилучаючи виклики до служби "
"ідентифікації Keystone. При використанні цієї опції рекомендується "
"встановити захищене з’єднання між api glance та реєстром glance за допомогою "
"проміжного проґрамного забезпечення, що відрізняється від auth_token."

#: glance/scrubber.py:64
msgid "Loop time between checking for new items to schedule for delete."
msgstr "Час циклу між перевіркою нових об’єктів відкладених до вилучення."

#: glance/scrubber.py:72
msgid ""
"Run as a long-running process. When not specified (the default) run the "
"scrub operation once and then exits. When specified do not exit and run "
"scrub on wakeup_time interval as specified in the config."
msgstr ""
"Виконується як тривалий процес. Коли не вказаний (типово), виконується "
"операція очистки один раз, потім виконується вихід. Коли вказаний, вихід не "
"виконується й виконуєтьсяя очистка з інтервалом wakeup_time, вказаним у "
"конфігурації."

#: glance/api/authorization.py:197 glance/api/authorization.py:380
msgid "Public images do not have members."
msgstr "Публічні образи не мають елементів."

#: glance/api/authorization.py:118 glance/api/authorization.py:129
#, python-format
msgid "You cannot get image member for %s"
msgstr "Ви не можете отримати елемент образу, для %s"

#: glance/api/authorization.py:137
#, python-format
msgid "You cannot delete image member for %s"
msgstr "Ви не можете вилучити елемент образу, для %s"

#: glance/api/authorization.py:146
#, python-format
msgid "You cannot add image member for %s"
msgstr "Ви не можете додавати елемент образу для % s"

#: glance/api/authorization.py:155
#, python-format
msgid "You cannot update image member %s"
msgstr "Не вдається оновити елемент образу % s"

#: glance/api/authorization.py:174
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr "Вам не дозволяється створювати образи, що належать '%s'."

#: glance/api/authorization.py:192
msgid "You are not permitted to create image members for the image."
msgstr "Вам не дозволяється створювати графічні елементи для образу."

#: glance/api/authorization.py:213
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr "Вам не дозволено змінювати '%(attr)s' цього %(resource)s."

#: glance/api/authorization.py:223
msgid "You are not permitted to modify locations for this image."
msgstr "Вам не дозволяється змінювати адресу для цього образу."

#: glance/api/authorization.py:247
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr "Вам не дозволяється змінювати '%s' на цей образ."

#: glance/api/authorization.py:251
msgid "You are not permitted to modify this image."
msgstr "Вам не дозволяється змінювати цей образ."

#: glance/api/authorization.py:264
msgid "You are not permitted to modify tags on this image."
msgstr "Вам не дозволяється змінювати теги на цей образ."

#: glance/api/authorization.py:305
msgid "You are not permitted to delete this image."
msgstr "Ви не можете вилучити цей образ."

#: glance/api/authorization.py:316
msgid "You are not permitted to upload data for this image."
msgstr "Вам не дозволяється завантажити дані для цього образу."

#: glance/api/authorization.py:342
msgid "You are not permitted to deactivate this image."
msgstr "Вам не дозволено деактивувати цей образ."

#: glance/api/authorization.py:346
msgid "You are not permitted to reactivate this image."
msgstr "Вам не дозволено вдруге активувати цей образ."

#: glance/api/authorization.py:350 glance/api/authorization.py:354
#: glance/api/authorization.py:358
msgid "You are not permitted to set status on this task."
msgstr "Вам не дозволено встановлювати статус цього завдання."

#: glance/api/authorization.py:420
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr ""
"Вам не дозволено створювати це завдання, використовуючи у ролі власника "
"користувача %s"

#: glance/api/authorization.py:515
msgid "You are not permitted to delete this namespace."
msgstr "Ви не можете вилучити цей простор імен"

#: glance/api/authorization.py:519
msgid "You are not permitted to update this namespace."
msgstr "Ви не можете оновити це простір імен"

#: glance/api/authorization.py:545
#, python-format
msgid "You are not permitted to create namespace owned by '%s'"
msgstr "Ви не можете створити простір імен, який належить '%s'"

#: glance/api/authorization.py:604
msgid "You are not permitted to delete this object."
msgstr "Ви не можете вилучити цей об'єкт."

#: glance/api/authorization.py:608
msgid "You are not permitted to update this object."
msgstr "Ви не можете оновити цей об'єкт."

#: glance/api/authorization.py:633
#, python-format
msgid "You are not permitted to create object owned by '%s'"
msgstr "Ви не можете сотворите об'єкт, який належить '%s'"

#: glance/api/authorization.py:696
msgid "You are not permitted to delete this meta_resource_type."
msgstr "Ви не можете вилучити цей meta_resource_type."

#: glance/api/authorization.py:722
#, python-format
msgid "You are not permitted to create resource_type owned by '%s'"
msgstr "Немає прав доступу на створення resource_type, що належить %s."

#: glance/api/authorization.py:780
msgid "You are not permitted to delete this property."
msgstr "Ви не можете вилучити цю властивість."

#: glance/api/authorization.py:784
msgid "You are not permitted to update this property."
msgstr "Ви не можете оновити цю властивість."

#: glance/api/authorization.py:809
#, python-format
msgid "You are not permitted to create property owned by '%s'"
msgstr "Ви не можете створити властивість, яка належить '%s'."

#: glance/api/authorization.py:867
msgid "You are not permitted to delete this tag."
msgstr "Ви не можете вилучити цей тег."

#: glance/api/authorization.py:871
msgid "You are not permitted to update this tag."
msgstr "Ви не можете змінити значення цього тегу."

#: glance/api/authorization.py:892
msgid "Owner must be specified to create a tag."
msgstr "Власник може бути також вказаний при створенні тегу."

#: glance/api/authorization.py:895
#, python-format
msgid "You are not permitted to create a tag in the namespace owned by '%s'"
msgstr "Ви не можете створювати теги з набору імен до яких належить '%s'"

#: glance/api/common.py:56
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr "Пошкоджено образ для завантаженого %(image_id)s"

#: glance/api/policy.py:220 glance/quota/__init__.py:343
#: glance/store/__init__.py:662
#, python-format
msgid "Invalid locations: %s"
msgstr "Пошкоджено адресу: %s"

#: glance/api/versions.py:27 glance/api/glare/versions.py:28
msgid ""
"Public url to use for versions endpoint. The default is None, which will use "
"the request's host_url attribute to populate the URL base. If Glance is "
"operating behind a proxy, you will want to change this to represent the "
"proxy's URL."
msgstr ""
"Спільна url для кінцевої точки версій. Типове значення - None, при якому для "
"заповнення бази URL буде використовуватися атрибут host_url запиту. Якщо "
"Glance розташований за proxy-сервером, то знадобиться вказати URL proxy-"
"сервера."

#: glance/api/glare/v0_1/glare.py:121
#, python-format
msgid "The format of the version %s is not valid. Use semver notation"
msgstr "Неприпустимий формат версії %s. використовуйте формат semver"

#: glance/api/glare/v0_1/glare.py:188
#, python-format
msgid "Invalid Content-Type for work with %s"
msgstr "Неприпустимий Content-Type для роботи з %s"

#: glance/api/glare/v0_1/glare.py:225
msgid "Invalid request PATCH for work with blob"
msgstr "Неприпустимий PATCH запиту для роботи з об’єктом blob"

#: glance/api/glare/v0_1/glare.py:239
#, python-format
msgid "Denying attempt to upload artifact because it exceeds the quota: %s"
msgstr "Заперечення спроби завантажити артефакт через перевищення квоти: %s"

#: glance/api/glare/v0_1/glare.py:263
#, python-format
msgid "Failed to find artifact %(artifact_id)s to delete"
msgstr "Не вдалося знайти артефакт %(artifact_id)s для вилучення"

#: glance/api/glare/v0_1/glare.py:267
#, python-format
msgid "Artifact %s could not be deleted because it is in use: %s"
msgstr "Не вдалося вилучити артефакт %s, оскільки він використовується: %s"

#: glance/api/glare/v0_1/glare.py:296
msgid "Unable to PUT to non-empty collection"
msgstr "Не вдалося виконати операцію PUT у непорожній набір"

#: glance/api/glare/v0_1/glare.py:299
msgid "Index is out of range"
msgstr "Індекс знаходиться поза діяпазоном"

#: glance/api/glare/v0_1/glare.py:322
#, python-format
msgid "Not a blob property '%s'"
msgstr "Не є властивістю великого двійкового об’єкту '%s'"

#: glance/api/glare/v0_1/glare.py:330
#, python-format
msgid "Not a list property '%s'"
msgstr "Не є властивістю переліку '%s'"

#: glance/api/glare/v0_1/glare.py:344
msgid "Error in store configuration. Adding artifacts to store is disabled."
msgstr ""
"Помилка у конфігурації сховища. Додавання артефактів у сховище відімкнено."

#: glance/api/glare/v0_1/glare.py:366
#, python-format
msgid "Artifact storage media is full: %s"
msgstr "Носій сховища артефактів заповнений: %s"

#: glance/api/glare/v0_1/glare.py:374
#, python-format
msgid "Artifact exceeds the storage quota: %s"
msgstr "Артефакт перевищує квоту сховища: %s"

#: glance/api/glare/v0_1/glare.py:382
#, python-format
msgid "The incoming artifact blob is too large: %s"
msgstr "Завеликий розмір вхідного артефакту: %s"

#: glance/api/glare/v0_1/glare.py:390
#, python-format
msgid "Insufficient permissions on artifact storage media: %s"
msgstr "Брак прав для доступу до носія артефактів: %s"

#: glance/api/glare/v0_1/glare.py:423
msgid "Index is required"
msgstr "Потрібен індекс"

#: glance/api/glare/v0_1/glare.py:431
msgid "Not a list property"
msgstr "Не є властивістю переліку"

#: glance/api/glare/v0_1/glare.py:435
msgid "Not a downloadable entity"
msgstr "Не є завантажуваною сутністю"

#: glance/api/v2/image_members.py:189 glance/api/v2/images.py:287
msgid "Body expected in request."
msgstr "У запиті очікувалося тіло."

#: glance/api/glare/v0_1/glare.py:577
#, python-format
msgid "Invalid headers \"Content-Type\": %s"
msgstr "Неприпустимі заголовки \"Content-Type\": %s"

#: glance/api/glare/v0_1/glare.py:615
#, python-format
msgid "Invalid json body: %s"
msgstr "Неприпустиме тіло json: %s"

#: glance/api/glare/v0_1/glare.py:628
msgid "Only list indexes are allowed for blob lists"
msgstr ""
"Для переліків великих двійкових об’єктів дозволені лише індекси переліків"

#: glance/api/glare/v0_1/glare.py:649
msgid "Limit param must be an integer"
msgstr "Параметр обмеження має бути цілим числом"

#: glance/api/glare/v0_1/glare.py:653
msgid "Limit param must be positive"
msgstr "Параметр Limit має бути додатнім числом"

#: glance/api/glare/v0_1/glare.py:657
#, python-format
msgid "Limit param must not be higher than %d"
msgstr "Параметр обмеження не повинен перевищувати %d"

#: glance/api/glare/v0_1/glare.py:667
#, python-format
msgid ""
"Invalid sort key: %(sort_key)s. If type version is not set it must be one of "
"the following: %(available)s."
msgstr ""
"Неприпустимий ключ сортування: %(sort_key)s. Якщо версія типу не задана, "
"допускається один із наступних: %(available)s."

#: glance/api/glare/v0_1/glare.py:678
#, python-format
msgid "Invalid sort key: %(sort_key)s. You cannot sort by this property"
msgstr ""
"Неприпустимий ключ сортування: %(sort_key)s. Неможна виконувати сортування "
"за цією властивістю"

#: glance/api/v2/images.py:498 glance/api/v2/tasks.py:134
#, python-format
msgid "Invalid sort direction: %s"
msgstr "Неприпустимий напрямок сортування: %s"

#: glance/api/middleware/context.py:28
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing "
"the request."
msgstr ""
"Якщо true, то цей параметр встановлює власником образу орендаря. В іншому "
"випадку, власник образу буде автентифікований як користувач, що виконує "
"запит."

#: glance/api/middleware/context.py:36
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""
"Дозволяє користувачам, які не пройшли перевірку для доступу до API права "
"лише на читання. Це застосовується лише при використанні ContextMiddleware."

#: glance/api/middleware/context.py:41
msgid "Limits request ID length."
msgstr "Обмежує довжину ідентифікатора запиту"

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr "Не вдається отримати ідентифікатор запиту від контексту"

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr "Невірний каталог послуг json."

#: glance/api/middleware/context.py:125
#, python-format
msgid "x-openstack-request-id is too long, max size %s"
msgstr "Завелика довжина x-openstack-request-id, максимальна довжина: %s"

#: glance/api/v1/controller.py:41 glance/api/v1/members.py:76
#, python-format
msgid "Image with identifier %s not found"
msgstr "Образ з ідентифікатором %s не знайдено"

#: glance/api/v1/controller.py:46
msgid "Forbidden image access"
msgstr "Доступ до образу заборонено"

#: glance/api/v1/controller.py:61
#, python-format
msgid "Image %s is deactivated"
msgstr "Образ %s деактивований"

#: glance/api/v1/controller.py:59
#, python-format
msgid "Image %s is not active"
msgstr "Образ %s не є активним"

#: glance/api/v1/controller.py:81
#, python-format
msgid "Store for image_id not found: %s"
msgstr "Сховище для image_id, не знайдено: %s"

#: glance/api/v1/controller.py:93
#, python-format
msgid "Data for image_id not found: %s"
msgstr "Не знайдені дані для image_id: %s"

#: glance/api/v1/images.py:87
#, python-format
msgid "Invalid time format for %s."
msgstr "Неприпустимий формат часу для %s."

#: glance/api/v1/images.py:73
#, python-format
msgid "Invalid disk format '%s' for image."
msgstr "Неправильний формат '%s' диска для зображення."

#: glance/api/v1/images.py:78
#, python-format
msgid "Invalid container format '%s' for image."
msgstr "Неправильний формат '%s' контейнера для зображення."

#: glance/api/v1/images.py:94
msgid ""
"Invalid mix of disk and container formats. When setting a disk or container "
"format to one of 'aki', 'ari', or 'ami', the container and disk formats must "
"match."
msgstr ""
"Неприпустиме поєднання дисків і форматів контейнера. При встановленні диска "
"або формат контейнера до одного 'aki', 'ari', або 'ami' формати контейнеру і "
"дисків повинні збігатися."

#: glance/api/v1/images.py:83
#, python-format
msgid "Image name too long: %d"
msgstr "Для образу занадто довге ім'я: %d"

#: glance/api/v1/images.py:139
#, python-format
msgid "Invalid checksum '%s': can't exceed 32 characters"
msgstr "Неправильна контрольна сума '%s': не може перевищувати 32 символи"

#: glance/api/v1/images.py:172
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""
"Був перевищений ліміт кількості дозволених властивостей образу. Значення: "
"%(num)s, максимум: %(quota)s"

#: glance/api/v1/images.py:194 glance/api/v1/images.py:238
#: glance/api/v1/images.py:272
#, python-format
msgid "Property '%s' is protected"
msgstr "Параметр '%s' захищено"

#: glance/api/v1/images.py:388
msgid "This operation is currently not permitted on Glance images details."
msgstr "Ця операція на цей час неприпустима на відомостях образів Glance."

#: glance/api/v1/images.py:380
#, python-format
msgid "Bad value passed to filter %(filter)s got %(val)s"
msgstr "Неправильне значення для фільтру %(filter)s що отримав(ли) %(val)s"

#: glance/api/v1/images.py:477
#, python-format
msgid "External sources are not supported: '%s'"
msgstr "Зовнішні ресурси не підтримуються: %s"

#: glance/api/v1/images.py:479
msgid "External source should not be empty"
msgstr "Зовнішнє джерело не повинне бути порожнім"

#: glance/api/v1/images.py:493
#, python-format
msgid "Required store %s is invalid"
msgstr "Запитуване сховище %s недійсне"

#: glance/api/v1/images.py:505 glance/api/v1/images.py:877
#, python-format
msgid "Invalid location %s"
msgstr "Невірне розташування %s"

#: glance/api/v1/images.py:528
#, python-format
msgid "An image with identifier %s already exists"
msgstr "Образ з ідентифікатором %s вже існує"

#: glance/api/v1/images.py:621
#, python-format
msgid "Failed to reserve image. Got error: %s"
msgstr "Зарезервувати образ не вдалося. Помилка: %s"

#: glance/api/v1/images.py:542
msgid "Forbidden to reserve image."
msgstr "Забороняється резервування образу."

#: glance/api/v1/images.py:578
msgid "Content-Type must be application/octet-stream"
msgstr "Content-Type повинно бути application/octet-stream"

#: glance/api/v1/images.py:729
#, python-format
msgid "Failed to activate image. Got error: %s"
msgstr "Не вдалося активувати образ. Сталася помилка: %s"

#: glance/api/v1/images.py:683
msgid "It's invalid to provide multiple image sources."
msgstr "Неприпустиме надання декількох джерел для образу."

#: glance/api/v1/images.py:709
#, python-format
msgid ""
"Provided image size must match the stored image size. (provided size: "
"%(ps)d, stored size: %(ss)d)"
msgstr ""
"Розмір наданого образу повинен відповідати розміру збереженого образу. "
"(Наданий: %(ps)d, збережений: %(ss)d)"

#: glance/api/v1/images.py:855
msgid "Disk format is not specified."
msgstr "Не вказаний формат диску."

#: glance/api/v1/images.py:860
msgid "Container format is not specified."
msgstr "Не вказаний формат контейнера."

#: glance/api/v1/images.py:831
msgid "Forbidden to update deleted image."
msgstr "Забороняється оновлювати вилучений образ."

#: glance/api/v1/images.py:978
#, python-format
msgid "Forbidden to modify '%(key)s' of %(status)s image."
msgstr "Заборонено змінювати '%(key)s' образу %(status)s."

#: glance/api/v1/images.py:987
#, python-format
msgid "Forbidden to modify '%s' of image."
msgstr "Забороненоо вносити зміни в образ '%s'."

#: glance/api/v1/images.py:860
msgid "Cannot upload to an unqueued image"
msgstr "Не вдається завантажити образ з черги"

#: glance/store/__init__.py:469
#, python-format
msgid "Invalid location: %s"
msgstr "Некоректна адреса: %s"

#: glance/api/v1/images.py:884
msgid "Attempted to update Location field for an image not in queued status."
msgstr "Спробував оновити місцезнаходження  на образ, що не в черзі."

#: glance/api/v1/images.py:1069 glance/registry/api/v1/images.py:502
#, python-format
msgid "Failed to update image metadata. Got error: %s"
msgstr "Не вдалося оновити метадані образу. Сталася помилка: %s"

#: glance/api/v1/images.py:1076
#, python-format
msgid "Failed to find image to update: %s"
msgstr "Знайти образ для оновлення не вдалося: %s"

#: glance/api/v1/images.py:1083
#, python-format
msgid "Forbidden to update image: %s"
msgstr "Оновлення образу неприпустиме: %s"

#: glance/api/v1/images.py:1091
msgid "Image operation conflicts"
msgstr "Конфлікти при виконанні операцій з образом"

#: glance/api/v1/images.py:977
msgid "Image is protected"
msgstr "Образ захищено"

#: glance/api/v1/images.py:984
#, python-format
msgid "Forbidden to delete a %s image."
msgstr "Забороняється вилучити %s образ."

#: glance/api/v1/images.py:989
#, python-format
msgid "Image %s not found."
msgstr "Образ %s не знайдено."

#: glance/api/v1/images.py:1171
#, python-format
msgid "Failed to find image to delete: %s"
msgstr "Знайти образ для вилучення не вдалося: %s"

#: glance/api/v1/images.py:1178
#, python-format
msgid "Forbidden to delete image: %s"
msgstr "Заборонено вилучати образ: %s"

#: glance/api/v1/images.py:1185 glance/api/v2/images.py:246
#, python-format
msgid "Image %(id)s could not be deleted because it is in use: %(exc)s"
msgstr ""
"Образ %(id)s не може бути вилучений, тому що використовується: %(exc)s"

#: glance/api/v1/images.py:1052 glance/store/__init__.py:231
#, python-format
msgid "Store for scheme %s not found"
msgstr "Сховище для схеми %s не знайдено"

#: glance/api/v1/images.py:1091 glance/api/v1/upload_utils.py:202
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr "Відмовлено у спробі завантажити образ більше ніж %d байт."

#: glance/api/v1/members.py:41 glance/registry/api/v1/members.py:32
msgid "No authenticated user"
msgstr "Відсутній автентифікований користувач"

#: glance/api/v1/members.py:53
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr "Образ з ідентифікатором %s було вилучено."

#: glance/api/v1/members.py:80
msgid "Unauthorized image access"
msgstr "Несанкціонований доступ до образу"

#: glance/api/v1/members.py:117 glance/common/exception.py:287
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for this "
"image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Ліміт кількості дозволених користувачів образу був вичерпаний. Кількість: "
"%(attempted)s, максимум: %(maximum)s"

#: glance/api/v1/upload_utils.py:115
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded image "
"(%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""
"Надані %(attr)s (%(supplied)s) і %(attr)s, згенеровані з завантаженого "
"образу (%(actual)s), не збігаються. Зміна статусу образу на 'вбитий'."

#: glance/api/v1/upload_utils.py:148
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload."
msgstr ""
"Образ %s не може бути знайдений після завантаження. Можливо він був "
"вилучений під час завантаження."

#: glance/api/v1/upload_utils.py:195 glance/api/v2/image_data.py:175
msgid "Error in store configuration. Adding images to store is disabled."
msgstr "Помилка у конфігурації носія. Додавання образів у носій вимкнено."

#: glance/api/v1/upload_utils.py:164
#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr "Спроба вивантаження дублікату образу: %s"

#: glance/api/v1/upload_utils.py:175
#, python-format
msgid "Forbidden upload attempt: %s"
msgstr "Спроба забороненого вивантаження: %s"

#: glance/api/v1/upload_utils.py:256 glance/api/v2/images.py:159
#, python-format
msgid "Denying attempt to upload image because it exceeds the quota: %s"
msgstr "Відмова при спробі вивантажити образ з-за перевищення квоти: %s"

#: glance/api/v1/upload_utils.py:233
msgid "Client disconnected before sending all data to backend"
msgstr "Клієнт від’єднався до того, як послав усю інформацію на бекенд"

#: glance/api/v1/upload_utils.py:241
#, python-format
msgid "Failed to upload image %s"
msgstr "Не вдалося завантажити образ %s"

#: glance/api/v2/image_data.py:139
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload, cleaning up the chunks uploaded."
msgstr ""
"Образ %s не знайдено після завантаження. Можливо, він був вилучений під час "
"передачі, виконується очистка переданих фрагментів."

#: glance/api/v2/image_data.py:154
#, python-format
msgid ""
"Authentication error - the token may have expired during file upload. "
"Deleting image data for %s."
msgstr ""
"Помилка автентифікації - термін дії маркера під час вивантаження файлу збіг. "
"Вилучення даних образу для %s."

#: glance/api/v2/image_data.py:114
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr "Образ перевищує квоту сховища: %s"

#: glance/api/v2/image_data.py:121
#, python-format
msgid "The incoming image is too large: %s"
msgstr "Вхідний образ завеликий: %s"

#: glance/api/v2/image_data.py:256
msgid ""
"The requested image has been deactivated. Image data download is forbidden."
msgstr "Запитаний образ деактивований. Завантаження даних образу заборонена."

#: glance/api/v2/image_members.py:56
#, python-format
msgid "Error fetching members of image %(image_id)s: %(inner_msg)s"
msgstr "Помилка отримання учасників образу %(image_id)s: %(inner_msg)s"

#: glance/api/v2/image_members.py:71
#, python-format
msgid "You are not authorized to lookup image %s."
msgstr "Ви не авторизировані для огляду образу %s."

#: glance/api/v2/image_members.py:80
#, python-format
msgid "%(m_id)s not found in the member list of the image %(i_id)s."
msgstr "%(m_id)s не знайдений у переліку учасників образу %(i_id)s."

#: glance/api/v2/image_members.py:86
#, python-format
msgid "You are not authorized to lookup the members of the image %s."
msgstr "Ви не авторизировані для огляду учасників образу %s."

#: glance/api/v2/image_members.py:119
#, python-format
msgid "Not allowed to create members for image %s."
msgstr "Неприпустиме створення участників для образу %s."

#: glance/api/v2/image_members.py:123
#, python-format
msgid "Member %(member_id)s is duplicated for image %(image_id)s"
msgstr "Участник %(member_id)s вдруге вказаний у образі %(image_id)s"

#: glance/api/v2/image_members.py:129
#, python-format
msgid "Image member limit exceeded for image %(id)s: %(e)s:"
msgstr "Припустима межа участників була перевищена для образу %(id)s: %(e)s:"

#: glance/api/v2/image_members.py:161
#, python-format
msgid "Not allowed to update members for image %s."
msgstr "Неприпустиме оновлення участників для образу %s."

#: glance/api/v2/image_members.py:165
#, python-format
msgid "Incorrect request: %s"
msgstr "Неправильний запит: %s"

#: glance/api/v2/image_members.py:197
#, python-format
msgid "Not allowed to list members for image %s."
msgstr "Неприпустимий вивід участників для образу %s."

#: glance/api/v2/image_members.py:239
#, python-format
msgid "Not allowed to delete members for image %s."
msgstr "Неприпустиме вилучення участників для образу %s."

#: glance/api/v2/image_members.py:200
msgid "Member to be added not specified"
msgstr "Не вказано користувача для додавання"

#: glance/api/v2/image_members.py:203
msgid "Member can't be empty"
msgstr "Вкажіть користувача"

#: glance/api/v2/image_members.py:269
msgid "Expected a member in the form: {\"member\": \"image_id\"}"
msgstr "Елемент має бути заданий у форматі: {\"member\": \"image_id\"}"

#: glance/api/v2/image_members.py:212
msgid "Status not specified"
msgstr "Стан не вказано"

#: glance/api/v2/image_members.py:282
msgid "Expected a status in the form: {\"status\": \"status\"}"
msgstr "Стан має бути вказаний у форматі: {\"status\": \"status\"}"

#: glance/api/v2/image_members.py:267
msgid "An identifier for the image member (tenantId)"
msgstr "Ідентифікатор користувача образу (tenantId)"

#: glance/api/v2/image_members.py:271 glance/api/v2/images.py:644
msgid "An identifier for the image"
msgstr "Ідентифікатор образу"

#: glance/api/v2/image_members.py:277
msgid "Date and time of image member creation"
msgstr "Дата і час створення користувача образу"

#: glance/api/v2/image_members.py:284
msgid "Date and time of last modification of image member"
msgstr "Дата і час останньої зміни користувача образу"

#: glance/api/v2/image_members.py:289
msgid "The status of this image member"
msgstr "Статус даного користувача образу"

#: glance/api/v2/image_tags.py:56
#, python-format
msgid "Not allowed to update tags for image %s."
msgstr "Неприпустиме оновлення тегів для образу %s."

#: glance/api/v2/image_tags.py:60
#, python-format
msgid "Could not update image: %s"
msgstr "Не зміг оновитися образ: %s"

#: glance/api/v2/image_tags.py:65
#, python-format
msgid "Image tag limit exceeded for image %(id)s: %(e)s:"
msgstr "Межа тегів була досягнута для образу %(id)s: %(e)s:"

#: glance/api/v2/image_tags.py:85
#, python-format
msgid "Not allowed to delete tags for image %s."
msgstr "Неприпустиме вилучення тегів для образу %s."

#: glance/api/v2/images.py:178
msgid "Cannot set locations to empty list."
msgstr "Перелік розташувань не може бути порожнім."

#: glance/api/v2/images.py:183
msgid "Owner can't be updated by non admin."
msgstr ""
"Власник не може бути оновлений користувачем без адміністративних повноважень."

#: glance/api/v2/images.py:156 glance/api/v2/images.py:184
#, python-format
msgid "Property %s does not exist."
msgstr "Властивість %s не існує."

#: glance/api/v2/images.py:168
#, python-format
msgid "Property %s already present."
msgstr "Властивість %s вже представлена."

#: glance/api/v2/images.py:179
#, python-format
msgid "Property %s may not be removed."
msgstr "Властивість %s не може бути вилучено."

#: glance/api/v2/images.py:197
#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr "Не вдалося знайти і вилучити образ %(image_id)s"

#: glance/api/v2/images.py:273
msgid "It's not allowed to update locations if locations are invisible."
msgstr "Не дозволено оновлювати розташування, якщо вони невидимі."

#: glance/api/v2/images.py:291
msgid "It's not allowed to add locations if locations are invisible."
msgstr "Не дозволено додавати розташування, якщо вони невидимі."

#: glance/api/v2/images.py:239
msgid "Invalid position for adding a location."
msgstr "Невірна позиція для додавання розташування"

#: glance/api/v2/images.py:312
msgid "It's not allowed to remove locations if locations are invisible."
msgstr "Не дозволено вилучати розташування, якщо вони невидимі."

#: glance/api/v2/images.py:319
msgid "Cannot remove last location in the image."
msgstr "Неможна вилучати останнє розташування із образу."

#: glance/api/v2/images.py:254
msgid "Invalid position for removing a location."
msgstr "Невірна позиція для вилучення розташування"

#: glance/api/v2/images.py:295 glance/api/v2/images.py:394
#, python-format
msgid "Attribute '%s' is read-only."
msgstr "Атрибут '%s' доступний лише для читання."

#: glance/api/v2/images.py:405
#, python-format
msgid ""
"Unable to find `op` in JSON Schema change. It must be one of the following: "
"%(available)s."
msgstr ""
"Не вдалося знайти `op` у змінені схеми JSON. Допускається одне із наступних "
"значень: %(available)s."

#: glance/api/v2/images.py:410
#, python-format
msgid ""
"Invalid operation: `%(op)s`. It must be one of the following: %(available)s."
msgstr ""
"Неприпустима операція: `%(op)s`. Має бути одна з наступних: %(available)s."

#: glance/api/v2/images.py:327
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\", or "
"\"replace\"."
msgstr ""
"Операції над об’єктами повинні приймати значення лише \"add\", \"remove\" "
"або \"replace\"."

#: glance/api/v2/images.py:332
msgid ""
"Operation objects must contain exactly one member named \"add\", \"remove\", "
"or \"replace\"."
msgstr ""
"Операції над об’єктами повинні містити рівно один елемент з іменем \"add\", "
"\"remove\" або \"replace\"."

#: glance/api/v2/images.py:319 glance/api/v2/images.py:341
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr "Неможливо знайти '%s' у змінах JSON Schema"

#: glance/api/v2/images.py:369
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr "Вказівник `%s` не починається з \"/\"."

#: glance/api/v2/images.py:372
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr "Вказівник `%s` містить прилеглий \"/\"."

#: glance/api/v2/images.py:375
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr "Вказівник `%s` закінчується на \"/\"."

#: glance/api/v2/images.py:378
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr "Вказівник `%s` не містить дійсного токену."

#: glance/api/v2/images.py:381
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""
"Вказівник `%s` містить \"~\", який не є частиною визнаної перемикаючої "
"послідовності."

#: glance/api/v2/images.py:387
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr "Операція \"%s\" потребує елементу з іменем \"value\""

#: glance/api/v2/images.py:397
#, python-format
msgid "Attribute '%s' is reserved."
msgstr "Атрибут '%s' зарезервовано."

#: glance/api/v2/images.py:427
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr "Невірний вказівник JSON для цього ресурсу: '/%s'"

#: glance/api/v2/images.py:439
msgid "Unrecognized JSON Schema draft version"
msgstr "Нерозпізнана попередня версія JSON Schema"

#: glance/api/v2/images.py:460
msgid "Request body must be a JSON array of operation objects."
msgstr ""
"Тіло запиту повинне бути представлене у вигляді масиву операційних об’єктів "
"JSON."

#: glance/api/v2/images.py:465
msgid "Operations must be JSON objects."
msgstr "Операції повинні бути представлені у вигляді об’єктів JSON."

#: glance/api/v2/images.py:487 glance/api/v2/tasks.py:164
#: glance/registry/api/v1/images.py:246
msgid "limit param must be an integer"
msgstr "обмежуючий параметр повинен бути цілочисельним"

#: glance/api/v2/images.py:491 glance/api/v2/tasks.py:168
#: glance/registry/api/v1/images.py:249
msgid "limit param must be positive"
msgstr "обмежуючий параметр повинен бути позитивним"

#: glance/api/v2/images.py:596
#, python-format
msgid ""
"Invalid sort key: %(sort_key)s. It must be one of the following: "
"%(available)s."
msgstr ""
"Неправильне сортування по ключу: %(sort_key)s. Допускається одне з "
"наступних: %(available)s."

#: glance/api/v2/images.py:505
#, python-format
msgid "Invalid status: %s"
msgstr "Невірний статус: %s"

#: glance/api/v2/images.py:514
#, python-format
msgid "Invalid visibility value: %s"
msgstr "Невірне значення видимості: %s"

#: glance/api/v2/images.py:626
msgid "The \"changes-since\" filter is no longer available on v2."
msgstr "Фільтр \"changes-since\" більше недоступний в v2."

#: glance/api/v2/images.py:645
msgid "Old and new sorting syntax cannot be combined"
msgstr "Попередній і новий синтаксиси сортування неможна змішувати"

#: glance/api/v2/images.py:676
msgid "Number of sort dirs does not match the number of sort keys"
msgstr "Число напрямків сортування не збігається з числом ключів сортування"

#: glance/api/v2/images.py:650
msgid "Descriptive name for the image"
msgstr "Показуване ім’я для образу"

#: glance/api/v2/images.py:848
msgid "Status of the image"
msgstr "Стан образу"

#: glance/api/v2/images.py:661
msgid "Scope of image accessibility"
msgstr "Лінза доступності образу"

#: glance/api/v2/images.py:666
msgid "If true, image will not be deletable."
msgstr "Якщо увімкнено, образ буде захищено від вилучення."

#: glance/api/v2/images.py:864
msgid "md5 hash of image contents."
msgstr "Хеш md5 вмісту образу."

#: glance/api/v2/images.py:675
msgid "Owner of the image"
msgstr "Власник образу"

#: glance/api/v2/images.py:875
msgid "Size of image file in bytes"
msgstr "Розмір файлу образу у байтах"

#: glance/api/v2/images.py:880
msgid "Virtual size of image in bytes"
msgstr "Віртуальний розмір образу у байтах"

#: glance/api/v2/images.py:688
msgid "Format of the container"
msgstr "Формат контейнера"

#: glance/api/v2/images.py:693
msgid "Format of the disk"
msgstr "Формат диска"

#: glance/api/v2/images.py:895
msgid "Date and time of image registration"
msgstr "Дата та час реєстрації образу"

#: glance/api/v2/images.py:904
msgid "Date and time of the last image modification"
msgstr "Дата та час останнього змінювання образу"

#: glance/api/v2/images.py:712
msgid "List of strings related to the image"
msgstr "Перелік рядків, що відносяться образу"

#: glance/api/v2/images.py:919
msgid "URL to access the image file kept in external store"
msgstr ""
"URL для доступу до файлу образу, що знаходиться у зовнішньому сховищі"

#: glance/api/v2/images.py:725
msgid "Amount of ram (in MB) required to boot image."
msgstr "Об’єм ОЗП (у МБ), потрібний для початкового завантаження образу."

#: glance/api/v2/images.py:729
msgid "Amount of disk space (in GB) required to boot image."
msgstr ""
"Об’єм місця на диску (у ГБ), потрібний для початкового завантаження образу."

#: glance/api/v2/images.py:934
msgid "An image self url"
msgstr "Власна url образу"

#: glance/api/v2/images.py:939
msgid "An image file url"
msgstr "url файлу образу"

#: glance/api/v2/images.py:944
msgid "An image schema url"
msgstr "url схеми образу"

#: glance/api/v2/images.py:759
msgid "A set of URLs to access the image file kept in external store"
msgstr ""
"набір URL вказівників для доступу до файлу образу, розташованому у "
"зовнішньому сховищі."

#: glance/api/v2/metadef_namespaces.py:675
msgid "The unique namespace text."
msgstr "Унікальний текст простору імен."

#: glance/api/v2/metadef_namespaces.py:680
msgid "The user friendly name for the namespace. Used by UI if available."
msgstr ""
"Зручне для користувача ім’я з простору імен. Можна використовувати UI "
"користувача, якщо це для нього допускається."

#: glance/api/v2/metadef_namespaces.py:686
msgid "Provides a user friendly description of the namespace."
msgstr ""
"Допускається використання зручного для користувача опису у просторі імен."

#: glance/api/v2/metadef_namespaces.py:692
msgid "Scope of namespace accessibility."
msgstr "Область доступности простору імен."

#: glance/api/v2/metadef_namespaces.py:697
msgid "If true, namespace will not be deletable."
msgstr "Якщо true, простір імен буде неможливо вилучити."

#: glance/api/v2/metadef_namespaces.py:701
msgid "Owner of the namespace."
msgstr "Власник простору імен."

#: glance/api/v2/metadef_namespaces.py:707
msgid "Date and time of namespace creation"
msgstr "Дата та час створення простору імен"

#: glance/api/v2/metadef_namespaces.py:713
msgid "Date and time of the last namespace modification"
msgstr "Дата та час останнього змінювання простору імен"

#: glance/api/v2/metadef_objects.py:197
msgid "Date and time of object creation"
msgstr "Дата та час створення об’єкту"

#: glance/api/v2/metadef_objects.py:203
msgid "Date and time of the last object modification"
msgstr "Дата та час останнього змінювання об’єкту"

#: glance/api/v2/metadef_properties.py:94
#, python-format
msgid ""
"Property %(property_name)s does not start with the expected resource type "
"association prefix of '%(prefix)s'."
msgstr ""
"Властивість %(property_name)s не починається з очікуваного префіксу зв’язку "
"типу ресурсу '%(prefix)s'."

#: glance/api/v2/metadef_resource_types.py:131
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:125
#, python-format
msgid "Failed to find resource type %(resourcetype)s to delete"
msgstr "Не вдалося знайти тип ресурсу %(resourcetype)s для вилучення"

#: glance/api/v2/metadef_resource_types.py:204
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:199
msgid ""
"Resource type names should be aligned with Heat resource types whenever "
"possible: "
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"
msgstr ""
"Імена типів ресурсів повинні бути у відповідності з набором імен типів "
"ресурсів, що часто використовуються скрізь де це можливо:\r\n"
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"

#: glance/api/v2/metadef_resource_types.py:212
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:207
msgid ""
"Specifies the prefix to use for the given resource type. Any properties in "
"the namespace should be prefixed with this prefix when being applied to the "
"specified resource type. Must include prefix separator (e.g. a colon :)."
msgstr ""
"Визначає префікс, що використовується для даного типу ресурсів. Будь-які "
"властивості у просторі імен повинні мати префікс, що може застосовуватися до "
"вказаного типу ресурсів. Префікс повинен включати розділювач (оскільки "
"двокрапка :)."

#: glance/api/v2/metadef_resource_types.py:221
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:216
msgid ""
"Some resource types allow more than one key / value pair per instance.  For "
"example, Cinder allows user and image metadata on volumes. Only the image "
"properties metadata is evaluated by Nova (scheduling or drivers). This "
"property allows a namespace target to remove the ambiguity."
msgstr ""
"Деякі типи ресурсів допускають використання більше ніж однієї пари ключ / "
"значення для кожного екземпляру об’єкту. Наприклад, Cinder може бути як "
"користувач і образ метаданих тому. Але властивості образу метаданих можуть "
"відноситися лише до Nova (для планувальників або драйверів). Ця властивість "
"простору імен використовується з метою усунення неоднозначності."

#: glance/api/v2/metadef_resource_types.py:233
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:228
msgid "Date and time of resource type association"
msgstr "Дата та час пов’язування типу ресурсу"

#: glance/api/v2/metadef_resource_types.py:239
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:234
msgid "Date and time of the last resource type association modification"
msgstr "Дата та час останнього змінювання зв’язку типу ресурсу"

#: glance/api/v2/metadef_tags.py:198
msgid "Date and time of tag creation"
msgstr "Дата та час створення тега"

#: glance/api/v2/metadef_tags.py:204
msgid "Date and time of the last tag modification"
msgstr "Дата та час останнього змінювання тега"

#: glance/api/v2/tasks.py:137
msgid ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."
msgstr ""
"На даний час виконання цієї операції не дозволено в Glance Tasks. Вони також "
"автоматично вилучаються після кінця терміну, вказаного у властивості "
"expires_at."

#: glance/api/v2/tasks.py:143
#, python-format
msgid "Invalid status value: %s"
msgstr "Невірний статус значення: %s"

#: glance/api/v2/tasks.py:149
#, python-format
msgid "Invalid type value: %s"
msgstr "Невірний тип значення: %s"

#: glance/api/v2/tasks.py:156 glance/registry/api/v1/images.py:258
msgid "Invalid marker format"
msgstr "Неприпустимий формат маркера"

#: glance/api/v2/tasks.py:177
#, python-format
msgid "Task '%s' is required"
msgstr "Потрібне завдання '%s'"

#: glance/api/v2/tasks.py:292
msgid "An identifier for the task"
msgstr "Ідентифікатор завдання"

#: glance/api/v2/tasks.py:293
msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"
msgstr ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"

#: glance/api/v2/tasks.py:298
msgid "The type of task represented by this content"
msgstr "Тип завдання, виходячи з контексту"

#: glance/api/v2/tasks.py:305
msgid "The current status of this task"
msgstr "Поточний статус завдання"

#: glance/api/v2/tasks.py:315
msgid "The parameters required by task, JSON blob"
msgstr "Параметри, потрібні для виконання завдання, блоб JSON"

#: glance/api/v2/tasks.py:319
msgid "The result of current task, JSON blob"
msgstr "Результат поточного завдання, блоб JSON"

#: glance/api/v2/tasks.py:323
msgid "An identifier for the owner of this task"
msgstr "Ідентифікатор власника завдання"

#: glance/api/v2/tasks.py:327
msgid ""
"Human-readable informative message only included when appropriate (usually "
"on failure)"
msgstr ""
"Зручночитане повідомлення включається лише у відповідних випадках (зазвичай "
"при збої)"

#: glance/api/v2/tasks.py:332
msgid "Datetime when this resource would be subject to removal"
msgstr "Дата і час, коли цей ресурс буде позначений для вилучення"

#: glance/api/v2/tasks.py:337
msgid "Datetime when this resource was created"
msgstr "Дата і час створення цього ресурсу"

#: glance/api/v2/tasks.py:341
msgid "Datetime when this resource was updated"
msgstr "Дата і час оновлення цього ресурсу"

#: glance/async/taskflow_executor.py:40
msgid "The mode in which the engine will run. Can be 'serial' or 'parallel'."
msgstr "Режим роботи служби. Припустимі значення: serial, parallel."

#: glance/async/taskflow_executor.py:44
msgid ""
"The number of parallel activities executed at the same time by the engine. "
"The value can be greater than one when the engine mode is 'parallel'."
msgstr ""
"Число паралельних операцій, одночасно виконуваних службою. Значення може "
"бути більшим 1, коли режим роботи служби - parallel."

#: glance/async/taskflow_executor.py:144
msgid "Task failed due to Internal Error"
msgstr "Помилка завдання з-за внутрішньої помилки"

#: glance/async/flows/base_import.py:95
#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Missing work dir: "
"%(work_dir)s"
msgstr ""
"Служба %(task_id)s типу %(task_type)s налаштована неправильно. Бракує "
"робочого каталогу: %(work_dir)s"

#: glance/async/flows/base_import.py:127
#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Could not load the "
"filesystem store"
msgstr ""
"Служба %(task_id)s типу %(task_type)s налаштована неправильно. Не вдалося "
"завантажити сховище у файловій системі"

#: glance/async/flows/base_import.py:170
#, python-format
msgid "File %(path)s has invalid backing file %(bfile)s, aborting."
msgstr ""
"Файл %(path)s містить неприпустимий базовий файл %(bfile)s, примусове "
"завершення."

#: glance/async/flows/convert.py:31
msgid ""
"The format to which images will be automatically converted. When using the "
"RBD backend, this should be set to 'raw'"
msgstr ""
"Формат, у який будуть автоматично перетворюватися образи. При роботі з RBD "
"має бути заданий як 'raw'"

#: glance/async/flows/ovf_process.py:112
msgid "OVA extract is limited to admin"
msgstr "Розпакування OVA може виконати лише адміністратор"

#: glance/async/flows/ovf_process.py:153
msgid "Could not find OVF file in OVA archive file."
msgstr "Не знайдено файл OVF у файлі архіву OVA."

#: glance/async/flows/ovf_process.py:205
msgid "Currently, OVA packages containing multiple disk are not supported."
msgstr "На даний час пакунки OVA з декількома дисками не підтримуються."

#: glance/async/flows/ovf_process.py:246
msgid ""
"OVF metadata of interest was not specified in ovf-metadata.json config file. "
"Please set \"cim_pasd\" to a list of interested "
"CIM_ProcessorAllocationSettingData properties."
msgstr ""
"Потрібні метадані OVF не задані у файлі конфігурації ovf-metadata.json. "
"Вкажіть у параметрі \"cim_pasd\" перелік потрібних властивостей "
"CIM_ProcessorAllocationSettingData."

#: glance/async/flows/ovf_process.py:252
msgid "OVF properties config file \"ovf-metadata.json\" was not found."
msgstr ""
"Файл конфігурації \"ovf-metadata.json\" з властивостями OVF не знайдений."

#: glance/cmd/__init__.py:41
#, python-format
msgid ""
"It appears that the eventlet module has been imported prior to setting "
"%s='yes'. It is currently necessary to disable eventlet.greendns if using "
"ipv6 since eventlet.greendns currently breaks with ipv6 addresses. Please "
"ensure that eventlet is not imported prior to this being set."
msgstr ""
"Ймовірно, модуль eventlet імпортований до вказування %s='yes'. В дану мить "
"необхідно вимкнути eventlet.greendns, якщо використовується ipv6, оскільки "
"eventlet.greendns на цей час не працює з адресами ipv6. Переконайтеся, що "
"бібліотека eventlet імпортується не до налаштування цих параметрів."

#: glance/cmd/control.py:102
#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr "%(serv)s вже запущений: %(pid)s"

#: glance/cmd/control.py:106
#, python-format
msgid "Removing stale pid file %s"
msgstr "Вилучення застарілого pid файлу %s"

#: glance/cmd/control.py:115
msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr ""
"Неможливо збільшити ліміт описувача файлу. Можливо, ви працюєте не від ім’я "
"адміністратора."

#: glance/cmd/control.py:164
#, python-format
msgid "%(verb)sing %(serv)s with %(conf)s"
msgstr "%(verb)s %(serv)s з %(conf)s"

#: glance/cmd/control.py:161
#, python-format
msgid "%(verb)sing %(serv)s"
msgstr "%(verb)sing %(serv)s"

#: glance/cmd/control.py:176
#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr "неможливо запустити %(serv)s. Отримана помилка: %(e)s"

#: glance/cmd/control.py:206
#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr "%(serv)s (pid %(pid)s) запущений..."

#: glance/cmd/control.py:209
#, python-format
msgid "%s is stopped"
msgstr "%s зупинений"

#: glance/cmd/control.py:225
#, python-format
msgid ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""
"Неможливо створити pid файл %(pid)s. Перевірте наявність root-прав.\n"
"Відкат на тимчасовий файл, ви можете зупинити %(service)s службу за "
"допомогою:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"

#: glance/cmd/control.py:246
#, python-format
msgid "Reload of %(serv)s not supported"
msgstr "Перезавантаження %(serv)s не підтримується"

#: glance/cmd/control.py:254
#, python-format
msgid "Server %(serv)s is stopped"
msgstr "Сервер %(serv)s зупинено"

#: glance/cmd/control.py:259
#, python-format
msgid "Reloading %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "Перезавантаження %(serv)s (pid %(pid)s) з сигналом (%(sig)s)"

#: glance/cmd/control.py:259
#, python-format
msgid "Process %d not running"
msgstr "Процес %d не запущений"

#: glance/cmd/control.py:255
#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "Зупинка %(serv)s (pid %(pid)s) за допомогою сигналу(%(sig)s)"

#: glance/cmd/control.py:266
#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr ""
"Файли pid %(pid)s (%(file)s) не були вилучені протягом 15 секунд; перехід до "
"наступної операції"

#: glance/cmd/control.py:269
#, python-format
msgid "%s is already stopped"
msgstr "%s вже зупинений"

#: glance/cmd/control.py:372
#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr "Призупинений %(rsn)s був відновлений як %(serv)s."

#: glance/cmd/manage.py:163
#, python-format
msgid "Invalid int value for age_in_days: %(age_in_days)s"
msgstr "Невірне ціле значення для age_in_days:%(age_in_days)s"

#: glance/cmd/manage.py:169
#, python-format
msgid "Invalid int value for max_rows: %(max_rows)s"
msgstr "Невірне ціле значення для max_rows: %(max_rows)s"

#: glance/cmd/manage.py:173
msgid "Must supply a positive, non-zero value for age."
msgstr "У якости віку необхідно вказати додатнє число, що не дорівнює 0."

#: glance/cmd/manage.py:175
msgid "Maximal age is count of days since epoch."
msgstr "Максимальний вік - число днів з початку епохи."

#: glance/cmd/manage.py:177
msgid "Minimal rows limit is 1."
msgstr "Мінімальне число рядків дорівнює 1."

#: glance/cmd/manage.py:330
msgid "Available categories:"
msgstr "Наявні категорії:"

#: glance/cmd/manage.py:332
#, python-format
msgid "\t%s"
msgstr "\t%s"

#: glance/cmd/replicator.py:55
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did not "
"find it. This indicates that we do not have permissions to see all the "
"images on the slave server."
msgstr ""
"Образ %s вже знаходиться на підпорядкованому сервері, але наша перевірка не "
"виявила його. Це каже про те, що в нас невистачає повноважень для перегляду "
"усіх образів, розташованих на підпорядкованому сервері."

#: glance/cmd/replicator.py:282 glance/cmd/replicator.py:319
#: glance/cmd/replicator.py:404 glance/cmd/replicator.py:483
#: glance/cmd/replicator.py:560
msgid "Too few arguments."
msgstr "Замало аргументів"

#: glance/cmd/replicator.py:303
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr "Загальний розмір: %(size)d байтів. Кількість образів: %(img_count)d"

#: glance/cmd/replicator.py:717
#, python-format
msgid "Unknown command: %s"
msgstr "Невідома команда: %s"

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr "Несподівана відповідь: %s"

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr "Невідома стратегія авторизації '%s'"

#: glance/common/client.py:240
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert, "
"however you have failed to supply either a key_file parameter or set the "
"GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""
"Ви вибрали використання з’єднання з SSL й надали сертифікат, тим не менш, "
"сталася помилка у наданні параметру key_file або набору змінних середовищ "
"GLANCE_CLIENT_KEY_FILE"

#: glance/common/client.py:248
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the "
"GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""
"Ви вибрали для використання SSL при під’єднанні, й ви поставили ключ, але ви "
"не змогли надати або cert_file параметрів або встановити змінну оточення "
"GLANCE_CLIENT_CERT_FILE"

#: glance/common/client.py:257
#, python-format
msgid "The key file you specified %s does not exist"
msgstr "Вказаний вами ключовий файл %s не існує"

#: glance/common/client.py:264
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr "Вказаний вами файл сертифікату %s не існує"

#: glance/common/client.py:271
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr "Вказаний вами CA файл %s не існує"

#: glance/common/client.py:410
#, python-format
msgid "Constructed URL: %s"
msgstr "Створений URL: %s"

#: glance/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the service "
"name removed. For example, if your paste section name is [pipeline:glance-"
"api-keystone] use the value \"keystone\""
msgstr ""
"Неповне ім’я конвеєра у файлі конфігурації що вставляється, з якого вилучено "
"ім’я служби. Наприклад, якщо ім’я розділу що вставляється - [pipeline:glance-"
"api-keystone], то використовується значення \"keystone\""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr "Ім’я файлу конфігурації, що вставляється."

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr "Підтримувані значення для атрибуту образу 'container_format'"

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr "Підтримувані значення для атрибуту образу 'disk_format'"

#: glance/common/config.py:60
msgid ""
"Time in hours for which a task lives after, either succeeding or failing"
msgstr ""
"Час в годинах, протягом якого завдання буде залишатися запущеним у випадку "
"як вдалого, так і невдалого завершення"

#: glance/common/config.py:67
msgid "Specifies which task executor to be used to run the task scripts."
msgstr ""
"Вказує, щоб застосовуваний виконувач задачі виконував сценарії задачі."

#: glance/common/config.py:70
msgid ""
"Work dir for asynchronous task operations. The directory set here will be "
"used to operate over images - normally before they are imported in the "
"destination store. When providing work dir, make sure enough space is "
"provided for concurrent tasks to run efficiently without running out of "
"space. A rough estimation can be done by multiplying the number of "
"`max_workers` - or the N of workers running - by an average image size (e.g "
"500MB). The image size estimation should be done based on the average size "
"in your deployment. Note that depending on the tasks running you may need to "
"multiply this number by some factor depending on what the task does. For "
"example, you may want to double the available size if image conversion is "
"enabled. All this being said, remember these are just estimations and you "
"should do them based on the worst case scenario and be prepared to act in "
"case they were wrong."
msgstr ""
"Робочий каталог для операцій асинхронних задач. Вказаний тут каталог буде "
"використовуватися для образів (зазвичай перед їх імпортом у цільове "
"сховище). Вказуючи робочий каталог, переконайтеся, що у ньому вистачає місця "
"для ефективного виконання паралельних задач. У якости грубої оцінки можна "
"помножити значення max_workers (або число працюючих виконувачів) на середній "
"розмір образу (наприклад, 500 МБ). Оцінка розміру образу повинна "
"виконуватися на підставі середнього розміру у розгортанні. Нотатка: залежно "
"від виконуваних задач може знадобитися помножити це значення на певний "
"коеффіцієнт, який залежить від того, що задачі роблять. Наприклад, може "
"знадобитися подвоїти доступний розмір, якщо увімкнено перетворення образів. "
"Пам’ятайте, що це лише приблизна оцінка, її слід виконувати, виходячи з "
"найгіршого сценарію, й потрібно бути готовим до того, що її результати "
"можуть виявитися невірними."

#: glance/common/config.py:67
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""
"Визначає, чи дозволено користувачам вказувати властивості образу окрім тих, "
"що надані схемою"

#: glance/common/config.py:70
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""
"Максимальне число користувачів для одного образу. При введенні негативних "
"значень кількість користувачів буде необмеженою."

#: glance/common/config.py:73
msgid ""
"Maximum number of properties allowed on an image. Negative values evaluate "
"to unlimited."
msgstr ""
"Максимально дозволена кількість властивостей образу. Від’ємні значення "
"будуть розцінені як відсутність обмежень."

#: glance/common/config.py:76
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""
"Максимально дозволена кількість позначок образу. Від’ємні значення будуть "
"розцінені як відсутність обмежень."

#: glance/common/config.py:79
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""
"Максимально дозволена кількість місцезнаходжень образу. Від’ємні значення "
"будуть розцінені як відсутність обмежень."

#: glance/common/config.py:82
msgid "Python module path of data access API"
msgstr "Шлях модулю Python до API доступу до даних"

#: glance/common/config.py:84
msgid ""
"Default value for the number of items returned by a request if not specified "
"explicitly in the request"
msgstr ""
"Кількість позицій, що видаватимуться на запит типово, якщо у ньому не "
"вказано точне значення"

#: glance/common/config.py:87
msgid ""
"Maximum permissible number of items that could be returned by a request"
msgstr ""
"Максимально припустиме число позицій, які можуть бути видані на запит"

#: glance/common/config.py:90
msgid ""
"Whether to include the backend image storage location in image properties. "
"Revealing storage location can be a security risk, so use this setting with "
"caution!"
msgstr ""
"Визначає, чи варто включати місцезнаходження бекенд-сховища образу у "
"властивості образу. Розкривання місцезнаходження сховища може бути пов’язано "
"з ризиком для безпеки, тому використовуйте це налаштування з обережністю!"

#: glance/common/config.py:119
msgid ""
"Whether to include the backend image locations in image properties. For "
"example, if using the file system store a URL of \"file:///path/to/image\" "
"will be returned to the user in the 'direct_url' meta-data field. Revealing "
"storage location can be a security risk, so use this setting with caution! "
"Setting this to true overrides the show_image_direct_url option."
msgstr ""
"Вказує, чи включати розташування образів у базовій системі у властивости "
"образів. Наприклад, якщо використовується сховище у файловій системі, URL "
"\"file:///шлях/до/образу\" буде повертатися користувачу у поле метаданих "
"direct_url. Розкриття інформації про розташування сховища може бути загрозою "
"захисту, тому даний параметр слід використовувати з обережністю! Якщо "
"параметр заданий таким, що дорівнює true, то він перевизначає "
"show_image_direct_url."

#: glance/common/config.py:131
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to 1099511627776 "
"bytes (1 TB).WARNING: this value should only be increased after careful "
"consideration and must be set to a value under 8 EB (9223372036854775808)."
msgstr ""
"Максимальний розмір образу, який може бути завантажений користувачем, "
"1099511627776 байтів (1 ТБ). ПОПЕРЕДЖЕННЯ: це значення слід збільшувати лише "
"після ретельної оцінки; воно не може перевищувати 8 ЕБ (9223372036854775808)."

#: glance/common/config.py:137
msgid ""
"Set a system wide quota for every user. This value is the total capacity "
"that a user can use across all storage systems. A value of 0 means "
"unlimited.Optional unit can be specified for the value. Accepted units are "
"B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, GigaBytes and "
"TeraBytes respectively. If no unit is specified then Bytes is assumed. Note "
"that there should not be any space between value and unit and units are case "
"sensitive."
msgstr ""
"Встановити загальносистемну квоту для кожного користувача. Це загальний "
"об’єм пам’яти, доступної користувачу в усіх системах зберігання даних. 0 "
"означає відсутність обмеження. Додатково можна вказати одиницю вимірювання. "
"Припустимі одиниці вимірювання: Б (байт), КБ (кілобайт), МБ (мегабайт), ГБ "
"(гігабайт) та ТБ (терабайт). Типова одиниця вимірювання - Б (байт). "
"Зауважте, що одиниця вимірювання вказується без пробілу й з врахуванням "
"регістру."

#: glance/common/config.py:107
msgid "Deploy the v1 OpenStack Images API."
msgstr "Розгортання v1 OpenStack Images API."

#: glance/common/config.py:109
msgid "Deploy the v2 OpenStack Images API."
msgstr "Розгортання v2 OpenStack Images API."

#: glance/common/config.py:111
msgid "Deploy the v1 OpenStack Registry API."
msgstr "Розгортання v1 OpenStack Registry API."

#: glance/common/config.py:113
msgid "Deploy the v2 OpenStack Registry API."
msgstr "Розгортання v2 OpenStack Registry API."

#: glance/common/config.py:115
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""
"Ім’я хосту або IP-адреса процесу pydev, що приймає з’єднання налагодження"

#: glance/common/config.py:118
msgid "The port on which a pydev process is listening for connections."
msgstr "Порт, через який процес pydev приймає з’єднання."

#: glance/common/config.py:161
msgid ""
"AES key for encrypting store 'location' metadata. This includes, if used, "
"Swift or S3 credentials. Should be set to a random string of length 16, 24 "
"or 32 bytes"
msgstr ""
"Ключ AES для шифрування метаданих location сховища. Якщо використовується, "
"то включає ідентифікаційні дані Swift або S3. Значення повинне бути "
"випадковим рядком довжиною 16, 24 або 32 байтів"

#: glance/common/config.py:166
msgid ""
"Digest algorithm which will be used for digital signature. Use the command "
"\"openssl list-message-digest-algorithms\" to get the available algorithms "
"supported by the version of OpenSSL on the platform. Examples are \"sha1\", "
"\"sha256\", \"sha512\", etc."
msgstr ""
"Алгоритм дайджесту, що застосовується для цифрового підпису. Команда "
"\"openssl list-message-digest-algorithms\" виводить алгоритми, підтримувані "
"версією OpenSSL на даній плятформі. Приклади: \"sha1\", \"sha256\", "
"\"sha512\" тощо."

#: glance/common/config.py:179
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr "Не вдається знайти/вставити файл конфігурації для %s."

#: glance/common/config.py:218
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"Неможливо завантажити %(app_name)s з файлу конфігурації %(conf_file)s.\n"
"Отримано: %(e)r"

#: glance/common/exception.py:38
msgid "An unknown exception occurred"
msgstr "Виявлено невідомий виняток"

#: glance/common/exception.py:63
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "Відсутність потрібних облікових даних: %(required)s"

#: glance/common/exception.py:67
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"Невірна стратегія авторизації, очікувалося \"%(expected)s\", але було "
"отримано \"%(received)s\""

#: glance/common/exception.py:72
msgid "An object with the specified identifier was not found."
msgstr "Об’єкт з вказаним ідентифікатором не знайдено."

#: glance/common/exception.py:80
msgid "The Store URI was malformed."
msgstr "Некоректне посилання на сховище."

#: glance/common/exception.py:84
msgid "An object with the same identifier already exists."
msgstr "Об’єкт з цим ідентифікатором вже існує."

#: glance/common/exception.py:88
msgid "An object with the same identifier is currently being operated on."
msgstr "Об’єкт з таким ідентифікатором вже обробляється."

#: glance/common/exception.py:97
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""
"Розмір даних %(image_size)s витрачає ліміт. Залишилося %(remaining)s байтів."

#: glance/common/exception.py:106
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""
"Помилка під’єднання/неприпустимий запит до служби авторизації за адресою "
"%(url)s."

#: glance/common/exception.py:110
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "Адреса служби авторизації %(url)s не знайдена."

#: glance/common/exception.py:114
msgid "Authorization failed."
msgstr "Помилка авторизації."

#: glance/common/exception.py:118
msgid "You are not authenticated."
msgstr "Автентифікація не виконана."

#: glance/common/exception.py:112
#, python-format
msgid "Image upload problem: %s"
msgstr "Проблема при передачі образу: %s"

#: glance/common/exception.py:122 glance/common/exception.py:126
msgid "You are not authorized to complete this action."
msgstr "Вы не маєте повноважень для завершення цієї дії."

#: glance/common/exception.py:130
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr "Образ %(image_id)s захищений й не може бути вилученим."

#: glance/common/exception.py:128
#, python-format
msgid ""
"Metadata definition namespace %(namespace)s is protected and cannot be "
"deleted."
msgstr ""
"Простір імен %(namespace)s визначення метаданих захищено й не може бути "
"вилучено."

#: glance/common/exception.py:133
#, python-format
msgid ""
"Metadata definition property %(property_name)s is protected and cannot be "
"deleted."
msgstr ""
"Властивіть %(property_name)s визначення метаданих захищено й не може бути "
"вилучено."

#: glance/common/exception.py:138
#, python-format
msgid ""
"Metadata definition object %(object_name)s is protected and cannot be "
"deleted."
msgstr ""
"Об’єкт %(object_name)s визначення метаданих захищено й не може бути вилучено."

#: glance/common/exception.py:143
#, python-format
msgid ""
"Metadata definition resource-type-association %(resource_type)s is protected "
"and cannot be deleted."
msgstr ""
"Зв’язок типу ресурсу %(resource_type)s визначення метаданих захищено й не "
"може бути вилучено."

#: glance/common/exception.py:148
#, python-format
msgid ""
"Metadata definition resource-type %(resource_type_name)s is a seeded-system "
"type and cannot be deleted."
msgstr ""
"Тип ресурсу %(resource_type_name)s визначення метаданих є системним типом й "
"не може бути вилучено."

#: glance/common/exception.py:153
#, python-format
msgid ""
"Metadata definition tag %(tag_name)s is protected and cannot be deleted."
msgstr ""
"Тег %(tag_name)s визначення метаданих захищено й не може бути вилучено."

#: glance/common/exception.py:134
msgid "Data supplied was not valid."
msgstr "Введені дані недійсні."

#: glance/common/exception.py:138
#: glance/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr "Наданий сортувальний ключ недійсний."

#: glance/common/exception.py:166
msgid "Sort direction supplied was not valid."
msgstr "Вказано неприпустимий напрямок сортування."

#: glance/common/exception.py:142
msgid "Invalid configuration in property protection file."
msgstr "Неприпустима конфігурація у файлі захисту властивостей."

#: glance/common/exception.py:174
msgid "Invalid configuration in glance-swift conf file."
msgstr "Неприпустима конфігурація у файлі конфігурації glance-swift."

#: glance/common/exception.py:178
msgid "Unable to filter using the specified operator."
msgstr "Не вдається відфільтрувати з використанням вказаного оператора."

#: glance/common/exception.py:146
msgid "Unable to filter using the specified range."
msgstr "Неможливо зробити фільтрацію використовуючи вказаний діапазон."

#: glance/common/exception.py:186
#, python-format
msgid "Invalid value for option %(option)s: %(value)s"
msgstr "Неприпустиме значення для опції %(option)s: %(value)s"

#: glance/common/exception.py:150
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "Атрибут '%(property)s' лише для читання."

#: glance/common/exception.py:154
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "Атрибут '%(property)s' зарезервований."

#: glance/common/exception.py:158
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "Перенаправлення на %(uri)s для виконання авторизації."

#: glance/common/exception.py:162
msgid "There was an error connecting to a server"
msgstr "Помилка при під’єднанні до сервера"

#: glance/common/exception.py:166
msgid "There was an error configuring the client."
msgstr "При налаштуванні клієнта трапилася помилка."

#: glance/common/exception.py:170
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that you "
"have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"Результат запиту: 302 Multiple Choices. Це зазвичай означає, що ви не "
"включили індикатор версії у URI запиту.\n"
"\n"
"Тіло результата:\n"
"%(body)s"

#: glance/common/exception.py:176
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means "
"that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"Запит повернув помилку 413 - Суттєвість запиту завелика. Як правило, це "
"означає, що порушено обмеження на швидкість або поріг квоти.\n"
"\n"
"Тіло відповіді:\n"
"%(body)s"

#: glance/common/exception.py:227
msgid ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."
msgstr ""
"Запит повернув помилку 503 - Служба недоступна. Як правило, це відбувається "
"при перевантаженні служби або іншому тимчасовому збої"

#: glance/common/exception.py:198
msgid "The request returned 500 Internal Server Error."
msgstr "Запит повернув помилку: 500 Internal Server Error."

#: glance/common/exception.py:202
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"Запит повернув непередбачений стан: %(status)s.\n"
"\n"
"Тіло відповіді:\n"
"%(body)s"

#: glance/common/exception.py:207
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "Неприпустимий тип вмісту %(content_type)s"

#: glance/common/exception.py:211
#, python-format
msgid ""
"Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""
"Реєстр не був правильно налаштований на API сервері. Причина: %(reason)s"

#: glance/common/exception.py:221
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""
"Драйвер %(driver_name)s не може бути налаштований правильно. Причина: "
"%(reason)s"

#: glance/common/exception.py:243
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""
"Максимальну кількість перенаправлень (%(redirects)s) було перевищено."

#: glance/common/exception.py:247
msgid "Received invalid HTTP redirect."
msgstr "Отримано недійсне HTTP-перенаправлення."

#: glance/common/exception.py:251
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr "Відповідь від Keystone не містить кінцевої точки Glance."

#: glance/common/exception.py:255
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally means "
"that a region is required and you have not supplied one."
msgstr ""
"Декілька відповідностей служби 'image' для регіону %(region)s. Зазвичай це "
"означє, що регіон обов’язковий, але Ви його не вказали."

#: glance/common/exception.py:261
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "Створити виконувач сервера не вдалося: %(reason)s."

#: glance/common/exception.py:265
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "Неможливо завантажити схему: %(reason)s"

#: glance/common/exception.py:269
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr "Наданий об’єкт не відповідає схемі '%(schema)s': %(reason)s"

#: glance/common/exception.py:283
msgid "The provided image is too large."
msgstr "Наданий образ завеликий."

#: glance/common/exception.py:293
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Ліміт на кількість дозволених властивостей образу був вичерпаний. Кількість: "
"%(attempted)s, максимум: %(maximum)s"

#: glance/common/exception.py:298
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. Attempted: "
"%(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Ліміт на кількість дозволених тегів образу був вичерпаний. Кількість: "
"%(attempted)s, максимум: %(maximum)s"

#: glance/common/exception.py:303
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Ліміт на кількість дозволених місцезнаходжень образу був вичерпаний. "
"Кількість: %(attempted)s, максимум: %(maximum)s"

#: glance/common/exception.py:317
msgid "System SIGHUP signal received."
msgstr "Отримано системний сигнал SIGHUP."

#: glance/common/exception.py:308
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr "У останньому виклику rpc виникла виключна ситуація %(cls)s: %(val)s"

#: glance/common/exception.py:312
msgid "An unknown task exception occurred"
msgstr "Непередбачена виключна ситуація"

#: glance/common/exception.py:329
msgid "Task was not configured properly"
msgstr "Задача неправильно налаштована"

#: glance/common/exception.py:333
#, python-format
msgid "Image with the given id %(image_id)s was not found"
msgstr "Образ із заданим ідентифікатором %(image_id)s не знайдений"

#: glance/common/exception.py:316
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr "Завдання з заданим id %(task_id)s не знайдено"

#: glance/common/exception.py:320
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr "Предоставлений стан завдання не підтримується: %(status)s"

#: glance/common/exception.py:324
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr "Вказано непідтримуваний тип задачі: %(type)s"

#: glance/common/exception.py:328
#, python-format
msgid ""
"Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr "Змінювати стан %(cur_status)s на %(new_status)s не дозволяється"

#: glance/common/exception.py:354
msgid "An import task exception occurred"
msgstr "Виключна ситуація у задачі імпорту"

#: glance/common/exception.py:333
#, python-format
msgid "The location %(location)s already exists"
msgstr "Розташування %(location)s вже існує"

#: glance/common/exception.py:341
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""
"Некоректне значення '%(value)s' для параметру '%(param)s': %(extra_msg)s"

#: glance/common/exception.py:346
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""
"Змінювати стан %(cur_status)s образу на %(new_status)s не дозволяється"

#: glance/common/exception.py:372
#, python-format
msgid "The metadata definition namespace=%(namespace_name)s already exists."
msgstr "Простір імен %(namespace_name)s визначення метаданих вже існує."

#: glance/common/exception.py:377
#, python-format
msgid ""
"A metadata definition object with name=%(object_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"Об’єкт визначення метаданих з іменем %(object_name)s вже існує у просторі "
"імен %(namespace_name)s."

#: glance/common/exception.py:382
#, python-format
msgid ""
"A metadata definition property with name=%(property_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"Властивість визначення метаданих з іменем %(property_name)s вже існує у "
"просторі імен %(namespace_name)s."

#: glance/common/exception.py:387
#, python-format
msgid ""
"A metadata definition resource-type with name=%(resource_type_name)s already "
"exists."
msgstr ""
"Тип ресурсу визначення метаданих з іменем %(resource_type_name)s вже існує."

#: glance/common/exception.py:392
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s already exists."
msgstr ""
"Зв’язок типу ресурсу визначення метаданих для типу "
"ресурсу%(resource_type_name)s і простору імен %(namespace_name)s вже існує."

#: glance/common/exception.py:399
#, python-format
msgid ""
"A metadata tag with name=%(name)s already exists in "
"namespace=%(namespace_name)s. (Please note that metadata tag names are case "
"insensitive)."
msgstr ""
"Тег метаданих з іменем=%(name)s вже існує в просторі "
"імен=%(namespace_name)s. (Зверніть увагу, що імена тегів метаданих є "
"нечутливими до регістру)."

#: glance/common/exception.py:410
#, python-format
msgid ""
"The metadata definition %(record_type)s with name=%(record_name)s not "
"deleted. Other records still refer to it."
msgstr ""
"Визначення метаданих %(record_type)s з іменем %(record_name)s не вилучено. "
"Інші записи усе ще посилаються на нього."

#: glance/common/exception.py:416
#, python-format
msgid "Metadata definition namespace=%(namespace_name)s was not found."
msgstr ""
"Простір імен для визначення метаданих=%(namespace_name)s не знайдено."

#: glance/common/exception.py:421
#, python-format
msgid ""
"The metadata definition object with name=%(object_name)s was not found in "
"namespace=%(namespace_name)s."
msgstr ""
"Об’єкт визначення метаданих з іменем %(object_name)s не знайдений у просторі "
"імен %(namespace_name)s."

#: glance/common/exception.py:427
#, python-format
msgid ""
"The metadata definition property with name=%(property_name)s was not found "
"in namespace=%(namespace_name)s."
msgstr ""
"Властивість визначення метаданих з іменем %(property_name)s не знайдено у "
"просторі імен %(namespace_name)s."

#: glance/common/exception.py:433
#, python-format
msgid ""
"The metadata definition resource-type with name=%(resource_type_name)s, was "
"not found."
msgstr ""
"Тип ресурсу визначення метаданих з іменем %(resource_type_name)s не "
"знайдений."

#: glance/common/exception.py:438
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s, was not found."
msgstr ""
"Зв’язок типу ресурсу визначення метаданих для типу "
"ресурсу%(resource_type_name)s й простору імен %(namespace_name)s не "
"знайдений."

#: glance/common/exception.py:445
#, python-format
msgid ""
"The metadata definition tag with name=%(name)s was not found in "
"namespace=%(namespace_name)s."
msgstr ""
"Тег визначення метаданих з іменем %(name)s не знайдений у просторі імен "
"%(namespace_name)s."

#: glance/common/exception.py:451
#, python-format
msgid "Unable to verify signature: %(reason)s"
msgstr "Не вдалося перевірити підпис: %(reason)s"

#: glance/common/exception.py:455
#, python-format
msgid "Version is invalid: %(reason)s"
msgstr "Неприпустима версія: %(reason)s"

#: glance/common/exception.py:459
msgid "Invalid property definition"
msgstr "Неприпустиме визначення властивости"

#: glance/common/exception.py:463
msgid "Invalid type definition"
msgstr "Неприпустиме визначення типу"

#: glance/common/exception.py:467
#, python-format
msgid "Property '%(name)s' may not have value '%(val)s': %(msg)s"
msgstr "Властивість '%(name)s' не може мати значення '%(val)s': %(msg)s"

#: glance/common/exception.py:477
#, python-format
msgid "Artifact with id=%(id)s was not found"
msgstr "Артефакт з id=%(id)s не знайдений"

#: glance/common/exception.py:481
#, python-format
msgid "Artifact with id=%(id)s is not accessible"
msgstr "Артефакт з id=%(id)s не доступний"

#: glance/common/exception.py:485
msgid "Artifact with the specified type, name and version already exists"
msgstr "Артефакт з вказаними типом, іменем та версією вже існує"

#: glance/common/exception.py:490
#, python-format
msgid "Artifact cannot change state from %(source)s to %(target)s"
msgstr "Артефакт не може змінити стан з %(source)s на %(target)s"

#: glance/common/exception.py:494
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the direct "
"dependency=%(dep)s"
msgstr ""
"Артефакт з вказаними типом, іменем та версією вже має пряму "
"залежність=%(dep)s"

#: glance/common/exception.py:499
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the "
"transitive dependency=%(dep)s"
msgstr ""
"Артефакт з вказаними типом, іменем та версією вже має транзитивну "
"залежність=%(dep)s"

#: glance/common/exception.py:504
msgid "Artifact with a circular dependency can not be created"
msgstr "Неможна створити артефакт з циклічною залежністю"

#: glance/common/exception.py:508
#, python-format
msgid "Operator %(op)s is not supported"
msgstr "Оператор %(op)s не підтримується"

#: glance/common/exception.py:512
#, python-format
msgid "Show level %(shl)s is not supported in this operation"
msgstr "Рівень відображення %(shl)s не підтримується у цій операції"

#: glance/common/exception.py:516
#, python-format
msgid "Property's %(prop)s value has not been found"
msgstr "Значення %(prop)s параметру не знайдено"

#: glance/common/exception.py:520
#, python-format
msgid "Artifact has no property %(prop)s"
msgstr "Артефакт не має параметру %(prop)s"

#: glance/common/exception.py:524
#, python-format
msgid "Cannot use this parameter with the operator %(op)s"
msgstr "Неможливо використовувати цей параметр з оператором %(op)s"

#: glance/common/exception.py:528
#, python-format
msgid "Cannot load artifact '%(name)s'"
msgstr "Неможливо завантажити артефакт '%(name)s'"

#: glance/common/exception.py:532
#, python-format
msgid "Plugin name '%(plugin)s' should match artifact typename '%(name)s'"
msgstr ""
"Ім’я модулю '%(plugin)s' повинне відповідати імені типу артефакту '%(name)s'"

#: glance/common/exception.py:537
#, python-format
msgid "No plugin for '%(name)s' has been loaded"
msgstr "Модуль для '%(name)s' не завантажений"

#: glance/common/exception.py:541
#, python-format
msgid ""
"Artifact type with name '%(name)s' and version '%(version)s' is not known"
msgstr "Тип артефакту з іменем '%(name)s' і версією '%(version)s' невідомий"

#: glance/common/exception.py:546
#, python-format
msgid "Artifact state cannot be changed from %(curr)s to %(to)s"
msgstr "Стан артефакту не може бути змінений з %(curr)s на %(to)s"

#: glance/common/exception.py:550
msgid "Invalid jsonpatch request"
msgstr "Невірний запит jsonpatch"

#: glance/common/exception.py:554
#, python-format
msgid "The provided body %(body)s is invalid under given schema: %(schema)s"
msgstr "Вказане тіло %(body)s невірне для даної схеми: %(schema)s"

#: glance/common/exception.py:559
#, python-format
msgid "The provided path '%(path)s' is invalid: %(explanation)s"
msgstr "Вказаний шлях '%(path)s' невірний: %(explanation)s"

#: glance/common/jsonpatchvalidator.py:103
msgid ""
"Json path should start with a '/', end with no '/', no 2 subsequent '/' are "
"allowed."
msgstr ""
"Шлях Json повинен починатися з '/' й закінчуватися не на '/'. 2 послідовних "
"символи '/' не дозволені."

#: glance/common/jsonpatchvalidator.py:107
msgid ""
"Pointer contains '~' which is not part of a recognized escape sequence [~0, "
"~1]."
msgstr ""
"Вказівник містить символ '~', який не входить у склад розпізнаної escape-"
"послідовности [~0, ~1]."

#: glance/common/property_utils.py:31
msgid ""
"The location of the property protection file.This file contains the rules "
"for property protections and the roles/policies associated with it. If this "
"config value is not specified, by default, property protections won't be "
"enforced. If a value is specified and the file is not found, then the glance-"
"api service will not start."
msgstr ""
"Розташування файлу захисту властивостей. Цей файл містить правила для "
"захисту властивостей і ролі/стратегії, з ними пов’язані. Якщо це значення "
"конфігурації не вказано, то типово захист властивостей увімкнено. Якщо "
"значення вказано, але файл не знайдений, то служба не запуститься glance-api."

#: glance/common/property_utils.py:40
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in "
"the property protection file."
msgstr ""
"Цей файл конфігурації вказує, чи будуть \"roles\" або \"policies\" "
"використовуватися у файлі захисту властивостей."

#: glance/common/property_utils.py:127
#, python-format
msgid ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."
msgstr ""
"Правило захисту властивостей в операції %(operation)s для правила %(rule)s "
"не знайдено. Користувачам ні у якій ролі не буде дозволено виконувати цю "
"операцію."

#: glance/common/rpc.py:139
msgid "Request must be a list of commands"
msgstr "Запит повинен бути наданий у вигляді переліку команд"

#: glance/common/rpc.py:144
#, python-format
msgid "Bad Command: %s"
msgstr "Неправильна команда %s"

#: glance/common/rpc.py:151
#, python-format
msgid "Wrong command structure: %s"
msgstr "Неправильна структура команди: %s"

#: glance/common/rpc.py:160
msgid "Command not found"
msgstr "Команду не знайдено"

#: glance/common/semver_db.py:77
#, python-format
msgid "Version component is too large (%d max)"
msgstr "Компонент версії завеликий (макс. %d)"

#: glance/common/semver_db.py:125
#, python-format
msgid "Prerelease numeric component is too large (%d characters max)"
msgstr "Завеликий числовий компонент перед випуском (макс. %d символів)"

#: glance/common/signature_utils.py:138
#, python-format
msgid "Invalid signature key type: %s"
msgstr "Неприпустимий тип ключа підпису: %s"

#: glance/common/signature_utils.py:161
#, python-format
msgid "Invalid mask_gen_algorithm: %s"
msgstr "Неприпустимий mask_gen_algorithm: %s"

#: glance/common/signature_utils.py:174
#, python-format
msgid "Invalid pss_salt_length: %s"
msgstr "Неприпустимий pss_salt_length: %s"

#: glance/common/signature_utils.py:261 glance/common/signature_utils.py:335
msgid ""
"Required image properties for signature verification do not exist. Cannot "
"verify signature."
msgstr ""
"Відсутні властивости образу, необхідні для перевірки підпису. Перевірка "
"підпису неможлива."

#: glance/common/signature_utils.py:285 glance/common/signature_utils.py:361
msgid ""
"Unable to verify signature since the algorithm is unsupported on this system"
msgstr ""
"Не вдається перевірити підпис, оскільки алгоритм не підтримується в системі"

#: glance/common/signature_utils.py:294
msgid "Error occurred while creating the verifier"
msgstr "Помилка при створенні агента перевірки"

#: glance/common/signature_utils.py:373
msgid "Signature verification failed."
msgstr "Перевірка підпису не виконана."

#: glance/common/signature_utils.py:378
msgid "Error occurred while verifying the signature"
msgstr "Помилка при перевірці підпису"

#: glance/common/signature_utils.py:394
msgid "The signature data was not properly encoded using base64"
msgstr "Дані підпису у кодуванні base64 містять помилку"

#: glance/common/signature_utils.py:410
#, python-format
msgid "Invalid signature hash method: %s"
msgstr "Неприпустимий метод хешу підпису: %s"

#: glance/common/signature_utils.py:436
#, python-format
msgid "Invalid public key type for signature key type: %s"
msgstr "Неприпустимий тип відкритого ключа для даного типу ключа підпису: %s"

#: glance/common/signature_utils.py:467
#, python-format
msgid "Unable to retrieve certificate with ID: %s"
msgstr "Не вдалося отримати сертифікат з ID: %s"

#: glance/common/signature_utils.py:473
#, python-format
msgid "Invalid certificate format: %s"
msgstr "Невірний формат сертифікату: %s"

#: glance/common/signature_utils.py:483
#, python-format
msgid "Certificate format not supported: %s"
msgstr "Формат сертифікату не підтримується: %s"

#: glance/common/signature_utils.py:505
#, python-format
msgid "Certificate is not valid before: %s UTC"
msgstr "Сертифікат не діє до: %s UTC"

#: glance/common/signature_utils.py:510
#, python-format
msgid "Certificate is not valid after: %s UTC"
msgstr "Сертифікат не дійсний після: %s UTC"

#: glance/common/swift_store_utils.py:25
msgid ""
"The reference to the default swift account/backing store parameters to use "
"for adding new images."
msgstr ""
"Посилання на параметри облікових записів і резервного зберігання swift "
"типове для використання при додаванні нових образів."

#: glance/common/swift_store_utils.py:28
msgid ""
"The address where the Swift authentication service is listening.(deprecated)"
msgstr "Адреса, за якою приймає служба ідентифікації Swift. (Застаріло)"

#: glance/common/swift_store_utils.py:31
msgid ""
"The user to authenticate against the Swift authentication service "
"(deprecated)"
msgstr "Користувач для ідентифікації службою Swift (застаріло)"

#: glance/common/swift_store_utils.py:34
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service. (deprecated)"
msgstr ""
"Ідентифікаційний ключ для ідентифікації користувача службою Swift. "
"(Застаріло)"

#: glance/common/swift_store_utils.py:37
msgid "The config file that has the swift account(s)configs."
msgstr "Файл конфігурації з обліковими записами swift."

#: glance/common/utils.py:251
#, python-format
msgid "Bad header: %(header_name)s"
msgstr "Неправильний заголовок: %(header_name)s"

#: glance/common/utils.py:261
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr "Не вдається перетворити %(key)s '%(value)s' у ціле число."

#: glance/common/utils.py:313
msgid "Cannot be a negative value."
msgstr "Не може бути від'ємне значення."

#: glance/common/utils.py:509
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it.  Error: %(ioe)s"
msgstr ""
"Виникла проблема з вашими %(error_key_name)s %(error_filename)s. Будь ласка, "
"перевірте дані. Помилка: %(ioe)s"

#: glance/common/utils.py:516
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it. OpenSSL error: %(ce)s"
msgstr ""
"Виникла проблема з вашими %(error_key_name)s %(error_filename)s. Будь ласка, "
"перевірте дані. Помилка OpenSSL: %(ce)s"

#: glance/common/utils.py:530
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""
"Виникла проблема з вашою парою ключів. Будь ласка, переконайтеся, що "
"сертифікат %(cert_file)s і ключ %(key_file)s відповідають один одному. "
"Помилка OpenSSL: %(ce)s"

#: glance/common/utils.py:480
#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr "Хост і порт \"%s\" неприпустимі."

#: glance/common/utils.py:483
#, python-format
msgid "Port \"%s\" is not valid."
msgstr "Порт \"%s\" неприпустимий."

#: glance/common/utils.py:492
#, python-format
msgid "Host \"%s\" is not valid."
msgstr "Хост \"%s\" неприпустимий."

#: glance/common/utils.py:495
#, python-format
msgid ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in brackets "
"separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""
"%s Вкажіть пару host:port, де host - це адреса IPv4, адреса IPv6, ім’я хосту "
"або FQDN. При вказуванні адреси IPv6 помістіть його у квадратні дужки окремо "
"від порта (наприклад, \"[fe80::a:b:c]:9876\")."

#: glance/common/utils.py:530
msgid "Property names can't contain 4 byte unicode."
msgstr ""
"Імена властивостей не можуть містити символи у кодуванні 4-байтового unicode."

#: glance/common/utils.py:533
#, python-format
msgid "%s can't contain 4 byte unicode characters."
msgstr "%s не може містити символи у кодуванні 4-байтового unicode."

#: glance/common/utils.py:542
msgid "Param values can't contain 4 byte unicode."
msgstr ""
"Значення параметрів не можуть містити символи у кодуванні 4-байтового "
"unicode."

#: glance/common/utils.py:562
#, python-format
msgid "Value %(value)d out of range, must not exceed %(max)d"
msgstr ""
"Значення %(value)d поза діяпазоном, воно не повинне перевищувати %(max)d"

#: glance/common/utils.py:570
#, python-format
msgid "'%(param)s' value out of range, must not exceed %(max)d"
msgstr ""
"Значення %(param)s виходить за межі діяпазону, воно не повинне перевищувати "
"%(max)d"

#: glance/common/utils.py:627
#, python-format
msgid ""
"Invalid filter value %s. There is no comma before opening quotation mark."
msgstr ""
"Неприпустиме значення фільтру %s. Немає коми перед відкриваючою лапкою."

#: glance/common/utils.py:632
#, python-format
msgid ""
"Invalid filter value %s. There is no comma after closing quotation mark."
msgstr ""
"Неприпустиме значення фільтру %s. Немає коми після закриваючої лапки."

#: glance/common/utils.py:637
#, python-format
msgid "Invalid filter value %s. The quote is not closed."
msgstr "Неприпустиме значення фільтру %s. Немає закриваючої лапки."

#: glance/common/utils.py:687
msgid "Unable to filter on a unknown operator."
msgstr "Не вдається відфільтрувати з використанням невідомого оператора."

#: glance/common/wsgi.py:53
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""
"Адреса прив’язки сервера. Корисна при виборі конкретного мережевого "
"інтерфейсу."

#: glance/common/wsgi.py:56
msgid "The port on which the server will listen."
msgstr "Порт на якому сервер буде вести прослуховування."

#: glance/common/wsgi.py:61
msgid ""
"The backlog value that will be used when creating the TCP listener socket."
msgstr ""
"Базове значення, яке буде використано при створенні приймального сокету TCP."

#: glance/common/wsgi.py:64
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in seconds "
"that the connection must be idle before TCP starts sending keepalive probes."
msgstr ""
"Значення для опції сокету TCP_KEEPIDLE. Це час у секундах, протягом якого "
"з’єднання повинне простоювати, перед чим TCP почне відправляти тести "
"keepalive."

#: glance/common/wsgi.py:67
msgid "CA certificate file to use to verify connecting clients."
msgstr "Файл сертифікату CA для перевірки клієнтів, що під’єднуються."

#: glance/common/wsgi.py:69
msgid "Certificate file to use when starting API server securely."
msgstr ""
"Файл сертифікату для використання при захищеному запуску сервера API."

#: glance/common/wsgi.py:71
msgid "Private key file to use when starting API server securely."
msgstr ""
"Файл особистого ключа для використання при захищеному запуску сервера API."

#: glance/common/wsgi.py:83
msgid ""
"The number of child process workers that will be created to service "
"requests. The default will be equal to the number of CPUs available."
msgstr ""
"Кількість виконавців дочірнього процесу, які будуть створені для "
"обслуговування запитів. Типове значення буде дорівнювати кількости доступних "
"CPU."

#: glance/common/wsgi.py:85
msgid ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated by "
"the Keystone v3 API with big service catalogs"
msgstr ""
"Максимальний розмір рядка заголовку повідомлень. Можливо, max_header_line "
"знадобиться збільшити при використанні великих маркерів (як правило, "
"створених API Keystone версії 3 API з великими каталогами)"

#: glance/common/wsgi.py:92
msgid ""
"If False, server will return the header \"Connection: close\", If True, "
"server will return \"Connection: Keep-Alive\" in its responses. In order to "
"close the client socket connection explicitly after the response is sent and "
"read successfully by the client, you simply have to set this option to False "
"when you create a wsgi server."
msgstr ""
"Якщо False, сервер повертає заголовок \"Connection: close\". Якщо True, "
"сервер повертає \"Connection: Keep-Alive\" у своїх відповідях. Для того щоб "
"явно закрити з’єднання сокету клієнта, після того як відповідь відправлена й "
"успішно прочитана клієнтом, необхідно просто привласнити цьому параметру "
"значення False при створенні сервера wsgi."

#: glance/common/wsgi.py:101
msgid ""
"Timeout for client connections' socket operations. If an incoming connection "
"is idle for this number of seconds it will be closed. A value of '0' means "
"wait forever."
msgstr ""
"Час очікування для Socket під’єднань клієнта. Якщо вхідне під’єднання очікує "
"цю кількість секунд, то під’єднання закривається. Значення '0' означає "
"нескінчене очікування."

#: glance/common/wsgi.py:109
msgid ""
"The HTTP header used to determine the scheme for the original request, even "
"if it was removed by an SSL terminating proxy. Typical value is "
"\"HTTP_X_FORWARDED_PROTO\"."
msgstr ""
"Заголовок HTTP використовуваний для визначення схеми оригінального запиту, "
"навіть якщо він був вилучений через перерваний проксі-сервер SSL. Типовим "
"значенням є \"HTTP_X_FORWARDED_PROTO\"."

#: glance/common/wsgi.py:117
msgid "If False fully disable profiling feature."
msgstr "У випадку False повністю вимкнути функцію профілювання."

#: glance/common/wsgi.py:119
msgid "If False doesn't trace SQL requests."
msgstr "У випадку False не трасувати запити SQL."

#: glance/common/wsgi.py:121
msgid ""
"Secret key to use to sign Glance API and Glance Registry services tracing "
"messages."
msgstr ""
"Секретний ключ для підписування повідомлень трасування служб Glance API і "
"реєстру Glance."

#: glance/common/wsgi.py:131
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"При запуску сервера у режимі SSL, вам потрібно вказати значення параметрів "
"cert_file і key_file у вашому файлі конфігурації"

#: glance/common/wsgi.py:169
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""
"Не вдалося виконати зв’язування з %(host)s:%(port)s протягом 30 секунд"

#: glance/common/wsgi.py:233
msgid "eventlet 'poll' nor 'selects' hubs are available on this platform"
msgstr ""
"Для цієї платформи відсутні центри обробки подій poll і selects бібліотеки "
"eventlet"

#: glance/common/wsgi.py:786
#, python-format
msgid "Malformed Content-Range header: %s"
msgstr "Неправильний формат заголовку Content-Range: %s"

#: glance/common/wsgi.py:819
msgid "Unexpected body type. Expected list/dict."
msgstr "Непередбачений тип тіла. Очікувався перелік або словник."

#: glance/common/wsgi.py:552
msgid "Malformed JSON in request body."
msgstr "Неправильно сформований JSON у тілі запиту."

#: glance/common/wsgi.py:912
msgid "A body is not expected with this request."
msgstr "У цьому запиті не повинно бути тіла."

#: glance/common/wsgi.py:924
msgid ""
"Error decoding your request. Either the URL or the request body contained "
"characters that could not be decoded by Glance"
msgstr ""
"Помилка при декодуванні запиту. URL або тіло запиту містять символи, які "
"Glance не здатен декодувати"

#: glance/common/glare/declarative.py:59
msgid "Not a valid value type"
msgstr "Неприпустимий тип значення"

#: glance/common/glare/declarative.py:92
msgid "Default value is invalid"
msgstr "Невірне типове значення"

#: glance/common/glare/declarative.py:106
#: glance/common/glare/declarative.py:712
msgid "Value is required"
msgstr "Значення є обов’язковим"

#: glance/common/glare/declarative.py:129
msgid "Invalid item type specification"
msgstr "Неприпустима специфікація типу елемента"

#: glance/common/glare/declarative.py:132
msgid "List definitions may hot have defaults"
msgstr "Визначення переліків не можуть мати типових значень"

#: glance/common/glare/declarative.py:147
msgid "Cannot specify 'min_size' explicitly"
msgstr "Неможливо вказати 'min_size' явно"

#: glance/common/glare/declarative.py:152
msgid "Cannot specify 'max_size' explicitly"
msgstr "Неможливо вказати 'max_size' явно"

#: glance/common/glare/declarative.py:177
msgid "List size is less than minimum"
msgstr "Розмір переліку менший мінімального"

#: glance/common/glare/declarative.py:186
msgid "List size is greater than maximum"
msgstr "Розмір переліку більший максимального"

#: glance/common/glare/declarative.py:201
msgid "Items have to be unique"
msgstr "Елементи повинні бути унікальними"

#: glance/common/glare/declarative.py:249
msgid "Invalid dict property type specification"
msgstr "Неприпустима специфікація типу параметра dict"

#: glance/common/glare/declarative.py:255
msgid "Invalid dict property type"
msgstr "Невірний тип параметра dict"

#: glance/common/glare/declarative.py:269
msgid "Dictionary contains unexpected key(s)"
msgstr "Словник містить неочікувані ключі"

#: glance/common/glare/declarative.py:285
msgid "Dictionary size is less than minimum"
msgstr "Розмір словника менший мінімального"

#: glance/common/glare/declarative.py:295
msgid "Dictionary size is greater than maximum"
msgstr "Розмір словника більший максимального"

#: glance/common/glare/declarative.py:362
msgid "Custom validators list should contain tuples '(function, message)'"
msgstr ""
"Перелік користувацьких агентів перевірки повинен містити кортежі '(function, "
"message)'"

#: glance/common/glare/declarative.py:379
#, python-format
msgid "Allowed values %s are invalid under given validators"
msgstr "Дозволені значенния %s неприпустимі для даних агентів перевірки"

#: glance/common/glare/declarative.py:386
msgid "Is not allowed value"
msgstr "Не є дозволеним значенням"

#: glance/common/glare/declarative.py:404
msgid "Dependency relations cannot be mutable"
msgstr "Відношення залежности не можуть бути змінюваними"

#: glance/common/glare/declarative.py:463
msgid "Attempt to set readonly property"
msgstr "Зроблена спроба встановити властивість, доступну лише для читання"

#: glance/common/glare/declarative.py:471
msgid "Attempt to set value of immutable property"
msgstr "Зроблена спроба встановити значення незмінюваної властивости"

#: glance/common/glare/declarative.py:557
msgid "Type version has to be a valid semver string"
msgstr "Версія типу повинна бути допустимим рядком semver"

#: glance/common/glare/declarative.py:565
#, python-format
msgid "%(attribute)s is required"
msgstr "%(attribute)s є обов’язковим"

#: glance/common/glare/declarative.py:570
#, python-format
msgid "%(attribute)s have to be string"
msgstr "%(attribute)s має бути рядком"

#: glance/common/glare/declarative.py:573
#, python-format
msgid "%(attribute)s may not be longer than %(length)i"
msgstr "%(attribute)s не може бути довше %(length)i"

#: glance/common/glare/declarative.py:577
#, python-format
msgid "%(attribute)s may not be shorter than %(length)i"
msgstr "%(attribute)s не може бути коротше %(length)i"

#: glance/common/glare/declarative.py:581
#, python-format
msgid "%(attribute)s should match pattern %(pattern)s"
msgstr "%(attribute)s повинен відповідати шаблону %(pattern)s"

#: glance/common/glare/declarative.py:625
msgid "Cannot declare artifact property with reserved name 'metadata'"
msgstr ""
"Неможливо оголосити властивість артефакту з зарезервованим іменем 'metadata'"

#: glance/common/glare/declarative.py:654
msgid "Unable to modify collection in immutable or readonly property"
msgstr ""
"Неможливо змінити набір у незмінюваному або доступному лише для читання "
"параметрі"

#: glance/common/glare/definitions.py:71
msgid "Max string length may not exceed 255 characters"
msgstr "Максимальна довжина рядка не може перевищувати 255 символів"

#: glance/common/glare/definitions.py:74
msgid "Length  is greater than maximum"
msgstr "Довжина більше максимальної"

#: glance/common/glare/definitions.py:85
msgid "Min string length may not be negative"
msgstr "Мінімальна довжина рядка не може бути від’ємною"

#: glance/common/glare/definitions.py:89
msgid "Length is less than minimum"
msgstr "Довжина менша мінімальної"

#: glance/common/glare/definitions.py:101
msgid "Does not match pattern"
msgstr "Не відповідає шаблону"

#: glance/common/glare/definitions.py:158
#: glance/common/glare/definitions.py:210
#: glance/common/glare/definitions.py:260
msgid "Value is less than minimum"
msgstr "Значення менше мінімального"

#: glance/common/glare/definitions.py:169
#: glance/common/glare/definitions.py:221
#: glance/common/glare/definitions.py:271
msgid "Value is greater than maximum"
msgstr "Значення більше максимального"

#: glance/common/glare/definitions.py:312
msgid "Array property can't have item_type=Array"
msgstr "Властивість масиву не може мати item_type=Array"

#: glance/common/glare/definitions.py:384
msgid "Unable to specify artifact type explicitly"
msgstr "Неможливо вказати тип артефакту явно"

#: glance/common/glare/definitions.py:387
msgid "Unable to specify artifact type version explicitly"
msgstr "Неможливо вказати версію типу артефакту явно"

#: glance/common/glare/definitions.py:426
msgid "Unable to specify version if multiple types are possible"
msgstr "Неможливо вказати версію, якщо можливо декілька типів"

#: glance/common/glare/definitions.py:441
msgid "Invalid referenced type"
msgstr "Вказано невірний тип"

#: glance/common/glare/definitions.py:444
msgid "Unable to specify version if type is not specified"
msgstr "Неможливо вказати версію, якщо тип не вказаний"

#: glance/common/glare/definitions.py:462
msgid "Invalid reference list specification"
msgstr "Невірна специфікація переліку вказівників"

#: glance/common/glare/definitions.py:522
msgid "BinaryObject property cannot be declared mutable"
msgstr "Властивість BinaryObject не може бути оголошено як mutable"

#: glance/common/glare/definitions.py:532
msgid "Blob size is not set"
msgstr "Розмір великого двійкового об’єкту не встановлений"

#: glance/common/glare/definitions.py:536
msgid "File too large"
msgstr "Файл завеликий"

#: glance/common/glare/definitions.py:540
msgid "File too small"
msgstr "Файл замалий"

#: glance/common/glare/definitions.py:545
msgid "Too few locations"
msgstr "Замало розташувань"

#: glance/common/glare/definitions.py:550
msgid "Too many locations"
msgstr "Забагато розташувань"

#: glance/common/glare/loader.py:31
msgid ""
"When false, no artifacts can be loaded regardless of available_plugins. When "
"true, artifacts can be loaded."
msgstr ""
"Коли дорівнює false, артефакти не можуть бути завантажені, незалежно від "
"available_plugins. Коли дорівнює true, артефакти можуть бути завантажені."

#: glance/common/glare/loader.py:35
msgid ""
"A list of artifacts that are allowed in the format name or name-version. "
"Empty list means that any artifact can be loaded."
msgstr ""
"Перелік дозволених артефактів у форматі ім’я або ім’я-версія. Порожній "
"перелік означає, що усі артефакти можуть бути завантажені"

#: glance/common/glare/serialization.py:192
#, python-format
msgid "Blob %(name)s may not have multiple values"
msgstr "Великий двійковий об’єкт %(name)s може мати декілька значень"

#: glance/common/glare/serialization.py:213
#, python-format
msgid "Relation %(name)s may not have multiple values"
msgstr "Відношення %(name)s може мати декілька значень"

#: glance/common/location_strategy/__init__.py:25
msgid ""
"This value sets what strategy will be used to determine the image location "
"order. Currently two strategies are packaged with Glance 'location_order' "
"and 'store_type'."
msgstr ""
"Значення визначає, яка стратегія буде використана для визначення модулю "
"location order образу. На цю мить дві стратегії запаковані з "
"'location_order' і 'store_type' Glance."

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being used."
msgstr ""
"%(strategy)s зареєстрована як модуль двічі. %(module)s не використовується."

#: glance/common/location_strategy/__init__.py:74
#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""
"Невірний параметр location_strategy: %(name)s. Вірні параметри стратегії: "
"%(strategies)s"

#: glance/common/location_strategy/store_type.py:28
msgid ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'stores' config option. This "
"option will be applied when you using 'store_type' option as image location "
"strategy defined by the 'location_strategy' config option."
msgstr ""
"Імена сховищ даних, що використовуються для отримання порядку параметрів "
"сховищ. Ім’я повинне бути зареєстрованим у одному зі сховищ, визначених в "
"опції налаштування 'stores'. Ця опція буде застосована при використанні "
"опції 'store_type' у якості стратегії пошуку образу, визначеній в опції "
"налаштування 'location_strategy'."

#: glance/common/scripts/utils.py:61
#, python-format
msgid "Input does not contain '%(key)s' field"
msgstr "Ввід не містить поле %(key)s"

#: glance/common/scripts/utils.py:95
msgid ""
"File based imports are not allowed. Please use a non-local source of image "
"data."
msgstr ""
"Імпорти на піставі файлів не дозволені. Використовуйте нелокальне джерело "
"даних образу."

#: glance/common/scripts/utils.py:104
#, python-format
msgid ""
"The given uri is not valid. Please specify a valid uri from the following "
"list of supported uri %(supported)s"
msgstr ""
"Вказаний uri неприпустимий. Вкажіть припустимий uri із наступного переліку "
"підтримуваних uri %(supported)s"

#: glance/common/scripts/image_import/main.py:103
#, python-format
msgid ""
"The Image %(image_id)s object being created by this task %(task_id)s, is no "
"longer in valid status for further processing."
msgstr ""
"Об’єкт образу %(image_id)s, створюваний за допомогою задачі %(task_id)s, "
"більше не знаходиться у припустимому стані для подальшої обробки."

#: glance/contrib/plugins/image_artifact/v2/image.py:44
msgid "Either a file or a legacy_image_id has to be specified"
msgstr "Необхідно вказати file або legacy_image_id"

#: glance/contrib/plugins/image_artifact/v2/image.py:49
msgid "Both file and legacy_image_id may not be specified at the same time"
msgstr "Неможливо одночасно вказати file і legacy_image_id"

#: glance/contrib/plugins/image_artifact/v2/image.py:59
msgid "Glance client not installed"
msgstr "Клієнт Glance не встановлений"

#: glance/contrib/plugins/image_artifact/v2/image.py:68
msgid "Unable to get legacy image"
msgstr "Неможливо отримати застарілий образ"

#: glance/contrib/plugins/image_artifact/v2/image.py:82
msgid "Legacy image was not found"
msgstr "Застарілий образ не знайдений"

#: glance/db/__init__.py:85 glance/db/__init__.py:127 glance/db/__init__.py:137
#: glance/db/__init__.py:151
#, python-format
msgid "No artifact found with ID %s"
msgstr "Не знайдені артефакти з ІД %s"

#: glance/db/__init__.py:64 glance/db/__init__.py:167 glance/db/__init__.py:179
#: glance/db/sqlalchemy/api.py:181
#, python-format
msgid "No image found with ID %s"
msgstr "Не знайдено образів з ID %s"

#: glance/db/__init__.py:238
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr "Користувач %(member_id)s вже асоційований з образом %(image_id)s."

#: glance/db/__init__.py:255
#, python-format
msgid "The specified member %s could not be found"
msgstr "Вказаний користувач %s не знайдений"

#: glance/db/__init__.py:334 glance/db/__init__.py:360
#: glance/db/__init__.py:377 glance/db/simple/api.py:762
#, python-format
msgid "Could not find task %s"
msgstr "Завдання %s не може бути знайдено"

#: glance/db/__init__.py:539
#, python-format
msgid "Could not find namespace %s"
msgstr "Не знайдено простору імен %s"

#: glance/db/__init__.py:561 glance/db/__init__.py:571
#: glance/db/__init__.py:581 glance/db/__init__.py:591
#, python-format
msgid "The specified namespace %s could not be found"
msgstr "Вказаного простору імен %s не знайдено"

#: glance/db/__init__.py:682
#, python-format
msgid "Could not find metadata object %s"
msgstr "Не знайденю об’єкт метаданих %s"

#: glance/db/__init__.py:705
#, python-format
msgid "The specified metadata object %s could not be found"
msgstr "Вказаний об’єкт метаданих %s не знайдений"

#: glance/db/__init__.py:798
#, python-format
msgid "The specified resource type %s could not be found "
msgstr "Вказаний тип ресурсу %s не знайдений "

#: glance/db/__init__.py:845
#, python-format
msgid "Could not find property %s"
msgstr "Не знайдено властивість %s"

#: glance/db/__init__.py:867
#, python-format
msgid "The specified property %s could not be found"
msgstr "Вказана властивість %s не знайдена"

#: glance/db/__init__.py:931
#, python-format
msgid "Could not find metadata tag %s"
msgstr "Не вдалося знайти тег метаданих %s"

#: glance/db/__init__.py:957
#, python-format
msgid "The specified metadata tag %s could not be found"
msgstr "Не вдалося знайти вказаний тег метаданих %s"

#: glance/db/simple/api.py:256 glance/db/sqlalchemy/api.py:407
msgid "Unable to filter on a range with a non-numeric value."
msgstr "Відфільтрувати по діяпазону з нечисловим значенням неможливо."

#: glance/db/simple/api.py:317 glance/db/sqlalchemy/api.py:525
#, python-format
msgid "Unable to filter by unknown operator '%s'."
msgstr ""
"Не вдається відфільтрувати з використанням невідомого оператора: '%s'"

#: glance/db/simple/api.py:425 glance/db/sqlalchemy/api.py:951
msgid "Image id is required."
msgstr "Потрібен ідентифікатор образу."

#: glance/db/simple/api.py:570 glance/db/sqlalchemy/api.py:873
#, python-format
msgid "The location data has an invalid ID: %d"
msgstr "Дані про розташування містять неприпустимий ІД: %d"

#: glance/db/simple/api.py:590 glance/db/simple/api.py:616
#: glance/db/sqlalchemy/api.py:893 glance/db/sqlalchemy/api.py:919
#, python-format
msgid "No location found with ID %(loc)s from image %(img)s"
msgstr "Розташування з ІД %(loc)s із образу %(img)s не знайдено"

#: glance/db/simple/api.py:600
msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'."
msgstr ""
"Стан розташування віддаленого образу може дорівнювати лише 'pending_delete' "
"або 'deleted'."

#: glance/db/simple/api.py:772 glance/db/sqlalchemy/api.py:1256
#, python-format
msgid "Forbidding request, task %s is not visible"
msgstr "Запит забороняється, задача %s невидима"

#: glance/db/simple/api.py:890
msgid "Task does not exist"
msgstr "Задача не існує"

#: glance/db/simple/api.py:1155
#: glance/db/sqlalchemy/metadef_api/namespace.py:249
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition namespace "
"with the same name of %s"
msgstr ""
"Неприпустиме оновлення. Воно створює простір імен визначення метаданих з "
"таким же іменем, як у простору імен %s"

#: glance/db/simple/api.py:1176
#: glance/db/sqlalchemy/metadef_api/namespace.py:88
#, python-format
msgid "Metadata definition namespace not found for id=%s"
msgstr "Не знайдено простору імен визначення метаданих для ІД %s"

#: glance/db/simple/api.py:1184 glance/db/simple/api.py:2128
#: glance/db/sqlalchemy/metadef_api/namespace.py:97
#: glance/db/sqlalchemy/metadef_api/namespace.py:119
#, python-format
msgid "Forbidding request, metadata definition namespace=%s is not visible."
msgstr "Заборонений запит: простір імен %s визначення метаданих невидимий."

#: glance/db/simple/api.py:1307 glance/db/sqlalchemy/metadef_api/object.py:35
#, python-format
msgid "Metadata definition object not found for id=%s"
msgstr "Не знайдено об’єкт визначення метаданих для ІД %s"

#: glance/db/simple/api.py:1388
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s  in namespace=%(namespace_name)s."
msgstr ""
"Неприпустиме оновлення. Воно створює об’єкт визначення метаданих з таким "
"самим іменем, як у об’єкту %(name)s у просторі імен %(namespace_name)s."

#: glance/db/simple/api.py:1515
#: glance/db/sqlalchemy/metadef_api/property.py:122
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition property "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"Неприпустиме оновлення. Воно створює простір імен визначення метаданих з "
"таким самим іменем, як у властивости %(name)s у просторі імен "
"%(namespace_name)s."

#: glance/db/simple/api.py:1559 glance/db/sqlalchemy/metadef_api/property.py:37
#, python-format
msgid "Metadata definition property not found for id=%s"
msgstr "Не знайдено властивости визначення метаданих для ІД %s"

#: glance/db/simple/api.py:1765
#, python-format
msgid "Metadata definition tag not found for id=%s"
msgstr "Не знайдено тегу визначення метаданих для ІД %s"

#: glance/db/sqlalchemy/api.py:85
msgid "You do not own this image"
msgstr "Цей образ належить не вам"

#: glance/db/sqlalchemy/api.py:337
#: glance/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Невідомий напрямок сортування, повинен бути 'desc' або 'asc'"

#: glance/db/sqlalchemy/api.py:507
#, python-format
msgid "Bad \"%s\" query filter format. Use ISO 8601 DateTime notation."
msgstr ""
"Неприпустимий формат фільтру запиту \"%s\". Використовуйте нотацію DateTime "
"ISO 8601."

#: glance/db/sqlalchemy/api.py:682
#: glance/tests/unit/v2/test_registry_client.py:500
#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"
msgstr ""
"не вдається виконати перехід від %(current)s до %(next)s при оновленні "
"(потрібен from_state=%(from)s)"

#: glance/db/sqlalchemy/api.py:902
msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'"
msgstr ""
"Стан розташування віддаленого образу може дорівнювати лише 'pending_delete' "
"або 'deleted'"

#: glance/db/sqlalchemy/metadata.py:42
msgid "Path to the directory where json metadata files are stored"
msgstr "Шлях до каталогу, де зберігаються файли метаданих json"

#: glance/db/sqlalchemy/metadef_api/object.py:112
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"Неприпустиме оновлення. Воно створює об’єкт визначення метаданих з таким "
"самим іменем, як у об’єкту %(name)s у просторі імен %(namespace_name)s."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:86
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:149
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like swift://user:pass@http://authurl.com/v1/container/obj, "
"you need to change it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI не може містити більше однієї схеми. Якщо вказаний URI типу "
"swift://user:pass@http://authurl.com/v1/container/obj, то потрібно замінити "
"схему на swift+http://, наприклад: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:123
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:185
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr "Неправильно сформовані реквізити '%(creds)s' у URI Swift"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:135
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:197
#: glance/store/swift.py:246
msgid "Badly formed credentials in Swift URI."
msgstr "Неправильно сформовані ідентифікаційні дані в URI Swift."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:152
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:214
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr "Неправильно сформований URI S3: %(uri)s"

#: glance/domain/__init__.py:59
#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr "В new_image() отримані непередбачені ключові слова %s"

#: glance/domain/__init__.py:129
#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr "В __init__() отримано непередбачений іменований аргумент '%s'"

#: glance/domain/__init__.py:151
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr "Властивість %s повинна бути вказана до збереження даних."

#: glance/domain/__init__.py:154
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr "Властивости %s мають бути вказані до збереження даних."

#: glance/domain/__init__.py:171
msgid "Visibility must be either \"public\" or \"private\""
msgstr "Видимість повинна бути \"public\" або \"private\""

#: glance/domain/__init__.py:190
msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""
"container_format атрибуту може бути замінений лише для образу, що "
"знаходиться у черзі."

#: glance/domain/__init__.py:202
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""
"disk_format атрибуту може бути замінений лише для образу, що знаходиться у "
"черзі."

#: glance/domain/__init__.py:214 glance/domain/__init__.py:227
msgid "Cannot be a negative value"
msgstr "Не може приймати негативне значення"

#: glance/domain/__init__.py:255
#, python-format
msgid "Not allowed to deactivate image in status '%s'"
msgstr "Заборонено деактивувати образ у стані %s"

#: glance/domain/__init__.py:268
#, python-format
msgid "Not allowed to reactivate image in status '%s'"
msgstr "Заборонено повторно активувати образ у стані %s"

#: glance/domain/__init__.py:292
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr "Стан повинен бути \"pending\", \"accepted\" або \"rejected\"."

#: glance/glare/dependency.py:66
#, python-format
msgid "Not all dependencies are in '%s' state"
msgstr "Не усі залежності знаходяться у стані '%s'"

#: glance/glare/dependency.py:98
#, python-format
msgid "Dependency property '%s' has to be deleted first"
msgstr "Спочатку необхідно вилучити властивість залежності '%s'"

#: glance/glare/location.py:159
#, python-format
msgid "Get blob %(name)s data failed: %(err)s."
msgstr ""
"Отримання даних великого двійкового об’єкту %(name)s не виконано: %(err)s."

#: glance/glare/updater.py:52
msgid "No property to access"
msgstr "Відсутня властивість для доступу"

#: glance/glare/updater.py:130
#, python-format
msgid "Array has no element at position %d"
msgstr "Масив не має елементу в позиції %d"

#: glance/glare/updater.py:134
#, python-format
msgid "Not an array idx '%s'"
msgstr "Не є індексом масиву '%s'"

#: glance/glare/updater.py:174
#, python-format
msgid "No such key '%s' in a dict"
msgstr "У словнику відсутній ключ '%s'"

#: glance/image_cache/__init__.py:34
msgid "The driver to use for image cache management."
msgstr "Драйвер для керування кешем образів."

#: glance/image_cache/__init__.py:39
msgid ""
"The upper limit (the maximum size of accumulated cache in bytes) beyond "
"which the cache pruner, if running, starts cleaning the image cache."
msgstr ""
"Максимальний розмір акумульованого кешу у байтах, при перевищенні якого "
"агент очистки кешу, якщо він запущений, починає очистку кешу образів."

#: glance/image_cache/__init__.py:43
msgid ""
"The amount of time to let an incomplete image remain in the cache, before "
"the cache cleaner, if running, will remove the incomplete image."
msgstr ""
"Час, протягом якого неповний образ може залишатися у кеші перед тим, як його "
"вилучить агент очистки кешу, якщо він запущений."

#: glance/image_cache/__init__.py:47
msgid "Base directory that the image cache uses."
msgstr "Базовий каталог для кешу образів."

#: glance/image_cache/__init__.py:253
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr ""
"Перевірка контрольною сумою не виконана. Кешування образу '%s' перервано."

#: glance/image_cache/client.py:117
msgid ""
"--os_auth_url option or OS_AUTH_URL environment variable required when "
"keystone authentication strategy is enabled\n"
msgstr ""
"Опція --os_auth_url або змінна середовища OS_AUTH_URL потрібна, якщо "
"увімкнена стратегія ідентифікації Keystone\n"

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr "Не вдалося зчитати %s з конфігураційного файлу"

#: glance/image_cache/drivers/sqlite.py:39
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""
"Шлях до бази даних файлів sqlite, яка буде використана для керування кешем "
"образів."

#: glance/image_cache/drivers/sqlite.py:121
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr ""
"Помилка ініціалізації бази даних тимчасових файлів образу. Отримана помилка: "
"%s"

#: glance/image_cache/drivers/xattr.py:104
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not "
"support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the cache "
"directory."
msgstr ""
"Пристрій, на якому знаходиться директорія кешованих образів "
"%(image_cache_dir)s, не підтримує xattr. Швидше за все, вам потрібно "
"відредагувати fstab і додати опцію user_xattr до відповідного рядка для "
"пристрою, на якому знаходиться директорія кешованих образів."

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr "Адреса для пошуку сервера реєстру."

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr "Порт, через який сервер реєстру веде приймання."

#: glance/registry/api/v1/images.py:107 glance/registry/api/v1/images.py:112
msgid "Invalid marker. Image could not be found."
msgstr "Неприпустимий маркер. Образ не знайдено."

#: glance/registry/api/v1/images.py:216
msgid "Unrecognized changes-since value"
msgstr "Нерозпізнане значення змін за період"

#: glance/registry/api/v1/images.py:221
msgid "protected must be True, or False"
msgstr "Параметр protected повинен дорівнювати True або False"

#: glance/registry/api/v1/images.py:268
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr "Непідтримуваний sort_key. Припустимі значення: %s"

#: glance/registry/api/v1/images.py:277
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr "Непідтримуваний sort_dir. Припустимі значення: %s"

#: glance/registry/api/v1/images.py:303
msgid "is_public must be None, True, or False"
msgstr "is_public повинен мати значення None, True або False"

#: glance/registry/api/v1/images.py:395
msgid "Invalid image id format"
msgstr "Неприпустимий формат ідентифікатора образу"

#: glance/registry/api/v1/images.py:409
#, python-format
msgid "Image with identifier %s already exists!"
msgstr "Образ з ідентифікатором %s вже існує!"

#: glance/registry/api/v1/images.py:451
#, python-format
msgid "Failed to add image metadata. Got error: %s"
msgstr "Додати метадані образу не вдалося. Помилка: %s"

#: glance/registry/api/v1/images.py:322 glance/registry/api/v1/images.py:363
#: glance/registry/api/v1/images.py:466 glance/registry/api/v1/members.py:66
#: glance/registry/api/v1/members.py:100 glance/registry/api/v1/members.py:213
#: glance/registry/api/v1/members.py:273
#, python-format
msgid "Image %(id)s not found"
msgstr "Образ %(id)s не знайдено"

#: glance/registry/api/v1/members.py:114 glance/registry/api/v1/members.py:227
#: glance/registry/api/v1/members.py:287
msgid "No permission to share that image"
msgstr "Немає дозволів для відкриття загального доступу до цього образу"

#: glance/registry/api/v1/members.py:125 glance/registry/api/v1/members.py:141
#: glance/registry/api/v1/members.py:240
#, python-format
msgid "Invalid membership association: %s"
msgstr "Неприпустима асоціяція членства: %s"

#: glance/registry/api/v1/members.py:300 glance/registry/api/v1/members.py:317
msgid "Membership could not be found."
msgstr "Членство не знайдено."

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr "Служба реєстру не може використовувати %s"

#: glance/registry/client/__init__.py:20
msgid ""
"The protocol to use for communication with the registry server.  Either http "
"or https."
msgstr "Протокол зв’язку з сервером реєстру. Або http, або https."

#: glance/registry/client/__init__.py:26
msgid ""
"The path to the key file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_KEY_FILE environment "
"variable to a filepath of the key file"
msgstr ""
"Шлях до файлу ключа для використання у з’єднаннях SSL з сервером реєстру "
"(якщо такий є). Або можна привласнити змінній середовища "
"GLANCE_CLIENT_KEY_FILE шлях до файлу ключа"

#: glance/registry/client/__init__.py:31
msgid ""
"The path to the cert file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_CERT_FILE environment "
"variable to a filepath of the CA cert file"
msgstr ""
"Шлях до файлу сертифікату для використання у з’єднаннях SSL з сервером "
"реєстру (якщо такий є). Або можна привласнити змінній середовища "
"GLANCE_CLIENT_CERT_FILE шлях до файлу сертифікату CA"

#: glance/registry/client/__init__.py:36
msgid ""
"The path to the certifying authority cert file to use in SSL connections to "
"the registry server, if any. Alternately, you may set the "
"GLANCE_CLIENT_CA_FILE environment variable to a filepath of the CA cert file."
msgstr ""
"Шлях до файлу сертифікату CA для використання у з’єднаннях SSL з сервером "
"реєстру (якщо такий є). Або можна привласнити змінній середовища "
"GLANCE_CLIENT_CA_FILE шлях до файлу сертифікату CA ."

#: glance/registry/client/__init__.py:42
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority. This is the registry's equivalent of "
"specifying --insecure on the command line using glanceclient for the API."
msgstr ""
"При використанні SSL у з’єднаннях з сервером реєстру не вимагати перевірки у "
"сертифікатної компанії. Це реєстровий еквівалент параметру --insecure "
"командного рядка в glanceclient для API."

#: glance/registry/client/__init__.py:36
msgid ""
"The period of time, in seconds, that the API server will wait for a registry "
"request to complete. A value of 0 implies no timeout."
msgstr ""
"Час у секундах, протягом якого сервер API буде очікувати виконання запиту до "
"реєстру. 0 означає відсутність тайм-ауту."

#: glance/registry/client/__init__.py:64
msgid ""
"Whether to pass through the user token when making requests to the registry. "
"To prevent failures with token expiration during big files upload, it is "
"recommended to set this parameter to False.If \"use_user_token\" is not in "
"effect, then admin credentials can be specified."
msgstr ""
"Чи здійснювати наскрізну передачу користувацького маркера при створенні "
"запитів у реєстр Для попередження збоїв, пов’язаних із закінченням терміну "
"дії маркера під час передачі великих даних, рекомендується привласнювати "
"цьому параметру значення False. Якщо \"use_user_token\" не використовується, "
"можна вказати ідентифікаційні дані адміністратора."

#: glance/registry/client/__init__.py:73
msgid ""
"The administrators user name. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"Ім’я адміністратора. Якщо \"use_user_token\" не діє, можуть бути вказані "
"ідентифікаційні дані адміністратора."

#: glance/registry/client/__init__.py:78
msgid ""
"The administrators password. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"Пароль адміністратора. Якщо \"use_user_token\" не діє, можуть бути вказані "
"ідентифікаційні дані адміністратора."

#: glance/registry/client/__init__.py:83
msgid ""
"The tenant name of the administrative user. If \"use_user_token\" is not in "
"effect, then admin tenant name can be specified."
msgstr ""
"Ім’я арендатора адміністратора. Якщо \"use_user_token\" не діє, можна "
"вказати ім’я арендатора адміністратора."

#: glance/registry/client/__init__.py:88
msgid ""
"The URL to the keystone service. If \"use_user_token\" is not in effect and "
"using keystone auth, then URL of keystone can be specified."
msgstr ""
"URL служби Keystone. Якщо \"use_user_token\" не діє й використовується "
"ідентифікація Keystone, можна вказати URL Keystone."

#: glance/registry/client/__init__.py:94
msgid ""
"The strategy to use for authentication. If \"use_user_token\" is not in "
"effect, then auth strategy can be specified."
msgstr ""
"Стратегія ідентифікації. Якщо \"use_user_token\" не діє, можна вказати "
"стратегію ідентифікації."

#: glance/registry/client/__init__.py:99
msgid ""
"The region for the authentication service. If \"use_user_token\" is not in "
"effect and using keystone auth, then region name can be specified."
msgstr ""
"Регіон служби ідентифікації. Якщо \"use_user_token\" не діє й "
"використовується ідентифікація Keystone, можна вказатии ім’я регіону."

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr "Неприпустима опція конфігурації"

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr "Обов’язкова опція конфігурації не знайдена"

#: glance/tests/unit/test_migrations.py:927
#, python-format
msgid "location: %s data lost"
msgstr "місце: %s втрати даних"
