# Ukrainian translations for keystone.
# Copyright (C) 2013 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2016-04-21 07:06+0000\n"
"PO-Revision-Date: 2016-04-08 08:32+0000\n"
"Last-Translator: Mykola Tkach <chistomov@gmail.com>\n"
"Language-Team: Ukrainian "
"(http://www.transifex.com/projects/p/openstack/language/uk/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-03-25 09:32+0000\n"
"X-Generator: Launchpad (build aec24aef7a9042c99ef3e238d8b0ca01df9e1a9f)\n"
"Generated-By: Babel 1.3\n"

#: keystone/exception.py:83
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not comply "
"with the request since it is either malformed or otherwise incorrect. The "
"client is assumed to be in error."
msgstr ""
"Очікується %(attribute)s в %(target)s - серверу не вдалося задовільнити "
"запит, оскільки його формат є невірним, або запит некоректний з іншої "
"причини. Припущення, що клієнт знаходиться у стані помилки."

#: keystone/exception.py:92
#, python-format
msgid "Cannot create an endpoint with an invalid URL: %(url)s"
msgstr "Не вдалося створити кінцеву точку із неприпустимою URL: %(url)s"

#: keystone/exception.py:99
#, python-format
msgid "%(detail)s"
msgstr "%(detail)s"

#: keystone/exception.py:103
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client is "
"assumed to be in error."
msgstr ""
"Відмітка не у очікуваному форматі. Сервер не може виконати запит, оскільки "
"він або пошкоджений або хибний. Клієнт вважається помилковим."

#: keystone/exception.py:112
msgid ""
"The 'expires_at' must not be before now. The server could not comply with "
"the request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""
"Значення параметру 'expires_at' не повинне бути менше поточного часу. "
"Серверу не вдалося виконати запит, оскільки він пошкоджений або неправильно "
"сформований. Ймовірно, клієнт знаходиться у стані помилки."

#: keystone/exception.py:121
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the limit "
"of column %(type)s(CHAR(%(length)d))."
msgstr ""
"Перевищена довжина рядка. Перевищено ліміт довжини рядка '%(string)s' у "
"стовпці %(type)s(CHAR(%(length)d))."

#: keystone/exception.py:127
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. The "
"server could not comply with the request because the attribute size is "
"invalid (too large). The client is assumed to be in error."
msgstr ""
"Запит атрибуту %(attribute)s повинен бути меншим або дорівнювати %(size)i. "
"Сервер не може виконати запит бо розмір атрибуту є неприпустимим. Клієнт "
"вважається помилковим."

#: keystone/exception.py:137
#, python-format
msgid ""
"The specified parent region %(parent_region_id)s would create a circular "
"region hierarchy."
msgstr ""
"Вказана батьківська область %(parent_region_id)s створить кругову структуру "
"області."

#: keystone/exception.py:156
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server could "
"not comply with the request because the password is invalid."
msgstr ""
"Довжина паролю не повинна перевищувати %(size)i. Сервер не може виконати "
"запит, оскільки пароль неприпустимий."

#: keystone/exception.py:162
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions have "
"associated endpoints."
msgstr ""
"Не вдалося вилучити регіон %(region_id)s: регіон або його дочірні регіони "
"мають зв’язані кінцеві точки."

#: keystone/exception.py:167
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""
"Запитувані Вами сертифікати не доступні. Цілком ймовірно, що цей сервер не "
"використовує PKI-маркери, у протилежному випадку це результат неправильного "
"налаштування."

#: keystone/exception.py:179
msgid "(Disable insecure_debug mode to suppress these details.)"
msgstr "(Вимкніть режим insecure_debug, щоб не показувати ці подробиці.)"

#: keystone/exception.py:189
#, python-format
msgid "%(message)s %(amendment)s"
msgstr "%(message)s %(amendment)s"

#: keystone/exception.py:197
msgid "The request you have made requires authentication."
msgstr "Запит що ви зробили вимагає автентифікації."

#: keystone/exception.py:203
msgid "Authentication plugin error."
msgstr "Помилка модулю автентифікації."

#: keystone/exception.py:211
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""
"Не вдається знайти дійсні групи, використовуючи відображення %(mapping_id)s"

#: keystone/exception.py:216
msgid "Attempted to authenticate with an unsupported method."
msgstr "Спроба автентифікації непідтримуваним методом."

#: keystone/exception.py:224
msgid "Additional authentications steps required."
msgstr "Потрібні додаткові етапи автентифікації"

#: keystone/exception.py:232
msgid "You are not authorized to perform the requested action."
msgstr "Ви повинні авторизуватися для виконання данної дії"

#: keystone/exception.py:239
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr "В Вас немає прав на виконання запитаної дії: %(action)s"

#: keystone/exception.py:244
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target %(target)s"
msgstr ""
"Змінити постійний атрибут '%(attributes)s' у мети %(target)s неможливо"

#: keystone/exception.py:249
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in question "
"is %(group_id)s, user is %(user_id)s"
msgstr ""
"Членство у групі не може розповсюджуватися через межі базових систем, група "
"під питанням - %(group_id)s, користувач - %(user_id)s"

#: keystone/exception.py:255
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service or "
"Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, Service: "
"%(service_id)s, Region: %(region_id)s"
msgstr ""
"Неприпустиме змішування сутностей для зв’язування стратегії. Лише Кінцева "
"точка, Служба та Регіон+Служба дозволені. У запиті було: Кінцева точка "
"%(endpoint_id)s, Служба %(service_id)s, Регіон %(region_id)s"

#: keystone/exception.py:262
#, python-format
msgid "Invalid domain specific configuration: %(reason)s"
msgstr "Неприпустима конфігурація для домену: %(reason)s"

#: keystone/exception.py:266
#, python-format
msgid "Could not find: %(target)s"
msgstr "не знайдена: %(target)s"

#: keystone/exception.py:272
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr "Кінцева точка %(endpoint_id)s не знайдена"

#: keystone/exception.py:279
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr "Необроблене виключення: Не знайдені метадані."

#: keystone/exception.py:284
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr "Стратегія %(policy_id)s не знайдена"

#: keystone/exception.py:288
msgid "Could not find policy association"
msgstr "Не знайдено зв’язок стратегії"

#: keystone/exception.py:292
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr "Роль %(role_id)s не знайдена"

#: keystone/exception.py:296
#, python-format
msgid "%(prior_role_id)s does not imply %(implied_role_id)s"
msgstr "%(prior_role_id)s не має на увазі %(implied_role_id)s"

#: keystone/exception.py:300
#, python-format
msgid "%(role_id)s cannot be an implied roles"
msgstr "%(role_id)s не може бути роллю, що мається на увазі"

#: keystone/exception.py:304
#, python-format
msgid ""
"Could not find role assignment with role: %(role_id)s, user or group: "
"%(actor_id)s, project or domain: %(target_id)s"
msgstr ""
"Не знайдено привласнення ролі %(role_id)s, користувач/група: %(actor_id)s, "
"проєкт/домен: %(target_id)s"

#: keystone/exception.py:310
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr "Не вдалося знайти область: %(region_id)s"

#: keystone/exception.py:314
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr "Не вдалося знайти сервіс: %(service_id)s"

#: keystone/exception.py:318
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr "Домен %(domain_id)s не знайдено"

#: keystone/exception.py:322
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr "Проєкт %(project_id)s не знайдено"

#: keystone/exception.py:326
#, python-format
msgid "Cannot create project with parent: %(project_id)s"
msgstr "Не вдається створити проєкт з батьківським об’єктом: %(project_id)s"

#: keystone/exception.py:330
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr "Ключ %(token_id)s не знайдено"

#: keystone/exception.py:334
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr "Користувач %(user_id)s не знайдений"

#: keystone/exception.py:338
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr "Група %(group_id)s не знайдена"

#: keystone/exception.py:342
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr "Відображення %(mapping_id)s не знайдено"

#: keystone/exception.py:346
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr "Група довір’я %(trust_id)s не знайдена"

#: keystone/exception.py:350
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr "Варіянтів використання групи довір’я %(trust_id)s не залишилося"

#: keystone/exception.py:354
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr "Ідентифікаційні дані %(credential_id)s не знайдені"

#: keystone/exception.py:358
#, python-format
msgid "Could not find version: %(version)s"
msgstr "Версія %(version)s не знайдена"

#: keystone/exception.py:362
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr "Не знайдена група кінцевих точок: %(endpoint_group_id)s"

#: keystone/exception.py:366
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr "Постачальник ідентифікаторів %(idp_id)s не знайдений"

#: keystone/exception.py:370
#, python-format
msgid "Could not find Service Provider: %(sp_id)s"
msgstr "Не вдалося знайти постачальник служб %(sp_id)s"

#: keystone/exception.py:374
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""
"Об’єднанийй протокол %(protocol_id)s для постачальника ідентифікаторів "
"%(idp_id)s не знайдений"

#: keystone/exception.py:385
#, python-format
msgid ""
"Could not find %(group_or_option)s in domain configuration for domain "
"%(domain_id)s"
msgstr ""
"Не знайдений користувач/група %(group_or_option)s у конфігурації домену "
"%(domain_id)s"

#: keystone/exception.py:403
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr "При спробі зберегти %(type)s виник конфлікт - %(details)s"

#: keystone/exception.py:412
msgid ""
"An unexpected error prevented the server from fulfilling your request."
msgstr "Непередбачена помилка перешкоджає серверу виконати запит."

#: keystone/exception.py:415
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""
"З-за непередбаченої помилки Ваш запит не був виконаний сервером: "
"%(exception)s"

#: keystone/exception.py:433
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr "Прийняти групу довір’я %(trust_id)s і захопити блокування неможливо."

#: keystone/exception.py:438
msgid ""
"Expected signing certificates are not available on the server. Please check "
"Keystone configuration."
msgstr ""
"Очікувані сертифікати підпису не доступні на сервері. Будь ласка, перевірте "
"конфігурацію Keystone."

#: keystone/exception.py:444
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""
"Некоректна URL кінцевої точки (%(endpoint)s), дивіться подробиці у журналі "
"помилок."

#: keystone/exception.py:449
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in the "
"backend."
msgstr ""
"Група %(group_id)s, повернена перетворенням %(mapping_id)s, не знайдена на "
"базовому сервері."

#: keystone/exception.py:454
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr "Помилка читання файлу метаданих: %(reason)s"

#: keystone/exception.py:458
#, python-format
msgid ""
"Local section in mapping %(mapping_id)s refers to a remote match that "
"doesn't exist (e.g. {0} in a local section)."
msgstr ""
"Локальний розділ у перетворенні %(mapping_id)s вказує на віддалений збіг, "
"який не існує (наприклад, {0} у локальному розділі)."

#: keystone/exception.py:464
#, python-format
msgid ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"
msgstr ""
"Непередбачена комбінація атрибутів надання доступу - користувач: "
"%(user_id)s, група: %(group_id)s, проєкт: %(project_id)s, домен: "
"%(domain_id)s"

#: keystone/exception.py:471
msgid "The action you have requested has not been implemented."
msgstr "Дію, яку ви запитали, ще не реалізовано."

#: keystone/exception.py:478
msgid "The service you have requested is no longer available on this server."
msgstr "Сервіс, який Ви запитали, більше не доступний на цьому сервері."

#: keystone/exception.py:485
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr "Файл конфігурації Keystone %(config_file)s не може бути знайдено."

#: keystone/exception.py:490
msgid ""
"No encryption keys found; run keystone-manage fernet_setup to bootstrap one."
msgstr ""
"Не знайдені ключі шифрування. Виконайте команду keystone-manage "
"fernet_setup, щоб створити ключ."

#: keystone/exception.py:495
#, python-format
msgid ""
"The Keystone domain-specific configuration has specified more than one SQL "
"driver (only one is permitted): %(source)s."
msgstr ""
"У конфігурації для домену Keystone вказано декілька драйверів SQL "
"(допустимий лише один): %(source)s."

#: keystone/exception.py:502
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration repository "
"path at %(path)s doesn't exist or isn't a directory."
msgstr ""
"%(mod_name)s не забезпечує можливість перенесення бази даних. Шлях "
"переміщення репозиторію у %(path)s не існує або не є каталогом."

#: keystone/exception.py:509
msgid "Token version is unrecognizable or unsupported."
msgstr "Версія маркера нерозпінана або не підтримується"

#: keystone/exception.py:514
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not have "
"xmlsec1 installed, or this is the result of misconfiguration. Reason "
"%(reason)s"
msgstr ""
"Не вдалося підписати ствердження SAML. Ймовірно, на цьому сервері не "
"встановлена проґрама xmlsec1 або це результат неправильного налаштування. "
"Причина: %(reason)s"

#: keystone/exception.py:521
msgid ""
"No Authorization headers found, cannot proceed with OAuth related calls, if "
"running under HTTPd or Apache, ensure WSGIPassAuthorization is set to On."
msgstr ""
"Не знайдені заголовки надання доступу - виклики, пов’язані з OAuth, "
"неможливі при виконанні під керуванням HTTPd або Apache. Переконайтеся, що "
"параметру WSGIPassAuthorization привласнено значення On."

#: keystone/exception.py:528
#, python-format
msgid ""
"Could not determine Identity Provider ID. The configuration option "
"%(issuer_attribute)s was not found in the request environment."
msgstr ""
"Не вдалося визначити ІД постачальника ідентифікації. Опція конфігурації "
"%(issuer_attribute)s не знайдена у середовищі запиту."

#: keystone/exception.py:536
#, python-format
msgid ""
"The %s extension has been moved into keystone core and as such its "
"migrations are maintained by the main keystone database control. Use the "
"command: keystone-manage db_sync"
msgstr ""
"Розширення %s було переміщено в ядро keystone, й його перенесення "
"підтримується основною системою керування бази даних keystone. "
"Використовуйте команду: keystone-manage db_sync"

#: keystone/exception.py:544
#, python-format
msgid "%(driver)s is not supported driver version"
msgstr "%(driver)s не підтримується версію драйвера"

#: keystone/notifications.py:232
#, python-format
msgid ""
"%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""
"%(event)s не є допустимою подією сповіщення, потрібне одне зі значень: "
"%(actions)s"

#: keystone/notifications.py:241
#, python-format
msgid "Method not callable: %s"
msgstr "Виклик методу неможливий: %s"

#: keystone/assignment/controllers.py:100 keystone/identity/controllers.py:71
#: keystone/resource/controllers.py:90
msgid "Name field is required and cannot be empty"
msgstr "Потрібно заповнити поле назви"

#: keystone/assignment/controllers.py:146
#: keystone/assignment/controllers.py:163
#: keystone/assignment/controllers.py:182
msgid "User roles not supported: tenant_id required"
msgstr "Ролі користувачів не підтримуються, потрібен tenant_id"

#: keystone/assignment/controllers.py:567
#: keystone/assignment/controllers.py:856
msgid "Specify a domain or project, not both"
msgstr ""
"Вкажіть домен або проект. Допускається вказування лише одного варіанту."

#: keystone/assignment/controllers.py:570
msgid "Specify one of domain or project"
msgstr "Вкажіть один домен або проєкт"

#: keystone/assignment/controllers.py:575
#: keystone/assignment/controllers.py:861
msgid "Specify a user or group, not both"
msgstr ""
"Вкажіть користувача або групу. Допускається вказування лише одного варіанту."

#: keystone/assignment/controllers.py:578
msgid "Specify one of user or group"
msgstr "Вкажіть одного користувача або групу"

#: keystone/assignment/controllers.py:845
msgid ""
"Combining effective and group filter will always result in an empty list."
msgstr ""
"Комбінація діючого фільтру і фільтру групи завжди дає порожній перелік."

#: keystone/assignment/controllers.py:850
msgid ""
"Combining effective, domain and inherited filters will always result in an "
"empty list."
msgstr ""
"Комбінація діючого фільтру, фільтру домена й успадкованого фільтру завжди "
"дає порожній перелік."

#: keystone/assignment/controllers.py:952
msgid ""
"scope.project.id must be specified if include_subtree is also specified"
msgstr "scope.project.id необхідно вказати, якщо вказаний include_subtree"

#: keystone/assignment/core.py:77
msgid ""
"Use of the identity driver config to automatically configure the same "
"assignment driver has been deprecated, in the \"O\" release, the assignment "
"driver will need to be expicitly configured if different than the default "
"(SQL)."
msgstr ""
"Використання конфігурації драйвера ідентифікатора для автоматичного "
"налаштування такого ж драйвера привласнення застаріло. У випуску \"O\" "
"драйвер привласнення повинен буде налаштовуватися явним чином, якщо він не "
"збігається з типовим драйвером (SQL)."

#: keystone/assignment/core.py:88
#, python-format
msgid ""
"Attempted automatic driver selection for assignment based upon [identity]\\"
"driver option failed since driver %s is not found. Set [assignment]/driver "
"to a valid driver in keystone config."
msgstr ""
"Не вдалося автоматично обрати драйвер на основі опції [identity]\\driver, "
"оскільки драйвер %s не знайдено. Вкажіть потрібнийй драйвер в "
"[assignment]/driver у конфігурації keystone."

#: keystone/assignment/core.py:179
msgid "Must specify either domain or project"
msgstr "Необхідно вказати домен або проєкт"

#: keystone/assignment/core.py:848
msgid "Cannot list assignments sourced from groups and filtered by user ID."
msgstr ""
"Не вдається показати перелік привласнень, отриманих із груп та "
"відфільтрованих за ІД користувача."

#: keystone/assignment/core.py:1058
#, python-format
msgid "Project (%s)"
msgstr "Проект (%s)"

#: keystone/assignment/core.py:1060
#, python-format
msgid "Domain (%s)"
msgstr "Домен (%s)"

#: keystone/assignment/core.py:1062
msgid "Unknown Target"
msgstr "Невідоме завдання"

#: keystone/assignment/core.py:1518
msgid "Update of `domain_id` is not allowed."
msgstr "Оновлення `domain_id` не дозволено."

#: keystone/assignment/core.py:1743
msgid "Domain specific roles are not supported in the V8 role driver"
msgstr "Особливі ролі домену не підтримуються у драйвері ролей V8"

#: keystone/assignment/V8_backends/sql.py:287
#: keystone/assignment/backends/sql.py:137
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr "Неможливо вилучити роль, яка не була дозволена, %s"

#: keystone/assignment/V8_backends/sql.py:363
#: keystone/assignment/backends/sql.py:213
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr "Виявлений непередбачуваний тип призначення, %s"

#: keystone/auth/controllers.py:60
#, python-format
msgid ""
"Direct import of auth plugin %(name)r is deprecated as of Liberty in favor "
"of its entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"Прямий імпорт модулю ідентифікації %(name)r застарів в Liberty й може бути "
"вилучений у випуску N. Замість цього використовується його точка входу із "
"%(namespace)r."

#: keystone/auth/controllers.py:121
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has conflicting "
"values %(new)s and %(old)s"
msgstr ""
"Погодити атрибут ідентифікатора, %(attribute)s, неможливо, оскільки він "
"містить конфліктуючі значення %(new)s і %(old)s"

#: keystone/auth/controllers.py:182
msgid "Domain name cannot contain reserved characters."
msgstr "Доменне ім'я не може містити зарезервовані символи."

#: keystone/auth/controllers.py:205
msgid "Project name cannot contain reserved characters."
msgstr "Назва проєкту не може містити зарезервовані символи."

#: keystone/auth/controllers.py:355 keystone/middleware/auth.py:130
msgid "Scoping to both domain and project is not allowed"
msgstr "Проведення огляду для домену та проекту не допускається"

#: keystone/auth/controllers.py:358
msgid "Scoping to both domain and trust is not allowed"
msgstr "Одночасний огляд домену і довіреності заборонено"

#: keystone/auth/controllers.py:361
msgid "Scoping to both project and trust is not allowed"
msgstr "Одночасний огляд проекту і довіреності заборонено"

#: keystone/auth/controllers.py:530
msgid "User not found"
msgstr "Користувача не знайдено"

#: keystone/auth/controllers.py:644
msgid "A project-scoped token is required to produce a service catalog."
msgstr "Для створення каталогу служби необхідний маркер рівню проєкту."

#: keystone/auth/plugins/external.py:42
msgid "No authenticated user"
msgstr "Відсутній автентифікований користувач"

#: keystone/auth/plugins/external.py:52
#, python-format
msgid "Unable to lookup user %s"
msgstr "Неможливий пошук користувача %s"

#: keystone/auth/plugins/external.py:100
msgid "auth_type is not Negotiate"
msgstr "auth_type відрізняється від Negotiate"

#: keystone/auth/plugins/mapped.py:246
msgid ""
"Could not map user while setting ephemeral user identity. Either mapping "
"rules must specify user id/name or REMOTE_USER environment variable must be "
"set."
msgstr ""
"Не вдалося прив’язати користувача під час налаштування часового "
"ідентифікатора користувача. Правила прив’язки мають вказувати ім’я/ІД "
"користувача, або повинна бути задана змінна середовища REMOTE_USER."

#: keystone/auth/plugins/oauth1.py:46
msgid "Access token is expired"
msgstr "Термін дії маркера доступу скінчився"

#: keystone/auth/plugins/oauth1.py:60
msgid "Could not validate the access token"
msgstr "Не вдалося перевірити ключ доступу"

#: keystone/auth/plugins/password.py:39
msgid "Invalid username or password"
msgstr "Неправильне ім'я користувача або пароль"

#: keystone/auth/plugins/token.py:70 keystone/token/controllers.py:160
msgid "rescope a scoped token"
msgstr "Змінити область поміщеного в область ключа"

#: keystone/auth/plugins/totp.py:96
msgid "Invalid username or TOTP passcode"
msgstr "Неприпустиме ім’я користувача або пароль TOTP"

#: keystone/catalog/controllers.py:215
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr "Вказані конфліктуючі ІД регіонів: \"%(url_id)s\" != \"%(ref_id)s\""

#: keystone/catalog/core.py:149 keystone/common/ldap/core.py:1411
#, python-format
msgid "Duplicate ID, %s."
msgstr "Повторюється ID, %s."

#: keystone/catalog/backends/sql.py:389
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr "Кінцева точка %(endpoint_id)s не знайдена у проєкті %(project_id)s"

#: keystone/catalog/backends/sql.py:492
msgid "Endpoint Group Project Association not found"
msgstr "Не знайдений зв’язок проєкту групи кінцевих точок"

#: keystone/cmd/cli.py:173
msgid ""
"Either --bootstrap-password argument or OS_BOOTSTRAP_PASSWORD must be set."
msgstr ""
"Необхідно вказати аргумент --bootstrap-password або OS_BOOTSTRAP_PASSWORD."

#: keystone/cmd/cli.py:586
msgid "At least one option must be provided"
msgstr "Необхідно вказати хоча б одну опцію"

#: keystone/cmd/cli.py:593
msgid "--all option cannot be mixed with other options"
msgstr "опцію --all неможна вказувати разом з іншими опціями"

#: keystone/cmd/cli.py:600
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr "В опції --domain-name вказано невідоме ім’я домену '%(name)s'"

#: keystone/cmd/cli.py:679 keystone/tests/unit/test_cli.py:411
msgid ""
"At least one option must be provided, use either --all or --domain-name"
msgstr ""
"Має бути вказаний хоча б один параметр. Вкажіть --all або --domain-name"

#: keystone/cmd/cli.py:685 keystone/tests/unit/test_cli.py:427
msgid "The --all option cannot be used with the --domain-name option"
msgstr "Параметр --all неможна вказувати разом з параметром --domain-name"

#: keystone/cmd/cli.py:710 keystone/tests/unit/test_cli.py:444
#, python-format
msgid ""
"Invalid domain name: %(domain)s found in config file name: %(file)s - "
"ignoring this file."
msgstr ""
"Виявлено неприпустиме ім’я домену %(domain)s у файлі конфігурації %(file)s - "
"файл пропущено."

#: keystone/cmd/cli.py:718 keystone/tests/unit/test_cli.py:385
#, python-format
msgid ""
"Domain: %(domain)s already has a configuration defined - ignoring file: "
"%(file)s."
msgstr ""
"В домену %(domain)s вже визначена конфігурація - файл пропущено: %(file)s."

#: keystone/cmd/cli.py:732
#, python-format
msgid ""
"Error parsing configuration file for domain: %(domain)s, file: %(file)s."
msgstr ""
"Помилка аналізу файлу конфігурації для домену %(domain)s, файл: %(file)s."

#: keystone/cmd/cli.py:783
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr "Не вдалося знайти каталог конфігурації домену: %s"

#: keystone/cmd/cli.py:803
msgid ""
"Unable to access the keystone database, please check it is configured "
"correctly."
msgstr ""
"Неможливо отримати доступ до бази данних keystone, будь ласка перевірте чи "
"усе налаштовано правильно."

#: keystone/cmd/cli.py:866
#, python-format
msgid "Error while parsing rules %(path)s: %(err)s"
msgstr "Помилка під час розбору правила %(path)s: %(err)s"

#: keystone/cmd/cli.py:875
#, python-format
msgid "Error while opening file %(path)s: %(err)s"
msgstr "Помилка під час відкриття файлу %(path)s: %(err)s"

#: keystone/cmd/cli.py:885
#, python-format
msgid "Error while parsing line: '%(line)s': %(err)s"
msgstr "Помилка під час розбору рядка: '%(line)s': %(err)s"

#: keystone/common/authorization.py:61 keystone/common/wsgi.py:67
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr ""
"Посилання на повинне відноситися до типу KeystoneToken, а отримано %s"

#: keystone/common/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr "%s не може бути порожнім."

#: keystone/common/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr "%(property_name)s не може містити менше %(min_length)s символів."

#: keystone/common/clean.py:31
#, python-format
msgid ""
"%(property_name)s should not be greater than %(max_length)s characters."
msgstr "%(property_name)s не повинен містити більше %(max_length)s символів."

#: keystone/common/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr "%(property_name)s не є %(display_expected_type)s"

#: keystone/common/controller.py:349 keystone/common/controller.py:377
#: keystone/identity/core.py:595 keystone/resource/core.py:1145
#, python-format
msgid "Expected dict or list: %s"
msgstr "Очікування словника чи списку: %s"

#: keystone/common/controller.py:390
msgid "Marker could not be found"
msgstr "Маркер не знайдено"

#: keystone/common/controller.py:401
msgid "Invalid limit value"
msgstr "Неприпустиме значення обмеження"

#: keystone/common/controller.py:705
msgid "Cannot change Domain ID"
msgstr "Неможливо змінити ІД домену"

#: keystone/common/controller.py:751
msgid ""
"You have tried to create a resource using the admin token. As this token is "
"not within a domain you must explicitly include a domain for this resource "
"to belong to."
msgstr ""
"Спроба створення ресурсу за допомогою адміністративного маркера. Оскільки "
"цей маркер не належить домену, необхідно явно вказати домен, якому буде "
"належати ресурс."

#: keystone/common/dependency.py:65
#, python-format
msgid "Unregistered dependency: %(name)s for %(targets)s"
msgstr "Незареєстрована залежність %(name)s для %(targets)s"

#: keystone/common/driver_hints.py:38
msgid ""
"Cannot truncate a driver call without hints list as first parameter after "
"self "
msgstr ""
"Неможливо відсікти виклик драйвера без переліку підказок у якості першого "
"параметру після самого себе "

#: keystone/common/json_home.py:76
#, python-format
msgid "Unexpected status requested for JSON Home response, %s"
msgstr "Запитано несподіваний стан для відповіді JSON Home, %s"

#: keystone/common/manager.py:82
#, python-format
msgid ""
"Direct import of driver %(name)r is deprecated as of Liberty in favor of its "
"entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"Прямий імпорт драйвера %(name)r застарів в Liberty й може бути вилучений у "
"випуску N. Замість цього використовується його точка входу із %(namespace)r."

#: keystone/common/tokenless_auth.py:73
msgid "Neither Project Domain ID nor Project Domain Name was provided."
msgstr "Не вказані ні ІД домену проєкту, ні ім’я домену проєкту."

#: keystone/common/tokenless_auth.py:165
msgid ""
"User auth cannot be built due to missing either user id, or user name with "
"domain id, or user name with domain name."
msgstr ""
"Не вдалося скомпонувати ідентифікацію користувача, оскільки відсутній ІД "
"користувача, ім’я користувача з ІД домену або ім’я користувача з іменем "
"домену."

#: keystone/common/utils.py:63
msgid ""
"Length of transformable resource id > 64, which is max allowed characters"
msgstr ""
"Довжина ІД перетворюваного ресурсу > 64 символів, тобто перевищує "
"максимально припустиму"

#: keystone/common/utils.py:192 keystone/credential/controllers.py:44
msgid "Invalid blob in credential"
msgstr "Неприпустимий великий двійковий об’єкт у дозволі"

#: keystone/common/wsgi.py:208
msgid "Query string is not UTF-8 encoded"
msgstr "Рядок запиту вказаний у кодуванні, що відрізняється від UTF-8"

#: keystone/common/wsgi.py:341
#, python-format
msgid "%s field is required and cannot be empty"
msgstr "Поле %s є обов’язковим й не може бути порожнім"

#: keystone/common/wsgi.py:353
#, python-format
msgid "%s field(s) cannot be empty"
msgstr "Поле %s не може бути порожнім"

#: keystone/common/wsgi.py:548
msgid "The resource could not be found."
msgstr "Ресурси не можуть бути знайдені."

#: keystone/common/kvs/core.py:88
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr "Час натискання перевищено для клавіші, %(target)s"

#: keystone/common/kvs/core.py:123
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr "Регіон KVS %s вже налаштований. Змінювання конфігурації неможливе."

#: keystone/common/kvs/core.py:166
#, python-format
msgid "Key Value Store not configured: %s"
msgstr "Сховище значень ключів не налаштовано: %s"

#: keystone/common/kvs/core.py:219
msgid "`key_mangler` option must be a function reference"
msgstr "Опція `key_mangler` має бути посиланням на функцію"

#: keystone/common/kvs/core.py:376
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr "Блокування має відповідати цільовому ключу: %(lock)s != %(target)s"

#: keystone/common/kvs/core.py:380
msgid "Must be called within an active lock context."
msgstr "Потрібен виклик у контексті активного блокування."

#: keystone/common/kvs/backends/memcached.py:68
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr "Виконано максимальне число спроб блокування в %s."

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(backend)s` is not a valid memcached backend. Valid backends: "
"%(backend_list)s"
msgstr ""
"Базова система `%(backend)s` не є припустимою базовою системою у кеші "
"пам’яті. Припустимі базові системи: %(backend_list)s"

#: keystone/common/kvs/backends/memcached.py:185
msgid "`key_mangler` functions must be callable."
msgstr "Функції `key_mangler` повинні бути доступні для виклику."

#: keystone/common/ldap/core.py:199
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""
"Неприпустима опція deref LDAP: %(option)s. Виберіть одне з наступних "
"значень: %(options)s"

#: keystone/common/ldap/core.py:209
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""
"Неприпустима опція certs TLS LDAP: %(option)s. Виберіть одне з наступних "
"значень: %(options)s"

#: keystone/common/ldap/core.py:221
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""
"Неприпустима область LDAP: %(scope)s. Виберіть одне з наступних значень: "
"%(options)s"

#: keystone/common/ldap/core.py:591
msgid "Invalid TLS / LDAPS combination"
msgstr "Невірна TLS / LDAPS комбінація"

#: keystone/common/ldap/core.py:596
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr "Неприпустима опція TLS_AVAIL LDAP: %s. TLS недоступний"

#: keystone/common/ldap/core.py:606
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr "tls_cacertfile %s не знайдено або не є файлом"

#: keystone/common/ldap/core.py:618
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr "tls_cacertdir %s не знайдена або не є директорією"

#: keystone/common/ldap/core.py:1333
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr "Атрибут ІД %(id_attr)s не знайдений в об’єкті LDAP %(dn)s"

#: keystone/common/ldap/core.py:1378
#, python-format
msgid "LDAP %s create"
msgstr "Створити в LDAP %s"

#: keystone/common/ldap/core.py:1383
#, python-format
msgid "LDAP %s update"
msgstr "Оновити %s в LDAP"

#: keystone/common/ldap/core.py:1388
#, python-format
msgid "LDAP %s delete"
msgstr "Вилучити %s в LDAP"

#: keystone/common/ldap/core.py:1400
#, python-format
msgid "Duplicate name, %s."
msgstr "Повторюється назва, %s."

#: keystone/common/ldap/core.py:1557
msgid ""
"Disabling an entity where the 'enable' attribute is ignored by configuration."
msgstr ""
"Відмикання сутності, при якому атрибут 'enable' у конфігурації нехтується."

#: keystone/common/ldap/core.py:1568
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr "Неможливо змінити %(option_name)s %(attr)s"

#: keystone/common/ldap/core.py:1655
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr "Елемент %(member)s вже є участником групи %(group)s"

#: keystone/common/sql/core.py:413
msgid "Duplicate Entry"
msgstr "Дублікат запису"

#: keystone/common/sql/core.py:429
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr "При спробі зберегти %s сталася непередбачена помилка"

#: keystone/common/sql/migration_helpers.py:167
msgid "Unable to downgrade schema"
msgstr "Не вдається понизити версію схеми"

#: keystone/common/sql/migration_helpers.py:185
#: keystone/common/sql/migration_helpers.py:231
#, python-format
msgid "%s extension does not exist."
msgstr "%s розширення не існує."

#: keystone/common/validation/__init__.py:44
#, python-format
msgid ""
"validated expected to find %(param_name)r in function signature for "
"%(func_name)r."
msgstr ""
"очікувалося знайти перевірений параметр %(param_name)r у підпису функції "
"%(func_name)r."

#: keystone/common/validation/validators.py:53
#, python-format
msgid "Invalid input for field '%(path)s': %(message)s"
msgstr "Неприпустиме введення для поля '%(path)s': %(message)s"

#: keystone/contrib/admin_crud/core.py:28
msgid ""
"Remove admin_crud_extension from the paste pipeline, the admin_crud "
"extension is now always available. Updatethe [pipeline:admin_api] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Вилучіть admin_crud_extension із конвеєра вставки, розширення admin_crud "
"тепер доступне завжди. Оновіть розділ [pipeline:admin_api] у файлі keystone-"
"paste.ini відповідно, оскільки він буде вилучений у випуску O."

#: keystone/contrib/ec2/controllers.py:80 keystone/contrib/s3/core.py:111
#: keystone/contrib/s3/core.py:114
msgid "Invalid EC2 signature."
msgstr "Невірний підпис EC2."

#: keystone/contrib/ec2/controllers.py:83
#: keystone/contrib/ec2/controllers.py:87
#: keystone/contrib/ec2/controllers.py:125
msgid "EC2 signature not supplied."
msgstr "Ненаданий підпис EC2."

#: keystone/contrib/ec2/controllers.py:159
msgid "User not valid for tenant."
msgstr "Неприпустимий користувач для арендатора."

#: keystone/contrib/ec2/controllers.py:260
msgid "EC2 access key not found."
msgstr "EC2 не знайдено ключ доступу."

#: keystone/contrib/ec2/controllers.py:326
msgid "Token belongs to another user"
msgstr "Маркер привласнений іншому користувачу"

#: keystone/contrib/ec2/controllers.py:354
msgid "Credential belongs to another user"
msgstr "Дозвіл належить іншому користувачу"

#: keystone/contrib/endpoint_filter/routers.py:29
msgid ""
"Remove endpoint_filter_extension from the paste pipeline, the endpoint "
"filter extension is now always available. Update the [pipeline:api_v3] "
"section in keystone-paste.ini accordingly as it will be removed in the O "
"release."
msgstr ""
"Вилучіть endpoint_filter_extension із конвеєра вставки, розширення фільтру "
"кінцевої точки тепер доступне завжди. Оновіть розділ [pipeline:api_v3] у "
"файлі keystone-paste.ini відповідно, оскільки він буде вилучений у випуску O."

#: keystone/contrib/federation/routers.py:27
msgid ""
"Remove federation_extension from the paste pipeline, the federation "
"extension is now always available. Update the [pipeline:api_v3] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Вилучіть federation_filter_extension із конвеєра вставки, розширення "
"об’єднання тепер доступне завжди. Оновіть розділ [pipeline:api_v3] у файлі "
"keystone-paste.ini відповідно, оскільки він буде вилучений у випуску O."

#: keystone/contrib/oauth1/routers.py:29
msgid ""
"Remove oauth1_extension from the paste pipeline, the oauth1 extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Вилучіть oauth1_filter_extension із конвеєра вставки, розширення oauth1 "
"тепер доступне завжди. Оновіть розділ [pipeline:api_v3] у файлі keystone-"
"paste.ini відповідно, оскільки він буде вилучений у випуску O."

#: keystone/contrib/revoke/routers.py:27
msgid ""
"Remove revoke_extension from the paste pipeline, the revoke extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Вилучіть revoke_filter_extension із конвеєра вставки, розширення відклику "
"тепер доступне завжди. Оновіть розділ [pipeline:api_v3] у файлі keystone-"
"paste.ini відповідно, оскільки він буде вилучений у випуску O."

#: keystone/contrib/s3/core.py:82
msgid "Credential signature mismatch"
msgstr "Незбіг підпису ідентифікаційних даних"

#: keystone/contrib/simple_cert/routers.py:27
msgid ""
"Remove simple_cert from the paste pipeline, the PKI and PKIz token providers "
"are now deprecated and simple_cert was only used insupport of these token "
"providers. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Вилучіть simple_cert із конвеєра вставки, тепер постачальники ключів PKI і "
"PKIz застаріли, а simple_cert використовувався лише для підтримки цих "
"постачальників. Оновіть розділ [pipeline:api_v3] у файлі keystone-paste.ini "
"відповідно, оскільки він буде вилучений у випуску O."

#: keystone/contrib/user_crud/core.py:28
msgid ""
"Remove user_crud_extension from the paste pipeline, the user_crud extension "
"is now always available. Updatethe [pipeline:public_api] section in keystone-"
"paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Вилучіть user_crud_extension із конвеєра вставки, розширення user_crud тепер "
"доступне завжди. Оновіть розділ [pipeline:public_api] у файлі keystone-"
"paste.ini відповідно, оскільки він буде вилучений у випуску O."

#: keystone/endpoint_policy/core.py:264
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr "З кінцевою точкою %(endpoint_id)s не пов’язано жодної стратегії."

#: keystone/federation/controllers.py:269
msgid "Request must have an origin query parameter"
msgstr "Запит повинен містити параметр origin"

#: keystone/federation/controllers.py:278
#, python-format
msgid "%(host)s is not a trusted dashboard host"
msgstr "%(host)s не є надійним хостом звідних панелей"

#: keystone/federation/controllers.py:309
msgid "Missing entity ID from environment"
msgstr "У середовищі відсутні ІД сутності"

#: keystone/federation/controllers.py:357
msgid "Use a project scoped token when attempting to create a SAML assertion"
msgstr ""
"Використовувати локальний ключ проєкту при створенні ствердження SAML"

#: keystone/federation/idp.py:486
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr "Не вдалося відкрити сертифікат %(cert_file)s. Причина: %(reason)s"

#: keystone/federation/idp.py:552
msgid "Ensure configuration option idp_entity_id is set."
msgstr "Переконайтеся, що вказано параметр конфігурації idp_entity_id."

#: keystone/federation/idp.py:555
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr "Переконайтеся, що вказано параметр конфігурації idp_sso_endpoint."

#: keystone/federation/idp.py:574
msgid ""
"idp_contact_type must be one of: [technical, other, support, administrative "
"or billing."
msgstr ""
"Значення idp_contact_type має бути одним з наступних: technical, other, "
"support, administrative або billing."

#: keystone/federation/utils.py:234
msgid "Federation token is expired"
msgstr "Термін дії ключа об’єднання вийшов"

#: keystone/federation/utils.py:286
msgid "Could not find Identity Provider identifier in environment"
msgstr ""
"Не вдалося знайти ідентифікатор постачальника ідентифікаторів у середовищі"

#: keystone/federation/utils.py:290
msgid ""
"Incoming identity provider identifier not included among the accepted "
"identifiers."
msgstr ""
"Вхідний ідентифікатор постачальника ідентифікаторів не включений у "
"принйнятні ідентифікатори."

#: keystone/federation/utils.py:585
#, python-format
msgid "User type %s not supported"
msgstr "Тип користувача %s не підтримується"

#: keystone/federation/utils.py:605
msgid ""
"Could not map any federated user properties to identity values. Check debug "
"logs or the mapping used for additional details."
msgstr ""
"Не вдається пов’язати об’єднані ціхи користувача з ідентифікаторами. "
"Додаткові відомости про пов’язування наведено у протоколі зневадження."

#: keystone/federation/utils.py:629
#, python-format
msgid ""
"Invalid rule: %(identity_value)s. Both 'groups' and 'domain' keywords must "
"be specified."
msgstr ""
"Неприпустиме правило: %(identity_value)s. Ключові слова 'groups' і 'domain' "
"мають бути вказані."

#: keystone/federation/utils.py:854
#, python-format
msgid "Identity Provider %(idp)s is disabled"
msgstr "Постачальник ідентифікаторів %(idp)s вимкнений"

#: keystone/federation/utils.py:862
#, python-format
msgid "Service Provider %(sp)s is disabled"
msgstr "Постачальник служби %(sp)s вимкнений"

#: keystone/federation/backends/sql.py:182
#, python-format
msgid "Duplicate remote ID: %s"
msgstr "Дублікат віддаленого ID: %s"

#: keystone/federation/backends/sql.py:184
#, python-format
msgid "Duplicate entry: %s"
msgstr "Дублікат запису: %s"

#: keystone/identity/controllers.py:74
msgid "Enabled field must be a boolean"
msgstr "Активне поле має бути булевським значенням"

#: keystone/identity/controllers.py:103
msgid "Enabled field should be a boolean"
msgstr "Активне поле має бути булевським значенням"

#: keystone/identity/core.py:265
#, python-format
msgid "Config API entity at /domains/%s/config"
msgstr "Налаштувати елемент API в /domains/%s/config"

#: keystone/identity/core.py:271
#, python-format
msgid ""
"Exceeded attempts to register domain %(domain)s to use the SQL driver, the "
"last domain that appears to have had it is %(last_domain)s, giving up"
msgstr ""
"Перевищено число спроб реєстрації домену %(domain)s для використання "
"драйвера SQL. Останній домен, для якого це було зроблено - %(last_domain)s. "
"Більше спроб не буде"

#: keystone/identity/core.py:450 keystone/identity/backends/ldap.py:62
#: keystone/identity/backends/ldap.py:64 keystone/identity/backends/ldap.py:70
#: keystone/identity/backends/ldap.py:72 keystone/identity/backends/sql.py:210
#: keystone/identity/backends/sql.py:212
msgid "Invalid user / password"
msgstr "Неприпустимий користувач / пароль"

#: keystone/identity/core.py:895
#, python-format
msgid "User is disabled: %s"
msgstr "Користувач відімкнений: %s"

#: keystone/identity/core.py:928 keystone/resource/core.py:375
msgid ""
"update of domain_id is deprecated as of Mitaka and will be removed in O."
msgstr "оновлення domain_id застаріло в Mitaka й буде вилучено в O."

#: keystone/identity/core.py:947
msgid "Cannot change user ID"
msgstr "Неможливо змінити ІД користувача"

#: keystone/identity/backends/ldap.py:35
#, python-format
msgid ""
"%s for the LDAP identity backend has been deprecated in the Mitaka release "
"in favor of read-only identity LDAP access. It will be removed in the \"O\" "
"release."
msgstr ""
"%s для системи ідентифікації LDAP застаріло Mitaka, замість нього "
"використовується ідентифікація LDAP з доступом лише для читання. Ця функція "
"буде вилучена у випуску \"O\"."

#: keystone/identity/backends/ldap.py:106
msgid "Cannot change user name"
msgstr "Неможливо змінити ім’я користувача"

#: keystone/identity/backends/ldap.py:214 keystone/identity/backends/sql.py:292
#: keystone/identity/backends/sql.py:310
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr "Користувач '%(user_id)s' не знайдений у групі '%(group_id)s'"

#: keystone/identity/backends/ldap.py:366
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr "Користувач %(user_id)s вже є членом групи %(group_id)s"

#: keystone/models/token_model.py:62
msgid "Found invalid token: scoped to both project and domain."
msgstr ""
"Виявлено неприпустимий маркер: він відноситься й до рівню проєкту, й до "
"рівню домену."

#: keystone/oauth1/controllers.py:126
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""
"Показати перелік маркерів запитів з маркером, виданим за допомогою "
"делегування, неможливо."

#: keystone/oauth1/controllers.py:187 keystone/oauth1/backends/sql.py:256
msgid "User IDs do not match"
msgstr "Ідентифікатори користувача не збігаються"

#: keystone/oauth1/controllers.py:243
msgid "Invalid signature"
msgstr "Нечинний підпис"

#: keystone/oauth1/controllers.py:294 keystone/oauth1/controllers.py:372
msgid "Request token is expired"
msgstr "Термін дії маркера запиту вийшов"

#: keystone/oauth1/controllers.py:308
msgid "There should not be any non-oauth parameters"
msgstr "Не допускаються параметри, що відрізняються від oauth"

#: keystone/oauth1/controllers.py:312
msgid "provided consumer key does not match stored consumer key"
msgstr "переданий ключ приймача не збігається із збереженим"

#: keystone/oauth1/controllers.py:316
msgid "provided verifier does not match stored verifier"
msgstr "передана функція перевірки не збігається із збереженою"

#: keystone/oauth1/controllers.py:320
msgid "provided request key does not match stored request key"
msgstr "переданий ключ запиту не збігається із збереженим"

#: keystone/oauth1/controllers.py:324
msgid "Request Token does not have an authorizing user id"
msgstr "Маркер запиту не містить ІД користувача для надання прав доступу"

#: keystone/oauth1/controllers.py:361
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""
"Надати права доступу маркеру запиту з маркером, виданим за допомогою "
"делегування, неможливо."

#: keystone/oauth1/controllers.py:388
msgid "authorizing user does not have role required"
msgstr "користувачу, що надає права доступу, не привласнена потрібна роль"

#: keystone/oauth1/controllers.py:401
msgid "User is not a member of the requested project"
msgstr "Користувач не є членом викликаного проекту"

#: keystone/oauth1/backends/sql.py:91
msgid "Consumer not found"
msgstr "Споживач не знайдений"

#: keystone/oauth1/backends/sql.py:177
msgid "Request token not found"
msgstr "Ключ запиту не знайдено"

#: keystone/oauth1/backends/sql.py:237
msgid "Access token not found"
msgstr "Маркер доступу не знайдено"

#: keystone/resource/controllers.py:94
msgid "The creation of projects acting as domains is not allowed in v2."
msgstr "Створення проєктів, що працюють у якости доменів, не дозволено в v2."

#: keystone/resource/controllers.py:284
msgid ""
"Cannot use parents_as_list and parents_as_ids query params at the same time."
msgstr ""
"Неможна використовувати параметри запиту parents_as_list і parents_as_ids "
"одночасно."

#: keystone/resource/controllers.py:290
msgid ""
"Cannot use subtree_as_list and subtree_as_ids query params at the same time."
msgstr ""
"Неможна використовувати параметри запиту subtree_as_list і subtree_as_ids "
"одночасно."

#: keystone/resource/core.py:106
#, python-format
msgid "Max hierarchy depth reached for %s branch."
msgstr "Для гілки %s досягнута максимальна глибина ієрархії."

#: keystone/resource/core.py:123
msgid "Multiple domains are not supported"
msgstr "Множинні домени не підтримуються"

#: keystone/resource/core.py:129
msgid "only root projects are allowed to act as domains."
msgstr "лише root проєктам дозволяється діяти як доменам."

#: keystone/resource/core.py:152
#, python-format
msgid ""
"Cannot create project, since its parent (%(domain_id)s) is acting as a "
"domain, but project's specified parent_id (%(parent_id)s) does not match "
"this domain_id."
msgstr ""
"Не вдається створити проєкт, оскільки його батьківський елемент "
"(%(domain_id)s) працює у якости домену, але parent_id (%(parent_id)s), "
"вказаний для проєкту, не відповідає даному domain_id."

#: keystone/resource/core.py:163
#, python-format
msgid ""
"Cannot create project, since it specifies its owner as domain %(domain_id)s, "
"but specifies a parent in a different domain (%(parent_domain_id)s)."
msgstr ""
"Не вдається створити проєкт, оскільки його власник вказаний як домен "
"%(domain_id)s, але його батьківський об’єкт заданий у іншому домені "
"(%(parent_domain_id)s)."

#: keystone/resource/core.py:183
#, python-format
msgid "cannot create a project in a branch containing a disabled project: %s"
msgstr "Неможна створити проєкт у гілці, що містить відімкнений проєкт: %s"

#: keystone/resource/core.py:191
#, python-format
msgid ""
"%(entity)s name cannot contain the following reserved characters: %(chars)s"
msgstr ""
"Ім’я %(entity)s не може містити наступні зарезервовані символи: %(chars)s"

#: keystone/resource/core.py:201
#, python-format
msgid ""
"it is not permitted to have two projects acting as domains with the same "
"name: %s"
msgstr ""
"Не дозволено використовувати два проєкти у якости доменів з однаковим "
"іменем: %s"

#: keystone/resource/core.py:205
#, python-format
msgid ""
"it is not permitted to have two projects with the same name in the same "
"domain : %s"
msgstr ""
"не дозволяється мати два проекти з однаковим ім'ям в одному домені : %s"

#: keystone/resource/core.py:262
#, python-format
msgid "Domain is disabled: %s"
msgstr "Домен відімкнуто:: %s"

#: keystone/resource/core.py:279
#, python-format
msgid "Domain cannot be named %s"
msgstr "Домену неможна привласнити ім’я %s"

#: keystone/resource/core.py:282
#, python-format
msgid "Domain cannot have ID %s"
msgstr "Домен не може мати ідентифікатор %s"

#: keystone/resource/core.py:297
#, python-format
msgid "Project is disabled: %s"
msgstr "Проект вимкнуто: %s"

#: keystone/resource/core.py:304
#, python-format
msgid "Cannot enable project %s since it has disabled parents"
msgstr ""
"Не вдається увімкнути проєкт %s, оскільки в нього відімкнені батьківські "
"об’єкти"

#: keystone/resource/core.py:340
msgid "Update of `parent_id` is not allowed."
msgstr "Оновлення `parent_id` не дозволено."

#: keystone/resource/core.py:345
msgid "Update of `is_domain` is not allowed."
msgstr "Оновлення `is_domain` не дозволено."

#: keystone/resource/core.py:359
msgid "Update of domain_id of projects acting as domains is not allowed."
msgstr ""
"Не дозволено оновлювати domain_id для проєктів, що працюють у якости доменів."

#: keystone/resource/core.py:366
msgid "Update of domain_id is only allowed for root projects."
msgstr "Оновлення domain_id дозволено лише для кореневих проєктів."

#: keystone/resource/core.py:371
msgid "Cannot update domain_id of a project that has children."
msgstr ""
"Не дозволено оновлювати domain_id для проєкту, в якого є дочірні об’єкти."

#: keystone/resource/core.py:396
#, python-format
msgid ""
"Cannot disable project %(project_id)s since its subtree contains enabled "
"projects."
msgstr ""
"Неможна відімкнути проєкт %(project_id)s, оскільки його піддерево містить "
"увімкнені проєкти."

#: keystone/resource/core.py:443
msgid "Cascade update is only allowed for enabled attribute."
msgstr "Каскадне оновлення дозволено лише для увімкнених атрибутів."

#: keystone/resource/core.py:507
#, python-format
msgid ""
"cannot delete an enabled project acting as a domain. Please disable the "
"project %s first."
msgstr ""
"не можна вилучити увімнений проєкт, діючий як домен. Будь ласка, спочатку "
"вимкніть %s проєкт."

#: keystone/resource/core.py:513
#, python-format
msgid ""
"Cannot delete the project %s since it is not a leaf in the hierarchy. Use "
"the cascade option if you want to delete a whole subtree."
msgstr ""
"Неможливо вилучити проєкт %s, оскільки він не є кінцевим об’єктом у "
"структурі. Використовуйте каскадну опцію для вилучення усього піддерева."

#: keystone/resource/core.py:526
#, python-format
msgid ""
"Cannot delete project %(project_id)s since its subtree contains enabled "
"projects."
msgstr ""
"Неможливо вилучити проєкт %(project_id)s, оскільки його піддерево містить "
"увімкнені проєкти."

#: keystone/resource/core.py:554
msgid "Project field is required and cannot be empty."
msgstr "Поле проєкту є обов’язковим й не може бути порожнім."

#: keystone/resource/core.py:795
msgid "Cannot delete a domain that is enabled, please disable it first."
msgstr "Неможливо вилучити увімкнений домен, спочатку вимкніть його."

#: keystone/resource/core.py:1570
msgid "No options specified"
msgstr "Параметри не вказані"

#: keystone/resource/core.py:1576
#, python-format
msgid ""
"The value of group %(group)s specified in the config should be a dictionary "
"of options"
msgstr ""
"Значення групи %(group)s, вказане у конфігурації, має бути словарем "
"параметрів"

#: keystone/resource/core.py:1600
#, python-format
msgid ""
"Option %(option)s found with no group specified while checking domain "
"configuration request"
msgstr ""
"Виявлено параметр %(option)s без вказаної групи під час перевірки запиту на "
"налаштування домену"

#: keystone/resource/core.py:1607
#, python-format
msgid "Group %(group)s is not supported for domain specific configurations"
msgstr "Група %(group)s не підтримується для певних конфігурацій домену"

#: keystone/resource/core.py:1614
#, python-format
msgid ""
"Option %(option)s in group %(group)s is not supported for domain specific "
"configurations"
msgstr ""
"Параметр %(option)s у групі %(group)s не підтримується для певних "
"конфігурацій домену"

#: keystone/resource/core.py:1666
msgid "An unexpected error occurred when retrieving domain configs"
msgstr "Виникла непередбачена помилка при отриманні конфігурацій доменів"

#: keystone/resource/core.py:1745 keystone/resource/core.py:1828
#: keystone/resource/core.py:1898 keystone/resource/config_backends/sql.py:76
#, python-format
msgid "option %(option)s in group %(group)s"
msgstr "параметр %(option)s у групі %(group)s"

#: keystone/resource/core.py:1748 keystone/resource/core.py:1833
#: keystone/resource/core.py:1894
#, python-format
msgid "group %(group)s"
msgstr "група %(group)s"

#: keystone/resource/core.py:1750
msgid "any options"
msgstr "будь-які параметри"

#: keystone/resource/core.py:1793
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, so that, and only "
"that, option must be specified  in the config"
msgstr ""
"Зміна параметру %(option)s у групі %(group)s, щоб параметр повинен був "
"вказуватися лише у конфігурації"

#: keystone/resource/core.py:1798
#, python-format
msgid ""
"Trying to update group %(group)s, so that, and only that, group must be "
"specified in the config"
msgstr ""
"Зміна групи %(group)s, щоб група повинна була вказуватися лише у конфігурації"

#: keystone/resource/core.py:1807
#, python-format
msgid ""
"request to update group %(group)s, but config provided contains group "
"%(group_other)s instead"
msgstr ""
"запит на зміну групи %(group)s, однак передана конфігурація містить групу "
"%(group_other)s замість неї"

#: keystone/resource/core.py:1814
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, but config provided "
"contains option %(option_other)s instead"
msgstr ""
"Зміна параметру %(option)s у групі %(group)s, однак передана конфігурація "
"містить параметр %(option_other)s замість нього"

#: keystone/resource/core.py:2006
#, python-format
msgid "Group  %s not found in config"
msgstr "Група %s не знайдена у конфігурації"

#: keystone/resource/core.py:2016
#, python-format
msgid ""
"Reading the default for option %(option)s in group %(group)s is not supported"
msgstr ""
"Читання типового значення для параметру %(option)s у групі %(group)s не "
"підтримується"

#: keystone/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr "неправильний формат дати %s"

#: keystone/revoke/core.py:156
msgid ""
"The revoke call must not have both domain_id and project_id. This is a bug "
"in the Keystone server. The current request is aborted."
msgstr ""
"У виклику revoke мають бути вказані domain_id і project_id. Це помилка у "
"коді сервера Keystone. Поточний запит переваний."

#: keystone/revoke/core.py:226 keystone/token/provider.py:217
#: keystone/token/provider.py:256 keystone/token/provider.py:336
#: keystone/token/provider.py:343
msgid "Failed to validate token"
msgstr "Помилка перевірки маркера"

#: keystone/token/controllers.py:372
msgid "Tenant name cannot contain reserved characters."
msgstr "Ім’я арендатора не може містити зарезервовані символи."

#: keystone/token/controllers.py:392
#, python-format
msgid "Project ID not found: %(t_id)s"
msgstr "ID проєкту не знайдений: %(t_id)s"

#: keystone/token/controllers.py:396
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr "В користувача %(u_id)s немає доступу до арендатора %(t_id)s"

#: keystone/token/controllers.py:415 keystone/token/controllers.py:418
msgid "Token does not belong to specified tenant."
msgstr "Маркер не належить вказаному тимчасовому власнику."

#: keystone/token/provider.py:269 keystone/token/provider.py:293
msgid "No token in the request"
msgstr "Немає маркера у запиті"

#: keystone/token/persistence/backends/kvs.py:132
#, python-format
msgid "Unknown token version %s"
msgstr "Невідома версія маркера %s"

#: keystone/token/providers/common.py:313
#: keystone/token/providers/common.py:445
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""
"Користувач %(user_id)s не має дозволу доступу до проекту %(project_id)s"

#: keystone/token/providers/common.py:318
#: keystone/token/providers/common.py:450
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""
"Користувач %(user_id)s не має дозволу доступу до домену %(domain_id)s"

#: keystone/token/providers/common.py:345
msgid "Trustor is disabled."
msgstr "Довірювач відімкнений."

#: keystone/token/providers/common.py:434
msgid "Trustee has no delegated roles."
msgstr "В довіреної особи немає делегованих ролей."

#: keystone/token/providers/common.py:496
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr "Неприпустимий тип даних у інформації контролю: %(data)s (%(type)s)"

#: keystone/token/providers/common.py:560
#: keystone/token/providers/common.py:587
msgid "The configured token provider does not support bind authentication."
msgstr "Налаштований постачальник маркера не підтримує автентифікацію bind."

#: keystone/token/providers/common.py:598
msgid "User is not a trustee."
msgstr "Користувач не є довіреною особою."

#: keystone/token/providers/common.py:665
msgid ""
"Attempting to use OS-FEDERATION token with V2 Identity Service, use V3 "
"Authentication"
msgstr ""
"Спроба використовувати маркер OS-FEDERATION із службою ідентифікації версії "
"2. Слід використовувати ідентифікацію версії 3"

#: keystone/token/providers/common.py:675
msgid "Non-default domain is not supported"
msgstr ""
"Домен, який відрізняється від застосовуваного типово, не підтримується"

#: keystone/token/providers/common.py:679
msgid "Domain scoped token is not supported"
msgstr "Маркер, область якого - домен, не підтримується"

#: keystone/token/providers/pki.py:53 keystone/token/providers/pkiz.py:31
msgid "Unable to sign token."
msgstr "Підписати маркер неможливо."

#: keystone/token/providers/fernet/token_formatters.py:102
#, python-format
msgid "This is not a recognized Fernet token %s"
msgstr "Це не маркер Fernet: %s"

#: keystone/token/providers/fernet/token_formatters.py:198
#, python-format
msgid "This is not a recognized Fernet payload version: %s"
msgstr "Це нерозпізнана версія корисного навантаження Fernet: %s"

#: keystone/trust/controllers.py:107
#, python-format
msgid "role %s is not defined"
msgstr "роль %s не визначена"

#: keystone/trust/controllers.py:131
msgid "Redelegation allowed for delegated by trust only"
msgstr "Зміна делегування дозволена лише для довіреного користувача"

#: keystone/trust/controllers.py:164
msgid "The authenticated user should match the trustor."
msgstr "Ідентифікований користувач має відповідати довірювачу."

#: keystone/trust/controllers.py:169
msgid "At least one role should be specified."
msgstr "Необхідно вказати принаймні одну роль."

#: keystone/trust/core.py:58
#, python-format
msgid ""
"Remaining redelegation depth of %(redelegation_depth)d out of allowed range "
"of [0..%(max_count)d]"
msgstr ""
"Решта глибини зміни делегування %(redelegation_depth)d виходить за межі "
"дозволеного діяпазону [0..%(max_count)d]"

#: keystone/trust/core.py:67
#, python-format
msgid ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"
msgstr ""
"Полю \"remaining_uses\" привласнено значення %(value)s, хоча поле не може "
"бути задано для зміни делегування групи довір’я"

#: keystone/trust/core.py:78
msgid "Requested expiration time is more than redelegated trust can provide"
msgstr ""
"Запитаний час закінчення терміну дії перевищує значення, яке може вказати "
"довірений користувач"

#: keystone/trust/core.py:88
msgid "Some of requested roles are not in redelegated trust"
msgstr ""
"Деякі із запитаних ролей не відносяться до довіреного користувача зі "
"зміненими повноваженнями"

#: keystone/trust/core.py:112
msgid "One of the trust agents is disabled or deleted"
msgstr "Один з довірених агентів відімкнений або вилучений"

#: keystone/trust/core.py:131
msgid "remaining_uses must be a positive integer or null."
msgstr ""
"Значення remaining_uses має бути додатнім цілим числом або рівним нулю."

#: keystone/trust/core.py:137
#, python-format
msgid ""
"Requested redelegation depth of %(requested_count)d is greater than allowed "
"%(max_count)d"
msgstr ""
"Запитана глибина зміни делегування %(requested_count)d перевищує дозволену "
"%(max_count)d"

#: keystone/trust/core.py:144
msgid "remaining_uses must not be set if redelegation is allowed"
msgstr ""
"Якщо увімкнено зміну делегування, параметр remaining_uses не повинен бути "
"вказаний"

#: keystone/trust/core.py:154
msgid ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting "
"this parameter is advised."
msgstr ""
"Зміна параметру \"redelegation_count\" під час зміни делегування заборонено. "
"Можливий пропуск цього параметру."
