# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: glance VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-19 06:56+0000\n"
"PO-Revision-Date: 2017-01-06 15:45+0000\n"
"Last-Translator: Eugene Roskin <Unknown>\n"
"Language-Team: Russian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-03-11 06:44+0000\n"
"X-Generator: Launchpad (build 2e4955e3d556e61e2eb54acf7a827d17e9e46822)\n"
"Language: ru\n"
"Generated-By: Babel 2.0\n"

#: glance/location.py:101
msgid "Invalid location"
msgstr "Недопустимое расположение"

#: glance/location.py:333
msgid "Invalid locations"
msgstr "Недопустимые расположения"

#: glance/store/__init__.py:667
#, python-format
msgid "Original locations is not empty: %s"
msgstr "Исходные расположения не пусты: %s"

#: glance/location.py:440
msgid "Signature verification failed"
msgstr "Проверка подписи не выполнена."

#: glance/store/__init__.py:739
#, python-format
msgid "Get image %(id)s data failed: %(err)s."
msgstr "Получить данные для образа %(id)s не удалось: %(err)s."

#: glance/notifier.py:239 glance/api/v1/upload_utils.py:184
#: glance/api/v2/image_data.py:107
#, python-format
msgid "Image storage media is full: %s"
msgstr "Носитель образов переполнен: %s"

#: glance/notifier.py:243 glance/api/v1/upload_utils.py:193
#: glance/api/v2/image_data.py:128
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr "Недостаточные права для доступа к носителю образов: %s"

#: glance/notifier.py:248
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr "Не удается сохранить данные для образа %(image_id)s: %(error)s"

#: glance/notifier.py:254
#, python-format
msgid ""
"Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""
"Не удается загрузить данные для дубликата образа %(image_id)s: %(error)s"

#: glance/notifier.py:261
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr "Загружать данные для образа %(image_id)s не разрешено: %(error)s"

#: glance/notifier.py:267
#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have been "
"deleted during the upload: %(error)s"
msgstr ""
"Образ %(image_id)s не найден после загрузки. Возможно, он удален во время "
"загрузки: %(error)s"

#: glance/notifier.py:274
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""
"Загрузить данные образа %(image_id)s не удалось из-за ошибки HTTP: %(error)s"

#: glance/notifier.py:281
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error: "
"%(error)s"
msgstr ""
"Загрузить данные образа %(image_id)s не удалось из-за внутренней ошибки: "
"%(error)s"

#: glance/schema.py:58
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr "настраиваемые свойства (%(props)s) конфликтуют с базовыми свойствами"

#: glance/scrubber.py:42 glance/store/__init__.py:58
msgid "The amount of time in seconds to delay before performing a delete."
msgstr "Время задержки перед выполнением удаления, в секундах."

#: glance/scrubber.py:40
msgid ""
"The size of thread pool to be used for scrubbing images. The default is one, "
"which signifies serial scrubbing. Any value above one indicates the max "
"number of images that may be scrubbed in parallel."
msgstr ""
"Размер пула нитей для очистки образов. Значение по умолчанию: один, что "
"означает последовательную очистку. Любое значение, превышающее 1, означает "
"максимальное число образов, которое можно очищать одновременно."

#: glance/store/__init__.py:53
msgid "Turn on/off delayed delete."
msgstr "Включить/выключить отложенное удаление."

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr ""
"Роль, применяемая для определения идентифицированного пользователя в "
"качестве администратора."

#: glance/scrubber.py:51 glance/registry/client/v1/api.py:34
msgid ""
"Whether to pass through headers containing user and tenant information when "
"making requests to the registry. This allows the registry to use the context "
"middleware without keystonemiddleware's auth_token middleware, removing "
"calls to the keystone auth service. It is recommended that when using this "
"option, secure communication between glance api and glance registry is "
"ensured by means other than auth_token middleware."
msgstr ""
"Передавать ли заголовки, содержащие информацию о пользователях и "
"арендаторах, при отправке запросов к реестру. Позволяет реестру использовать "
"промежуточное программное обеспечение контекста без промежуточного "
"программного обеспечения auth_token Keystone, удаляя вызовы к службе "
"идентификации Keystone. При использовании этой опции рекомендуется "
"установить защищенное соединение между api glance и реестром glance при "
"помощи промежуточного программного обеспечения, отличного от auth_token."

#: glance/scrubber.py:64
msgid "Loop time between checking for new items to schedule for delete."
msgstr ""
"Время цикла между проверками появления новых элементов, чье удаление "
"необходимо запланировать."

#: glance/scrubber.py:72
msgid ""
"Run as a long-running process. When not specified (the default) run the "
"scrub operation once and then exits. When specified do not exit and run "
"scrub on wakeup_time interval as specified in the config."
msgstr ""
"Выполняется как продолжительный процесс. Когда не указан (по умолчанию), "
"выполняется операция очистки один раз, затем выполняется выход. Когда "
"указан, выход не выполняется и выполняется очистка с интервалом wakeup_time, "
"указанным в конфигурации."

#: glance/api/authorization.py:197 glance/api/authorization.py:380
msgid "Public images do not have members."
msgstr "У общедоступных образов нет участников."

#: glance/api/authorization.py:118 glance/api/authorization.py:129
#, python-format
msgid "You cannot get image member for %s"
msgstr "Невозможно получить участник образа для %s"

#: glance/api/authorization.py:137
#, python-format
msgid "You cannot delete image member for %s"
msgstr "Невозможно удалить участник образа для %s"

#: glance/api/authorization.py:146
#, python-format
msgid "You cannot add image member for %s"
msgstr "Невозможно добавить участник образа для %s"

#: glance/api/authorization.py:155
#, python-format
msgid "You cannot update image member %s"
msgstr "Невозможно обновить участник образа %s"

#: glance/api/authorization.py:174
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr "Вам не разрешено создавать образы, принадлежащие '%s'."

#: glance/api/authorization.py:192
msgid "You are not permitted to create image members for the image."
msgstr "Вам не разрешено создавать участники образов для данного образа."

#: glance/api/authorization.py:213
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr "Вам не разрешено изменять '%(attr)s' в этом %(resource)s."

#: glance/api/authorization.py:223
msgid "You are not permitted to modify locations for this image."
msgstr "Вам не разрешено изменять расположения этого образа."

#: glance/api/authorization.py:247
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr "Вам не разрешено изменять '%s' в этом образе."

#: glance/api/authorization.py:251
msgid "You are not permitted to modify this image."
msgstr "Вам не разрешено изменять этот образ."

#: glance/api/authorization.py:264
msgid "You are not permitted to modify tags on this image."
msgstr "Вам не разрешено изменять теги этого образа."

#: glance/api/authorization.py:305
msgid "You are not permitted to delete this image."
msgstr "Вам не разрешено удалять этот образ."

#: glance/api/authorization.py:316
msgid "You are not permitted to upload data for this image."
msgstr "Вам не разрешено загружать данные для этого образа."

#: glance/api/authorization.py:342
msgid "You are not permitted to deactivate this image."
msgstr "Вам не разрешено деактивировать этот образ."

#: glance/api/authorization.py:346
msgid "You are not permitted to reactivate this image."
msgstr "Вам не разрешено повторно активировать этот образ."

#: glance/api/authorization.py:350 glance/api/authorization.py:354
#: glance/api/authorization.py:358
msgid "You are not permitted to set status on this task."
msgstr "Вам не разрешено указывать состояние этой задачи."

#: glance/api/authorization.py:420
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr "Вам не разрешено создавать эту задачу с владельцем: %s"

#: glance/api/authorization.py:515
msgid "You are not permitted to delete this namespace."
msgstr "Нет прав доступа на удаление этого пространства имен."

#: glance/api/authorization.py:519
msgid "You are not permitted to update this namespace."
msgstr "Нет прав доступа на обновление этого пространства имен."

#: glance/api/authorization.py:545
#, python-format
msgid "You are not permitted to create namespace owned by '%s'"
msgstr "Нет прав доступа на создание пространства имен, принадлежащего %s."

#: glance/api/authorization.py:604
msgid "You are not permitted to delete this object."
msgstr "Нет прав доступа на удаление этого объекта."

#: glance/api/authorization.py:608
msgid "You are not permitted to update this object."
msgstr "Нет прав доступа на обновление этого объекта."

#: glance/api/authorization.py:633
#, python-format
msgid "You are not permitted to create object owned by '%s'"
msgstr "Нет прав доступа на создание объекта, принадлежащего %s."

#: glance/api/authorization.py:696
msgid "You are not permitted to delete this meta_resource_type."
msgstr "Нет прав доступа на удаление этого meta_resource_type."

#: glance/api/authorization.py:722
#, python-format
msgid "You are not permitted to create resource_type owned by '%s'"
msgstr "Нет прав доступа на создание resource_type, принадлежащего %s."

#: glance/api/authorization.py:780
msgid "You are not permitted to delete this property."
msgstr "Нет прав доступа на удаление этого свойства."

#: glance/api/authorization.py:784
msgid "You are not permitted to update this property."
msgstr "Нет прав доступа на обновление этого свойства."

#: glance/api/authorization.py:809
#, python-format
msgid "You are not permitted to create property owned by '%s'"
msgstr "Нет прав доступа на создание свойства, принадлежащего %s."

#: glance/api/authorization.py:867
msgid "You are not permitted to delete this tag."
msgstr "У вас нет прав доступа для удаления этого тега."

#: glance/api/authorization.py:871
msgid "You are not permitted to update this tag."
msgstr "У вас нет прав доступа для изменения этого тега."

#: glance/api/authorization.py:892
msgid "Owner must be specified to create a tag."
msgstr "Для создания тега необходимо указать владельца."

#: glance/api/authorization.py:895
#, python-format
msgid "You are not permitted to create a tag in the namespace owned by '%s'"
msgstr ""
"У вас нет прав доступа для создания тега в пространстве имен, владельцем "
"которого является '%s'"

#: glance/api/common.py:56
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr "Образ %(image_id)s скачан поврежденным"

#: glance/api/policy.py:220 glance/quota/__init__.py:343
#: glance/store/__init__.py:662
#, python-format
msgid "Invalid locations: %s"
msgstr "Недопустимые расположения: %s"

#: glance/api/versions.py:27 glance/api/glare/versions.py:28
msgid ""
"Public url to use for versions endpoint. The default is None, which will use "
"the request's host_url attribute to populate the URL base. If Glance is "
"operating behind a proxy, you will want to change this to represent the "
"proxy's URL."
msgstr ""
"Общий url для конечной точки версий. Значение по умолчанию - None, при "
"котором для заполнения базы URL будет использоваться атрибут host_url "
"запроса. Если Glance расположен за proxy-сервером, то потребуется указать "
"URL proxy-сервера."

#: glance/api/glare/v0_1/glare.py:121
#, python-format
msgid "The format of the version %s is not valid. Use semver notation"
msgstr "Недопустимый формат версии %s. Используйте формат semver"

#: glance/api/glare/v0_1/glare.py:188
#, python-format
msgid "Invalid Content-Type for work with %s"
msgstr "Недопустимый Content-Type для работы с  %s"

#: glance/api/glare/v0_1/glare.py:225
msgid "Invalid request PATCH for work with blob"
msgstr "Недопустимый PATCH запроса для работы с объектом blob"

#: glance/api/glare/v0_1/glare.py:239
#, python-format
msgid "Denying attempt to upload artifact because it exceeds the quota: %s"
msgstr "Попытка загрузить артефакт с превышением квоты отклонена: %s"

#: glance/api/glare/v0_1/glare.py:263
#, python-format
msgid "Failed to find artifact %(artifact_id)s to delete"
msgstr "Не удалось найти артефакт %(artifact_id)s для удаления"

#: glance/api/glare/v0_1/glare.py:267
#, python-format
msgid "Artifact %s could not be deleted because it is in use: %s"
msgstr "Не удалось удалить артефакт %s, так как он используется: %s"

#: glance/api/glare/v0_1/glare.py:296
msgid "Unable to PUT to non-empty collection"
msgstr "Не удалось выполнить операцию PUT в непустой набор"

#: glance/api/glare/v0_1/glare.py:299
msgid "Index is out of range"
msgstr "Индекс выходит за пределы диапазона"

#: glance/api/glare/v0_1/glare.py:322
#, python-format
msgid "Not a blob property '%s'"
msgstr "Не является свойством большого двоичного объекта '%s'"

#: glance/api/glare/v0_1/glare.py:330
#, python-format
msgid "Not a list property '%s'"
msgstr "Не является свойством списка '%s'"

#: glance/api/glare/v0_1/glare.py:344
msgid "Error in store configuration. Adding artifacts to store is disabled."
msgstr ""
"Ошибка в конфигурации хранилища. Добавление артефактов в хранилище отключено."

#: glance/api/glare/v0_1/glare.py:366
#, python-format
msgid "Artifact storage media is full: %s"
msgstr "Носитель хранилища артефактов заполнен: %s"

#: glance/api/glare/v0_1/glare.py:374
#, python-format
msgid "Artifact exceeds the storage quota: %s"
msgstr "Артефакт превышает квоту хранилища: %s"

#: glance/api/glare/v0_1/glare.py:382
#, python-format
msgid "The incoming artifact blob is too large: %s"
msgstr "Чересчур большой размер входящего артефакта: %s"

#: glance/api/glare/v0_1/glare.py:390
#, python-format
msgid "Insufficient permissions on artifact storage media: %s"
msgstr "Недостаточные права для доступа к носителю артефактов: %s"

#: glance/api/glare/v0_1/glare.py:423
msgid "Index is required"
msgstr "Требуется индекс"

#: glance/api/glare/v0_1/glare.py:431
msgid "Not a list property"
msgstr "Не является свойством списка"

#: glance/api/glare/v0_1/glare.py:435
msgid "Not a downloadable entity"
msgstr "Не является загружаемой сущностью"

#: glance/api/v2/image_members.py:189 glance/api/v2/images.py:287
msgid "Body expected in request."
msgstr "В запросе ожидалось тело."

#: glance/api/glare/v0_1/glare.py:577
#, python-format
msgid "Invalid headers \"Content-Type\": %s"
msgstr "Недопустимые заголовки \"Content-Type\": %s"

#: glance/api/glare/v0_1/glare.py:615
#, python-format
msgid "Invalid json body: %s"
msgstr "Недопустимое тело json: %s"

#: glance/api/glare/v0_1/glare.py:628
msgid "Only list indexes are allowed for blob lists"
msgstr ""
"Для списков больших двоичных объектов разрешены только индексы списков"

#: glance/api/glare/v0_1/glare.py:649
msgid "Limit param must be an integer"
msgstr "Параметр ограничения должен быть целым числом"

#: glance/api/glare/v0_1/glare.py:653
msgid "Limit param must be positive"
msgstr "Параметр Limit должен быть положительным числом"

#: glance/api/glare/v0_1/glare.py:657
#, python-format
msgid "Limit param must not be higher than %d"
msgstr "Параметр ограничения не должен превышать %d"

#: glance/api/glare/v0_1/glare.py:667
#, python-format
msgid ""
"Invalid sort key: %(sort_key)s. If type version is not set it must be one of "
"the following: %(available)s."
msgstr ""
"Недопустимый ключ сортировки: %(sort_key)s. Если версия типа не задана, "
"допускается один из следующих: %(available)s."

#: glance/api/glare/v0_1/glare.py:678
#, python-format
msgid "Invalid sort key: %(sort_key)s. You cannot sort by this property"
msgstr ""
"Недопустимый ключ сортировки: %(sort_key)s. Нельзя выполнять сортировку по "
"этому свойству"

#: glance/api/v2/images.py:498 glance/api/v2/tasks.py:134
#, python-format
msgid "Invalid sort direction: %s"
msgstr "Недопустимое направление сортировки: %s"

#: glance/api/middleware/context.py:28
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing "
"the request."
msgstr ""
"Если эта опция равна true, то она назначает арендатором владельца образа. В "
"противном случае владельцем образа будет идентифицированный пользователь, "
"отправивший запрос."

#: glance/api/middleware/context.py:36
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""
"Разрешить неидентифицированным пользователям доступ к API с правами только "
"на чтение. Это применимо только при использовании ContextMiddleware."

#: glance/api/middleware/context.py:41
msgid "Limits request ID length."
msgstr "Ограничивает длину ИД запроса."

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr "Невозможно извлечь ИД запроса из контекста"

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr "Недопустимый json каталога службы."

#: glance/api/middleware/context.py:125
#, python-format
msgid "x-openstack-request-id is too long, max size %s"
msgstr "Слишком большая длина x-openstack-request-id, максимальная длина: %s"

#: glance/api/v1/controller.py:41 glance/api/v1/members.py:76
#, python-format
msgid "Image with identifier %s not found"
msgstr "Образ с идентификатором %s не найден"

#: glance/api/v1/controller.py:46
msgid "Forbidden image access"
msgstr "Доступ к образу запрещен"

#: glance/api/v1/controller.py:61
#, python-format
msgid "Image %s is deactivated"
msgstr "Образ %s деактивирован"

#: glance/api/v1/controller.py:59
#, python-format
msgid "Image %s is not active"
msgstr "Образ %s неактивен"

#: glance/api/v1/controller.py:81
#, python-format
msgid "Store for image_id not found: %s"
msgstr "Хранилище для image_id не найдено: %s"

#: glance/api/v1/controller.py:93
#, python-format
msgid "Data for image_id not found: %s"
msgstr "Не найдены данные для image_id: %s"

#: glance/api/v1/images.py:87
#, python-format
msgid "Invalid time format for %s."
msgstr "Недопустимый формат времени для %s."

#: glance/api/v1/images.py:73
#, python-format
msgid "Invalid disk format '%s' for image."
msgstr "Неверный формат диска '%s' для образа."

#: glance/api/v1/images.py:78
#, python-format
msgid "Invalid container format '%s' for image."
msgstr "Неверный формат контейнера '%s' для образа."

#: glance/api/v1/images.py:94
msgid ""
"Invalid mix of disk and container formats. When setting a disk or container "
"format to one of 'aki', 'ari', or 'ami', the container and disk formats must "
"match."
msgstr ""
"Недопустимое сочетание форматов диска и контейнера. При задании формата "
"диска или контейнера равным 'aki', 'ari' или 'ami' форматы контейнера и "
"диска должны совпадать."

#: glance/api/v1/images.py:83
#, python-format
msgid "Image name too long: %d"
msgstr "Имя образа слишком длинное: %d"

#: glance/api/v1/images.py:139
#, python-format
msgid "Invalid checksum '%s': can't exceed 32 characters"
msgstr ""
"Недопустимая контрольная сумма '%s': длина не может превышать 32 символа"

#: glance/api/v1/images.py:172
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""
"Превышено ограничение по числу разрешенных свойств образа. Указанное число: "
"%(num)s, максимальное число: %(quota)s"

#: glance/api/v1/images.py:194 glance/api/v1/images.py:238
#: glance/api/v1/images.py:272
#, python-format
msgid "Property '%s' is protected"
msgstr "Свойство '%s' защищено"

#: glance/api/v1/images.py:388
msgid "This operation is currently not permitted on Glance images details."
msgstr ""
"Эта операция в настоящее время не разрешена для сведений об образах Glance."

#: glance/api/v1/images.py:380
#, python-format
msgid "Bad value passed to filter %(filter)s got %(val)s"
msgstr "Фильтру %(filter)s передано неверное значение, получено %(val)s"

#: glance/api/v1/images.py:477
#, python-format
msgid "External sources are not supported: '%s'"
msgstr "Внешние ресурсы не поддерживаются: %s"

#: glance/api/v1/images.py:479
msgid "External source should not be empty"
msgstr "Внешний источник не должен быть пустым"

#: glance/api/v1/images.py:493
#, python-format
msgid "Required store %s is invalid"
msgstr "Необходимое хранилище %s недопустимо"

#: glance/api/v1/images.py:505 glance/api/v1/images.py:877
#, python-format
msgid "Invalid location %s"
msgstr "Неверное расположение %s"

#: glance/api/v1/images.py:528
#, python-format
msgid "An image with identifier %s already exists"
msgstr "Образ с идентификатором %s уже существует"

#: glance/api/v1/images.py:621
#, python-format
msgid "Failed to reserve image. Got error: %s"
msgstr "Зарезервировать образ не удалось. Ошибка: %s"

#: glance/api/v1/images.py:542
msgid "Forbidden to reserve image."
msgstr "Резервировать образ запрещено."

#: glance/api/v1/images.py:578
msgid "Content-Type must be application/octet-stream"
msgstr "Content-Type должен быть задан в формате приложение/октет-поток"

#: glance/api/v1/images.py:729
#, python-format
msgid "Failed to activate image. Got error: %s"
msgstr "Активировать образ не удалось. Ошибка: %s"

#: glance/api/v1/images.py:683
msgid "It's invalid to provide multiple image sources."
msgstr "Указывать несколько источников образов нельзя."

#: glance/api/v1/images.py:709
#, python-format
msgid ""
"Provided image size must match the stored image size. (provided size: "
"%(ps)d, stored size: %(ss)d)"
msgstr ""
"Указанный размер образа должен быть равен сохраненному размеру образа. "
"(Указанный размер: %(ps)d, сохраненный размер: %(ss)d)"

#: glance/api/v1/images.py:855
msgid "Disk format is not specified."
msgstr "Не указан формат диска."

#: glance/api/v1/images.py:860
msgid "Container format is not specified."
msgstr "Не указан формат контейнера."

#: glance/api/v1/images.py:831
msgid "Forbidden to update deleted image."
msgstr "Обновлять удаленный образ запрещено."

#: glance/api/v1/images.py:978
#, python-format
msgid "Forbidden to modify '%(key)s' of %(status)s image."
msgstr "Запрещено изменять '%(key)s' образа  %(status)s."

#: glance/api/v1/images.py:987
#, python-format
msgid "Forbidden to modify '%s' of image."
msgstr "Изменять '%s' образа запрещено."

#: glance/api/v1/images.py:860
msgid "Cannot upload to an unqueued image"
msgstr "Невозможно загрузить в образ, не находящийся в очереди"

#: glance/store/__init__.py:469
#, python-format
msgid "Invalid location: %s"
msgstr "Недопустимое расположение: %s"

#: glance/api/v1/images.py:884
msgid "Attempted to update Location field for an image not in queued status."
msgstr ""
"Предпринята попытка обновить поле Расположение для образа, не находящегося в "
"очереди."

#: glance/api/v1/images.py:1069 glance/registry/api/v1/images.py:502
#, python-format
msgid "Failed to update image metadata. Got error: %s"
msgstr "Обновить метаданные образа не удалось. Ошибка: %s"

#: glance/api/v1/images.py:1076
#, python-format
msgid "Failed to find image to update: %s"
msgstr "Найти образ для обновления не удалось: %s"

#: glance/api/v1/images.py:1083
#, python-format
msgid "Forbidden to update image: %s"
msgstr "Обновлять образ запрещено: %s"

#: glance/api/v1/images.py:1091
msgid "Image operation conflicts"
msgstr "Конфликт операций с образом"

#: glance/api/v1/images.py:977
msgid "Image is protected"
msgstr "Образ защищен"

#: glance/api/v1/images.py:984
#, python-format
msgid "Forbidden to delete a %s image."
msgstr "Удалять образ %s запрещено."

#: glance/api/v1/images.py:989
#, python-format
msgid "Image %s not found."
msgstr "Образ %s не найден."

#: glance/api/v1/images.py:1171
#, python-format
msgid "Failed to find image to delete: %s"
msgstr "Найти образ для удаления не удалось: %s"

#: glance/api/v1/images.py:1178
#, python-format
msgid "Forbidden to delete image: %s"
msgstr "Удалять образ запрещено: %s"

#: glance/api/v1/images.py:1185 glance/api/v2/images.py:246
#, python-format
msgid "Image %(id)s could not be deleted because it is in use: %(exc)s"
msgstr "Не удается удалить образ %(id)s, так как он используется: %(exc)s"

#: glance/api/v1/images.py:1052 glance/store/__init__.py:231
#, python-format
msgid "Store for scheme %s not found"
msgstr "Хранилище для схемы %s не найдено"

#: glance/api/v1/images.py:1091 glance/api/v1/upload_utils.py:202
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr "Попытка загрузить образ размером более %d байт отклонена."

#: glance/api/v1/members.py:41 glance/registry/api/v1/members.py:32
msgid "No authenticated user"
msgstr "Нет идентифицированного пользователя"

#: glance/api/v1/members.py:53
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr "Образ с идентификатором %s удален."

#: glance/api/v1/members.py:80
msgid "Unauthorized image access"
msgstr "Нет прав на доступ к образу"

#: glance/api/v1/members.py:117 glance/common/exception.py:287
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for this "
"image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Превышено ограничение по числу разрешенных участников данного образа. "
"Указанное число: %(attempted)s, максимальное число: %(maximum)s"

#: glance/api/v1/upload_utils.py:115
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded image "
"(%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""
"Предоставленный %(attr)s (%(supplied)s) и %(attr)s, сгенерированный из "
"загруженного образа (%(actual)s), не совпадают. Образ переводится в "
"состояние 'killed'."

#: glance/api/v1/upload_utils.py:148
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload."
msgstr ""
"Образ %s не найден после загрузки. Возможно, он удален во время загрузки."

#: glance/api/v1/upload_utils.py:195 glance/api/v2/image_data.py:175
msgid "Error in store configuration. Adding images to store is disabled."
msgstr ""
"Ошибка в конфигурации хранилища. Добавление образов в хранилище отключено."

#: glance/api/v1/upload_utils.py:164
#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr "Попытка загрузить дубликат образа: %s"

#: glance/api/v1/upload_utils.py:175
#, python-format
msgid "Forbidden upload attempt: %s"
msgstr "Запрещенная попытка загрузки: %s"

#: glance/api/v1/upload_utils.py:256 glance/api/v2/images.py:159
#, python-format
msgid "Denying attempt to upload image because it exceeds the quota: %s"
msgstr "Попытка загрузить образ с превышением квоты отклонена: %s"

#: glance/api/v1/upload_utils.py:233
msgid "Client disconnected before sending all data to backend"
msgstr "Клиент отключился, отправив не все данные в базовую систему"

#: glance/api/v1/upload_utils.py:241
#, python-format
msgid "Failed to upload image %s"
msgstr "Загрузить образ %s не удалось"

#: glance/api/v2/image_data.py:139
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted "
"during the upload, cleaning up the chunks uploaded."
msgstr ""
"Образ %s не найден после загрузки. Возможно, он был удален во время "
"передачи, выполняется очистка переданных фрагментов."

#: glance/api/v2/image_data.py:154
#, python-format
msgid ""
"Authentication error - the token may have expired during file upload. "
"Deleting image data for %s."
msgstr ""
"Ошибка идентификации. Возможно, время действия маркера истекло во время "
"загрузки файла. Данные образа для %s будут удалены."

#: glance/api/v2/image_data.py:114
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr "Размер образа превышает квоту хранилища: %s"

#: glance/api/v2/image_data.py:121
#, python-format
msgid "The incoming image is too large: %s"
msgstr "Чересчур большой размер входящего образа: %s"

#: glance/api/v2/image_data.py:256
msgid ""
"The requested image has been deactivated. Image data download is forbidden."
msgstr "Запрошенный образ деактивирован. Загрузка данных образа запрещена."

#: glance/api/v2/image_members.py:56
#, python-format
msgid "Error fetching members of image %(image_id)s: %(inner_msg)s"
msgstr "Ошибка при выборке элементов образа %(image_id)s: %(inner_msg)s"

#: glance/api/v2/image_members.py:71
#, python-format
msgid "You are not authorized to lookup image %s."
msgstr "У вас нет прав доступа для поиска образа %s."

#: glance/api/v2/image_members.py:80
#, python-format
msgid "%(m_id)s not found in the member list of the image %(i_id)s."
msgstr "%(m_id)s не найден в списке элементов образа %(i_id)s."

#: glance/api/v2/image_members.py:86
#, python-format
msgid "You are not authorized to lookup the members of the image %s."
msgstr "У вас нет прав доступа для поиска элементов образа %s."

#: glance/api/v2/image_members.py:119
#, python-format
msgid "Not allowed to create members for image %s."
msgstr "Не разрешено создавать участников для образа %s."

#: glance/api/v2/image_members.py:123
#, python-format
msgid "Member %(member_id)s is duplicated for image %(image_id)s"
msgstr "Обнаружена копия участника %(member_id)s для образа %(image_id)s"

#: glance/api/v2/image_members.py:129
#, python-format
msgid "Image member limit exceeded for image %(id)s: %(e)s:"
msgstr ""
"Превышено предельно допустимое число участников для образа %(id)s: %(e)s:"

#: glance/api/v2/image_members.py:161
#, python-format
msgid "Not allowed to update members for image %s."
msgstr "Не разрешено изменять участников для образа %s."

#: glance/api/v2/image_members.py:165
#, python-format
msgid "Incorrect request: %s"
msgstr "Неправильный запрос: %s"

#: glance/api/v2/image_members.py:197
#, python-format
msgid "Not allowed to list members for image %s."
msgstr "Не разрешено выводить список участников для образа %s."

#: glance/api/v2/image_members.py:239
#, python-format
msgid "Not allowed to delete members for image %s."
msgstr "Не разрешено удалять участников для образа %s."

#: glance/api/v2/image_members.py:200
msgid "Member to be added not specified"
msgstr "Добавляемый участник не указан"

#: glance/api/v2/image_members.py:203
msgid "Member can't be empty"
msgstr "Участник не может быть пустым"

#: glance/api/v2/image_members.py:269
msgid "Expected a member in the form: {\"member\": \"image_id\"}"
msgstr "Элемент должен быть задан в формате: {\"member\": \"image_id\"}"

#: glance/api/v2/image_members.py:212
msgid "Status not specified"
msgstr "Состояние не указано"

#: glance/api/v2/image_members.py:282
msgid "Expected a status in the form: {\"status\": \"status\"}"
msgstr "Состояние должно быть указано в формате: {\"status\": \"status\"}"

#: glance/api/v2/image_members.py:267
msgid "An identifier for the image member (tenantId)"
msgstr "Идентификатор участника образа (tenantId)"

#: glance/api/v2/image_members.py:271 glance/api/v2/images.py:644
msgid "An identifier for the image"
msgstr "Идентификатор образа"

#: glance/api/v2/image_members.py:277
msgid "Date and time of image member creation"
msgstr "Дата и время создания участника образа"

#: glance/api/v2/image_members.py:284
msgid "Date and time of last modification of image member"
msgstr "Дата и время последней модификации участника образа"

#: glance/api/v2/image_members.py:289
msgid "The status of this image member"
msgstr "Состояние этого участника образа"

#: glance/api/v2/image_tags.py:56
#, python-format
msgid "Not allowed to update tags for image %s."
msgstr "Не разрешено изменять теги для образа %s."

#: glance/api/v2/image_tags.py:60
#, python-format
msgid "Could not update image: %s"
msgstr "Не удалось изменить образ: %s"

#: glance/api/v2/image_tags.py:65
#, python-format
msgid "Image tag limit exceeded for image %(id)s: %(e)s:"
msgstr "Превышено предельно допустимое число тегов для образа %(id)s: %(e)s:"

#: glance/api/v2/image_tags.py:85
#, python-format
msgid "Not allowed to delete tags for image %s."
msgstr "Не разрешено удалять теги для образа %s."

#: glance/api/v2/images.py:178
msgid "Cannot set locations to empty list."
msgstr "Список расположений не может быть пустым."

#: glance/api/v2/images.py:183
msgid "Owner can't be updated by non admin."
msgstr "Обычный пользователь не может изменить владельца."

#: glance/api/v2/images.py:156 glance/api/v2/images.py:184
#, python-format
msgid "Property %s does not exist."
msgstr "Свойство %s не существует."

#: glance/api/v2/images.py:168
#, python-format
msgid "Property %s already present."
msgstr "Свойство %s уже существует."

#: glance/api/v2/images.py:179
#, python-format
msgid "Property %s may not be removed."
msgstr "Свойство %s нельзя удалить."

#: glance/api/v2/images.py:197
#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr "Найти образ для удаления %(image_id)s не удалось"

#: glance/api/v2/images.py:273
msgid "It's not allowed to update locations if locations are invisible."
msgstr "Не разрешено обновлять расположения, если они невидимы."

#: glance/api/v2/images.py:291
msgid "It's not allowed to add locations if locations are invisible."
msgstr "Не разрешено добавлять расположения, если они невидимы."

#: glance/api/v2/images.py:239
msgid "Invalid position for adding a location."
msgstr "Недопустимая позиция для добавления расположения."

#: glance/api/v2/images.py:312
msgid "It's not allowed to remove locations if locations are invisible."
msgstr "Не разрешено удалять расположения, если они невидимы."

#: glance/api/v2/images.py:319
msgid "Cannot remove last location in the image."
msgstr "Нельзя удалять последнее расположение из образа."

#: glance/api/v2/images.py:254
msgid "Invalid position for removing a location."
msgstr "Недопустимая позиция для удаления расположения."

#: glance/api/v2/images.py:295 glance/api/v2/images.py:394
#, python-format
msgid "Attribute '%s' is read-only."
msgstr "Атрибут '%s' предназначен только для чтения."

#: glance/api/v2/images.py:405
#, python-format
msgid ""
"Unable to find `op` in JSON Schema change. It must be one of the following: "
"%(available)s."
msgstr ""
"Не удалось найти `op` в изменении схемы JSON. Допускается одно из следующих "
"значений: %(available)s."

#: glance/api/v2/images.py:410
#, python-format
msgid ""
"Invalid operation: `%(op)s`. It must be one of the following: %(available)s."
msgstr ""
"Недопустимая операция: `%(op)s`. Допускается одна из следующих операций: "
"%(available)s."

#: glance/api/v2/images.py:327
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\", or "
"\"replace\"."
msgstr ""
"Объекты операции должны содержать только один участник с именем \"add\", "
"\"remove\" или \"replace\"."

#: glance/api/v2/images.py:332
msgid ""
"Operation objects must contain exactly one member named \"add\", \"remove\", "
"or \"replace\"."
msgstr ""
"Объекты операции должны содержать в точности один участник с именем \"add\", "
"\"remove\" или \"replace\"."

#: glance/api/v2/images.py:319 glance/api/v2/images.py:341
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr "'%s' не найден в изменении схемы JSON"

#: glance/api/v2/images.py:369
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr "Указатель `%s` не начинается с \"/\"."

#: glance/api/v2/images.py:372
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr "Указатель `%s` содержит смежный \"/\"."

#: glance/api/v2/images.py:375
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr "Указатель `%s` оканчивается на \"/\"."

#: glance/api/v2/images.py:378
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr "Указатель `%s` не содержит допустимого маркера."

#: glance/api/v2/images.py:381
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""
"Указатель `%s` содержит символ \"~\", не входящий в распознаваемую Esc-"
"последовательность."

#: glance/api/v2/images.py:387
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr "Операции \"%s\" требуется участник с именем \"value\"."

#: glance/api/v2/images.py:397
#, python-format
msgid "Attribute '%s' is reserved."
msgstr "Атрибут '%s' зарезервирован."

#: glance/api/v2/images.py:427
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr "Недопустимый указатель JSON для этого ресурса: '%s'"

#: glance/api/v2/images.py:439
msgid "Unrecognized JSON Schema draft version"
msgstr "Нераспознанная версия черновика схемы JSON"

#: glance/api/v2/images.py:460
msgid "Request body must be a JSON array of operation objects."
msgstr "Тело запроса должно быть массивом JSON объектов операции."

#: glance/api/v2/images.py:465
msgid "Operations must be JSON objects."
msgstr "Операции должны быть объектами JSON."

#: glance/api/v2/images.py:487 glance/api/v2/tasks.py:164
#: glance/registry/api/v1/images.py:246
msgid "limit param must be an integer"
msgstr "Параметр limit должен быть целым числом"

#: glance/api/v2/images.py:491 glance/api/v2/tasks.py:168
#: glance/registry/api/v1/images.py:249
msgid "limit param must be positive"
msgstr "Параметр limit должен быть положительным"

#: glance/api/v2/images.py:596
#, python-format
msgid ""
"Invalid sort key: %(sort_key)s. It must be one of the following: "
"%(available)s."
msgstr ""
"Недопустимый ключ сортировки %(sort_key)s. Допускается один из следующих "
"ключей: %(available)s."

#: glance/api/v2/images.py:505
#, python-format
msgid "Invalid status: %s"
msgstr "Недопустимое состояние: %s"

#: glance/api/v2/images.py:514
#, python-format
msgid "Invalid visibility value: %s"
msgstr "Недопустимое значение видимости: %s"

#: glance/api/v2/images.py:626
msgid "The \"changes-since\" filter is no longer available on v2."
msgstr "Фильтр \"changes-since\" больше недоступен в v2."

#: glance/api/v2/images.py:645
msgid "Old and new sorting syntax cannot be combined"
msgstr "Прежний и новый синтаксисы сортировки нельзя смешивать"

#: glance/api/v2/images.py:676
msgid "Number of sort dirs does not match the number of sort keys"
msgstr "Число направлений сортировки не совпадает с числом ключей сортировки"

#: glance/api/v2/images.py:650
msgid "Descriptive name for the image"
msgstr "Описательное имя образа"

#: glance/api/v2/images.py:848
msgid "Status of the image"
msgstr "Состояние образа"

#: glance/api/v2/images.py:661
msgid "Scope of image accessibility"
msgstr "Область доступности образа"

#: glance/api/v2/images.py:666
msgid "If true, image will not be deletable."
msgstr "Если значение равно true, то образ нельзя будет удалить."

#: glance/api/v2/images.py:864
msgid "md5 hash of image contents."
msgstr "Хэш md5 содержимого образа."

#: glance/api/v2/images.py:675
msgid "Owner of the image"
msgstr "Владелец образа"

#: glance/api/v2/images.py:875
msgid "Size of image file in bytes"
msgstr "Размер файла образа в байтах"

#: glance/api/v2/images.py:880
msgid "Virtual size of image in bytes"
msgstr "Виртуальный размер образа в байтах"

#: glance/api/v2/images.py:688
msgid "Format of the container"
msgstr "Формат контейнера"

#: glance/api/v2/images.py:693
msgid "Format of the disk"
msgstr "Формат диска"

#: glance/api/v2/images.py:895
msgid "Date and time of image registration"
msgstr "Дата и время регистрации образа"

#: glance/api/v2/images.py:904
msgid "Date and time of the last image modification"
msgstr "Дата и время последнего изменения образа"

#: glance/api/v2/images.py:712
msgid "List of strings related to the image"
msgstr "Список строк, относящихся к образу"

#: glance/api/v2/images.py:919
msgid "URL to access the image file kept in external store"
msgstr "URL для доступа к файлу образа, находящемуся во внешнем хранилище"

#: glance/api/v2/images.py:725
msgid "Amount of ram (in MB) required to boot image."
msgstr "Объем оперативной памяти (в МБ), необходимой для загрузки образа."

#: glance/api/v2/images.py:729
msgid "Amount of disk space (in GB) required to boot image."
msgstr "Объем дисковой памяти (в ГБ), необходимой для загрузки образа."

#: glance/api/v2/images.py:934
msgid "An image self url"
msgstr "Собственный url образа"

#: glance/api/v2/images.py:939
msgid "An image file url"
msgstr "url файла образа"

#: glance/api/v2/images.py:944
msgid "An image schema url"
msgstr "url схемы образа"

#: glance/api/v2/images.py:759
msgid "A set of URLs to access the image file kept in external store"
msgstr ""
"Набор URL для доступа к файлу образа, находящемуся во внешнем хранилище"

#: glance/api/v2/metadef_namespaces.py:675
msgid "The unique namespace text."
msgstr "Уникальный текст пространства имен."

#: glance/api/v2/metadef_namespaces.py:680
msgid "The user friendly name for the namespace. Used by UI if available."
msgstr ""
"Имя пространства имен для пользователя. Используется в пользовательском "
"интерфейсе."

#: glance/api/v2/metadef_namespaces.py:686
msgid "Provides a user friendly description of the namespace."
msgstr "Описание пространства имен для пользователя."

#: glance/api/v2/metadef_namespaces.py:692
msgid "Scope of namespace accessibility."
msgstr "Область доступности пространства имен."

#: glance/api/v2/metadef_namespaces.py:697
msgid "If true, namespace will not be deletable."
msgstr "Если true, пространство имен будет неудаляемым."

#: glance/api/v2/metadef_namespaces.py:701
msgid "Owner of the namespace."
msgstr "Владелец пространства имен."

#: glance/api/v2/metadef_namespaces.py:707
msgid "Date and time of namespace creation"
msgstr "Дата и время создания пространства имен"

#: glance/api/v2/metadef_namespaces.py:713
msgid "Date and time of the last namespace modification"
msgstr "Дата и время последнего изменения пространства имен"

#: glance/api/v2/metadef_objects.py:197
msgid "Date and time of object creation"
msgstr "Дата и время создания объекта"

#: glance/api/v2/metadef_objects.py:203
msgid "Date and time of the last object modification"
msgstr "Дата и время последнего изменения объекта"

#: glance/api/v2/metadef_properties.py:94
#, python-format
msgid ""
"Property %(property_name)s does not start with the expected resource type "
"association prefix of '%(prefix)s'."
msgstr ""
"Свойство %(property_name)s не начинается с ожидаемого префикса связи типа "
"ресурса '%(prefix)s'."

#: glance/api/v2/metadef_resource_types.py:131
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:125
#, python-format
msgid "Failed to find resource type %(resourcetype)s to delete"
msgstr "Не удалось найти тип ресурса %(resourcetype)s для удаления"

#: glance/api/v2/metadef_resource_types.py:204
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:199
msgid ""
"Resource type names should be aligned with Heat resource types whenever "
"possible: "
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"
msgstr ""
"Имена типов ресурсов должны быть согласованы с типами ресурсов Heat, когда "
"это возможно: "
"http://docs.openstack.org/developer/heat/template_guide/openstack.html"

#: glance/api/v2/metadef_resource_types.py:212
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:207
msgid ""
"Specifies the prefix to use for the given resource type. Any properties in "
"the namespace should be prefixed with this prefix when being applied to the "
"specified resource type. Must include prefix separator (e.g. a colon :)."
msgstr ""
"Задает префикс для данного типа ресурсов. Все свойства в пространстве имен "
"должны иметь этот префикс при применении к указанному типу ресурсов. Должен "
"использоваться разделитель префикса (например, двоеточие :)."

#: glance/api/v2/metadef_resource_types.py:221
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:216
msgid ""
"Some resource types allow more than one key / value pair per instance.  For "
"example, Cinder allows user and image metadata on volumes. Only the image "
"properties metadata is evaluated by Nova (scheduling or drivers). This "
"property allows a namespace target to remove the ambiguity."
msgstr ""
"Некоторые типы ресурсов допускают более одной пары ключ-значение на "
"экземпляр.  Например, в Cinder разрешены метаданные пользователей и образов "
"для томов. Только метаданные свойств образа обрабатываются Nova "
"(планирование или драйверы). Это свойство позволяет целевому объекту "
"пространства имен устранить неоднозначность."

#: glance/api/v2/metadef_resource_types.py:233
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:228
msgid "Date and time of resource type association"
msgstr "Дата и время связывания типа ресурса"

#: glance/api/v2/metadef_resource_types.py:239
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:234
msgid "Date and time of the last resource type association modification"
msgstr "Дата и время последнего изменения связи типа ресурса"

#: glance/api/v2/metadef_tags.py:198
msgid "Date and time of tag creation"
msgstr "Дата и время создания тега"

#: glance/api/v2/metadef_tags.py:204
msgid "Date and time of the last tag modification"
msgstr "Дата и время последнего изменения тега"

#: glance/api/v2/tasks.py:137
msgid ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."
msgstr ""
"Эта операция в настоящее время не разрешена для задач Glance. Они "
"автоматически удаляются после достижения срока, указанного в их свойстве "
"expires_at."

#: glance/api/v2/tasks.py:143
#, python-format
msgid "Invalid status value: %s"
msgstr "Недопустимое значение состояния: %s"

#: glance/api/v2/tasks.py:149
#, python-format
msgid "Invalid type value: %s"
msgstr "Недопустимое значение типа: %s"

#: glance/api/v2/tasks.py:156 glance/registry/api/v1/images.py:258
msgid "Invalid marker format"
msgstr "Недопустимый формат маркера"

#: glance/api/v2/tasks.py:177
#, python-format
msgid "Task '%s' is required"
msgstr "Требуется задача '%s'"

#: glance/api/v2/tasks.py:292
msgid "An identifier for the task"
msgstr "Идентификатор задачи"

#: glance/api/v2/tasks.py:293
msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"
msgstr ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-"
"fA-F]){12}$"

#: glance/api/v2/tasks.py:298
msgid "The type of task represented by this content"
msgstr "Тип задачи, представленной этим содержимым"

#: glance/api/v2/tasks.py:305
msgid "The current status of this task"
msgstr "Текущее состояние задачи"

#: glance/api/v2/tasks.py:315
msgid "The parameters required by task, JSON blob"
msgstr "Параметры, обязательные для задачи JSON blob"

#: glance/api/v2/tasks.py:319
msgid "The result of current task, JSON blob"
msgstr "Результат текущей задачи JSON blob"

#: glance/api/v2/tasks.py:323
msgid "An identifier for the owner of this task"
msgstr "Идентификатор владельца задачи"

#: glance/api/v2/tasks.py:327
msgid ""
"Human-readable informative message only included when appropriate (usually "
"on failure)"
msgstr ""
"Информационное сообщение для пользователя добавляется только в "
"соответствующих случаях (обычно в случае ошибки)"

#: glance/api/v2/tasks.py:332
msgid "Datetime when this resource would be subject to removal"
msgstr "Дата и время планового удаления ресурса"

#: glance/api/v2/tasks.py:337
msgid "Datetime when this resource was created"
msgstr "Дата и время создания ресурса"

#: glance/api/v2/tasks.py:341
msgid "Datetime when this resource was updated"
msgstr "Дата и время обновления ресурса"

#: glance/async/taskflow_executor.py:40
msgid "The mode in which the engine will run. Can be 'serial' or 'parallel'."
msgstr "Режим работы службы. Допустимые значения: serial, parallel."

#: glance/async/taskflow_executor.py:44
msgid ""
"The number of parallel activities executed at the same time by the engine. "
"The value can be greater than one when the engine mode is 'parallel'."
msgstr ""
"Число параллельных операций, одновременно выполняемых службой. Значение "
"может быть больше 1, когда режим работы службы - parallel."

#: glance/async/taskflow_executor.py:144
msgid "Task failed due to Internal Error"
msgstr "Задача не выполнена из-за внутренней ошибки"

#: glance/async/flows/base_import.py:95
#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Missing work dir: "
"%(work_dir)s"
msgstr ""
"Служба %(task_id)s типа %(task_type)s настроена неправильно. Отсутствует "
"рабочий каталог: %(work_dir)s"

#: glance/async/flows/base_import.py:127
#, python-format
msgid ""
"%(task_id)s of %(task_type)s not configured properly. Could not load the "
"filesystem store"
msgstr ""
"Служба %(task_id)s типа %(task_type)s настроена неправильно. Не удалось "
"загрузить хранилище в файловой системе"

#: glance/async/flows/base_import.py:170
#, python-format
msgid "File %(path)s has invalid backing file %(bfile)s, aborting."
msgstr ""
"Файл %(path)s содержит недопустимый базовый файл %(bfile)s, принудительное "
"завершение."

#: glance/async/flows/convert.py:31
msgid ""
"The format to which images will be automatically converted. When using the "
"RBD backend, this should be set to 'raw'"
msgstr ""
"Формат, в который будут автоматически преобразовываться образы. При работе с "
"RBD должен быть задан как 'raw'"

#: glance/async/flows/ovf_process.py:112
msgid "OVA extract is limited to admin"
msgstr "Распаковку OVA может выполнить только администратор"

#: glance/async/flows/ovf_process.py:153
msgid "Could not find OVF file in OVA archive file."
msgstr "Не найден файл OVF в файле архива OVA."

#: glance/async/flows/ovf_process.py:205
msgid "Currently, OVA packages containing multiple disk are not supported."
msgstr ""
"В настоящее время пакеты OVA с несколькими дисками не поддерживаются."

#: glance/async/flows/ovf_process.py:246
msgid ""
"OVF metadata of interest was not specified in ovf-metadata.json config file. "
"Please set \"cim_pasd\" to a list of interested "
"CIM_ProcessorAllocationSettingData properties."
msgstr ""
"Требуемые метаданные OVF не заданы в файле конфигурации ovf-metadata.json. "
"Укажите в параметре \"cim_pasd\" список требуемых свойств "
"CIM_ProcessorAllocationSettingData."

#: glance/async/flows/ovf_process.py:252
msgid "OVF properties config file \"ovf-metadata.json\" was not found."
msgstr "Файл конфигурации \"ovf-metadata.json\" со свойствами OVF не найден."

#: glance/cmd/__init__.py:41
#, python-format
msgid ""
"It appears that the eventlet module has been imported prior to setting "
"%s='yes'. It is currently necessary to disable eventlet.greendns if using "
"ipv6 since eventlet.greendns currently breaks with ipv6 addresses. Please "
"ensure that eventlet is not imported prior to this being set."
msgstr ""
"Вероятно, модуль eventlet импортирован до задания %s='yes'. В данный момент "
"необходимо отключить eventlet.greendns, если используется ipv6, так как "
"eventlet.greendns в настоящее время не работает с адресами ipv6. Убедитесь, "
"что библиотека eventlet импортируется не до настройки этих параметров."

#: glance/cmd/control.py:102
#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr "%(serv)s уже запущен: %(pid)s"

#: glance/cmd/control.py:106
#, python-format
msgid "Removing stale pid file %s"
msgstr "Удаление устаревшего файла pid %s"

#: glance/cmd/control.py:115
msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr ""
"Не удается увеличить предельное значение для дескриптора файлов. Запущен без "
"прав доступа root?"

#: glance/cmd/control.py:164
#, python-format
msgid "%(verb)sing %(serv)s with %(conf)s"
msgstr "%(verb)s %(serv)s с %(conf)s"

#: glance/cmd/control.py:161
#, python-format
msgid "%(verb)sing %(serv)s"
msgstr "%(verb)s на %(serv)s"

#: glance/cmd/control.py:176
#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr "не удается запустить %(serv)s. Ошибка: %(e)s"

#: glance/cmd/control.py:206
#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr "%(serv)s (pid %(pid)s) работает..."

#: glance/cmd/control.py:209
#, python-format
msgid "%s is stopped"
msgstr "%s остановлен"

#: glance/cmd/control.py:225
#, python-format
msgid ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""
"Не удается создать файл pid %(pid)s.  Запущен без прав доступа root?\n"
"Возврат к файлу temp, для завершения работы службы %(service)s:\n"
"  остановить %(file)s %(server)s - pid-файл %(fb)s"

#: glance/cmd/control.py:246
#, python-format
msgid "Reload of %(serv)s not supported"
msgstr "Перезагрузка %(serv)s не поддерживается"

#: glance/cmd/control.py:254
#, python-format
msgid "Server %(serv)s is stopped"
msgstr "Сервер %(serv)s остановлен"

#: glance/cmd/control.py:259
#, python-format
msgid "Reloading %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "Перезагрузка %(serv)s (pid %(pid)s) с сигналом (%(sig)s)"

#: glance/cmd/control.py:259
#, python-format
msgid "Process %d not running"
msgstr "Процесс %d не выполняется"

#: glance/cmd/control.py:255
#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr "Остановка %(serv)s (pid %(pid)s) с сигналом (%(sig)s)"

#: glance/cmd/control.py:266
#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr ""
"Система ожидала завершения pid %(pid)s (%(file)s) в течение 15 секунд; "
"освобождение"

#: glance/cmd/control.py:269
#, python-format
msgid "%s is already stopped"
msgstr "%s уже остановлен"

#: glance/cmd/control.py:372
#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr "Повторное порождение подавлено, поскольку %(serv)s был %(rsn)s."

#: glance/cmd/manage.py:163
#, python-format
msgid "Invalid int value for age_in_days: %(age_in_days)s"
msgstr ""

#: glance/cmd/manage.py:169
#, python-format
msgid "Invalid int value for max_rows: %(max_rows)s"
msgstr ""

#: glance/cmd/manage.py:173
msgid "Must supply a positive, non-zero value for age."
msgstr ""
"В качестве возраста необходимо указать положительное число, не равное 0."

#: glance/cmd/manage.py:175
msgid "Maximal age is count of days since epoch."
msgstr "Максимальный возраст - число дней с начала эпохи."

#: glance/cmd/manage.py:177
msgid "Minimal rows limit is 1."
msgstr "Минимальное число строк равно 1."

#: glance/cmd/manage.py:330
msgid "Available categories:"
msgstr "Доступные категории:"

#: glance/cmd/manage.py:332
#, python-format
msgid "\t%s"
msgstr "\t%s"

#: glance/cmd/replicator.py:55
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did not "
"find it. This indicates that we do not have permissions to see all the "
"images on the slave server."
msgstr ""
"Образ %s уже присутствует на подчиненном сервере, но наша проверка его не "
"обнаружила. Это означает, что у нас нет прав на просмотр всех образов на "
"подчиненном сервере."

#: glance/cmd/replicator.py:282 glance/cmd/replicator.py:319
#: glance/cmd/replicator.py:404 glance/cmd/replicator.py:483
#: glance/cmd/replicator.py:560
msgid "Too few arguments."
msgstr "Недостаточно аргументов."

#: glance/cmd/replicator.py:303
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr "Общий размер составляет %(size)d байт по %(img_count)d образам"

#: glance/cmd/replicator.py:717
#, python-format
msgid "Unknown command: %s"
msgstr "Неизвестная команда: %s"

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr "Непредвиденный ответ: %s"

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr "Неизвестная стратегия идентификации: '%s'"

#: glance/common/client.py:240
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert, "
"however you have failed to supply either a key_file parameter or set the "
"GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""
"Вы выбрали применение SSL в соединении и предоставили сертификат, однако вам "
"не удалось ни предоставить параметр key_file, ни задать переменную среды "
"GLANCE_CLIENT_KEY_FILE"

#: glance/common/client.py:248
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the "
"GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""
"Вы выбрали применение SSL в соединении и предоставили ключ, однако вам не "
"удалось ни предоставить параметр cert_file, ни задать переменную среды "
"GLANCE_CLIENT_CERT_FILE"

#: glance/common/client.py:257
#, python-format
msgid "The key file you specified %s does not exist"
msgstr "Указанный файл ключа %s не существует"

#: glance/common/client.py:264
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr "Указанный файл сертификата %s не существует"

#: glance/common/client.py:271
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr "Указанный файл CA %s не существует"

#: glance/common/client.py:410
#, python-format
msgid "Constructed URL: %s"
msgstr "Сформированный URL: %s"

#: glance/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the service "
"name removed. For example, if your paste section name is [pipeline:glance-"
"api-keystone] use the value \"keystone\""
msgstr ""
"Неполное имя конвейера в файле вставляемой конфигурации, из которого удалено "
"имя службы. Например, если имя вставляемого раздела - [pipeline:glance-api-"
"keystone], то используется значение \"keystone\""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr "Имя файла вставляемой конфигурации."

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr "Поддерживаемые значения атрибута образа 'container_format'"

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr "Поддерживаемые значения атрибута образа 'disk_format'"

#: glance/common/config.py:60
msgid ""
"Time in hours for which a task lives after, either succeeding or failing"
msgstr ""
"Время (ч) существования задачи после успешного выполнения или завершения с "
"ошибкой"

#: glance/common/config.py:67
msgid "Specifies which task executor to be used to run the task scripts."
msgstr ""
"Указывает, чтобы применяемый исполнитель задачи выполнял сценарии задачи."

#: glance/common/config.py:70
msgid ""
"Work dir for asynchronous task operations. The directory set here will be "
"used to operate over images - normally before they are imported in the "
"destination store. When providing work dir, make sure enough space is "
"provided for concurrent tasks to run efficiently without running out of "
"space. A rough estimation can be done by multiplying the number of "
"`max_workers` - or the N of workers running - by an average image size (e.g "
"500MB). The image size estimation should be done based on the average size "
"in your deployment. Note that depending on the tasks running you may need to "
"multiply this number by some factor depending on what the task does. For "
"example, you may want to double the available size if image conversion is "
"enabled. All this being said, remember these are just estimations and you "
"should do them based on the worst case scenario and be prepared to act in "
"case they were wrong."
msgstr ""
"Рабочий каталог для операций асинхронных задач. Указанный здесь каталог "
"будет использоваться для образов (обычно перед их импортом в целевое "
"хранилище). Указывая рабочий каталог, убедитесь, что в нем достаточно места "
"для эффективного выполнения параллельных задач. В качестве грубой оценки "
"можно умножить значение max_workers (или число работающих исполнителей) на "
"средний размер образа (например, 500 МБ). Оценка размера образа должна "
"производиться на основе среднего размера в развертывании. Примечание: в "
"зависимости от выполняемых задач может потребоваться умножить это значение "
"на некоторый коэффициент, который зависит от того, что задачи делают. "
"Например, может потребоваться удвоить доступный размер, если включено "
"преобразование образов. Помните, что это лишь приблизительная оценка, ее "
"следует выполнять, исходя из наихудшего сценария, и надо быть готовым к "
"тому, что ее результаты могут оказаться неверными."

#: glance/common/config.py:67
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""
"Разрешить ли пользователям указывать свойства образа сверх тех, что "
"предоставляет схема образа"

#: glance/common/config.py:70
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""
"Максимальное число участников образа. Отрицательное значение определяется "
"как отсутствие ограничений."

#: glance/common/config.py:73
msgid ""
"Maximum number of properties allowed on an image. Negative values evaluate "
"to unlimited."
msgstr ""
"Максимальное число свойств, разрешенных в образе. Отрицательное значение "
"определяется как неограниченное число."

#: glance/common/config.py:76
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""
"Максимальное число тегов, разрешенных в образе. Отрицательное значение "
"определяется как отсутствие ограничений."

#: glance/common/config.py:79
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""
"Максимальное число расположений, разрешенных в образе. Отрицательное "
"значение определяется как неограниченное число."

#: glance/common/config.py:82
msgid "Python module path of data access API"
msgstr "Путь модуля Python к API доступа к данным"

#: glance/common/config.py:84
msgid ""
"Default value for the number of items returned by a request if not specified "
"explicitly in the request"
msgstr ""
"Количество элементов, по умолчанию возвращаемое запросом, если это значение "
"не указано явно в запросе"

#: glance/common/config.py:87
msgid ""
"Maximum permissible number of items that could be returned by a request"
msgstr ""
"Максимальное разрешенное количество элементов, которое может быть возвращено "
"запросом"

#: glance/common/config.py:90
msgid ""
"Whether to include the backend image storage location in image properties. "
"Revealing storage location can be a security risk, so use this setting with "
"caution!"
msgstr ""
"Включать ли расположение хранилища образов в базовой системе в свойства "
"образов. Раскрытие местонахождения хранилища может представлять угрозу "
"защите, поэтому будьте осторожны при использовании этого параметра!"

#: glance/common/config.py:119
msgid ""
"Whether to include the backend image locations in image properties. For "
"example, if using the file system store a URL of \"file:///path/to/image\" "
"will be returned to the user in the 'direct_url' meta-data field. Revealing "
"storage location can be a security risk, so use this setting with caution! "
"Setting this to true overrides the show_image_direct_url option."
msgstr ""
"Указывает, включать ли расположения образов в базовой системе в свойства "
"образов. Например, если используется хранилище в файловой системе, URL "
"\"file:///путь/к/образу\" будет возвращаться пользователю в поле метаданных "
"direct_url. Раскрытие информации о расположении хранилища может представлять "
"угрозу защите, поэтому данный параметр следует использовать с осторожностью! "
"Если параметр задан равным true, то он переопределяет show_image_direct_url."

#: glance/common/config.py:131
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to 1099511627776 "
"bytes (1 TB).WARNING: this value should only be increased after careful "
"consideration and must be set to a value under 8 EB (9223372036854775808)."
msgstr ""
"Максимальный размер образа, который может быть загружен пользователем, "
"1099511627776 байт (1 ТБ). ПРЕДУПРЕЖДЕНИЕ: это значение следует увеличивать "
"только после тщательной оценки; оно не может превышать 8 ЭБ "
"(9223372036854775808)."

#: glance/common/config.py:137
msgid ""
"Set a system wide quota for every user. This value is the total capacity "
"that a user can use across all storage systems. A value of 0 means "
"unlimited.Optional unit can be specified for the value. Accepted units are "
"B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, GigaBytes and "
"TeraBytes respectively. If no unit is specified then Bytes is assumed. Note "
"that there should not be any space between value and unit and units are case "
"sensitive."
msgstr ""
"Установить общесистемную квоту для каждого пользователя. Это общий объем "
"памяти, доступной пользователю во всех системах хранения данных. 0 означает "
"отсутствие ограничения. Дополнительно можно задать единицу измерения. "
"Допустимые единицы измерения: Б (байт), КБ (килобайт), МБ (мегабайт), ГБ "
"(гигабайт) и ТБ (терабайт). Единица измерения по умолчанию - Б (байт). "
"Учтите, что единица измерения указывается без пробела и с учетом регистра."

#: glance/common/config.py:107
msgid "Deploy the v1 OpenStack Images API."
msgstr "Разверните API образов OpenStack версии 1."

#: glance/common/config.py:109
msgid "Deploy the v2 OpenStack Images API."
msgstr "Разверните API образов OpenStack версии 2."

#: glance/common/config.py:111
msgid "Deploy the v1 OpenStack Registry API."
msgstr "Разверните API реестров OpenStack версии 1."

#: glance/common/config.py:113
msgid "Deploy the v2 OpenStack Registry API."
msgstr "Разверните API реестров OpenStack версии 2."

#: glance/common/config.py:115
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""
"Имя хоста или IP-адрес процесса pydev, принимающего соединения отладки"

#: glance/common/config.py:118
msgid "The port on which a pydev process is listening for connections."
msgstr "Порт, через который процесс pydev принимает соединения."

#: glance/common/config.py:161
msgid ""
"AES key for encrypting store 'location' metadata. This includes, if used, "
"Swift or S3 credentials. Should be set to a random string of length 16, 24 "
"or 32 bytes"
msgstr ""
"Ключ AES для шифрования метаданных location хранилища. Если используется, то "
"включает идентификационные данные Swift или S3. Значение должно быть "
"случайной строкой длиной 16, 24 или 32 байт"

#: glance/common/config.py:166
msgid ""
"Digest algorithm which will be used for digital signature. Use the command "
"\"openssl list-message-digest-algorithms\" to get the available algorithms "
"supported by the version of OpenSSL on the platform. Examples are \"sha1\", "
"\"sha256\", \"sha512\", etc."
msgstr ""
"Алгоритм дайджеста, применяемый для цифровой подписи. Команда \"openssl list-"
"message-digest-algorithms\" выводит алгоритмы, поддерживаемые версией "
"OpenSSL на данной платформе. Примеры: \"sha1\", \"sha256\", \"sha512\" и т. "
"д."

#: glance/common/config.py:179
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr "Не удается найти/вставить файл конфигурации для %s."

#: glance/common/config.py:218
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"Невозможно загрузить %(app_name)s из файла конфигурации %(conf_file)s.\n"
"Ошибка: %(e)r"

#: glance/common/exception.py:38
msgid "An unknown exception occurred"
msgstr "Возникла неизвестная исключительная ситуация"

#: glance/common/exception.py:63
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "Отсутствуют обязательные идентификационные данные: %(required)s"

#: glance/common/exception.py:67
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"Неправильная стратегия идентификации, ожидалось \"%(expected)s\", но "
"получено \"%(received)s\""

#: glance/common/exception.py:72
msgid "An object with the specified identifier was not found."
msgstr "Объект с указанным идентификатором не найден."

#: glance/common/exception.py:80
msgid "The Store URI was malformed."
msgstr "URI хранилища неправильно сформирован."

#: glance/common/exception.py:84
msgid "An object with the same identifier already exists."
msgstr "Объект с таким идентификатором уже существует."

#: glance/common/exception.py:88
msgid "An object with the same identifier is currently being operated on."
msgstr "Объект с таким идентификатором занят в текущей операции."

#: glance/common/exception.py:97
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""
"Объем данных %(image_size)s превышает допустимый максимум. Остаток: "
"%(remaining)s байт."

#: glance/common/exception.py:106
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""
"Ошибка соединения или неправильный запрос к службе идентификации с URL "
"%(url)s."

#: glance/common/exception.py:110
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "Служба идентификации с URL %(url)s не найдена."

#: glance/common/exception.py:114
msgid "Authorization failed."
msgstr "Доступ не предоставлен."

#: glance/common/exception.py:118
msgid "You are not authenticated."
msgstr "Вы не прошли идентификацию."

#: glance/common/exception.py:112
#, python-format
msgid "Image upload problem: %s"
msgstr "Неполадка при передаче образа: %s"

#: glance/common/exception.py:122 glance/common/exception.py:126
msgid "You are not authorized to complete this action."
msgstr "У вас нет прав на выполнение этого действия."

#: glance/common/exception.py:130
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr "Образ %(image_id)s защищен и не может быть удален."

#: glance/common/exception.py:128
#, python-format
msgid ""
"Metadata definition namespace %(namespace)s is protected and cannot be "
"deleted."
msgstr ""
"Пространство имен %(namespace)s определения метаданных защищено и не может "
"быть удален."

#: glance/common/exception.py:133
#, python-format
msgid ""
"Metadata definition property %(property_name)s is protected and cannot be "
"deleted."
msgstr ""
"Свойство %(property_name)s определения метаданных защищено и не может быть "
"удалено."

#: glance/common/exception.py:138
#, python-format
msgid ""
"Metadata definition object %(object_name)s is protected and cannot be "
"deleted."
msgstr ""
"Объект %(object_name)s определения метаданных защищен и не может быть удален."

#: glance/common/exception.py:143
#, python-format
msgid ""
"Metadata definition resource-type-association %(resource_type)s is protected "
"and cannot be deleted."
msgstr ""
"Связь типа ресурса %(resource_type)s определения метаданных защищена и не "
"может быть удалена."

#: glance/common/exception.py:148
#, python-format
msgid ""
"Metadata definition resource-type %(resource_type_name)s is a seeded-system "
"type and cannot be deleted."
msgstr ""
"Тип ресурса %(resource_type_name)s определения метаданных являетсясистемным "
"типом и не может быть удален."

#: glance/common/exception.py:153
#, python-format
msgid ""
"Metadata definition tag %(tag_name)s is protected and cannot be deleted."
msgstr ""
"Тег %(tag_name)s определения метаданных защищен и не может быть удален."

#: glance/common/exception.py:134
msgid "Data supplied was not valid."
msgstr "Предоставленные данные недопустимы."

#: glance/common/exception.py:138
#: glance/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr "Задан недопустимый ключ сортировки."

#: glance/common/exception.py:166
msgid "Sort direction supplied was not valid."
msgstr "Указано недопустимое направление сортировки."

#: glance/common/exception.py:142
msgid "Invalid configuration in property protection file."
msgstr "Недопустимая конфигурация в файле защиты свойств."

#: glance/common/exception.py:174
msgid "Invalid configuration in glance-swift conf file."
msgstr "Недопустимая конфигурация в файле конфигурации glance-swift."

#: glance/common/exception.py:178
msgid "Unable to filter using the specified operator."
msgstr "Не удается отфильтровать с использованием указанного оператора."

#: glance/common/exception.py:146
msgid "Unable to filter using the specified range."
msgstr "Отфильтровать согласно указанному диапазону невозможно."

#: glance/common/exception.py:186
#, python-format
msgid "Invalid value for option %(option)s: %(value)s"
msgstr "Недопустимое значение для опции %(option)s: %(value)s"

#: glance/common/exception.py:150
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "Атрибут '%(property)s' предназначен только для чтения."

#: glance/common/exception.py:154
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "Атрибут '%(property)s' зарезервирован."

#: glance/common/exception.py:158
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "Перенаправляется на %(uri)s для предоставления доступа."

#: glance/common/exception.py:162
msgid "There was an error connecting to a server"
msgstr "При подключении к серверу произошла ошибка"

#: glance/common/exception.py:166
msgid "There was an error configuring the client."
msgstr "При настройке клиента произошла ошибка."

#: glance/common/exception.py:170
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that you "
"have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"Запрос возвратил ошибку 302 - Множественный выбор. Как правило, это "
"означает, что вы не включили индикатор версии в URI запроса.\n"
"\n"
"Возвращенное тело запроса:\n"
"%(body)s"

#: glance/common/exception.py:176
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means "
"that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"Запрос возвратил ошибку 413 - Сущность запроса слишком велика. Как правило, "
"это означает, что нарушено ограничение на скорость или порог квоты.\n"
"\n"
"Тело ответа:\n"
"%(body)s"

#: glance/common/exception.py:227
msgid ""
"The request returned 503 Service Unavailable. This generally occurs on "
"service overload or other transient outage."
msgstr ""
"Запрос возвратил ошибку 503 - Служба недоступна. Как правило, это происходит "
"при перегруженности службы или другом временном сбое."

#: glance/common/exception.py:198
msgid "The request returned 500 Internal Server Error."
msgstr "Запрос возвратил ошибку 500 - Внутренняя ошибка сервера."

#: glance/common/exception.py:202
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"Запрос возвратил непредвиденное состояние: %(status)s.\n"
"\n"
"Тело ответа:\n"
"%(body)s"

#: glance/common/exception.py:207
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "Недопустимый тип содержимого: %(content_type)s"

#: glance/common/exception.py:211
#, python-format
msgid ""
"Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr "Реестр настроен неправильно на сервере API. Причина: %(reason)s"

#: glance/common/exception.py:221
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""
"Драйвер %(driver_name)s не удалось правильно настроить. Причина: %(reason)s"

#: glance/common/exception.py:243
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "Превышено максимальное количество перенаправлений (%(redirects)s)."

#: glance/common/exception.py:247
msgid "Received invalid HTTP redirect."
msgstr "Получено недопустимое перенаправление HTTP."

#: glance/common/exception.py:251
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr "Ответ от Keystone не содержит конечной точки Glance."

#: glance/common/exception.py:255
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally means "
"that a region is required and you have not supplied one."
msgstr ""
"Несколько соответствий службы 'image' для региона %(region)s. Обычно это "
"означает, что регион обязателен, но вы его не указали."

#: glance/common/exception.py:261
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "Создать исполнитель сервера не удалось: %(reason)s."

#: glance/common/exception.py:265
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "Не удалось загрузить схему: %(reason)s"

#: glance/common/exception.py:269
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""
"Предоставленный объект не соответствует схеме '%(schema)s': %(reason)s"

#: glance/common/exception.py:283
msgid "The provided image is too large."
msgstr "Предоставленный образ слишком велик."

#: glance/common/exception.py:293
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Превышено ограничение по числу разрешенных свойств образа. Указанное число: "
"%(attempted)s, максимальное число: %(maximum)s"

#: glance/common/exception.py:298
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. Attempted: "
"%(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Превышено ограничение по числу разрешенных тегов образа. Указанное число: "
"%(attempted)s, максимальное число: %(maximum)s"

#: glance/common/exception.py:303
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""
"Превышено ограничение по числу разрешенных расположений образа. Указанное "
"число: %(attempted)s, максимальное число: %(maximum)s"

#: glance/common/exception.py:317
msgid "System SIGHUP signal received."
msgstr "Получен системный сигнал SIGHUP."

#: glance/common/exception.py:308
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr ""
"В последнем вызове rpc возникла исключительная ситуация %(cls)s: %(val)s"

#: glance/common/exception.py:312
msgid "An unknown task exception occurred"
msgstr "Непредвиденная исключительная ситуация"

#: glance/common/exception.py:329
msgid "Task was not configured properly"
msgstr "Задача неправильно настроена"

#: glance/common/exception.py:333
#, python-format
msgid "Image with the given id %(image_id)s was not found"
msgstr "Не найден образ с заданным ИД %(image_id)s"

#: glance/common/exception.py:316
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr "Задача с указанным ИД %(task_id)s не найдена"

#: glance/common/exception.py:320
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr "Указано неподдерживаемое состояние задачи: %(status)s"

#: glance/common/exception.py:324
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr "Указан неподдерживаемый тип задачи: %(type)s"

#: glance/common/exception.py:328
#, python-format
msgid ""
"Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr "Изменять состояние %(cur_status)s на %(new_status)s не разрешается"

#: glance/common/exception.py:354
msgid "An import task exception occurred"
msgstr "Исключительная ситуация в задаче импорта"

#: glance/common/exception.py:333
#, python-format
msgid "The location %(location)s already exists"
msgstr "Расположение %(location)s уже существует"

#: glance/common/exception.py:341
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr "Неверное значение '%(value)s' параметра '%(param)s': %(extra_msg)s"

#: glance/common/exception.py:346
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""
"Изменять состояние %(cur_status)s образа на %(new_status)s не разрешается"

#: glance/common/exception.py:372
#, python-format
msgid "The metadata definition namespace=%(namespace_name)s already exists."
msgstr ""
"Пространство имен %(namespace_name)s определения метаданных уже существует."

#: glance/common/exception.py:377
#, python-format
msgid ""
"A metadata definition object with name=%(object_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"Объект определения метаданных с именем %(object_name)s уже существует в "
"пространстве имен %(namespace_name)s."

#: glance/common/exception.py:382
#, python-format
msgid ""
"A metadata definition property with name=%(property_name)s already exists in "
"namespace=%(namespace_name)s."
msgstr ""
"Свойство определения метаданных с именем %(property_name)s уже существует в "
"пространстве имен %(namespace_name)s."

#: glance/common/exception.py:387
#, python-format
msgid ""
"A metadata definition resource-type with name=%(resource_type_name)s already "
"exists."
msgstr ""
"Тип ресурса определения метаданных с именем %(resource_type_name)s уже "
"существует."

#: glance/common/exception.py:392
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s already exists."
msgstr ""
"Связь типа ресурса определения метаданных для типа "
"ресурса%(resource_type_name)s и пространства имен %(namespace_name)s уже "
"существует."

#: glance/common/exception.py:399
#, python-format
msgid ""
"A metadata tag with name=%(name)s already exists in "
"namespace=%(namespace_name)s. (Please note that metadata tag names are case "
"insensitive)."
msgstr ""

#: glance/common/exception.py:410
#, python-format
msgid ""
"The metadata definition %(record_type)s with name=%(record_name)s not "
"deleted. Other records still refer to it."
msgstr ""
"Определение метаданных %(record_type)s с именем %(record_name)s не удалено. "
"Другие записи все еще ссылаются на него."

#: glance/common/exception.py:416
#, python-format
msgid "Metadata definition namespace=%(namespace_name)s was not found."
msgstr ""

#: glance/common/exception.py:421
#, python-format
msgid ""
"The metadata definition object with name=%(object_name)s was not found in "
"namespace=%(namespace_name)s."
msgstr ""
"Объект определения метаданных с именем %(object_name)s не найден в "
"пространстве имен %(namespace_name)s."

#: glance/common/exception.py:427
#, python-format
msgid ""
"The metadata definition property with name=%(property_name)s was not found "
"in namespace=%(namespace_name)s."
msgstr ""
"Свойство определения метаданных с именем %(property_name)s не найдено в "
"пространстве имен %(namespace_name)s."

#: glance/common/exception.py:433
#, python-format
msgid ""
"The metadata definition resource-type with name=%(resource_type_name)s, was "
"not found."
msgstr ""
"Тип ресурса определения метаданных с именем %(resource_type_name)s не найден."

#: glance/common/exception.py:438
#, python-format
msgid ""
"The metadata definition resource-type association of resource-"
"type=%(resource_type_name)s to namespace=%(namespace_name)s, was not found."
msgstr ""
"Связь типа ресурса определения метаданных для типа "
"ресурса%(resource_type_name)s и пространства имен %(namespace_name)s не "
"найдена."

#: glance/common/exception.py:445
#, python-format
msgid ""
"The metadata definition tag with name=%(name)s was not found in "
"namespace=%(namespace_name)s."
msgstr ""
"Тег определения метаданных с именем %(name)s не найден в пространстве имен "
"%(namespace_name)s."

#: glance/common/exception.py:451
#, python-format
msgid "Unable to verify signature: %(reason)s"
msgstr "Не удалось проверить подпись: %(reason)s"

#: glance/common/exception.py:455
#, python-format
msgid "Version is invalid: %(reason)s"
msgstr "Недопустимая версия: %(reason)s"

#: glance/common/exception.py:459
msgid "Invalid property definition"
msgstr "Недопустимое определение свойства"

#: glance/common/exception.py:463
msgid "Invalid type definition"
msgstr "Недопустимое определение типа"

#: glance/common/exception.py:467
#, python-format
msgid "Property '%(name)s' may not have value '%(val)s': %(msg)s"
msgstr "Свойство '%(name)s' не может иметь значение '%(val)s': %(msg)s"

#: glance/common/exception.py:477
#, python-format
msgid "Artifact with id=%(id)s was not found"
msgstr "Артефакт с id=%(id)s не найден"

#: glance/common/exception.py:481
#, python-format
msgid "Artifact with id=%(id)s is not accessible"
msgstr "Артефакт с id=%(id)s не доступен"

#: glance/common/exception.py:485
msgid "Artifact with the specified type, name and version already exists"
msgstr "Артефакт с указанными типом, именем и версией уже существует"

#: glance/common/exception.py:490
#, python-format
msgid "Artifact cannot change state from %(source)s to %(target)s"
msgstr "Артефакт не может изменить состояние с %(source)s на %(target)s"

#: glance/common/exception.py:494
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the direct "
"dependency=%(dep)s"
msgstr ""
"Артефакт с указанными типом, именем и версией уже имеет прямую "
"зависимость=%(dep)s"

#: glance/common/exception.py:499
#, python-format
msgid ""
"Artifact with the specified type, name and version already has the "
"transitive dependency=%(dep)s"
msgstr ""
"Артефакт с указанными типом, именем и версией уже имеет транзитивную "
"зависимость=%(dep)s"

#: glance/common/exception.py:504
msgid "Artifact with a circular dependency can not be created"
msgstr "Нельзя создать артефакт с циклической зависимостью"

#: glance/common/exception.py:508
#, python-format
msgid "Operator %(op)s is not supported"
msgstr "Оператор %(op)s не поддерживается"

#: glance/common/exception.py:512
#, python-format
msgid "Show level %(shl)s is not supported in this operation"
msgstr "Уровень отображения %(shl)s не поддерживается в этой операции"

#: glance/common/exception.py:516
#, python-format
msgid "Property's %(prop)s value has not been found"
msgstr "Значение %(prop)s параметра не найдено"

#: glance/common/exception.py:520
#, python-format
msgid "Artifact has no property %(prop)s"
msgstr "Артефакт не имеет параметра %(prop)s"

#: glance/common/exception.py:524
#, python-format
msgid "Cannot use this parameter with the operator %(op)s"
msgstr "Невозможно использовать этот параметр с оператором %(op)s"

#: glance/common/exception.py:528
#, python-format
msgid "Cannot load artifact '%(name)s'"
msgstr "Невозможно загрузить артефакт '%(name)s'"

#: glance/common/exception.py:532
#, python-format
msgid "Plugin name '%(plugin)s' should match artifact typename '%(name)s'"
msgstr ""
"Имя модуля '%(plugin)s' должно соответствовать имени типа артефакта "
"'%(name)s'"

#: glance/common/exception.py:537
#, python-format
msgid "No plugin for '%(name)s' has been loaded"
msgstr "Модуль для '%(name)s' не загружен"

#: glance/common/exception.py:541
#, python-format
msgid ""
"Artifact type with name '%(name)s' and version '%(version)s' is not known"
msgstr ""
"Тип артефакта с именем '%(name)s' и версией '%(version)s' не известен"

#: glance/common/exception.py:546
#, python-format
msgid "Artifact state cannot be changed from %(curr)s to %(to)s"
msgstr "Состояние артефакта не может быть изменено с %(curr)s на %(to)s"

#: glance/common/exception.py:550
msgid "Invalid jsonpatch request"
msgstr "Неверный запрос jsonpatch"

#: glance/common/exception.py:554
#, python-format
msgid "The provided body %(body)s is invalid under given schema: %(schema)s"
msgstr "Указанное тело %(body)s неверно для данной схемы: %(schema)s"

#: glance/common/exception.py:559
#, python-format
msgid "The provided path '%(path)s' is invalid: %(explanation)s"
msgstr "Указанный путь '%(path)s' неверен: %(explanation)s"

#: glance/common/jsonpatchvalidator.py:103
msgid ""
"Json path should start with a '/', end with no '/', no 2 subsequent '/' are "
"allowed."
msgstr ""
"Путь Json должен начинаться с '/' и заканчиваться не на '/'. 2 "
"последовательных символа '/' не разрешены."

#: glance/common/jsonpatchvalidator.py:107
msgid ""
"Pointer contains '~' which is not part of a recognized escape sequence [~0, "
"~1]."
msgstr ""
"Указатель содержит символ '~', который не входит в состав распознанной "
"escape-последовательности [~0, ~1]."

#: glance/common/property_utils.py:31
msgid ""
"The location of the property protection file.This file contains the rules "
"for property protections and the roles/policies associated with it. If this "
"config value is not specified, by default, property protections won't be "
"enforced. If a value is specified and the file is not found, then the glance-"
"api service will not start."
msgstr ""
"Расположение файла защиты свойств. Этот файл содержит правила для защиты "
"свойств и роли/стратегии, с ними связанные. Если это значение конфигурации "
"не указано, то по умолчанию защита свойств выключена. Если значение указано, "
"но файл не найден, то служба не запустится glance-api."

#: glance/common/property_utils.py:40
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in "
"the property protection file."
msgstr ""
"Этот файл конфигурации указывает, будут ли \"roles\" или \"policies\" "
"использоваться в файле защиты свойств."

#: glance/common/property_utils.py:127
#, python-format
msgid ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."
msgstr ""
"Правило защиты свойств в операции %(operation)s для правила %(rule)s не "
"найдено. Пользователям ни в какой роли не будет разрешено выполнять эту "
"операцию."

#: glance/common/rpc.py:139
msgid "Request must be a list of commands"
msgstr "Запрос должен быть списком команд"

#: glance/common/rpc.py:144
#, python-format
msgid "Bad Command: %s"
msgstr "Неправильная команда: %s"

#: glance/common/rpc.py:151
#, python-format
msgid "Wrong command structure: %s"
msgstr "Неверная структура команды: %s"

#: glance/common/rpc.py:160
msgid "Command not found"
msgstr "Команда не найдена"

#: glance/common/semver_db.py:77
#, python-format
msgid "Version component is too large (%d max)"
msgstr "Компонент версии слишком большой (макс. %d)"

#: glance/common/semver_db.py:125
#, python-format
msgid "Prerelease numeric component is too large (%d characters max)"
msgstr ""
"Слишком большой числовой компонент перед выпуском (макс. %d символов)"

#: glance/common/signature_utils.py:138
#, python-format
msgid "Invalid signature key type: %s"
msgstr "Недопустимый тип ключа подписи: %s"

#: glance/common/signature_utils.py:161
#, python-format
msgid "Invalid mask_gen_algorithm: %s"
msgstr "Недопустимый mask_gen_algorithm: %s"

#: glance/common/signature_utils.py:174
#, python-format
msgid "Invalid pss_salt_length: %s"
msgstr "Недопустимый pss_salt_length: %s"

#: glance/common/signature_utils.py:261 glance/common/signature_utils.py:335
msgid ""
"Required image properties for signature verification do not exist. Cannot "
"verify signature."
msgstr ""
"Отсутствуют свойства образа, необходимые для проверки подписи. Проверка "
"подписи невозможна."

#: glance/common/signature_utils.py:285 glance/common/signature_utils.py:361
msgid ""
"Unable to verify signature since the algorithm is unsupported on this system"
msgstr ""
"Не удается проверить подпись, так как алгоритм не поддерживается в системе"

#: glance/common/signature_utils.py:294
msgid "Error occurred while creating the verifier"
msgstr "Ошибка при создании агента проверки"

#: glance/common/signature_utils.py:373
msgid "Signature verification failed."
msgstr "Проверка подписи не выполнена."

#: glance/common/signature_utils.py:378
msgid "Error occurred while verifying the signature"
msgstr "Ошибка при проверке подписи"

#: glance/common/signature_utils.py:394
msgid "The signature data was not properly encoded using base64"
msgstr "Данные подписи в кодировке base64 содержат ошибку"

#: glance/common/signature_utils.py:410
#, python-format
msgid "Invalid signature hash method: %s"
msgstr "Недопустимый метод хэша подписи: %s"

#: glance/common/signature_utils.py:436
#, python-format
msgid "Invalid public key type for signature key type: %s"
msgstr "Недопустимый тип открытого ключа для данного типа ключа подписи: %s"

#: glance/common/signature_utils.py:467
#, python-format
msgid "Unable to retrieve certificate with ID: %s"
msgstr "Не удается получить сертификат с ИД: %s"

#: glance/common/signature_utils.py:473
#, python-format
msgid "Invalid certificate format: %s"
msgstr "Недопустимый формат сертификата: %s"

#: glance/common/signature_utils.py:483
#, python-format
msgid "Certificate format not supported: %s"
msgstr "Формат сертификата не поддерживается: %s"

#: glance/common/signature_utils.py:505
#, python-format
msgid "Certificate is not valid before: %s UTC"
msgstr "Сертификат будет действовать, начиная с: %s UTC"

#: glance/common/signature_utils.py:510
#, python-format
msgid "Certificate is not valid after: %s UTC"
msgstr "Сертификат не действует после: %s UTC"

#: glance/common/swift_store_utils.py:25
msgid ""
"The reference to the default swift account/backing store parameters to use "
"for adding new images."
msgstr ""
"Ссылка на параметры учетных записей и резервного хранения swift по умолчанию "
"для использования при добавлении новых образов."

#: glance/common/swift_store_utils.py:28
msgid ""
"The address where the Swift authentication service is listening.(deprecated)"
msgstr "Адрес, по которому принимает служба идентификации Swift. (Устарело)"

#: glance/common/swift_store_utils.py:31
msgid ""
"The user to authenticate against the Swift authentication service "
"(deprecated)"
msgstr "Пользователь для идентификации службой Swift (устарело)"

#: glance/common/swift_store_utils.py:34
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service. (deprecated)"
msgstr ""
"Идентификационный ключ для идентификации пользователя службой Swift. "
"(Устарело)"

#: glance/common/swift_store_utils.py:37
msgid "The config file that has the swift account(s)configs."
msgstr "Файл конфигурации с учетными записями swift."

#: glance/common/utils.py:251
#, python-format
msgid "Bad header: %(header_name)s"
msgstr "Неправильный заголовок: %(header_name)s"

#: glance/common/utils.py:261
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr "Не удается преобразовать %(key)s '%(value)s' в целое число."

#: glance/common/utils.py:313
msgid "Cannot be a negative value."
msgstr "Не может быть отрицательным значением."

#: glance/common/utils.py:509
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it.  Error: %(ioe)s"
msgstr ""
"Ошибка в %(error_key_name)s %(error_filename)s.  Проверьте. Ошибка: %(ioe)s"

#: glance/common/utils.py:516
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  Please "
"verify it. OpenSSL error: %(ce)s"
msgstr ""
"Ошибка в %(error_key_name)s %(error_filename)s.  Проверьте. Ошибка OpenSSL: "
"%(ce)s"

#: glance/common/utils.py:530
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""
"Неправильная пара ключей. Убедитесь, что сертификат %(cert_file)s и ключ "
"%(key_file)sсоответствуют друг другу. Ошибка OpenSSL: %(ce)s"

#: glance/common/utils.py:480
#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr "Хост и порт \"%s\" недопустимы."

#: glance/common/utils.py:483
#, python-format
msgid "Port \"%s\" is not valid."
msgstr "Порт \"%s\" недопустим."

#: glance/common/utils.py:492
#, python-format
msgid "Host \"%s\" is not valid."
msgstr "Хост \"%s\" недопустим."

#: glance/common/utils.py:495
#, python-format
msgid ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in brackets "
"separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""
"%s Укажите пару host:port, где host - это адрес IPv4, адрес IPv6, имя хоста "
"или FQDN. При указании адреса IPv6 заключите его в квадратные скобки "
"отдельно от порта (например, \"[fe80::a:b:c]:9876\")."

#: glance/common/utils.py:530
msgid "Property names can't contain 4 byte unicode."
msgstr ""
"Имена свойств не могут содержать символы в кодировке 4-байтового unicode."

#: glance/common/utils.py:533
#, python-format
msgid "%s can't contain 4 byte unicode characters."
msgstr "%s не может содержать символы в кодировке 4-байтового unicode."

#: glance/common/utils.py:542
msgid "Param values can't contain 4 byte unicode."
msgstr ""
"Значения параметров не могут содержать символы в кодировке 4-байтового "
"unicode."

#: glance/common/utils.py:562
#, python-format
msgid "Value %(value)d out of range, must not exceed %(max)d"
msgstr ""
"Значение %(value)d выходит за пределы диапазона, оно не должно превышать "
"%(max)d"

#: glance/common/utils.py:570
#, python-format
msgid "'%(param)s' value out of range, must not exceed %(max)d"
msgstr ""
"Значение %(param)s выходит за пределы диапазона, оно не должно превышать "
"%(max)d"

#: glance/common/utils.py:627
#, python-format
msgid ""
"Invalid filter value %s. There is no comma before opening quotation mark."
msgstr ""
"Недопустимое значение фильтра  %s. Нет запятой перед открывающей кавычкой."

#: glance/common/utils.py:632
#, python-format
msgid ""
"Invalid filter value %s. There is no comma after closing quotation mark."
msgstr ""
"Недопустимое значение фильтра  %s. Нет запятой после закрывающей кавычки."

#: glance/common/utils.py:637
#, python-format
msgid "Invalid filter value %s. The quote is not closed."
msgstr "Недопустимое значение фильтра  %s. Нет закрывающей кавычки."

#: glance/common/utils.py:687
msgid "Unable to filter on a unknown operator."
msgstr "Не удается отфильтровать с использованием неизвестного оператора."

#: glance/common/wsgi.py:53
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""
"Адрес привязки сервера. Полезен при выборе конкретного сетевого интерфейса."

#: glance/common/wsgi.py:56
msgid "The port on which the server will listen."
msgstr "Порт, через который сервер будет вести прием."

#: glance/common/wsgi.py:61
msgid ""
"The backlog value that will be used when creating the TCP listener socket."
msgstr ""
"Базовое значение, которое будет использовано при создании приемного сокета "
"TCP."

#: glance/common/wsgi.py:64
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in seconds "
"that the connection must be idle before TCP starts sending keepalive probes."
msgstr ""
"Значение для опции сокета TCP_KEEPIDLE. Это время в секундах, в течение "
"которого соединение должно простаивать, прежде чем TCP начнет отправлять "
"тесты keepalive."

#: glance/common/wsgi.py:67
msgid "CA certificate file to use to verify connecting clients."
msgstr "Файл сертификата CA для проверки подключающихся клиентов."

#: glance/common/wsgi.py:69
msgid "Certificate file to use when starting API server securely."
msgstr ""
"Файл сертификата для использования при защищенном запуске сервера API."

#: glance/common/wsgi.py:71
msgid "Private key file to use when starting API server securely."
msgstr ""
"Файл личного ключа для использования при защищенном запуске сервера API."

#: glance/common/wsgi.py:83
msgid ""
"The number of child process workers that will be created to service "
"requests. The default will be equal to the number of CPUs available."
msgstr ""
"Количество исполнителей дочернего процесса, которые будут созданы для "
"обслуживания запросов. Значение по умолчанию будет равно количеству "
"доступных CPU."

#: glance/common/wsgi.py:85
msgid ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated by "
"the Keystone v3 API with big service catalogs"
msgstr ""
"Максимальный размер строки заголовка сообщений. Возможно, max_header_line "
"потребуется увеличить при использовании больших маркеров (как правило, "
"созданных API Keystone версии 3 API с большими каталогами)"

#: glance/common/wsgi.py:92
msgid ""
"If False, server will return the header \"Connection: close\", If True, "
"server will return \"Connection: Keep-Alive\" in its responses. In order to "
"close the client socket connection explicitly after the response is sent and "
"read successfully by the client, you simply have to set this option to False "
"when you create a wsgi server."
msgstr ""
"Если False, сервер возвращает заголовок \"Connection: close\". Если True, "
"сервер возвращает \"Connection: Keep-Alive\" в своих ответах. Для того чтобы "
"явно закрыть соединение сокета клиента, после того как ответ отправлен и "
"успешно прочитан клиентом, необходимо просто присвоить этому параметру "
"значение False при создании сервера wsgi."

#: glance/common/wsgi.py:101
msgid ""
"Timeout for client connections' socket operations. If an incoming connection "
"is idle for this number of seconds it will be closed. A value of '0' means "
"wait forever."
msgstr ""
"Тайм-аут операций сокета соединений клиента. Если входящее соединение "
"простаивает в течение этого времени, оно будет закрыто. Значение '0' "
"означает неограниченное ожидание."

#: glance/common/wsgi.py:109
msgid ""
"The HTTP header used to determine the scheme for the original request, even "
"if it was removed by an SSL terminating proxy. Typical value is "
"\"HTTP_X_FORWARDED_PROTO\"."
msgstr ""
"Заголовок HTTP используемый для определения схемы исходного запроса, даже "
"если он был удалён терминирующим SSL прокси-сервером. Типичное значение "
"\"HTTP_X_FORWARDED_PROTO\"."

#: glance/common/wsgi.py:117
msgid "If False fully disable profiling feature."
msgstr "В случае False полностью отключить функцию профилирования."

#: glance/common/wsgi.py:119
msgid "If False doesn't trace SQL requests."
msgstr "В случае False не трассировать запросы SQL."

#: glance/common/wsgi.py:121
msgid ""
"Secret key to use to sign Glance API and Glance Registry services tracing "
"messages."
msgstr ""
"Секретный ключ для подписывания сообщений трассировки служб Glance API и "
"реестра Glance."

#: glance/common/wsgi.py:131
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"При работе сервера в режиме SSL необходимо указать cert_file и key_file в "
"файле конфигурации"

#: glance/common/wsgi.py:169
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""
"Не удалось выполнить связывание с %(host)s:%(port)s в течение 30 секунд"

#: glance/common/wsgi.py:233
msgid "eventlet 'poll' nor 'selects' hubs are available on this platform"
msgstr ""
"Для этой платформы отсутствуют центры обработки событий poll и selects "
"библиотеки eventlet"

#: glance/common/wsgi.py:786
#, python-format
msgid "Malformed Content-Range header: %s"
msgstr "Неправильный формат заголовка Content-Range: %s"

#: glance/common/wsgi.py:819
msgid "Unexpected body type. Expected list/dict."
msgstr "Непредвиденный тип тела. Ожидался список или словарь."

#: glance/common/wsgi.py:552
msgid "Malformed JSON in request body."
msgstr "Неправильно сформированный JSON в теле запроса."

#: glance/common/wsgi.py:912
msgid "A body is not expected with this request."
msgstr "В этом запросе не должно быть тела."

#: glance/common/wsgi.py:924
msgid ""
"Error decoding your request. Either the URL or the request body contained "
"characters that could not be decoded by Glance"
msgstr ""
"Ошибка при декодировании запроса. URL или тело запроса содержат символы, "
"которые Glance не способен декодировать"

#: glance/common/glare/declarative.py:59
msgid "Not a valid value type"
msgstr "Недопустимый тип значения"

#: glance/common/glare/declarative.py:92
msgid "Default value is invalid"
msgstr "Неверное значение по умолчанию"

#: glance/common/glare/declarative.py:106
#: glance/common/glare/declarative.py:712
msgid "Value is required"
msgstr "Значение является обязательным"

#: glance/common/glare/declarative.py:129
msgid "Invalid item type specification"
msgstr "Недопустимая спецификация типа элемента"

#: glance/common/glare/declarative.py:132
msgid "List definitions may hot have defaults"
msgstr "Определения списков не могут иметь значений по умолчанию"

#: glance/common/glare/declarative.py:147
msgid "Cannot specify 'min_size' explicitly"
msgstr "Невозможно указать 'min_size' явно"

#: glance/common/glare/declarative.py:152
msgid "Cannot specify 'max_size' explicitly"
msgstr "Невозможно указать 'max_size' явно"

#: glance/common/glare/declarative.py:177
msgid "List size is less than minimum"
msgstr "Размер списка меньше минимального"

#: glance/common/glare/declarative.py:186
msgid "List size is greater than maximum"
msgstr "Размер списка больше максимального"

#: glance/common/glare/declarative.py:201
msgid "Items have to be unique"
msgstr "Элементы должны быть уникальными"

#: glance/common/glare/declarative.py:249
msgid "Invalid dict property type specification"
msgstr "Недопустимая спецификация типа параметра dict"

#: glance/common/glare/declarative.py:255
msgid "Invalid dict property type"
msgstr "Неверный тип параметра dict"

#: glance/common/glare/declarative.py:269
msgid "Dictionary contains unexpected key(s)"
msgstr "Словарь содержит неожиданные ключи"

#: glance/common/glare/declarative.py:285
msgid "Dictionary size is less than minimum"
msgstr "Размер словаря меньше минимального"

#: glance/common/glare/declarative.py:295
msgid "Dictionary size is greater than maximum"
msgstr "Размер словаря больше максимального"

#: glance/common/glare/declarative.py:362
msgid "Custom validators list should contain tuples '(function, message)'"
msgstr ""
"Список пользовательских агентов проверки должен содержать кортежи "
"'(function, message)'"

#: glance/common/glare/declarative.py:379
#, python-format
msgid "Allowed values %s are invalid under given validators"
msgstr "Разрешенные значения %s недопустимы для данных агентов проверки"

#: glance/common/glare/declarative.py:386
msgid "Is not allowed value"
msgstr "Не является разрешенным значением"

#: glance/common/glare/declarative.py:404
msgid "Dependency relations cannot be mutable"
msgstr "Отношения зависимости не могут быть изменяемыми"

#: glance/common/glare/declarative.py:463
msgid "Attempt to set readonly property"
msgstr "Произведена попытка установить свойство, доступное только для чтения"

#: glance/common/glare/declarative.py:471
msgid "Attempt to set value of immutable property"
msgstr "Произведена попытка установить значение неизменяемого свойства"

#: glance/common/glare/declarative.py:557
msgid "Type version has to be a valid semver string"
msgstr "Версия типа должна быть допустимой строкой semver"

#: glance/common/glare/declarative.py:565
#, python-format
msgid "%(attribute)s is required"
msgstr "%(attribute)s является обязательным"

#: glance/common/glare/declarative.py:570
#, python-format
msgid "%(attribute)s have to be string"
msgstr "%(attribute)s должен быть строкой"

#: glance/common/glare/declarative.py:573
#, python-format
msgid "%(attribute)s may not be longer than %(length)i"
msgstr "%(attribute)s не может быть длиннее %(length)i"

#: glance/common/glare/declarative.py:577
#, python-format
msgid "%(attribute)s may not be shorter than %(length)i"
msgstr "%(attribute)s не может быть короче %(length)i"

#: glance/common/glare/declarative.py:581
#, python-format
msgid "%(attribute)s should match pattern %(pattern)s"
msgstr "%(attribute)s должен соответствовать шаблону %(pattern)s"

#: glance/common/glare/declarative.py:625
msgid "Cannot declare artifact property with reserved name 'metadata'"
msgstr ""
"Невозможно объявить свойство артефакта с зарезервированным именем 'metadata'"

#: glance/common/glare/declarative.py:654
msgid "Unable to modify collection in immutable or readonly property"
msgstr ""
"Невозможно изменить набор в неизменяемом или доступном только для чтения "
"параметре"

#: glance/common/glare/definitions.py:71
msgid "Max string length may not exceed 255 characters"
msgstr "Максимальная длина строки не может превышать 255 символов"

#: glance/common/glare/definitions.py:74
msgid "Length  is greater than maximum"
msgstr "Длина больше максимальной"

#: glance/common/glare/definitions.py:85
msgid "Min string length may not be negative"
msgstr "Минимальная длина строки не может быть отрицательной"

#: glance/common/glare/definitions.py:89
msgid "Length is less than minimum"
msgstr "Длина меньше минимальной"

#: glance/common/glare/definitions.py:101
msgid "Does not match pattern"
msgstr "Не соответствует шаблону"

#: glance/common/glare/definitions.py:158
#: glance/common/glare/definitions.py:210
#: glance/common/glare/definitions.py:260
msgid "Value is less than minimum"
msgstr "Значение меньше минимального"

#: glance/common/glare/definitions.py:169
#: glance/common/glare/definitions.py:221
#: glance/common/glare/definitions.py:271
msgid "Value is greater than maximum"
msgstr "Значение больше максимального"

#: glance/common/glare/definitions.py:312
msgid "Array property can't have item_type=Array"
msgstr "Свойство массива не может иметь item_type=Array"

#: glance/common/glare/definitions.py:384
msgid "Unable to specify artifact type explicitly"
msgstr "Невозможно указать тип артефакта явно"

#: glance/common/glare/definitions.py:387
msgid "Unable to specify artifact type version explicitly"
msgstr "Невозможно указать версию типа артефакта явно"

#: glance/common/glare/definitions.py:426
msgid "Unable to specify version if multiple types are possible"
msgstr "Невозможно указать версию, если возможно несколько типов"

#: glance/common/glare/definitions.py:441
msgid "Invalid referenced type"
msgstr "Указан неверный тип"

#: glance/common/glare/definitions.py:444
msgid "Unable to specify version if type is not specified"
msgstr "Невозможно указать версию, если тип не указан"

#: glance/common/glare/definitions.py:462
msgid "Invalid reference list specification"
msgstr "Неверная спецификация списка указателей"

#: glance/common/glare/definitions.py:522
msgid "BinaryObject property cannot be declared mutable"
msgstr "Свойство BinaryObject не может быть объявлено как mutable"

#: glance/common/glare/definitions.py:532
msgid "Blob size is not set"
msgstr "Размер большого двоичного объекта не установлен"

#: glance/common/glare/definitions.py:536
msgid "File too large"
msgstr "Слишком большой файл"

#: glance/common/glare/definitions.py:540
msgid "File too small"
msgstr "Слишком маленький файл"

#: glance/common/glare/definitions.py:545
msgid "Too few locations"
msgstr "Слишком мало расположений"

#: glance/common/glare/definitions.py:550
msgid "Too many locations"
msgstr "Слишком много расположений"

#: glance/common/glare/loader.py:31
msgid ""
"When false, no artifacts can be loaded regardless of available_plugins. When "
"true, artifacts can be loaded."
msgstr ""
"Когда равно false, артефакты не могут быть загружены, независимо от "
"available_plugins. Когда равно true, артефакты могут быть загружены."

#: glance/common/glare/loader.py:35
msgid ""
"A list of artifacts that are allowed in the format name or name-version. "
"Empty list means that any artifact can be loaded."
msgstr ""
"Список разрешенных артефактов в формате имя или имя-версия. Пустой список "
"означает, что все артефакты могут быть загружены."

#: glance/common/glare/serialization.py:192
#, python-format
msgid "Blob %(name)s may not have multiple values"
msgstr "Большой двоичный объект %(name)s может иметь несколько значений"

#: glance/common/glare/serialization.py:213
#, python-format
msgid "Relation %(name)s may not have multiple values"
msgstr "Отношение %(name)s может иметь несколько значений"

#: glance/common/location_strategy/__init__.py:25
msgid ""
"This value sets what strategy will be used to determine the image location "
"order. Currently two strategies are packaged with Glance 'location_order' "
"and 'store_type'."
msgstr ""
"Значение определяет, какая стратегия будет использована для определения "
"модуля location order образа. На данный момент две стратегии упакованы с "
"'location_order' и 'store_type' Glance."

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being used."
msgstr ""
"%(strategy)s зарегистрирована как модуль дважды. %(module)s не используется."

#: glance/common/location_strategy/__init__.py:74
#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""
"Неверный параметр location_strategy: %(name)s. Верные параметры стратегии: "
"%(strategies)s"

#: glance/common/location_strategy/store_type.py:28
msgid ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'stores' config option. This "
"option will be applied when you using 'store_type' option as image location "
"strategy defined by the 'location_strategy' config option."
msgstr ""
"Имена хранилищ данных, используемых для получения порядка параметров "
"хранилищ. Имя должно быть зарегистрированным в одном из хранилищ, "
"определенных в опции настройки 'stores'. Эта опция будет применена при "
"использовании опции 'store_type' в качестве стратегии поиска образа, "
"определенной в опции настройки 'location_strategy'."

#: glance/common/scripts/utils.py:61
#, python-format
msgid "Input does not contain '%(key)s' field"
msgstr "Ввод не содержит поле %(key)s"

#: glance/common/scripts/utils.py:95
msgid ""
"File based imports are not allowed. Please use a non-local source of image "
"data."
msgstr ""
"Импорты на основе файлов не разрешены. Используйте нелокальный источник "
"данных образа."

#: glance/common/scripts/utils.py:104
#, python-format
msgid ""
"The given uri is not valid. Please specify a valid uri from the following "
"list of supported uri %(supported)s"
msgstr ""
"Заданный uri недопустим. Укажите допустимый uri из следующего списка "
"поддерживаемых uri %(supported)s"

#: glance/common/scripts/image_import/main.py:103
#, python-format
msgid ""
"The Image %(image_id)s object being created by this task %(task_id)s, is no "
"longer in valid status for further processing."
msgstr ""
"Объект образа %(image_id)s, создаваемый с помощью задачи %(task_id)s, больше "
"не находится в допустимом состоянии для дальнейшей обработки."

#: glance/contrib/plugins/image_artifact/v2/image.py:44
msgid "Either a file or a legacy_image_id has to be specified"
msgstr "Необходимо указать file или legacy_image_id"

#: glance/contrib/plugins/image_artifact/v2/image.py:49
msgid "Both file and legacy_image_id may not be specified at the same time"
msgstr "Невозможно одновременно указать file и legacy_image_id"

#: glance/contrib/plugins/image_artifact/v2/image.py:59
msgid "Glance client not installed"
msgstr "Клиент Glance не установлен"

#: glance/contrib/plugins/image_artifact/v2/image.py:68
msgid "Unable to get legacy image"
msgstr "Невозможно получить устаревший образ"

#: glance/contrib/plugins/image_artifact/v2/image.py:82
msgid "Legacy image was not found"
msgstr "Устаревший образ не найден"

#: glance/db/__init__.py:85 glance/db/__init__.py:127 glance/db/__init__.py:137
#: glance/db/__init__.py:151
#, python-format
msgid "No artifact found with ID %s"
msgstr "Не найдены артефакты с ИД %s"

#: glance/db/__init__.py:64 glance/db/__init__.py:167 glance/db/__init__.py:179
#: glance/db/sqlalchemy/api.py:181
#, python-format
msgid "No image found with ID %s"
msgstr "Образ с ИД %s не найден"

#: glance/db/__init__.py:238
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr "Целевой участник %(member_id)s уже связан с образом %(image_id)s."

#: glance/db/__init__.py:255
#, python-format
msgid "The specified member %s could not be found"
msgstr "Указанный участник %s не найден"

#: glance/db/__init__.py:334 glance/db/__init__.py:360
#: glance/db/__init__.py:377 glance/db/simple/api.py:762
#, python-format
msgid "Could not find task %s"
msgstr "Задача %s не найдена"

#: glance/db/__init__.py:539
#, python-format
msgid "Could not find namespace %s"
msgstr "Не найдено пространство имен %s"

#: glance/db/__init__.py:561 glance/db/__init__.py:571
#: glance/db/__init__.py:581 glance/db/__init__.py:591
#, python-format
msgid "The specified namespace %s could not be found"
msgstr "Указанное пространство имен %s не найдено"

#: glance/db/__init__.py:682
#, python-format
msgid "Could not find metadata object %s"
msgstr "Не найден объект метаданных %s"

#: glance/db/__init__.py:705
#, python-format
msgid "The specified metadata object %s could not be found"
msgstr "Указанный объект метаданных %s не найден"

#: glance/db/__init__.py:798
#, python-format
msgid "The specified resource type %s could not be found "
msgstr "Указанный тип ресурса %s не найден "

#: glance/db/__init__.py:845
#, python-format
msgid "Could not find property %s"
msgstr "Не найдено свойство %s"

#: glance/db/__init__.py:867
#, python-format
msgid "The specified property %s could not be found"
msgstr "Указанное свойство %s не найдено"

#: glance/db/__init__.py:931
#, python-format
msgid "Could not find metadata tag %s"
msgstr "Не удалось найти тег метаданных %s"

#: glance/db/__init__.py:957
#, python-format
msgid "The specified metadata tag %s could not be found"
msgstr "Не удалось найти указанный тег метаданных %s"

#: glance/db/simple/api.py:256 glance/db/sqlalchemy/api.py:407
msgid "Unable to filter on a range with a non-numeric value."
msgstr "Отфильтровать по диапазону с нечисловым значением невозможно."

#: glance/db/simple/api.py:317 glance/db/sqlalchemy/api.py:525
#, python-format
msgid "Unable to filter by unknown operator '%s'."
msgstr ""
"Не удается отфильтровать с использованием неизвестного оператора: '%s'"

#: glance/db/simple/api.py:425 glance/db/sqlalchemy/api.py:951
msgid "Image id is required."
msgstr "Требуется ИД образа."

#: glance/db/simple/api.py:570 glance/db/sqlalchemy/api.py:873
#, python-format
msgid "The location data has an invalid ID: %d"
msgstr "Данные о расположении содержат недопустимый ИД: %d"

#: glance/db/simple/api.py:590 glance/db/simple/api.py:616
#: glance/db/sqlalchemy/api.py:893 glance/db/sqlalchemy/api.py:919
#, python-format
msgid "No location found with ID %(loc)s from image %(img)s"
msgstr "Расположение с ИД %(loc)s из образа %(img)s не найдено"

#: glance/db/simple/api.py:600
msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'."
msgstr ""
"Состояние расположения удаленного образа может быть равно только "
"'pending_delete' или 'deleted'."

#: glance/db/simple/api.py:772 glance/db/sqlalchemy/api.py:1256
#, python-format
msgid "Forbidding request, task %s is not visible"
msgstr "Запрос запрещается, задача %s невидима"

#: glance/db/simple/api.py:890
msgid "Task does not exist"
msgstr "Задача не существует"

#: glance/db/simple/api.py:1155
#: glance/db/sqlalchemy/metadef_api/namespace.py:249
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition namespace "
"with the same name of %s"
msgstr ""
"Недопустимое обновление. Оно создает пространство имен определения "
"метаданных с таким же именем, как у пространства имен %s"

#: glance/db/simple/api.py:1176
#: glance/db/sqlalchemy/metadef_api/namespace.py:88
#, python-format
msgid "Metadata definition namespace not found for id=%s"
msgstr "Не найдено пространство имен определения метаданных для ИД %s"

#: glance/db/simple/api.py:1184 glance/db/simple/api.py:2128
#: glance/db/sqlalchemy/metadef_api/namespace.py:97
#: glance/db/sqlalchemy/metadef_api/namespace.py:119
#, python-format
msgid "Forbidding request, metadata definition namespace=%s is not visible."
msgstr ""
"Запрещенный запрос: пространство имен %s определения метаданных невидимое."

#: glance/db/simple/api.py:1307 glance/db/sqlalchemy/metadef_api/object.py:35
#, python-format
msgid "Metadata definition object not found for id=%s"
msgstr "Не найден объект определения метаданных для ИД %s"

#: glance/db/simple/api.py:1388
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s  in namespace=%(namespace_name)s."
msgstr ""
"Недопустимое обновление. Оно создает объект определения метаданных с таким "
"же именем, как у объекта %(name)s в пространстве имен %(namespace_name)s."

#: glance/db/simple/api.py:1515
#: glance/db/sqlalchemy/metadef_api/property.py:122
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition property "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"Недопустимое обновление. Оно создает пространство имен определения "
"метаданных с таким же именем, как у свойства %(name)s в пространстве имен "
"%(namespace_name)s."

#: glance/db/simple/api.py:1559 glance/db/sqlalchemy/metadef_api/property.py:37
#, python-format
msgid "Metadata definition property not found for id=%s"
msgstr "Не найдено свойство определения метаданных для ИД %s"

#: glance/db/simple/api.py:1765
#, python-format
msgid "Metadata definition tag not found for id=%s"
msgstr "Не найден тег определения метаданных для ИД %s"

#: glance/db/sqlalchemy/api.py:85
msgid "You do not own this image"
msgstr "Этот образ вам не принадлежит"

#: glance/db/sqlalchemy/api.py:337
#: glance/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Неизвестное направление сортировки, должно быть 'desc' или 'asc'"

#: glance/db/sqlalchemy/api.py:507
#, python-format
msgid "Bad \"%s\" query filter format. Use ISO 8601 DateTime notation."
msgstr ""
"Недопустимый формат фильтра запроса \"%s\". Используйте нотацию DateTime ISO "
"8601."

#: glance/db/sqlalchemy/api.py:682
#: glance/tests/unit/v2/test_registry_client.py:500
#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"
msgstr ""
"не удается выполнить переход от %(current)s к %(next)s при обновлении "
"(требуется from_state=%(from)s)"

#: glance/db/sqlalchemy/api.py:902
msgid ""
"The status of deleted image location can only be set to 'pending_delete' or "
"'deleted'"
msgstr ""
"Состояние расположения удаленного образа может быть равно только "
"'pending_delete' или 'deleted'"

#: glance/db/sqlalchemy/metadata.py:42
msgid "Path to the directory where json metadata files are stored"
msgstr "Путь к каталогу, где хранятся файлы метаданных json"

#: glance/db/sqlalchemy/metadef_api/object.py:112
#, python-format
msgid ""
"Invalid update. It would result in a duplicate metadata definition object "
"with the same name=%(name)s in namespace=%(namespace_name)s."
msgstr ""
"Недопустимое обновление. Оно создает объект определения метаданных с таким "
"же именем, как у объекта %(name)s в пространстве имен %(namespace_name)s."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:86
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:149
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like swift://user:pass@http://authurl.com/v1/container/obj, "
"you need to change it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""
"URI не может содержать больше одного вхождения схемы. Если вы указали URI "
"вида swift://user:pass@http://authurl.com/v1/container/obj, то вам нужно "
"изменить его так, чтобы использовалась схема swift+http://, например: "
"swift+http://user:pass@authurl.com/v1/container/obj"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:123
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:185
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr ""
"Неправильно сформированные идентификационные данные '%(creds)s' в URI Swift"

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:135
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:197
#: glance/store/swift.py:246
msgid "Badly formed credentials in Swift URI."
msgstr "Неправильно сформированные идентификационные данные в URI Swift."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:152
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:214
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr "Неправильно сформированный URI S3: %(uri)s"

#: glance/domain/__init__.py:59
#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr "В new_image() получены непредвиденные ключевые слова %s"

#: glance/domain/__init__.py:129
#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr "В __init__() получен непредвиденный именованный аргумент '%s'"

#: glance/domain/__init__.py:151
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr "Свойство %s должно быть задано до сохранения данных."

#: glance/domain/__init__.py:154
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr "Свойства %s должны быть заданы до сохранения данных."

#: glance/domain/__init__.py:171
msgid "Visibility must be either \"public\" or \"private\""
msgstr "Видимость должна быть \"public\" или \"private\""

#: glance/domain/__init__.py:190
msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""
"container_format атрибута может быть заменен только для образа, находящегося "
"в очереди."

#: glance/domain/__init__.py:202
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""
"disk_format атрибута может быть заменен только для образа, находящегося в "
"очереди."

#: glance/domain/__init__.py:214 glance/domain/__init__.py:227
msgid "Cannot be a negative value"
msgstr "Значение не может быть отрицательным"

#: glance/domain/__init__.py:255
#, python-format
msgid "Not allowed to deactivate image in status '%s'"
msgstr "Запрещено деактивировать образ в состоянии %s"

#: glance/domain/__init__.py:268
#, python-format
msgid "Not allowed to reactivate image in status '%s'"
msgstr "Запрещено повторно активировать образ в состоянии %s"

#: glance/domain/__init__.py:292
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr "Состояние должно быть \"pending\", \"accepted\" или \"rejected\"."

#: glance/glare/dependency.py:66
#, python-format
msgid "Not all dependencies are in '%s' state"
msgstr "Не все зависимости находятся в состоянии '%s'"

#: glance/glare/dependency.py:98
#, python-format
msgid "Dependency property '%s' has to be deleted first"
msgstr "Сначала необходимо удалить свойство зависимости '%s'"

#: glance/glare/location.py:159
#, python-format
msgid "Get blob %(name)s data failed: %(err)s."
msgstr ""
"Получение данных большого двоичного объекта %(name)s не выполнено: %(err)s."

#: glance/glare/updater.py:52
msgid "No property to access"
msgstr "Отсутствует свойство для доступа"

#: glance/glare/updater.py:130
#, python-format
msgid "Array has no element at position %d"
msgstr "Массив не содержит элементов в позиции %d"

#: glance/glare/updater.py:134
#, python-format
msgid "Not an array idx '%s'"
msgstr "Не является индексом массива '%s'"

#: glance/glare/updater.py:174
#, python-format
msgid "No such key '%s' in a dict"
msgstr "В словаре отсутствует ключ '%s'"

#: glance/image_cache/__init__.py:34
msgid "The driver to use for image cache management."
msgstr "Драйвер для управления кэшем образов."

#: glance/image_cache/__init__.py:39
msgid ""
"The upper limit (the maximum size of accumulated cache in bytes) beyond "
"which the cache pruner, if running, starts cleaning the image cache."
msgstr ""
"Максимальный размер аккумулированного кэша в байтах, при превышении которого "
"агент очистки кэша, если он запущен, начинает очистку кэша образов."

#: glance/image_cache/__init__.py:43
msgid ""
"The amount of time to let an incomplete image remain in the cache, before "
"the cache cleaner, if running, will remove the incomplete image."
msgstr ""
"Время, в течение которого неполный образ может оставаться в кэше перед тем, "
"как его удалит агент очистки кэша, если он запущен."

#: glance/image_cache/__init__.py:47
msgid "Base directory that the image cache uses."
msgstr "Базовый каталог для кэша образов."

#: glance/image_cache/__init__.py:253
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr ""
"Проверка контрольной суммой не выполнена. Кэширование образа '%s' прервано."

#: glance/image_cache/client.py:117
msgid ""
"--os_auth_url option or OS_AUTH_URL environment variable required when "
"keystone authentication strategy is enabled\n"
msgstr ""
"Опция --os_auth_url или переменная среды OS_AUTH_URL требуется, если "
"включена стратегия идентификации Keystone\n"

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr "Прочесть %s из конфигурации не удалось"

#: glance/image_cache/drivers/sqlite.py:39
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""
"Путь к базе данных файлов sqlite, которая будет использована для управления "
"кэшем образом."

#: glance/image_cache/drivers/sqlite.py:121
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr "Инициализировать базу данных кэша образов не удалось. Ошибка: %s"

#: glance/image_cache/drivers/xattr.py:104
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not "
"support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the cache "
"directory."
msgstr ""
"Устройство, на котором размещен каталог %(image_cache_dir)s кэша образов, не "
"поддерживает xattr. По-видимому, вам нужно отредактировать fstab, добавив "
"опцию user_xattr в соответствующую строку для устройства, на котором "
"размещен каталог кэша."

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr "Адрес для поиска сервера реестра."

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr "Порт, через который сервер реестра ведет прием."

#: glance/registry/api/v1/images.py:107 glance/registry/api/v1/images.py:112
msgid "Invalid marker. Image could not be found."
msgstr "Недопустимый маркер. Образ не найден."

#: glance/registry/api/v1/images.py:216
msgid "Unrecognized changes-since value"
msgstr "Нераспознанное значение изменений за период"

#: glance/registry/api/v1/images.py:221
msgid "protected must be True, or False"
msgstr "Параметр protected должен быть равен True или False"

#: glance/registry/api/v1/images.py:268
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr "Неподдерживаемый sort_key. Допустимые значения: %s"

#: glance/registry/api/v1/images.py:277
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr "Неподдерживаемый sort_dir. Допустимые значения: %s"

#: glance/registry/api/v1/images.py:303
msgid "is_public must be None, True, or False"
msgstr "Параметр is_public должен быть равен None, True или False"

#: glance/registry/api/v1/images.py:395
msgid "Invalid image id format"
msgstr "Недопустимый формат ИД образа"

#: glance/registry/api/v1/images.py:409
#, python-format
msgid "Image with identifier %s already exists!"
msgstr "Образ с идентификатором %s уже существует!"

#: glance/registry/api/v1/images.py:451
#, python-format
msgid "Failed to add image metadata. Got error: %s"
msgstr "Добавить метаданные образа не удалось. Ошибка: %s"

#: glance/registry/api/v1/images.py:322 glance/registry/api/v1/images.py:363
#: glance/registry/api/v1/images.py:466 glance/registry/api/v1/members.py:66
#: glance/registry/api/v1/members.py:100 glance/registry/api/v1/members.py:213
#: glance/registry/api/v1/members.py:273
#, python-format
msgid "Image %(id)s not found"
msgstr "Образ %(id)s не найден"

#: glance/registry/api/v1/members.py:114 glance/registry/api/v1/members.py:227
#: glance/registry/api/v1/members.py:287
msgid "No permission to share that image"
msgstr "Нет прав на совместное использование этого образа"

#: glance/registry/api/v1/members.py:125 glance/registry/api/v1/members.py:141
#: glance/registry/api/v1/members.py:240
#, python-format
msgid "Invalid membership association: %s"
msgstr "Недопустимая ассоциация членства: %s"

#: glance/registry/api/v1/members.py:300 glance/registry/api/v1/members.py:317
msgid "Membership could not be found."
msgstr "Членство не найдено."

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr "Служба реестра не может использовать %s"

#: glance/registry/client/__init__.py:20
msgid ""
"The protocol to use for communication with the registry server.  Either http "
"or https."
msgstr "Протокол связи с сервером реестра. Либо http, либо https."

#: glance/registry/client/__init__.py:26
msgid ""
"The path to the key file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_KEY_FILE environment "
"variable to a filepath of the key file"
msgstr ""
"Путь к файлу ключа для использования в соединениях SSL с сервером реестра "
"(если таковой есть). Или можно присвоить переменной среды "
"GLANCE_CLIENT_KEY_FILE путь к файлу ключа"

#: glance/registry/client/__init__.py:31
msgid ""
"The path to the cert file to use in SSL connections to the registry server, "
"if any. Alternately, you may set the GLANCE_CLIENT_CERT_FILE environment "
"variable to a filepath of the CA cert file"
msgstr ""
"Путь к файлу сертификата для использования в соединениях SSL с сервером "
"реестра (если таковой есть). Или можно присвоить переменной среды "
"GLANCE_CLIENT_CERT_FILE путь к файлу сертификата CA"

#: glance/registry/client/__init__.py:36
msgid ""
"The path to the certifying authority cert file to use in SSL connections to "
"the registry server, if any. Alternately, you may set the "
"GLANCE_CLIENT_CA_FILE environment variable to a filepath of the CA cert file."
msgstr ""
"Путь к файлу сертификата CA для использования в соединениях SSL с сервером "
"реестра (если таковой есть). Или можно присвоить переменной среды "
"GLANCE_CLIENT_CA_FILE путь к файлу сертификата CA ."

#: glance/registry/client/__init__.py:42
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority. This is the registry's equivalent of "
"specifying --insecure on the command line using glanceclient for the API."
msgstr ""
"При использовании SSL в соединениях с сервером реестра не требовать проверки "
"в сертификатной компании. Это реестровый эквивалент параметра --insecure "
"командной строки в glanceclient для API."

#: glance/registry/client/__init__.py:36
msgid ""
"The period of time, in seconds, that the API server will wait for a registry "
"request to complete. A value of 0 implies no timeout."
msgstr ""
"Время в секундах, в течение которого сервер API будет ожидать выполнения "
"запроса к реестру. 0 означает отсутствие тайм-аута."

#: glance/registry/client/__init__.py:64
msgid ""
"Whether to pass through the user token when making requests to the registry. "
"To prevent failures with token expiration during big files upload, it is "
"recommended to set this parameter to False.If \"use_user_token\" is not in "
"effect, then admin credentials can be specified."
msgstr ""
"Осуществлять ли сквозную передачу пользовательского маркера при создании "
"запросов в реестр Для предотвращения сбоев, связанных с истечением срока "
"действия маркера во время передачи больших данных, рекомендуется присваивать "
"этому параметру значение False. Если \"use_user_token\" не используется, "
"можно указать идентификационные данные администратора."

#: glance/registry/client/__init__.py:73
msgid ""
"The administrators user name. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"Имя администратора. Если \"use_user_token\" не действует, могут быть указаны "
"идентификационные данные администратора."

#: glance/registry/client/__init__.py:78
msgid ""
"The administrators password. If \"use_user_token\" is not in effect, then "
"admin credentials can be specified."
msgstr ""
"Пароль администратора. Если \"use_user_token\" не действует, могут быть "
"указаны идентификационные данные администратора."

#: glance/registry/client/__init__.py:83
msgid ""
"The tenant name of the administrative user. If \"use_user_token\" is not in "
"effect, then admin tenant name can be specified."
msgstr ""
"Имя арендатора администратора. Если \"use_user_token\" не действует, можно "
"указать имя арендатора администратора."

#: glance/registry/client/__init__.py:88
msgid ""
"The URL to the keystone service. If \"use_user_token\" is not in effect and "
"using keystone auth, then URL of keystone can be specified."
msgstr ""
"URL службы Keystone. Если \"use_user_token\" не действует и используется "
"идентификация Keystone, можно указать URL Keystone."

#: glance/registry/client/__init__.py:94
msgid ""
"The strategy to use for authentication. If \"use_user_token\" is not in "
"effect, then auth strategy can be specified."
msgstr ""
"Стратегия идентификации. Если \"use_user_token\" не действует, можно указать "
"стратегию идентификации."

#: glance/registry/client/__init__.py:99
msgid ""
"The region for the authentication service. If \"use_user_token\" is not in "
"effect and using keystone auth, then region name can be specified."
msgstr ""
"Регион службы идентификации. Если \"use_user_token\" не действует и "
"используется идентификация Keystone, можно указать имя региона."

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr "Недопустимая опция конфигурации"

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr "Обязательная опция конфигурации не найдена"

#: glance/tests/unit/test_migrations.py:927
#, python-format
msgid "location: %s data lost"
msgstr "Расположение: данные %s утеряны"
