# Translations template for keystone.
# Copyright (C) 2015 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
# kogamatranslator49 <r.podarov@yandex.ru>, 2015
# sher <sher@online.ua>, 2013
# sher <sher@online.ua>, 2013
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: keystone VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-21 07:06+0000\n"
"PO-Revision-Date: 2016-09-05 11:22+0000\n"
"Last-Translator: Eugene Roskin <Unknown>\n"
"Language-Team: Russian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-03-11 06:44+0000\n"
"X-Generator: Launchpad (build 2e4955e3d556e61e2eb54acf7a827d17e9e46822)\n"
"Language: ru\n"
"Generated-By: Babel 2.0\n"

#: keystone/exception.py:83
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not comply "
"with the request since it is either malformed or otherwise incorrect. The "
"client is assumed to be in error."
msgstr ""
"Ожидается %(attribute)s в %(target)s - серверу не удалось удовлетворить "
"запрос, поскольку его формат является неверным, либо запрос некорректен по "
"другой причине. Предположительно, клиент находится в состоянии ошибки."

#: keystone/exception.py:92
#, python-format
msgid "Cannot create an endpoint with an invalid URL: %(url)s"
msgstr ""
"Не удается создать конечную точку с помощью недопустимого URL: %(url)s"

#: keystone/exception.py:99
#, python-format
msgid "%(detail)s"
msgstr "%(detail)s"

#: keystone/exception.py:103
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client is "
"assumed to be in error."
msgstr ""
"Метка в неожиданном формате. Сервер не может выполнить запрос, поскольку он "
"либо искажен или неправилен. Клиент, как предполагается, является ошибочным."

#: keystone/exception.py:112
msgid ""
"The 'expires_at' must not be before now. The server could not comply with "
"the request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""
"Значение параметра 'expires_at' не должно быть меньше настоящего времени. "
"Серверу не удалось исполнить запрос, так как он поврежден или неправильно "
"сформирован. Предположительно, клиент находится в состоянии ошибки."

#: keystone/exception.py:121
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the limit "
"of column %(type)s(CHAR(%(length)d))."
msgstr ""
"Превышена длина строки. Длина строки '%(string)s' превышает ограничение "
"столбца %(type)s(CHAR(%(length)d))."

#: keystone/exception.py:127
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. The "
"server could not comply with the request because the attribute size is "
"invalid (too large). The client is assumed to be in error."
msgstr ""
"Атрибут запроса %(attribute)s не может быть больше %(size)i. Серверу не "
"удалось удовлетворить запрос, поскольку размер атрибута является "
"недопустимым (слишком большой). Предположительно, клиент находится в "
"состоянии ошибки."

#: keystone/exception.py:137
#, python-format
msgid ""
"The specified parent region %(parent_region_id)s would create a circular "
"region hierarchy."
msgstr ""
"Заданная родительская область %(parent_region_id)s создаст круговую "
"структуру области."

#: keystone/exception.py:156
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server could "
"not comply with the request because the password is invalid."
msgstr ""
"Длина пароля не должна превышать %(size)i. Сервер не может выполнить запрос, "
"поскольку пароль недопустим."

#: keystone/exception.py:162
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions have "
"associated endpoints."
msgstr ""
"Не удалось удалить регион %(region_id)s: регион или его дочерние регионы "
"имеют связанные конечные точки."

#: keystone/exception.py:167
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""
"Запрошенные сертификаты недоступны. Вероятно, данный сервер не использует "
"маркеры PKI, в противном случае, это является следствием ошибки в "
"конфигурации."

#: keystone/exception.py:179
msgid "(Disable insecure_debug mode to suppress these details.)"
msgstr ""
"(Выключите режим insecure_debug, чтобы не показывать эти подробности.)"

#: keystone/exception.py:189
#, python-format
msgid "%(message)s %(amendment)s"
msgstr "%(message)s %(amendment)s"

#: keystone/exception.py:197
msgid "The request you have made requires authentication."
msgstr "Выданный запрос требует идентификации."

#: keystone/exception.py:203
msgid "Authentication plugin error."
msgstr "Ошибка модуля идентификации."

#: keystone/exception.py:211
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""
"Невозможно найти допустимые группы при использовании преобразования "
"%(mapping_id)s"

#: keystone/exception.py:216
msgid "Attempted to authenticate with an unsupported method."
msgstr "Попытка идентификации с использованием неподдерживаемого метода."

#: keystone/exception.py:224
msgid "Additional authentications steps required."
msgstr "Требуются дополнительные действия для идентификации."

#: keystone/exception.py:232
msgid "You are not authorized to perform the requested action."
msgstr "У вас нет прав на выполнение запрашиваемого действия."

#: keystone/exception.py:239
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr "У вас нет прав на выполнение запрошенного действия: %(action)s"

#: keystone/exception.py:244
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target %(target)s"
msgstr ""
"Изменить постоянный атрибут '%(attributes)s' в цели %(target)s невозможно"

#: keystone/exception.py:249
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in question "
"is %(group_id)s, user is %(user_id)s"
msgstr ""
"Членство в группе не может распространяться через границы базовых систем, "
"группа под вопросом - %(group_id)s, пользователь - %(user_id)s"

#: keystone/exception.py:255
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service or "
"Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, Service: "
"%(service_id)s, Region: %(region_id)s"
msgstr ""
"Недопустимое смешение сущностей для связывания стратегии. Только Конечная "
"точка, Служба и Регион+Служба разрешены. В запросе было: Конечная точка "
"%(endpoint_id)s, Служба %(service_id)s, Регион %(region_id)s"

#: keystone/exception.py:262
#, python-format
msgid "Invalid domain specific configuration: %(reason)s"
msgstr "Недопустимая конфигурация для домена: %(reason)s"

#: keystone/exception.py:266
#, python-format
msgid "Could not find: %(target)s"
msgstr "%(target)s не найдена"

#: keystone/exception.py:272
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr "Конечная точка %(endpoint_id)s не найдена"

#: keystone/exception.py:279
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""
"Возникла необработанная исключительная ситуация: не удалось найти метаданные."

#: keystone/exception.py:284
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr "Стратегия %(policy_id)s не найдена"

#: keystone/exception.py:288
msgid "Could not find policy association"
msgstr "Не найдена связь стратегии"

#: keystone/exception.py:292
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr "Роль %(role_id)s не найдена"

#: keystone/exception.py:296
#, python-format
msgid "%(prior_role_id)s does not imply %(implied_role_id)s"
msgstr "%(prior_role_id)s не подразумевает %(implied_role_id)s"

#: keystone/exception.py:300
#, python-format
msgid "%(role_id)s cannot be an implied roles"
msgstr "%(role_id)s не может быть подразумеваемой ролью"

#: keystone/exception.py:304
#, python-format
msgid ""
"Could not find role assignment with role: %(role_id)s, user or group: "
"%(actor_id)s, project or domain: %(target_id)s"
msgstr ""
"Не найдено присвоение роли %(role_id)s, пользователь/группа: %(actor_id)s, "
"проект/домен: %(target_id)s"

#: keystone/exception.py:310
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr "Регион %(region_id)s не найден"

#: keystone/exception.py:314
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr "Служба %(service_id)s не найдена"

#: keystone/exception.py:318
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr "Домен %(domain_id)s не найден"

#: keystone/exception.py:322
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr "Проект %(project_id)s не найден"

#: keystone/exception.py:326
#, python-format
msgid "Cannot create project with parent: %(project_id)s"
msgstr "Не удается создать проект с родительским объектом: %(project_id)s"

#: keystone/exception.py:330
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr "Ключ %(token_id)s не найден"

#: keystone/exception.py:334
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr "Пользователь %(user_id)s не найден"

#: keystone/exception.py:338
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr "Группа %(group_id)s не найдена"

#: keystone/exception.py:342
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr "Отображение %(mapping_id)s не найдено"

#: keystone/exception.py:346
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr "Группа доверия %(trust_id)s не найдена"

#: keystone/exception.py:350
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr "Вариантов использования группы доверия %(trust_id)s не осталось"

#: keystone/exception.py:354
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr "Идентификационные данные %(credential_id)s не найдены"

#: keystone/exception.py:358
#, python-format
msgid "Could not find version: %(version)s"
msgstr "Версия %(version)s не найдена"

#: keystone/exception.py:362
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr "Не найдена группа конечных точек: %(endpoint_group_id)s"

#: keystone/exception.py:366
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr "Поставщик идентификаторов %(idp_id)s не найден"

#: keystone/exception.py:370
#, python-format
msgid "Could not find Service Provider: %(sp_id)s"
msgstr "Не удалось найти поставщик служб %(sp_id)s"

#: keystone/exception.py:374
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""
"Объединенный протокол %(protocol_id)s для поставщика идентификаторов "
"%(idp_id)s не найден"

#: keystone/exception.py:385
#, python-format
msgid ""
"Could not find %(group_or_option)s in domain configuration for domain "
"%(domain_id)s"
msgstr ""
"Не найден пользователь/группа %(group_or_option)s в конфигурации домена "
"%(domain_id)s"

#: keystone/exception.py:403
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr "При попытке сохранить %(type)s возник конфликт - %(details)s"

#: keystone/exception.py:412
msgid ""
"An unexpected error prevented the server from fulfilling your request."
msgstr "Из-за непредвиденной ошибки ваш запрос не был выполнен сервером."

#: keystone/exception.py:415
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""
"Из-за непредвиденной ошибки ваш запрос не был выполнен сервером: "
"%(exception)s"

#: keystone/exception.py:433
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr ""
"Принять группу доверия %(trust_id)s и захватить блокировку невозможно."

#: keystone/exception.py:438
msgid ""
"Expected signing certificates are not available on the server. Please check "
"Keystone configuration."
msgstr ""
"Ожидаемые сертификаты подписания недоступны на сервере. Рекомендуется "
"проверить конфигурацию Keystone."

#: keystone/exception.py:444
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""
"Неверный формат URL конечной точки (%(endpoint)s), подробную информацию см. "
"в протоколе ОШИБОК."

#: keystone/exception.py:449
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in the "
"backend."
msgstr ""
"Группа %(group_id)s, возвращенная преобразованием %(mapping_id)s, не найдена "
"в на базовом сервере."

#: keystone/exception.py:454
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr "Ошибка чтения файла метаданных: %(reason)s"

#: keystone/exception.py:458
#, python-format
msgid ""
"Local section in mapping %(mapping_id)s refers to a remote match that "
"doesn't exist (e.g. {0} in a local section)."
msgstr ""
"Локальный раздел в преобразовании %(mapping_id)s указывает на удаленное "
"совпадение, которое не существует (например, {0} в локальном разделе)."

#: keystone/exception.py:464
#, python-format
msgid ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"
msgstr ""
"Непредвиденная комбинация атрибутов предоставления доступа - пользователь: "
"%(user_id)s, группа: %(group_id)s, проект: %(project_id)s, домен: "
"%(domain_id)s"

#: keystone/exception.py:471
msgid "The action you have requested has not been implemented."
msgstr "Запрошенное действие не реализовано."

#: keystone/exception.py:478
msgid "The service you have requested is no longer available on this server."
msgstr "Запрошенная служба более не доступна на данном сервере."

#: keystone/exception.py:485
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr "Не удалось найти файл конфигурации Keystone %(config_file)s."

#: keystone/exception.py:490
msgid ""
"No encryption keys found; run keystone-manage fernet_setup to bootstrap one."
msgstr ""
"Не найдены ключи шифрования. Выполните команду keystone-manage fernet_setup, "
"чтобы создать ключ."

#: keystone/exception.py:495
#, python-format
msgid ""
"The Keystone domain-specific configuration has specified more than one SQL "
"driver (only one is permitted): %(source)s."
msgstr ""
"В конфигурации для домена Keystone указано несколько драйверов SQL (допустим "
"только один): %(source)s."

#: keystone/exception.py:502
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration repository "
"path at %(path)s doesn't exist or isn't a directory."
msgstr ""
"%(mod_name)s не обеспечивает перенос баз данных. Путь к хранилищу миграции "
"%(path)s не существует или не является каталогом."

#: keystone/exception.py:509
msgid "Token version is unrecognizable or unsupported."
msgstr "Версия маркера не распознана либо не поддерживается."

#: keystone/exception.py:514
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not have "
"xmlsec1 installed, or this is the result of misconfiguration. Reason "
"%(reason)s"
msgstr ""
"Не удалось подписать утверждение SAML. Вероятно, на этом сервере не "
"установлена программа xmlsec1 или это результат неправильной настройки. "
"Причина: %(reason)s"

#: keystone/exception.py:521
msgid ""
"No Authorization headers found, cannot proceed with OAuth related calls, if "
"running under HTTPd or Apache, ensure WSGIPassAuthorization is set to On."
msgstr ""
"Не найдены заголовки предоставления доступа - вызовы, связанные с OAuth, "
"невозможны при выполнении под управлением HTTPd или Apache. Убедитесь, что "
"параметру WSGIPassAuthorization присвоено значение On."

#: keystone/exception.py:528
#, python-format
msgid ""
"Could not determine Identity Provider ID. The configuration option "
"%(issuer_attribute)s was not found in the request environment."
msgstr ""
"Не удалось определить ИД поставщика идентификации. Опция конфигурации "
"%(issuer_attribute)s не найдена в среде запроса."

#: keystone/exception.py:536
#, python-format
msgid ""
"The %s extension has been moved into keystone core and as such its "
"migrations are maintained by the main keystone database control. Use the "
"command: keystone-manage db_sync"
msgstr ""
"Расширение %s было перемещено в ядро keystone, и его перенос поддерживается "
"основной системой управления базы данных keystone. Используйте команду: "
"keystone-manage db_sync"

#: keystone/exception.py:544
#, python-format
msgid "%(driver)s is not supported driver version"
msgstr "Версия драйвера %(driver)s не поддерживается"

#: keystone/notifications.py:232
#, python-format
msgid ""
"%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""
"%(event)s не является допустимым событием уведомления, требуется одно из "
"значений: %(actions)s"

#: keystone/notifications.py:241
#, python-format
msgid "Method not callable: %s"
msgstr "Вызов метода невозможен: %s"

#: keystone/assignment/controllers.py:100 keystone/identity/controllers.py:71
#: keystone/resource/controllers.py:90
msgid "Name field is required and cannot be empty"
msgstr "Поле имени является обязательным и не может быть пустым"

#: keystone/assignment/controllers.py:146
#: keystone/assignment/controllers.py:163
#: keystone/assignment/controllers.py:182
msgid "User roles not supported: tenant_id required"
msgstr "Роли пользователей не поддерживаются, требуется tenant_id"

#: keystone/assignment/controllers.py:567
#: keystone/assignment/controllers.py:856
msgid "Specify a domain or project, not both"
msgstr "Укажите домен или проект, но не то и другое"

#: keystone/assignment/controllers.py:570
msgid "Specify one of domain or project"
msgstr "Укажите один домен или проект"

#: keystone/assignment/controllers.py:575
#: keystone/assignment/controllers.py:861
msgid "Specify a user or group, not both"
msgstr "Укажите пользователя или группу, но не то и другое"

#: keystone/assignment/controllers.py:578
msgid "Specify one of user or group"
msgstr "Укажите одного пользователя или группу"

#: keystone/assignment/controllers.py:845
msgid ""
"Combining effective and group filter will always result in an empty list."
msgstr ""
"Сочетание действующего фильтра и фильтра группы всегда дает пустой список."

#: keystone/assignment/controllers.py:850
msgid ""
"Combining effective, domain and inherited filters will always result in an "
"empty list."
msgstr ""
"Сочетание действующего фильтра, фильтра домена и унаследованного фильтра "
"всегда дает пустой список."

#: keystone/assignment/controllers.py:952
msgid ""
"scope.project.id must be specified if include_subtree is also specified"
msgstr "scope.project.id необходимо указать, если указан include_subtree"

#: keystone/assignment/core.py:77
msgid ""
"Use of the identity driver config to automatically configure the same "
"assignment driver has been deprecated, in the \"O\" release, the assignment "
"driver will need to be expicitly configured if different than the default "
"(SQL)."
msgstr ""
"Использование конфигурации драйвера идентификатора для автоматической "
"настройки такого же драйвера присвоения устарело. В выпуске \"O\" драйвер "
"присвоения должен будет настраиваться явным образом, если он не совпадает с "
"драйвером по умолчанию (SQL)."

#: keystone/assignment/core.py:88
#, python-format
msgid ""
"Attempted automatic driver selection for assignment based upon [identity]\\"
"driver option failed since driver %s is not found. Set [assignment]/driver "
"to a valid driver in keystone config."
msgstr ""
"Не удалось автоматически выбрать драйвер на основе опции [identity]\\driver, "
"так как драйвер %s не найден. Укажите требуемый драйвер в "
"[assignment]/driver в конфигурации keystone."

#: keystone/assignment/core.py:179
msgid "Must specify either domain or project"
msgstr "Необходимо указать домен или проект"

#: keystone/assignment/core.py:848
msgid "Cannot list assignments sourced from groups and filtered by user ID."
msgstr ""
"Не удается показать список присвоений, полученных из групп и отфильтрованных "
"по ИД пользователя."

#: keystone/assignment/core.py:1058
#, python-format
msgid "Project (%s)"
msgstr "Проект (%s)"

#: keystone/assignment/core.py:1060
#, python-format
msgid "Domain (%s)"
msgstr "Домен (%s)"

#: keystone/assignment/core.py:1062
msgid "Unknown Target"
msgstr "Неизвестный целевой объект"

#: keystone/assignment/core.py:1518
msgid "Update of `domain_id` is not allowed."
msgstr "Обновление `domain_id` не разрешено."

#: keystone/assignment/core.py:1743
msgid "Domain specific roles are not supported in the V8 role driver"
msgstr "Особые роли домена не поддерживаются в драйвере ролей V8"

#: keystone/assignment/V8_backends/sql.py:287
#: keystone/assignment/backends/sql.py:137
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr "Удалить роль, которая не была предоставлена, нельзя: %s"

#: keystone/assignment/V8_backends/sql.py:363
#: keystone/assignment/backends/sql.py:213
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr "Обнаружен непредвиденный тип назначения, %s"

#: keystone/auth/controllers.py:60
#, python-format
msgid ""
"Direct import of auth plugin %(name)r is deprecated as of Liberty in favor "
"of its entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"Прямой импорт модуля идентификации %(name)r устарел в Liberty и может быть "
"удален в выпуске N. Вместо этого используется его точка входа из "
"%(namespace)r."

#: keystone/auth/controllers.py:121
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has conflicting "
"values %(new)s and %(old)s"
msgstr ""
"Согласовать атрибут идентификатора, %(attribute)s, невозможно, поскольку он "
"содержит конфликтующие значения %(new)s и %(old)s"

#: keystone/auth/controllers.py:182
msgid "Domain name cannot contain reserved characters."
msgstr "Имя домена не может содержать зарезервированные символы."

#: keystone/auth/controllers.py:205
msgid "Project name cannot contain reserved characters."
msgstr "Имя проекта не может содержать зарезервированные символы."

#: keystone/auth/controllers.py:355 keystone/middleware/auth.py:130
msgid "Scoping to both domain and project is not allowed"
msgstr "Назначать и домен, и проект в качестве области нельзя"

#: keystone/auth/controllers.py:358
msgid "Scoping to both domain and trust is not allowed"
msgstr "Назначать и домен, и группу доверия в качестве области нельзя"

#: keystone/auth/controllers.py:361
msgid "Scoping to both project and trust is not allowed"
msgstr "Назначать и проект, и группу доверия в качестве области нельзя"

#: keystone/auth/controllers.py:530
msgid "User not found"
msgstr "Пользователь не найден"

#: keystone/auth/controllers.py:644
msgid "A project-scoped token is required to produce a service catalog."
msgstr "Для создания каталога службы необходим маркер уровня проекта."

#: keystone/auth/plugins/external.py:42
msgid "No authenticated user"
msgstr "Нет идентифицированного пользователя"

#: keystone/auth/plugins/external.py:52
#, python-format
msgid "Unable to lookup user %s"
msgstr "Найти пользователя %s невозможно"

#: keystone/auth/plugins/external.py:100
msgid "auth_type is not Negotiate"
msgstr "auth_type отличен от Negotiate"

#: keystone/auth/plugins/mapped.py:246
msgid ""
"Could not map user while setting ephemeral user identity. Either mapping "
"rules must specify user id/name or REMOTE_USER environment variable must be "
"set."
msgstr ""
"Не удалось привязать пользователя во время настройки временного "
"идентификатора пользователя. Правила привязка должны указывать имя/ИД "
"пользователя, либо должна быть задана переменная среды REMOTE_USER."

#: keystone/auth/plugins/oauth1.py:46
msgid "Access token is expired"
msgstr "Срок действия ключа доступа истек"

#: keystone/auth/plugins/oauth1.py:60
msgid "Could not validate the access token"
msgstr "Не удалось проверить ключ доступа"

#: keystone/auth/plugins/password.py:39
msgid "Invalid username or password"
msgstr "Недопустимое имя пользователя или пароль"

#: keystone/auth/plugins/token.py:70 keystone/token/controllers.py:160
msgid "rescope a scoped token"
msgstr "Изменить область помещенного в область ключа"

#: keystone/auth/plugins/totp.py:96
msgid "Invalid username or TOTP passcode"
msgstr "Недопустимое имя пользователя или пароль TOTP"

#: keystone/catalog/controllers.py:215
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr "Указаны конфликтующие ИД регионов: \"%(url_id)s\" != \"%(ref_id)s\""

#: keystone/catalog/core.py:149 keystone/common/ldap/core.py:1411
#, python-format
msgid "Duplicate ID, %s."
msgstr "Повторяющийся идентификатор, %s."

#: keystone/catalog/backends/sql.py:389
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr "Конечная точка %(endpoint_id)s не найдена в проекте %(project_id)s"

#: keystone/catalog/backends/sql.py:492
msgid "Endpoint Group Project Association not found"
msgstr "Не найдена связь проекта группы конечных точек"

#: keystone/cmd/cli.py:173
msgid ""
"Either --bootstrap-password argument or OS_BOOTSTRAP_PASSWORD must be set."
msgstr ""
"Необходимо указать аргумент --bootstrap-password или OS_BOOTSTRAP_PASSWORD."

#: keystone/cmd/cli.py:586
msgid "At least one option must be provided"
msgstr "Необходимо указать хотя бы одну опцию"

#: keystone/cmd/cli.py:593
msgid "--all option cannot be mixed with other options"
msgstr "опцию --all нельзя указывать вместе с другими опциями"

#: keystone/cmd/cli.py:600
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr "В опции --domain-name указано неизвестное имя домена '%(name)s'"

#: keystone/cmd/cli.py:679 keystone/tests/unit/test_cli.py:411
msgid ""
"At least one option must be provided, use either --all or --domain-name"
msgstr ""
"Должен быть указан хотя бы один параметр. Укажите --all или --domain-name"

#: keystone/cmd/cli.py:685 keystone/tests/unit/test_cli.py:427
msgid "The --all option cannot be used with the --domain-name option"
msgstr "Параметр --all нельзя указывать вместе с параметром --domain-name"

#: keystone/cmd/cli.py:710 keystone/tests/unit/test_cli.py:444
#, python-format
msgid ""
"Invalid domain name: %(domain)s found in config file name: %(file)s - "
"ignoring this file."
msgstr ""
"Обнаружено недопустимое имя домена %(domain)s в файле конфигурации %(file)s -"
" файл пропущен."

#: keystone/cmd/cli.py:718 keystone/tests/unit/test_cli.py:385
#, python-format
msgid ""
"Domain: %(domain)s already has a configuration defined - ignoring file: "
"%(file)s."
msgstr ""
"У домена %(domain)s уже определена конфигурация - файл пропущен: %(file)s."

#: keystone/cmd/cli.py:732
#, python-format
msgid ""
"Error parsing configuration file for domain: %(domain)s, file: %(file)s."
msgstr ""
"Ошибка анализа файла конфигурации для домена %(domain)s, файл: %(file)s."

#: keystone/cmd/cli.py:783
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr "Не удалось найти каталог конфигурации домена: %s"

#: keystone/cmd/cli.py:803
msgid ""
"Unable to access the keystone database, please check it is configured "
"correctly."
msgstr ""
"Нет доступа к базе данных Keystone. Убедитесь, что она настроена правильно."

#: keystone/cmd/cli.py:866
#, python-format
msgid "Error while parsing rules %(path)s: %(err)s"
msgstr "Ошибка при анализе правил %(path)s: %(err)s"

#: keystone/cmd/cli.py:875
#, python-format
msgid "Error while opening file %(path)s: %(err)s"
msgstr "Ошибка при открытии файла %(path)s: %(err)s"

#: keystone/cmd/cli.py:885
#, python-format
msgid "Error while parsing line: '%(line)s': %(err)s"
msgstr "Ошибка при анализе строки: '%(line)s': %(err)s"

#: keystone/common/authorization.py:61 keystone/common/wsgi.py:67
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr ""
"Ссылка на маркер должна относиться к типу KeystoneToken, а получено %s"

#: keystone/common/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr "%s не может быть пуст."

#: keystone/common/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr "%(property_name)s не может быть короче %(min_length)s символов."

#: keystone/common/clean.py:31
#, python-format
msgid ""
"%(property_name)s should not be greater than %(max_length)s characters."
msgstr "%(property_name)s не должен быть длинее %(max_length)s символов."

#: keystone/common/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr "%(property_name)s не принадлежит к типу %(display_expected_type)s"

#: keystone/common/controller.py:349 keystone/common/controller.py:377
#: keystone/identity/core.py:595 keystone/resource/core.py:1145
#, python-format
msgid "Expected dict or list: %s"
msgstr "Ожидается dict или list: %s"

#: keystone/common/controller.py:390
msgid "Marker could not be found"
msgstr "Не удалось найти маркер"

#: keystone/common/controller.py:401
msgid "Invalid limit value"
msgstr "Недопустимое значение ограничения"

#: keystone/common/controller.py:705
msgid "Cannot change Domain ID"
msgstr "Невозможно изменить ИД домена"

#: keystone/common/controller.py:751
msgid ""
"You have tried to create a resource using the admin token. As this token is "
"not within a domain you must explicitly include a domain for this resource "
"to belong to."
msgstr ""
"Попытка создания ресурса с помощью административного маркера. Так как этот "
"маркер не принадлежит домену, необходимо явно указать домен, которому будет "
"принадлежать ресурс."

#: keystone/common/dependency.py:65
#, python-format
msgid "Unregistered dependency: %(name)s for %(targets)s"
msgstr "Незарегистрированная зависимость %(name)s для %(targets)s"

#: keystone/common/driver_hints.py:38
msgid ""
"Cannot truncate a driver call without hints list as first parameter after "
"self "
msgstr ""
"Невозможно отсечь вызов драйвера без списка подсказок в качестве первого "
"параметра после самого себя "

#: keystone/common/json_home.py:76
#, python-format
msgid "Unexpected status requested for JSON Home response, %s"
msgstr "Запрошено неожиданное состояние для ответа JSON Home, %s"

#: keystone/common/manager.py:82
#, python-format
msgid ""
"Direct import of driver %(name)r is deprecated as of Liberty in favor of its "
"entrypoint from %(namespace)r and may be removed in N."
msgstr ""
"Прямой импорт драйвера %(name)r устарел в Liberty и может быть удален в "
"выпуске N. Вместо этого используется его точка входа из %(namespace)r."

#: keystone/common/tokenless_auth.py:73
msgid "Neither Project Domain ID nor Project Domain Name was provided."
msgstr "Не указаны ни ИД домена проекта, ни имя домена проекта."

#: keystone/common/tokenless_auth.py:165
msgid ""
"User auth cannot be built due to missing either user id, or user name with "
"domain id, or user name with domain name."
msgstr ""
"Не удалось скомпоновать идентификацию пользователя, так как отсутствует ИД "
"пользователя, имя пользователя с ИД домена либо имя пользователя с именем "
"домена."

#: keystone/common/utils.py:63
msgid ""
"Length of transformable resource id > 64, which is max allowed characters"
msgstr ""
"Длина ИД преобразуемого ресурса > 64 символов, то есть превышает максимально "
"допустимую"

#: keystone/common/utils.py:192 keystone/credential/controllers.py:44
msgid "Invalid blob in credential"
msgstr "Недопустимый большой двоичный объект в разрешении"

#: keystone/common/wsgi.py:208
msgid "Query string is not UTF-8 encoded"
msgstr "Строка запроса указана в кодировке, отличной от UTF-8"

#: keystone/common/wsgi.py:341
#, python-format
msgid "%s field is required and cannot be empty"
msgstr "Поле %s является обязательным и не может быть пустым"

#: keystone/common/wsgi.py:353
#, python-format
msgid "%s field(s) cannot be empty"
msgstr "Поле %s не может быть пустым"

#: keystone/common/wsgi.py:548
msgid "The resource could not be found."
msgstr "Ресурс не найден."

#: keystone/common/kvs/core.py:88
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr "Наступил тайм-аут блокировки для ключа, %(target)s"

#: keystone/common/kvs/core.py:123
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr "Регион KVS %s уже настроен. Изменение конфигурации невозможно."

#: keystone/common/kvs/core.py:166
#, python-format
msgid "Key Value Store not configured: %s"
msgstr "Хранилище значений ключей не настроено: %s"

#: keystone/common/kvs/core.py:219
msgid "`key_mangler` option must be a function reference"
msgstr "Опция `key_mangler` должна быть ссылкой на функцию"

#: keystone/common/kvs/core.py:376
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""
"Блокировка должна соответствовать целевому ключу: %(lock)s != %(target)s"

#: keystone/common/kvs/core.py:380
msgid "Must be called within an active lock context."
msgstr "Требуется вызов в контексте активной блокировки."

#: keystone/common/kvs/backends/memcached.py:68
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr "Выполнено максимальное число попыток блокировки в %s."

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(backend)s` is not a valid memcached backend. Valid backends: "
"%(backend_list)s"
msgstr ""
"Базовая система `%(backend)s` не является допустимой базовой системой в кэше "
"памяти. Допустимые базовые системы: %(backend_list)s"

#: keystone/common/kvs/backends/memcached.py:185
msgid "`key_mangler` functions must be callable."
msgstr "Функции `key_mangler` должны быть доступны для вызова."

#: keystone/common/ldap/core.py:199
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""
"Недопустимая опция deref LDAP: %(option)s. Выберите одно из следующих "
"значений: %(options)s"

#: keystone/common/ldap/core.py:209
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""
"Недопустимая опция certs TLS LDAP: %(option)s. Выберите одно из следующих "
"значений: %(options)s"

#: keystone/common/ldap/core.py:221
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""
"Недопустимая область LDAP: %(scope)s. Выберите одно из следующих значений: "
"%(options)s"

#: keystone/common/ldap/core.py:591
msgid "Invalid TLS / LDAPS combination"
msgstr "Недопустимое сочетание TLS/LDAPS"

#: keystone/common/ldap/core.py:596
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr "Недопустимая опция TLS_AVAIL LDAP: %s. TLS недоступен"

#: keystone/common/ldap/core.py:606
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr "tls_cacertfile %s не найден или не является файлом"

#: keystone/common/ldap/core.py:618
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr "tls_cacertdir %s не найден или не является каталогом"

#: keystone/common/ldap/core.py:1333
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr "Атрибут ИД %(id_attr)s не найден в объекте LDAP %(dn)s"

#: keystone/common/ldap/core.py:1378
#, python-format
msgid "LDAP %s create"
msgstr "LDAP %s создание"

#: keystone/common/ldap/core.py:1383
#, python-format
msgid "LDAP %s update"
msgstr "LDAP %s обновление"

#: keystone/common/ldap/core.py:1388
#, python-format
msgid "LDAP %s delete"
msgstr "LDAP %s удаление"

#: keystone/common/ldap/core.py:1400
#, python-format
msgid "Duplicate name, %s."
msgstr "Повторяющееся имя, %s."

#: keystone/common/ldap/core.py:1557
msgid ""
"Disabling an entity where the 'enable' attribute is ignored by configuration."
msgstr ""
"Отключение сущности, при котором атрибут 'enable' в конфигурации "
"игнорируется."

#: keystone/common/ldap/core.py:1568
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr "Невозможно изменить %(option_name)s %(attr)s"

#: keystone/common/ldap/core.py:1655
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr "Элемент %(member)s уже является участником группы %(group)s"

#: keystone/common/sql/core.py:413
msgid "Duplicate Entry"
msgstr "Дубликат записи"

#: keystone/common/sql/core.py:429
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr "При попытке сохранить %s произошла непредвиденная ошибка"

#: keystone/common/sql/migration_helpers.py:167
msgid "Unable to downgrade schema"
msgstr "Не удается понизить версию схемы"

#: keystone/common/sql/migration_helpers.py:185
#: keystone/common/sql/migration_helpers.py:231
#, python-format
msgid "%s extension does not exist."
msgstr "Расширение %s не существует"

#: keystone/common/validation/__init__.py:44
#, python-format
msgid ""
"validated expected to find %(param_name)r in function signature for "
"%(func_name)r."
msgstr ""
"ожидалось найти проверенный параметр %(param_name)r в подписи функции "
"%(func_name)r."

#: keystone/common/validation/validators.py:53
#, python-format
msgid "Invalid input for field '%(path)s': %(message)s"
msgstr "Недопустимый ввод для поля '%(path)s': %(message)s"

#: keystone/contrib/admin_crud/core.py:28
msgid ""
"Remove admin_crud_extension from the paste pipeline, the admin_crud "
"extension is now always available. Updatethe [pipeline:admin_api] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Удалите admin_crud_extension из конвейера вставки, расширение admin_crud "
"теперь доступно всегда. Обновите раздел [pipeline:admin_api] в файле "
"keystone-paste.ini соответственно, так как он будет удален в выпуске O."

#: keystone/contrib/ec2/controllers.py:80 keystone/contrib/s3/core.py:111
#: keystone/contrib/s3/core.py:114
msgid "Invalid EC2 signature."
msgstr "Недопустимая подпись EC2."

#: keystone/contrib/ec2/controllers.py:83
#: keystone/contrib/ec2/controllers.py:87
#: keystone/contrib/ec2/controllers.py:125
msgid "EC2 signature not supplied."
msgstr "Не указана подпись EC2."

#: keystone/contrib/ec2/controllers.py:159
msgid "User not valid for tenant."
msgstr "Недопустимый пользователь для арендатора."

#: keystone/contrib/ec2/controllers.py:260
msgid "EC2 access key not found."
msgstr "Ключ доступа EC2 не найден."

#: keystone/contrib/ec2/controllers.py:326
msgid "Token belongs to another user"
msgstr "Маркер принадлежит другому пользователю"

#: keystone/contrib/ec2/controllers.py:354
msgid "Credential belongs to another user"
msgstr "Разрешение принадлежит другому пользователю"

#: keystone/contrib/endpoint_filter/routers.py:29
msgid ""
"Remove endpoint_filter_extension from the paste pipeline, the endpoint "
"filter extension is now always available. Update the [pipeline:api_v3] "
"section in keystone-paste.ini accordingly as it will be removed in the O "
"release."
msgstr ""
"Удалите endpoint_filter_extension из конвейера вставки, расширение фильтра "
"конечной точки теперь доступно всегда. Обновите раздел [pipeline:api_v3] в "
"файле keystone-paste.ini соответственно, так как он будет удален в выпуске O."

#: keystone/contrib/federation/routers.py:27
msgid ""
"Remove federation_extension from the paste pipeline, the federation "
"extension is now always available. Update the [pipeline:api_v3] section in "
"keystone-paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Удалите federation_filter_extension из конвейера вставки, расширение "
"объединения теперь доступно всегда. Обновите раздел [pipeline:api_v3] в "
"файле keystone-paste.ini соответственно, так как он будет удален в выпуске O."

#: keystone/contrib/oauth1/routers.py:29
msgid ""
"Remove oauth1_extension from the paste pipeline, the oauth1 extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Удалите oauth1_filter_extension из конвейера вставки, расширение oauth1 "
"теперь доступно всегда. Обновите раздел [pipeline:api_v3] в файле keystone-"
"paste.ini соответственно, так как он будет удален в выпуске O."

#: keystone/contrib/revoke/routers.py:27
msgid ""
"Remove revoke_extension from the paste pipeline, the revoke extension is now "
"always available. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Удалите revoke_filter_extension из конвейера вставки, расширение отзыва "
"теперь доступно всегда. Обновите раздел [pipeline:api_v3] в файле keystone-"
"paste.ini соответственно, так как он будет удален в выпуске O."

#: keystone/contrib/s3/core.py:82
msgid "Credential signature mismatch"
msgstr "Несовпадение подписи идентификационных данных"

#: keystone/contrib/simple_cert/routers.py:27
msgid ""
"Remove simple_cert from the paste pipeline, the PKI and PKIz token providers "
"are now deprecated and simple_cert was only used insupport of these token "
"providers. Update the [pipeline:api_v3] section in keystone-paste.ini "
"accordingly, as it will be removed in the O release."
msgstr ""
"Удалите simple_cert из конвейера вставки, теперь поставщики ключей PKI и "
"PKIz устарели, а simple_cert использовался только для поддержки этих "
"поставщиков. Обновите раздел [pipeline:api_v3] в файле keystone-paste.ini "
"соответственно, так как он будет удален в выпуске O."

#: keystone/contrib/user_crud/core.py:28
msgid ""
"Remove user_crud_extension from the paste pipeline, the user_crud extension "
"is now always available. Updatethe [pipeline:public_api] section in keystone-"
"paste.ini accordingly, as it will be removed in the O release."
msgstr ""
"Удалите user_crud_extension из конвейера вставки, расширение user_crud "
"теперь доступно всегда. Обновите раздел [pipeline:public_api] в файле "
"keystone-paste.ini соответственно, так как он будет удален в выпуске O."

#: keystone/endpoint_policy/core.py:264
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr "С конечной точкой %(endpoint_id)s не связано ни одной стратегии."

#: keystone/federation/controllers.py:269
msgid "Request must have an origin query parameter"
msgstr "Запрос должен содержать параметр origin"

#: keystone/federation/controllers.py:278
#, python-format
msgid "%(host)s is not a trusted dashboard host"
msgstr "%(host)s не является надежным хостом сводных панелей"

#: keystone/federation/controllers.py:309
msgid "Missing entity ID from environment"
msgstr "В среде отсутствует ИД сущности"

#: keystone/federation/controllers.py:357
msgid "Use a project scoped token when attempting to create a SAML assertion"
msgstr "Использовать локальный ключ проекта при создании утверждения SAML"

#: keystone/federation/idp.py:486
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr "Не удалось открыть сертификат %(cert_file)s. Причина: %(reason)s"

#: keystone/federation/idp.py:552
msgid "Ensure configuration option idp_entity_id is set."
msgstr "Убедитесь, что указан параметр конфигурации idp_entity_id."

#: keystone/federation/idp.py:555
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr "Убедитесь, что указан параметр конфигурации idp_sso_endpoint."

#: keystone/federation/idp.py:574
msgid ""
"idp_contact_type must be one of: [technical, other, support, administrative "
"or billing."
msgstr ""
"Значение idp_contact_type должно быть одним из следующих: technical, other, "
"support, administrative или billing."

#: keystone/federation/utils.py:234
msgid "Federation token is expired"
msgstr "Срок действия ключа объединения истек"

#: keystone/federation/utils.py:286
msgid "Could not find Identity Provider identifier in environment"
msgstr "Не удалось найти идентификатор поставщика идентификаторов в среде"

#: keystone/federation/utils.py:290
msgid ""
"Incoming identity provider identifier not included among the accepted "
"identifiers."
msgstr ""
"Входящий идентификатор поставщика идентификаторов не включен в принятые "
"идентификаторы."

#: keystone/federation/utils.py:585
#, python-format
msgid "User type %s not supported"
msgstr "Тип пользователя %s не поддерживается"

#: keystone/federation/utils.py:605
msgid ""
"Could not map any federated user properties to identity values. Check debug "
"logs or the mapping used for additional details."
msgstr ""
"Не удается связать объединенные свойства пользователя с идентификаторами. "
"Дополнительные сведения о связывании приведены в протоколе отладки."

#: keystone/federation/utils.py:629
#, python-format
msgid ""
"Invalid rule: %(identity_value)s. Both 'groups' and 'domain' keywords must "
"be specified."
msgstr ""
"Недопустимое правило: %(identity_value)s. Ключевые слова 'groups' и 'domain' "
"должны быть указаны."

#: keystone/federation/utils.py:854
#, python-format
msgid "Identity Provider %(idp)s is disabled"
msgstr "Поставщик идентификаторов %(idp)s отключен"

#: keystone/federation/utils.py:862
#, python-format
msgid "Service Provider %(sp)s is disabled"
msgstr "Поставщик службы %(sp)s отключен"

#: keystone/federation/backends/sql.py:182
#, python-format
msgid "Duplicate remote ID: %s"
msgstr "Повторяющийся удаленный ИД: %s"

#: keystone/federation/backends/sql.py:184
#, python-format
msgid "Duplicate entry: %s"
msgstr "Повторяющаяся запись: %s"

#: keystone/identity/controllers.py:74
msgid "Enabled field must be a boolean"
msgstr "Активное поле должно быть булевским значением"

#: keystone/identity/controllers.py:103
msgid "Enabled field should be a boolean"
msgstr "Активное поле должно быть булевским значением"

#: keystone/identity/core.py:265
#, python-format
msgid "Config API entity at /domains/%s/config"
msgstr "Настроить элемент API в /domains/%s/config"

#: keystone/identity/core.py:271
#, python-format
msgid ""
"Exceeded attempts to register domain %(domain)s to use the SQL driver, the "
"last domain that appears to have had it is %(last_domain)s, giving up"
msgstr ""
"Превышено число попыток регистрации домена %(domain)s для использования "
"драйвера SQL. Последний домен, для которого это было сделано - "
"%(last_domain)s. Больше попыток не будет"

#: keystone/identity/core.py:450 keystone/identity/backends/ldap.py:62
#: keystone/identity/backends/ldap.py:64 keystone/identity/backends/ldap.py:70
#: keystone/identity/backends/ldap.py:72 keystone/identity/backends/sql.py:210
#: keystone/identity/backends/sql.py:212
msgid "Invalid user / password"
msgstr "Недопустимый пользователь / пароль"

#: keystone/identity/core.py:895
#, python-format
msgid "User is disabled: %s"
msgstr "Пользователь отключен: %s"

#: keystone/identity/core.py:928 keystone/resource/core.py:375
msgid ""
"update of domain_id is deprecated as of Mitaka and will be removed in O."
msgstr "обновление domain_id устарело в Mitaka и будет удалено в O."

#: keystone/identity/core.py:947
msgid "Cannot change user ID"
msgstr "Невозможно изменить ИД пользователя"

#: keystone/identity/backends/ldap.py:35
#, python-format
msgid ""
"%s for the LDAP identity backend has been deprecated in the Mitaka release "
"in favor of read-only identity LDAP access. It will be removed in the \"O\" "
"release."
msgstr ""
"%s для системы идентификации LDAP устарело Mitaka, вместо него используется "
"идентификация LDAP с доступом только для чтения. Эта функция будет удалена в "
"выпуске \"O\"."

#: keystone/identity/backends/ldap.py:106
msgid "Cannot change user name"
msgstr "Невозможно изменить имя пользователя"

#: keystone/identity/backends/ldap.py:214 keystone/identity/backends/sql.py:292
#: keystone/identity/backends/sql.py:310
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr "Пользователь '%(user_id)s' не найден в группе '%(group_id)s'"

#: keystone/identity/backends/ldap.py:366
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr "Пользователь %(user_id)s уже является участником группы %(group_id)s"

#: keystone/models/token_model.py:62
msgid "Found invalid token: scoped to both project and domain."
msgstr ""
"Обнаружен недопустимый маркер: он относится и к уровню проекта, и к уровню "
"домена."

#: keystone/oauth1/controllers.py:126
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""
"Показать список маркеров запросов с маркером, выданным посредством "
"делегирования, невозможно."

#: keystone/oauth1/controllers.py:187 keystone/oauth1/backends/sql.py:256
msgid "User IDs do not match"
msgstr "ИД пользователей не совпадают"

#: keystone/oauth1/controllers.py:243
msgid "Invalid signature"
msgstr "Недопустимая подпись"

#: keystone/oauth1/controllers.py:294 keystone/oauth1/controllers.py:372
msgid "Request token is expired"
msgstr "Срок действия маркера запроса истек"

#: keystone/oauth1/controllers.py:308
msgid "There should not be any non-oauth parameters"
msgstr "Не допускаются параметры, отличные от oauth"

#: keystone/oauth1/controllers.py:312
msgid "provided consumer key does not match stored consumer key"
msgstr "переданный ключ приемника не совпадает с сохраненным"

#: keystone/oauth1/controllers.py:316
msgid "provided verifier does not match stored verifier"
msgstr "переданная функция проверки не совпадает с сохраненной"

#: keystone/oauth1/controllers.py:320
msgid "provided request key does not match stored request key"
msgstr "переданный ключ запроса не совпадает с сохраненным"

#: keystone/oauth1/controllers.py:324
msgid "Request Token does not have an authorizing user id"
msgstr ""
"Маркер запроса не содержит ИД пользователя для предоставления прав доступа"

#: keystone/oauth1/controllers.py:361
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""
"Предоставить права доступа маркеру запроса с маркером, выданным посредством "
"делегирования, невозможно."

#: keystone/oauth1/controllers.py:388
msgid "authorizing user does not have role required"
msgstr ""
"пользователю, предоставляющему права доступа, не присвоена требуемая роль"

#: keystone/oauth1/controllers.py:401
msgid "User is not a member of the requested project"
msgstr "Пользователь не является участником запрошенного проекта"

#: keystone/oauth1/backends/sql.py:91
msgid "Consumer not found"
msgstr "Приемник не найден"

#: keystone/oauth1/backends/sql.py:177
msgid "Request token not found"
msgstr "Маркер запроса не найден"

#: keystone/oauth1/backends/sql.py:237
msgid "Access token not found"
msgstr "Ключ доступа не найден"

#: keystone/resource/controllers.py:94
msgid "The creation of projects acting as domains is not allowed in v2."
msgstr "Создание проектов, работающих в качестве доменов, не разрешено в v2."

#: keystone/resource/controllers.py:284
msgid ""
"Cannot use parents_as_list and parents_as_ids query params at the same time."
msgstr ""
"Нельзя использовать параметры запроса parents_as_list и parents_as_ids "
"одновременно."

#: keystone/resource/controllers.py:290
msgid ""
"Cannot use subtree_as_list and subtree_as_ids query params at the same time."
msgstr ""
"Нельзя использовать параметры запроса subtree_as_list и subtree_as_ids "
"одновременно."

#: keystone/resource/core.py:106
#, python-format
msgid "Max hierarchy depth reached for %s branch."
msgstr "Для ветви %s достигнута максимальная глубина иерархии."

#: keystone/resource/core.py:123
msgid "Multiple domains are not supported"
msgstr "Множественные домены не поддерживаются"

#: keystone/resource/core.py:129
msgid "only root projects are allowed to act as domains."
msgstr "Только корневые проекты могут работать в качестве доменов."

#: keystone/resource/core.py:152
#, python-format
msgid ""
"Cannot create project, since its parent (%(domain_id)s) is acting as a "
"domain, but project's specified parent_id (%(parent_id)s) does not match "
"this domain_id."
msgstr ""
"Не удается создать проект, так как его родительский элемент (%(domain_id)s) "
"работает в качестве домена, но parent_id (%(parent_id)s), указанный для "
"проекта, не соответствует данному domain_id."

#: keystone/resource/core.py:163
#, python-format
msgid ""
"Cannot create project, since it specifies its owner as domain %(domain_id)s, "
"but specifies a parent in a different domain (%(parent_domain_id)s)."
msgstr ""
"Не удается создать проект, так как его владелец указан как домен "
"%(domain_id)s, но его родительский объект задан в другом домене  "
"(%(parent_domain_id)s)."

#: keystone/resource/core.py:183
#, python-format
msgid "cannot create a project in a branch containing a disabled project: %s"
msgstr "Нельзя создать проект в ветви, содержащей отключенный проект: %s"

#: keystone/resource/core.py:191
#, python-format
msgid ""
"%(entity)s name cannot contain the following reserved characters: %(chars)s"
msgstr ""
"Имя %(entity)s не может содержать следующие зарезервированные символы: "
"%(chars)s"

#: keystone/resource/core.py:201
#, python-format
msgid ""
"it is not permitted to have two projects acting as domains with the same "
"name: %s"
msgstr ""
"Не разрешено использовать два проекта в качестве доменов с одинаковым "
"именем: %s"

#: keystone/resource/core.py:205
#, python-format
msgid ""
"it is not permitted to have two projects with the same name in the same "
"domain : %s"
msgstr ""
"не разрешается иметь два проекта с одинаковыми именами на одном и том же "
"домене: %s"

#: keystone/resource/core.py:262
#, python-format
msgid "Domain is disabled: %s"
msgstr "Домен отключен: %s"

#: keystone/resource/core.py:279
#, python-format
msgid "Domain cannot be named %s"
msgstr "Домену нельзя присвоить имя %s"

#: keystone/resource/core.py:282
#, python-format
msgid "Domain cannot have ID %s"
msgstr "Домен не может иметь идентификатор %s"

#: keystone/resource/core.py:297
#, python-format
msgid "Project is disabled: %s"
msgstr "Проект отключен: %s"

#: keystone/resource/core.py:304
#, python-format
msgid "Cannot enable project %s since it has disabled parents"
msgstr ""
"Не удается включить проект %s, так как у него отключены родительские объекты"

#: keystone/resource/core.py:340
msgid "Update of `parent_id` is not allowed."
msgstr "Обновление `parent_id` не разрешено."

#: keystone/resource/core.py:345
msgid "Update of `is_domain` is not allowed."
msgstr "Обновление `is_domain` не разрешено."

#: keystone/resource/core.py:359
msgid "Update of domain_id of projects acting as domains is not allowed."
msgstr ""
"Не разрешено обновлять domain_id для проектов, работающих в качестве доменов."

#: keystone/resource/core.py:366
msgid "Update of domain_id is only allowed for root projects."
msgstr "Обновление domain_id разрешено только для корневых проектов."

#: keystone/resource/core.py:371
msgid "Cannot update domain_id of a project that has children."
msgstr ""
"Не разрешено обновлять domain_id для проекта, у которого есть дочерние "
"объекты."

#: keystone/resource/core.py:396
#, python-format
msgid ""
"Cannot disable project %(project_id)s since its subtree contains enabled "
"projects."
msgstr ""
"Нельзя отключить проект %(project_id)s, так как его поддерево содержит "
"включенные проекты"

#: keystone/resource/core.py:443
msgid "Cascade update is only allowed for enabled attribute."
msgstr "Каскадное обновление разрешено только для включенных атрибутов."

#: keystone/resource/core.py:507
#, python-format
msgid ""
"cannot delete an enabled project acting as a domain. Please disable the "
"project %s first."
msgstr ""
"Невозможно удалить включенный проект, работающий как домен. Сначала "
"выключите проект %s."

#: keystone/resource/core.py:513
#, python-format
msgid ""
"Cannot delete the project %s since it is not a leaf in the hierarchy. Use "
"the cascade option if you want to delete a whole subtree."
msgstr ""
"Невозможно удалить проект %s, так как он не является конечным объектом в "
"структуре. Используйте каскадную опцию для удаления всего поддерева."

#: keystone/resource/core.py:526
#, python-format
msgid ""
"Cannot delete project %(project_id)s since its subtree contains enabled "
"projects."
msgstr ""
"Невозможно удалить проект %(project_id)s, так как его поддерево содержит "
"включенные проекты"

#: keystone/resource/core.py:554
msgid "Project field is required and cannot be empty."
msgstr "Поле проекта является обязательным и не может быть пустым."

#: keystone/resource/core.py:795
msgid "Cannot delete a domain that is enabled, please disable it first."
msgstr "Невозможно удалить включенный домен, сначала выключите его."

#: keystone/resource/core.py:1570
msgid "No options specified"
msgstr "Параметры не указаны"

#: keystone/resource/core.py:1576
#, python-format
msgid ""
"The value of group %(group)s specified in the config should be a dictionary "
"of options"
msgstr ""
"Значение группы %(group)s, указанное в конфигурации, должно быть словарем "
"параметров"

#: keystone/resource/core.py:1600
#, python-format
msgid ""
"Option %(option)s found with no group specified while checking domain "
"configuration request"
msgstr ""
"Обнаружен параметр %(option)s без указанной группы во время проверки запроса "
"на настройку домена"

#: keystone/resource/core.py:1607
#, python-format
msgid "Group %(group)s is not supported for domain specific configurations"
msgstr ""
"Группа %(group)s не поддерживается для определенных конфигураций домена"

#: keystone/resource/core.py:1614
#, python-format
msgid ""
"Option %(option)s in group %(group)s is not supported for domain specific "
"configurations"
msgstr ""
"Параметр %(option)s в группе %(group)s не поддерживается для определенных "
"конфигураций домена"

#: keystone/resource/core.py:1666
msgid "An unexpected error occurred when retrieving domain configs"
msgstr "Возникла непредвиденная ошибка при получении конфигураций доменов"

#: keystone/resource/core.py:1745 keystone/resource/core.py:1828
#: keystone/resource/core.py:1898 keystone/resource/config_backends/sql.py:76
#, python-format
msgid "option %(option)s in group %(group)s"
msgstr "параметр %(option)s в группе %(group)s"

#: keystone/resource/core.py:1748 keystone/resource/core.py:1833
#: keystone/resource/core.py:1894
#, python-format
msgid "group %(group)s"
msgstr "группа %(group)s"

#: keystone/resource/core.py:1750
msgid "any options"
msgstr "любые параметры"

#: keystone/resource/core.py:1793
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, so that, and only "
"that, option must be specified  in the config"
msgstr ""
"Изменение параметра %(option)s в группе %(group)s, чтобы параметр должен был "
"указываться только в конфигурации"

#: keystone/resource/core.py:1798
#, python-format
msgid ""
"Trying to update group %(group)s, so that, and only that, group must be "
"specified in the config"
msgstr ""
"Изменение группы %(group)s, чтобы группа должна была указываться только в "
"конфигурации"

#: keystone/resource/core.py:1807
#, python-format
msgid ""
"request to update group %(group)s, but config provided contains group "
"%(group_other)s instead"
msgstr ""
"запрос на изменение группы %(group)s, однако переданная конфигурация "
"содержит группу %(group_other)s вместо нее"

#: keystone/resource/core.py:1814
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, but config provided "
"contains option %(option_other)s instead"
msgstr ""
"Изменение параметра %(option)s в группе %(group)s, однако переданная "
"конфигурация содержит параметр %(option_other)s вместо него"

#: keystone/resource/core.py:2006
#, python-format
msgid "Group  %s not found in config"
msgstr "Группа %s не найдена в конфигурации"

#: keystone/resource/core.py:2016
#, python-format
msgid ""
"Reading the default for option %(option)s in group %(group)s is not supported"
msgstr ""
"Чтение значения по умолчанию для параметра  %(option)s в группе %(group)s не "
"поддерживается"

#: keystone/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr "Недопустимый формат даты %s"

#: keystone/revoke/core.py:156
msgid ""
"The revoke call must not have both domain_id and project_id. This is a bug "
"in the Keystone server. The current request is aborted."
msgstr ""
"В вызове revoke должны быть указаны domain_id и project_id. Это ошибка в "
"коде сервера Keystone. Текущий запрос прерван."

#: keystone/revoke/core.py:226 keystone/token/provider.py:217
#: keystone/token/provider.py:256 keystone/token/provider.py:336
#: keystone/token/provider.py:343
msgid "Failed to validate token"
msgstr "Проверить маркер не удалось"

#: keystone/token/controllers.py:372
msgid "Tenant name cannot contain reserved characters."
msgstr "Имя арендатора не может содержать зарезервированные символы."

#: keystone/token/controllers.py:392
#, python-format
msgid "Project ID not found: %(t_id)s"
msgstr "Не найден ИД проекта: %(t_id)s"

#: keystone/token/controllers.py:396
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr "У пользователя %(u_id)s нет доступа к арендатору %(t_id)s"

#: keystone/token/controllers.py:415 keystone/token/controllers.py:418
msgid "Token does not belong to specified tenant."
msgstr "Маркер не принадлежит указанному арендатору."

#: keystone/token/provider.py:269 keystone/token/provider.py:293
msgid "No token in the request"
msgstr "В запросе отсутствует маркер"

#: keystone/token/persistence/backends/kvs.py:132
#, python-format
msgid "Unknown token version %s"
msgstr "Неизвестная версия маркера %s"

#: keystone/token/providers/common.py:313
#: keystone/token/providers/common.py:445
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr "У пользователя %(user_id)s нет доступа к проекту %(project_id)s"

#: keystone/token/providers/common.py:318
#: keystone/token/providers/common.py:450
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr "У пользователя %(user_id)s нет доступа к домену %(domain_id)s"

#: keystone/token/providers/common.py:345
msgid "Trustor is disabled."
msgstr "Доверитель отключен."

#: keystone/token/providers/common.py:434
msgid "Trustee has no delegated roles."
msgstr "У доверенного лица нет делегированных ролей."

#: keystone/token/providers/common.py:496
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr "Недопустимый тип данных в информации контроля: %(data)s (%(type)s)"

#: keystone/token/providers/common.py:560
#: keystone/token/providers/common.py:587
msgid "The configured token provider does not support bind authentication."
msgstr "Настроенный модуль маркера не поддерживает идентификацию привязки."

#: keystone/token/providers/common.py:598
msgid "User is not a trustee."
msgstr "Пользователь не является доверенным лицом."

#: keystone/token/providers/common.py:665
msgid ""
"Attempting to use OS-FEDERATION token with V2 Identity Service, use V3 "
"Authentication"
msgstr ""
"Попытка использовать маркер OS-FEDERATION со службой идентификации версии 2. "
"Следует использовать идентификацию версии 3"

#: keystone/token/providers/common.py:675
msgid "Non-default domain is not supported"
msgstr "Домен, отличный от применяемого по умолчанию, не поддерживается"

#: keystone/token/providers/common.py:679
msgid "Domain scoped token is not supported"
msgstr "Маркер, область которого - домен, не поддерживается"

#: keystone/token/providers/pki.py:53 keystone/token/providers/pkiz.py:31
msgid "Unable to sign token."
msgstr "Подписать маркер невозможно."

#: keystone/token/providers/fernet/token_formatters.py:102
#, python-format
msgid "This is not a recognized Fernet token %s"
msgstr "Это не маркер Fernet: %s"

#: keystone/token/providers/fernet/token_formatters.py:198
#, python-format
msgid "This is not a recognized Fernet payload version: %s"
msgstr "Это не распознанная версия полезной нагрузки Fernet: %s"

#: keystone/trust/controllers.py:107
#, python-format
msgid "role %s is not defined"
msgstr "роль %s не определена"

#: keystone/trust/controllers.py:131
msgid "Redelegation allowed for delegated by trust only"
msgstr ""
"Изменение делегирования разрешено только для доверенного пользователя"

#: keystone/trust/controllers.py:164
msgid "The authenticated user should match the trustor."
msgstr "Идентифицированный пользователь должен соответствовать доверителю."

#: keystone/trust/controllers.py:169
msgid "At least one role should be specified."
msgstr "Необходимо указать по крайней мере одну роль."

#: keystone/trust/core.py:58
#, python-format
msgid ""
"Remaining redelegation depth of %(redelegation_depth)d out of allowed range "
"of [0..%(max_count)d]"
msgstr ""
"Оставшаяся глубина изменения делегирования %(redelegation_depth)d выходит за "
"пределы разрешенного диапазона [0..%(max_count)d]"

#: keystone/trust/core.py:67
#, python-format
msgid ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"
msgstr ""
"Полю \"remaining_uses\" присвоено значение %(value)s, хотя поле не может "
"быть задано для изменения делегирования группы доверия"

#: keystone/trust/core.py:78
msgid "Requested expiration time is more than redelegated trust can provide"
msgstr ""
"Запрошенное время истечения срока действия превышает значение, которое может "
"указать доверенный пользователь"

#: keystone/trust/core.py:88
msgid "Some of requested roles are not in redelegated trust"
msgstr ""
"Некоторые из запрошенных ролей не относятся к доверенному пользователю с "
"измененными полномочиями"

#: keystone/trust/core.py:112
msgid "One of the trust agents is disabled or deleted"
msgstr "Один из доверенных агентов отключен или удален"

#: keystone/trust/core.py:131
msgid "remaining_uses must be a positive integer or null."
msgstr ""
"Значение remaining_uses должно быть положительным целым числом или равным "
"нулю."

#: keystone/trust/core.py:137
#, python-format
msgid ""
"Requested redelegation depth of %(requested_count)d is greater than allowed "
"%(max_count)d"
msgstr ""
"Запрошенная глубина изменения делегирования %(requested_count)d превышает "
"разрешенную %(max_count)d"

#: keystone/trust/core.py:144
msgid "remaining_uses must not be set if redelegation is allowed"
msgstr ""
"Если включено изменение делегирования, параметр remaining_uses не должен "
"быть задан"

#: keystone/trust/core.py:154
msgid ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting "
"this parameter is advised."
msgstr ""
"Изменение параметра \"redelegation_count\" во время изменения делегирования "
"запрещено. Возможен пропуск этого параметра."
