# Translations template for swift.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the swift project.
#
# Translators:
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: swift VERSION\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2011-01-26 23:59+0000\n"
"PO-Revision-Date: 2021-12-09 16:42+0000\n"
"Last-Translator: Copied by Zanata <Unknown>\n"
"Language-Team: Russian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-03-11 06:44+0000\n"
"X-Generator: Launchpad (build 2e4955e3d556e61e2eb54acf7a827d17e9e46822)\n"
"Generated-By: Babel 2.0\n"
"Language: ru\n"

#: swift/account/auditor.py:52 swift/account/auditor.py:75
#, python-format
msgid ""
"Since %(time)s: Account audits: %(passed)s passed audit, %(failed)s failed "
"audit"
msgstr ""
"C %(time)s: Аудит учётной записи: %(passed)s аудит пройден, %(failed)s "
"ошибка аудита"

#: swift/account/auditor.py:100 swift/container/auditor.py:103
#, python-format
msgid "Audit passed for %s"
msgstr "Аудит пройден для %s"

#: swift/account/auditor.py:103
#, python-format
msgid "ERROR Could not get account info %s"
msgstr "Ошибка: не удалось получить сведения об учетной записи %s"

#: swift/account/reaper.py:80 swift/container/updater.py:64
#, python-format
msgid "Loading account ring from %s"
msgstr ""

#: swift/account/reaper.py:88 swift/obj/updater.py:57
#, python-format
msgid "Loading container ring from %s"
msgstr ""

#: swift/account/reaper.py:96
#, python-format
msgid "Loading object ring from %s"
msgstr ""

#: swift/account/reaper.py:106
msgid "Daemon started."
msgstr "Служба запущена."

#: swift/account/reaper.py:122
#, python-format
msgid "Begin devices pass: %s"
msgstr ""

#: swift/account/reaper.py:128 swift/common/utils.py:805
#: swift/obj/updater.py:74 swift/obj/updater.py:113
#, python-format
msgid "Skipping %s as it is not mounted"
msgstr "%s будет пропущен, так как он не смонтирован"

#: swift/account/reaper.py:132
#, python-format
msgid "Devices pass completed: %.02fs"
msgstr "Проход устройств выполнен: %.02fs"

#: swift/account/reaper.py:215
#, python-format
msgid "Beginning pass on account %s"
msgstr "Начинается проход для учетной записи %s"

#: swift/account/reaper.py:238
#, python-format
msgid "Exception with containers for account %s"
msgstr "Исключительная ситуация в контейнерах для учетной записи %s"

#: swift/account/reaper.py:243
#, python-format
msgid "Exception with account %s"
msgstr "Исключительная ситуация в учетной записи %s"

#: swift/account/reaper.py:244
#, python-format
msgid "Incomplete pass on account %s"
msgstr "Не завершен проход для учетной записи %s"

#: swift/account/reaper.py:246
#, python-format
msgid ", %s containers deleted"
msgstr ", удалено контейнеров: %s"

#: swift/account/reaper.py:248
#, python-format
msgid ", %s objects deleted"
msgstr ", удалено объектов: %s"

#: swift/account/reaper.py:250
#, python-format
msgid ", %s containers remaining"
msgstr ", осталось контейнеров: %s"

#: swift/account/reaper.py:253
#, python-format
msgid ", %s objects remaining"
msgstr ", осталось объектов: %s"

#: swift/account/reaper.py:255
#, python-format
msgid ", %s containers possibly remaining"
msgstr ", осталось контейнеров (возможно): %s"

#: swift/account/reaper.py:258
#, python-format
msgid ", %s objects possibly remaining"
msgstr ", осталось объектов (возможно): %s"

#: swift/account/reaper.py:261
msgid ", return codes: "
msgstr ", коды возврата: "

#: swift/account/reaper.py:265
#, python-format
msgid ", elapsed: %.02fs"
msgstr ", прошло: %.02fs"

#: swift/account/reaper.py:320 swift/account/reaper.py:355
#: swift/account/reaper.py:406 swift/container/updater.py:277
#, python-format
msgid "Exception with %(ip)s:%(port)s/%(device)s"
msgstr "Исключительная ситуация в %(ip)s:%(port)s/%(device)s"

#: swift/account/reaper.py:333
#, python-format
msgid ""
"Exception with objects for container %(container)s for account %(account)s"
msgstr ""
"Исключительная ситуация в объектах для контейнера %(container)s для учетной "
"записи %(account)s"

#: swift/account/server.py:309 swift/container/server.py:397
#: swift/obj/server.py:597
#, python-format
msgid "ERROR __call__ error with %(method)s %(path)s "
msgstr "Ошибка: ошибка __call__ в %(method)s %(path)s "

#: swift/auth/server.py:96 swift/common/middleware/swauth.py:94
msgid "No super_admin_key set in conf file! Exiting."
msgstr "В конфигурационном файле не задано super_admin_key ! Выход."

#: swift/auth/server.py:152
#, python-format
msgid ""
"\n"
"THERE ARE ACCOUNTS IN YOUR auth.db THAT DO NOT BEGIN WITH YOUR NEW RESELLER\n"
"PREFIX OF \"%(reseller)s\".\n"
"YOU HAVE A FEW OPTIONS:\n"
"    1. RUN \"swift-auth-update-reseller-prefixes %(db_file)s "
"%(reseller)s\",\n"
"       \"swift-init auth-server restart\", AND\n"
"       \"swift-auth-recreate-accounts -K ...\" TO CREATE FRESH ACCOUNTS.\n"
"    OR\n"
"    2. REMOVE %(db_file)s, RUN \"swift-init auth-server restart\", AND RUN\n"
"       \"swift-auth-add-user ...\" TO CREATE BRAND NEW ACCOUNTS THAT WAY.\n"
"    OR\n"
"    3. ADD \"reseller_prefix = %(previous)s\" (WITHOUT THE QUOTES) TO YOUR\n"
"       proxy-server.conf IN THE [filter:auth] SECTION AND TO YOUR\n"
"       auth-server.conf IN THE [app:auth-server] SECTION AND RUN\n"
"       \"swift-init proxy-server restart\" AND \"swift-init auth-server "
"restart\"\n"
"       TO REVERT BACK TO YOUR PREVIOUS RESELLER PREFIX.\n"
"\n"
"    %(note)s\n"
"                    "
msgstr ""

#: swift/auth/server.py:173
msgid ""
"\n"
"    SINCE YOUR PREVIOUS RESELLER PREFIX WAS AN EMPTY STRING, IT IS NOT\n"
"    RECOMMENDED TO PERFORM OPTION 3 AS THAT WOULD MAKE SUPPORTING MULTIPLE\n"
"    RESELLERS MORE DIFFICULT.\n"
"                    "
msgstr ""

#: swift/auth/server.py:178
msgid "CRITICAL: "
msgstr "КРИТИЧНО: "

#: swift/auth/server.py:213
#, python-format
msgid "ERROR attempting to create account %(url)s: %(status)s %(reason)s"
msgstr ""
"ОШИБКА при попытке создания учётной записи %(url)s: %(status)s %(reason)s"

#: swift/auth/server.py:346
#, python-format
msgid ""
"ALREADY EXISTS create_user(%(account)s, %(user)s, _, %(admin)s, "
"%(reseller_admin)s) [%(elapsed).02f]"
msgstr ""
"УЖЕ СУЩЕСТВУЕТ create_user(%(account)s, %(user)s, _, %(admin)s, "
"%(reseller_admin)s) [%(elapsed).02f]"

#: swift/auth/server.py:364
#, python-format
msgid ""
"FAILED create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"[%(elapsed).02f]"
msgstr ""
"СБОЙ create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"[%(elapsed).02f]"

#: swift/auth/server.py:381
#, python-format
msgid ""
"SUCCESS create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"= %(url)s [%(elapsed).02f]"
msgstr ""
"УСПЕШНО create_user(%(account)s, %(user)s, _, %(admin)s, %(reseller_admin)s) "
"= %(url)s [%(elapsed).02f]"

#: swift/auth/server.py:656
msgid "ERROR Unhandled exception in ReST request"
msgstr "ОШИБКА Необрабатываемое исключение в запросе ReST"

#: swift/common/bench.py:85
#, python-format
msgid "%(complete)s %(title)s [%(fail)s failures], %(rate).01f/s"
msgstr "%(complete)s %(title)s [%(fail)s failures], %(rate).01f/s"

#: swift/common/bench.py:97
msgid "CannotSendRequest.  Skipping..."
msgstr "Невозможно послать запрос.  Пропускается..."

#: swift/common/bufferedhttp.py:96
#, python-format
msgid ""
"HTTP PERF: %(time).5f seconds to %(method)s %(host)s:%(port)s %(path)s)"
msgstr ""

#: swift/common/db.py:299
msgid "Broker error trying to rollback locked connection"
msgstr "Ошибка посредника при попытке отката заблокированного соединения"

#: swift/common/db.py:754 swift/common/db.py:1221
#, python-format
msgid "Invalid pending entry %(file)s: %(entry)s"
msgstr "Недопустимая ожидающая запись %(file)s: %(entry)s"

#: swift/common/db_replicator.py:84
#, python-format
msgid "ERROR reading HTTP response from %s"
msgstr "Ошибка чтения ответа HTTP из %s"

#: swift/common/db_replicator.py:123
#, python-format
msgid ""
"Attempted to replicate %(count)d dbs in %(time).5f seconds (%(rate).5f/s)"
msgstr ""
"Попытка репликации %(count)d баз данных за %(time).5f секунд (%(rate).5f/s)"

#: swift/common/db_replicator.py:129
#, python-format
msgid "Removed %(remove)d dbs"
msgstr "Удалено баз данных: %(remove)d"

#: swift/common/db_replicator.py:130
#, python-format
msgid "%(success)s successes, %(failure)s failures"
msgstr "%(success)s успешно, %(failure)s с ошибками"

#: swift/common/db_replicator.py:155
#, python-format
msgid "ERROR rsync failed with %(code)s: %(args)s"
msgstr "Ошибка: команда rsync не выполнена с кодом %(code)s: %(args)s"

#: swift/common/db_replicator.py:205
#, python-format
msgid "Syncing chunks with %s"
msgstr "Синхронизация фрагментов данных с %s"

#: swift/common/db_replicator.py:213
#, python-format
msgid "ERROR Bad response %(status)s from %(host)s"
msgstr "Ошибка: Неправильный запрос %(status)s из %(host)s"

#: swift/common/db_replicator.py:278
#, python-format
msgid "ERROR Unable to connect to remote server: %s"
msgstr "ОШИБКА: Невозможно подключиться к удалённому серверу: %s"

#: swift/common/db_replicator.py:316
#, python-format
msgid "Replicating db %s"
msgstr "Копирование БД %s"

#: swift/common/db_replicator.py:325 swift/common/db_replicator.py:479
#, python-format
msgid "Quarantining DB %s"
msgstr "БД %s помещена в карантин"

#: swift/common/db_replicator.py:328
#, python-format
msgid "ERROR reading db %s"
msgstr "Ошибка чтения базы данных %s"

#: swift/common/db_replicator.py:361
#, python-format
msgid "ERROR Remote drive not mounted %s"
msgstr "Ошибка: удаленный накопитель не смонтирован %s"

#: swift/common/db_replicator.py:363
#, python-format
msgid "ERROR syncing %(file)s with node %(node)s"
msgstr "Ошибка синхронизации %(file)s с узлом %(node)s"

#: swift/common/db_replicator.py:405
msgid "ERROR Failed to get my own IPs?"
msgstr "Ошибка: не удалось получить собственные IP-адреса?"

#: swift/common/db_replicator.py:412
#, python-format
msgid "Skipping %(device)s as it is not mounted"
msgstr "%(device)s будет пропущен, так как он не смонтирован"

#: swift/common/db_replicator.py:420
msgid "Beginning replication run"
msgstr "Запуск репликации"

#: swift/common/db_replicator.py:425
msgid "Replication run OVER"
msgstr "Репликация запущена поверх"

#: swift/common/db_replicator.py:436
msgid "ERROR trying to replicate"
msgstr "Ошибка при попытке репликации"

#: swift/common/memcached.py:69
#, python-format
msgid "Timeout %(action)s to memcached: %(server)s"
msgstr "Тайм-аут действия %(action)s для сохранения в кэш памяти: %(server)s"

#: swift/common/memcached.py:72
#, python-format
msgid "Error %(action)s to memcached: %(server)s"
msgstr "Ошибка действия %(action)s для сохранения в кэш памяти: %(server)s"

#: swift/common/memcached.py:81
#, python-format
msgid "Error limiting server %s"
msgstr "Ошибка ограничения сервера %s"

#: swift/common/utils.py:88
#, python-format
msgid "Unable to locate %s in libc.  Leaving as a no-op."
msgstr "Не удалось найти %s в libc.  Оставлено как no-op."

#: swift/common/utils.py:255
msgid "STDOUT: Connection reset by peer"
msgstr "STDOUT: Соединение сброшено сервером"

#: swift/common/utils.py:257 swift/common/utils.py:260
#, python-format
msgid "STDOUT: %s"
msgstr "STDOUT: %s"

#: swift/common/utils.py:324
msgid "Connection refused"
msgstr "Соединение отклонено"

#: swift/common/utils.py:326
msgid "Host unreachable"
msgstr "Хост недоступен"

#: swift/common/utils.py:328
msgid "Connection timeout"
msgstr "Тайм-аут соединения"

#: swift/common/utils.py:464
msgid "UNCAUGHT EXCEPTION"
msgstr "Необрабатываемая исключительная ситуация"

#: swift/common/utils.py:511
msgid "Error: missing config file argument"
msgstr "Ошибка: отсутствует аргумент конфигурационного файла"

#: swift/common/utils.py:516
#, python-format
msgid "Error: unable to locate %s"
msgstr "Ошибка: не удалось найти %s"

#: swift/common/utils.py:743
#, python-format
msgid "Unable to read config file %s"
msgstr "Невозможно прочитать конфигурационный файл %s"

#: swift/common/utils.py:749
#, python-format
msgid "Unable to find %s config section in %s"
msgstr "Не удалось найти раздел конфигурации %s в %s"

#: swift/common/middleware/catch_errors.py:39
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"

#: swift/common/middleware/cname_lookup.py:91
#, python-format
msgid "Mapped %(given_domain)s to %(found_domain)s"
msgstr "Преобразовано %(given_domain)s в %(found_domain)s"

#: swift/common/middleware/cname_lookup.py:102
#, python-format
msgid "Following CNAME chain for  %(given_domain)s to %(found_domain)s"
msgstr "Следующая цепочка CNAME для %(given_domain)s в %(found_domain)s"

#: swift/common/middleware/ratelimit.py:172
msgid "Returning 497 because of blacklisting"
msgstr ""

#: swift/common/middleware/ratelimit.py:185
#, python-format
msgid ""
"Ratelimit sleep log: %(sleep)s for %(account)s/%(container)s/%(object)s"
msgstr ""
"Протокол тайм-аута при ограничении скорости %(sleep)s для "
"%(account)s/%(container)s/%(object)s"

#: swift/common/middleware/ratelimit.py:192
#, python-format
msgid "Returning 498 because of ops rate limiting (Max Sleep) %s"
msgstr ""

#: swift/common/middleware/ratelimit.py:212
msgid "Warning: Cannot ratelimit without a memcached client"
msgstr ""
"Предупреждение: не удается ограничить скорость без клиента с кэшированием "
"памяти"

#: swift/common/middleware/swauth.py:635
#, python-format
msgid ""
"ERROR: Exception while trying to communicate with "
"%(scheme)s://%(host)s:%(port)s/%(path)s"
msgstr ""
"ОШИБКА: Исключительная ситуация при попытке связи с "
"%(scheme)s://%(host)s:%(port)s/%(path)s"

#: swift/container/auditor.py:54 swift/container/auditor.py:78
#, python-format
msgid ""
"Since %(time)s: Container audits: %(pass)s passed audit, %(fail)s failed "
"audit"
msgstr ""
"Выполнено проверок контейнера: %(time)s, из них успешно: %(pass)s, с "
"ошибками: %(fail)s"

#: swift/container/auditor.py:68
msgid "Begin container audit \"once\" mode"
msgstr "Начать проверку контейнера в \"однократном\" режиме"

#: swift/container/auditor.py:88
#, python-format
msgid "Container audit \"once\" mode completed: %.02fs"
msgstr "Проверка контейнера в \"однократном\" режиме завершена: %.02fs"

#: swift/container/auditor.py:106
#, python-format
msgid "ERROR Could not get container info %s"
msgstr "Ошибка: не удалось получить информацию о контейнере %s"

#: swift/container/server.py:114
#, python-format
msgid ""
"ERROR Account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): Response %(status)s %(reason)s"
msgstr ""
"Ошибка: обновление учетной записи не выполнено для "
"%(ip)s:%(port)s/%(device)s (операция будет повторена позднее): Ответ: "
"%(status)s %(reason)s"

#: swift/container/server.py:122
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later)"
msgstr ""
"Ошибка: обновление учетной записи не выполнено для "
"%(ip)s:%(port)s/%(device)s (операция будет повторена позднее)"

#: swift/container/updater.py:78 swift/obj/replicator.py:492
#, python-format
msgid "%s is not mounted"
msgstr "%s не смонтирован"

#: swift/container/updater.py:97
#, python-format
msgid "ERROR with loading suppressions from %s: "
msgstr "Ошибка при загрузки скрытых объектов из %s: "

#: swift/container/updater.py:107
msgid "Begin container update sweep"
msgstr "Начать сплошную проверку обновлений контейнера"

#: swift/container/updater.py:140
#, python-format
msgid ""
"Container update sweep of %(path)s completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""
"Сплошная проверка обновлений контейнера в %(path)s завершена: "
"%(elapsed).02fs, успешно: %(success)s, сбоев: %(fail)s, без изменений: "
"%(no_change)s"

#: swift/container/updater.py:154
#, python-format
msgid "Container update sweep completed: %.02fs"
msgstr "Сплошная проверка обновлений контейнера завершена: %.02fs"

#: swift/container/updater.py:164
msgid "Begin container update single threaded sweep"
msgstr "Начать однонитевую сплошную проверку обновлений контейнера"

#: swift/container/updater.py:172
#, python-format
msgid ""
"Container update single threaded sweep completed: %(elapsed).02fs, "
"%(success)s successes, %(fail)s failures, %(no_change)s with no changes"
msgstr ""
"Сплошная однонитевая проверка обновлений контейнера завершена: "
"%(elapsed).02fs, успешно: %(success)s, сбоев: %(fail)s, без изменений: "
"%(no_change)s"

#: swift/container/updater.py:224
#, python-format
msgid "Update report sent for %(container)s %(dbfile)s"
msgstr "Отчет об обновлении отправлен для %(container)s %(dbfile)s"

#: swift/container/updater.py:232
#, python-format
msgid "Update report failed for %(container)s %(dbfile)s"
msgstr "Отчет об обновлении для %(container)s %(dbfile)s не выполнен"

#: swift/container/updater.py:266
#, python-format
msgid ""
"ERROR account update failed with %(ip)s:%(port)s/%(device)s (will retry "
"later): "
msgstr ""
"Ошибка: обновление учетной записи не выполнено для "
"%(ip)s:%(port)s/%(device)s (операция будет повторена позднее): "

#: swift/obj/auditor.py:61
#, python-format
msgid "Begin object audit \"%s\" mode"
msgstr ""

#: swift/obj/auditor.py:73
#, python-format
msgid ""
"Since %(start_time)s: Locally: %(passes)d passed audit, %(quars)d "
"quarantined, %(errors)d errors files/sec: %(frate).2f , bytes/sec: "
"%(brate).2f"
msgstr ""

#: swift/obj/auditor.py:90
#, python-format
msgid ""
"Object audit \"%(mode)s\" mode completed: %(elapsed).02fs. Total files/sec: "
"%(frate).2f , Total bytes/sec: %(brate).2f "
msgstr ""

#: swift/obj/auditor.py:141
#, python-format
msgid "ERROR Object %(obj)s failed audit and will be quarantined: %(err)s"
msgstr ""
"ОШИБКА Сбой аудита объекта %(obj)s, объект будет помещён в карантин: %(err)s"

#: swift/obj/auditor.py:150
#, python-format
msgid "ERROR Trying to audit %s"
msgstr "Ошибка при попытке контроля %s"

#: swift/obj/replicator.py:182
msgid "Error hashing suffix"
msgstr "Ошибка хэширования суффикса"

#: swift/obj/replicator.py:246
#, python-format
msgid "Killing long-running rsync: %s"
msgstr "Принудительное завершение долго выполняющегося rsync: %s"

#: swift/obj/replicator.py:257
#, python-format
msgid "Bad rsync return code: %(args)s -> %(ret)d"
msgstr ""

#: swift/obj/replicator.py:261 swift/obj/replicator.py:265
#, python-format
msgid "Successful rsync of %(src)s at %(dst)s (%(time).03f)"
msgstr "Успешное выполнение rsync для %(src)s на %(dst)s (%(time).03f)"

#: swift/obj/replicator.py:350
#, python-format
msgid "Removing partition: %s"
msgstr "Удаление раздела: %s"

#: swift/obj/replicator.py:353
msgid "Error syncing handoff partition"
msgstr "Ошибка при синхронизации раздела передачи управления"

#: swift/obj/replicator.py:383
#, python-format
msgid "%(ip)s/%(device)s responded as unmounted"
msgstr "Ответили как размонтированные: %(ip)s/%(device)s"

#: swift/obj/replicator.py:388
#, python-format
msgid "Invalid response %(resp)s from %(ip)s"
msgstr "Недопустимый ответ %(resp)s от %(ip)s"

#: swift/obj/replicator.py:410
#, python-format
msgid "Error syncing with node: %s"
msgstr "Ошибка синхронизации с узлом %s"

#: swift/obj/replicator.py:414
msgid "Error syncing partition"
msgstr "Ошибка синхронизации раздела"

#: swift/obj/replicator.py:424
#, python-format
msgid ""
"%(replicated)d/%(total)d (%(percentage).2f%%) partitions replicated in "
"%(time).2fs (%(rate).2f/sec, %(remaining)s remaining)"
msgstr ""
"Реплицировано разделов: %(replicated)d/%(total)d (%(percentage).2f%%) за "
"время %(time).2f с (%(rate).2f/с, осталось: %(remaining)s)"

#: swift/obj/replicator.py:433
#, python-format
msgid ""
"%(checked)d suffixes checked - %(hashed).2f%% hashed, %(synced).2f%% synced"
msgstr ""
"Проверено суффиксов: %(checked)d - хэшировано: %(hashed).2f%%, "
"синхронизировано: %(synced).2f%%"

#: swift/obj/replicator.py:439
#, python-format
msgid "Partition times: max %(max).4fs, min %(min).4fs, med %(med).4fs"
msgstr ""
"Время раздела: максимум: %(max).4fs, минимум: %(min).4fs, среднее: %(med).4fs"

#: swift/obj/replicator.py:446
#, python-format
msgid "Nothing replicated for %s seconds."
msgstr "Ничего не реплицировано за %s с."

#: swift/obj/replicator.py:475
msgid "Lockup detected.. killing live coros."
msgstr ""
"Обнаружена блокировка.. принудительное завершение работающих модулей."

#: swift/obj/replicator.py:530
msgid "Ring change detected. Aborting current replication pass."
msgstr ""
"Обнаружено кольцевое изменение. Принудительное завершение текущего прохода "
"репликации."

#: swift/obj/replicator.py:540
msgid "Exception in top-level replication loop"
msgstr "Исключительная ситуация в цикле репликации верхнего уровня"

#: swift/obj/replicator.py:549
msgid "Running object replicator in script mode."
msgstr "Запуск утилиты репликации объектов в режиме сценариев."

#: swift/obj/replicator.py:553 swift/obj/replicator.py:565
#, python-format
msgid "Object replication complete. (%.02f minutes)"
msgstr "Репликация объекта выполнена. (%.02f мин.)"

#: swift/obj/replicator.py:560
msgid "Starting object replication pass."
msgstr "Запуск прохода репликации объектов."

#: swift/obj/replicator.py:566
#, python-format
msgid "Replication sleeping for %s seconds."
msgstr "Копирование в режиме ожидания %s секунд."

#: swift/obj/server.py:313
#, python-format
msgid ""
"ERROR Container update failed (saving for async update later): %(status)d "
"response from %(ip)s:%(port)s/%(dev)s"
msgstr ""
"Ошибка. Обновление контейнера не выполнено (сохранение асинхронных "
"обновлений будет выполнено позднее): %(status)d ответ от "
"%(ip)s:%(port)s/%(dev)s"

#: swift/obj/server.py:319
#, python-format
msgid ""
"ERROR container update failed with %(ip)s:%(port)s/%(dev)s (saving for async "
"update later)"
msgstr ""
"Ошибка. Обновление контейнера не выполнена с %(ip)s:%(port)s/%(dev)s "
"(сохранение асинхронного обновления будет выполнено позднее)"

#: swift/obj/updater.py:65
msgid "Begin object update sweep"
msgstr "Начать сплошную проверку обновлений объекта"

#: swift/obj/updater.py:89
#, python-format
msgid ""
"Object update sweep of %(device)s completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures"
msgstr ""
"Сплошная проверка обновлений объекта на устройстве %(device)s завершена: "
"%(elapsed).02fs, успешно: %(success)s, ошибка: %(fail)s"

#: swift/obj/updater.py:98
#, python-format
msgid "Object update sweep completed: %.02fs"
msgstr "Сплошная проверка обновлений объекта завершена: %.02fs"

#: swift/obj/updater.py:105
msgid "Begin object update single threaded sweep"
msgstr "Начать однонитевую сплошную проверку обновлений объекта"

#: swift/obj/updater.py:117
#, python-format
msgid ""
"Object update single threaded sweep completed: %(elapsed).02fs, %(success)s "
"successes, %(fail)s failures"
msgstr ""
"Сплошная однонитевая проверка обновлений объекта завершена: %(elapsed).02fs, "
"%(success)s успешно, %(fail)s с ошибками"

#: swift/obj/updater.py:157
#, python-format
msgid "ERROR Pickle problem, quarantining %s"
msgstr "Ошибка Pickle, %s помещается в карантин"

#: swift/obj/updater.py:177
#, python-format
msgid "Update sent for %(obj)s %(path)s"
msgstr "Обновление для %(obj)s %(path)s"

#: swift/obj/updater.py:182
#, python-format
msgid "Update failed for %(obj)s %(path)s"
msgstr "Ошибка обновления %(obj)s %(path)s"

#: swift/obj/updater.py:206
#, python-format
msgid "ERROR with remote server %(ip)s:%(port)s/%(device)s"
msgstr "Ошибка с удаленным сервером %(ip)s:%(port)s/%(device)s"

#: swift/proxy/server.py:165 swift/proxy/server.py:629
#: swift/proxy/server.py:696 swift/proxy/server.py:712
#: swift/proxy/server.py:721 swift/proxy/server.py:1004
#: swift/proxy/server.py:1044 swift/proxy/server.py:1089
msgid "Object"
msgstr "Объект"

#: swift/proxy/server.py:170
#, python-format
msgid "Could not load object segment %(path)s: %(status)s"
msgstr "Невозможно загрузить сегмент объекта %(path)s: %(status)s"

#: swift/proxy/server.py:177 swift/proxy/server.py:210
#: swift/proxy/server.py:257
#, python-format
msgid "ERROR: While processing manifest /%(acc)s/%(cont)s/%(obj)s"
msgstr "ОШИБКА: во время обработки манифеста /%(acc)s/%(cont)s/%(obj)s"

#: swift/proxy/server.py:292
#, python-format
msgid "%(msg)s %(ip)s:%(port)s"
msgstr "%(msg)s %(ip)s:%(port)s"

#: swift/proxy/server.py:304
#, python-format
msgid "ERROR with %(type)s server %(ip)s:%(port)s/%(device)s re: %(info)s"
msgstr ""
"Ошибка с сервером %(type)s %(ip)s:%(port)s/%(device)s, возврат: %(info)s"

#: swift/proxy/server.py:328
#, python-format
msgid "Node error limited %(ip)s:%(port)s (%(device)s)"
msgstr "Ограниченная ошибка узла %(ip)s:%(port)s (%(device)s)"

#: swift/proxy/server.py:388 swift/proxy/server.py:1451
#: swift/proxy/server.py:1497 swift/proxy/server.py:1545
#: swift/proxy/server.py:1590
msgid "Account"
msgstr "Учетная запись"

#: swift/proxy/server.py:389
#, python-format
msgid "Trying to get account info for %s"
msgstr "Попытка получения сведений об учётной записи для %s"

#: swift/proxy/server.py:466 swift/proxy/server.py:740
#: swift/proxy/server.py:772 swift/proxy/server.py:1214
#: swift/proxy/server.py:1301 swift/proxy/server.py:1356
#: swift/proxy/server.py:1413
msgid "Container"
msgstr "контейнер"

#: swift/proxy/server.py:467
#, python-format
msgid "Trying to get container info for %s"
msgstr "Попытка получения сведений о контейнере для %s"

#: swift/proxy/server.py:552
#, python-format
msgid "%(type)s returning 503 for %(statuses)s"
msgstr "%(type)s возвратил 503 для %(statuses)s"

#: swift/proxy/server.py:598 swift/proxy/server.py:697
#, python-format
msgid "Trying to %(method)s %(path)s"
msgstr "Попытка выполнения метода %(method)s %(path)s"

#: swift/proxy/server.py:627
msgid "Client disconnected on read"
msgstr "Клиент отключен во время чтения"

#: swift/proxy/server.py:630
#, python-format
msgid "Trying to read during GET of %s"
msgstr ""

#: swift/proxy/server.py:653
#, python-format
msgid "ERROR %(status)d %(body)s From %(type)s Server"
msgstr "Ошибка %(status)d %(body)s из сервера %(type)s"

#: swift/proxy/server.py:692
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server"
msgstr ""

#: swift/proxy/server.py:776 swift/proxy/server.py:783
#, python-format
msgid "Object manifest GET could not continue listing: %s %s"
msgstr ""

#: swift/proxy/server.py:905
msgid "Object POST"
msgstr "Объект POST"

#: swift/proxy/server.py:1005
#, python-format
msgid "Expect: 100-continue on %s"
msgstr "Ожидаемое значение: 100-continue в %s"

#: swift/proxy/server.py:1017
#, python-format
msgid "Object PUT returning 503, %(conns)s/%(nodes)s required connections"
msgstr ""

#: swift/proxy/server.py:1045
#, python-format
msgid "Trying to write to %s"
msgstr "Попытка записи в %s"

#: swift/proxy/server.py:1049
#, python-format
msgid ""
"Object PUT exceptions during send, %(conns)s/%(nodes)s required connections"
msgstr ""

#: swift/proxy/server.py:1058
#, python-format
msgid "ERROR Client read timeout (%ss)"
msgstr "Ошибка: тайм-аут чтения клиента (%ss)"

#: swift/proxy/server.py:1063
msgid "ERROR Exception causing client disconnect"
msgstr "Ошибка. Исключительная ситуация при отключении клиента"

#: swift/proxy/server.py:1068
msgid "Client disconnected without sending enough data"
msgstr "Клиент отключен без отправки данных"

#: swift/proxy/server.py:1083
#, python-format
msgid "ERROR %(status)d %(body)s From Object Server re: %(path)s"
msgstr "Ошибка %(status)d %(body)s, ответ от сервера объекта: %(path)s"

#: swift/proxy/server.py:1090
#, python-format
msgid "Trying to get final status of PUT to %s"
msgstr "Попытка получения конечного состояния PUT в %s"

#: swift/proxy/server.py:1093
#, python-format
msgid "Object servers returned %s mismatched etags"
msgstr "Серверы объектов вернули несоответствующие etag: %s"

#: swift/proxy/server.py:1101
msgid "Object PUT"
msgstr "Функция PUT объекта"

#: swift/proxy/server.py:1153
msgid "Object DELETE"
msgstr "Объект DELETE"

#: swift/proxy/server.py:1302 swift/proxy/server.py:1498
#, python-format
msgid "Trying to PUT to %s"
msgstr ""

#: swift/proxy/server.py:1314
msgid "Container PUT"
msgstr "Контейнер PUT"

#: swift/proxy/server.py:1357 swift/proxy/server.py:1546
#, python-format
msgid "Trying to POST %s"
msgstr "Попытка POST %s"

#: swift/proxy/server.py:1369
msgid "Container POST"
msgstr "Контейнер POST"

#: swift/proxy/server.py:1414 swift/proxy/server.py:1591
#, python-format
msgid "Trying to DELETE %s"
msgstr "Попытка DELETE %s"

#: swift/proxy/server.py:1426
msgid "Container DELETE"
msgstr "Контейнер DELETE"

#: swift/proxy/server.py:1433
msgid "Returning 503 because not all container nodes confirmed DELETE"
msgstr "Возвращено 503, поскольку не все узлы контейнера подтвердили DELETE"

#: swift/proxy/server.py:1508
msgid "Account PUT"
msgstr ""

#: swift/proxy/server.py:1556
msgid "Account POST"
msgstr ""

#: swift/proxy/server.py:1601
msgid "Account DELETE"
msgstr ""

#: swift/proxy/server.py:1757
msgid "ERROR Unhandled exception in request"
msgstr "Ошибка. Необрабатываемая исключительная ситуация в запросе"

#: swift/stats/access_processor.py:63 swift/stats/stats_processor.py:40
#, python-format
msgid "Bad line data: %s"
msgstr "Недопустимые строковые данные: %s"

#: swift/stats/access_processor.py:67
#, python-format
msgid "Bad server name: found \"%(found)s\" expected \"%(expected)s\""
msgstr ""
"Недопустимое имя сервера: полученное \"%(found)s\" ожидаемое \"%(expected)s\""

#: swift/stats/access_processor.py:75
#, python-format
msgid "Invalid path: %(error)s from data: %(log)s"
msgstr "Недопустимый путь: %(error)s в данных: %(log)s"

#: swift/stats/access_processor.py:199
#, python-format
msgid ""
"I found a bunch of bad lines in %(name)s (%(bad)d bad, %(total)d total)"
msgstr ""
"Обнаружено множество недопустимых строк в %(name)s (%(bad)d bad, %(total)d "
"total)"

#: swift/stats/account_stats.py:55
msgid "Gathering account stats"
msgstr "Сбор данных о статусе учетных записей"

#: swift/stats/account_stats.py:59
#, python-format
msgid "Gathering account stats complete (%0.2f minutes)"
msgstr "Сбор данных о статусе учетных записей завершён (%0.2f minutes)"

#: swift/stats/account_stats.py:75
#, python-format
msgid "Device %s is not mounted, skipping."
msgstr "Устройство %s не подсоединено, пропуск."

#: swift/stats/account_stats.py:81
#, python-format
msgid "Path %s does not exist, skipping."
msgstr "Адрес %s не существует, пропуск."

#: swift/stats/log_processor.py:62
#, python-format
msgid "Loaded plugin \"%s\""
msgstr "Загружена надстройка \"%s\""

#: swift/stats/log_processor.py:79
#, python-format
msgid "Processing %(obj)s with plugin \"%(plugin)s\""
msgstr "Обработка %(obj)s с надстройкой \"%(plugin)s\""

#: swift/stats/log_processor.py:179
#, python-format
msgid "Bad compressed data for %s"
msgstr "Повреждённые сжатые данные %s"

#: swift/stats/log_processor.py:240
msgid "Beginning log processing"
msgstr "Начало обработки журнала событий"

#: swift/stats/log_processor.py:278
#, python-format
msgid "found %d processed files"
msgstr "обнаружено %d обработанных файлов"

#: swift/stats/log_processor.py:283
#, python-format
msgid "loaded %d files to process"
msgstr "загружено %d файлов на обработку"

#: swift/stats/log_processor.py:286 swift/stats/log_processor.py:360
#, python-format
msgid "Log processing done (%0.2f minutes)"
msgstr "Обработка журнала событий завершена (%0.2f минут)"

#: swift/stats/log_uploader.py:71
msgid "Uploading logs"
msgstr "Выгрузка отчётов"

#: swift/stats/log_uploader.py:74
#, python-format
msgid "Uploading logs complete (%0.2f minutes)"
msgstr "Выгрузка отчётов завершена (%0.2f минут)"

#: swift/stats/log_uploader.py:129
#, python-format
msgid "Unexpected log: %s"
msgstr "Непредвиденный журнал: %s"

#: swift/stats/log_uploader.py:135
#, python-format
msgid "Skipping log: %(file)s (< %(cutoff)d seconds old)"
msgstr ""

#: swift/stats/log_uploader.py:142
#, python-format
msgid "Log %s is 0 length, skipping"
msgstr "Журнал %s - пустой, пропустить"

#: swift/stats/log_uploader.py:144
#, python-format
msgid "Processing log: %s"
msgstr "Обработка отчёта: %s"

#: swift/stats/log_uploader.py:165
#, python-format
msgid "Uploaded log %(file)s to %(target)s"
msgstr "Загружено журналов %(file)s в %(target)s"

#: swift/stats/log_uploader.py:170
#, python-format
msgid "ERROR: Upload of log %s failed!"
msgstr "ОШИБКА: Сбой загрузки журнала %s !"
