msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-12-01 22:25+0000\n"
"PO-Revision-Date: 2021-12-16 14:53\n"
"Last-Translator: XiveZ <kyrsant2008@list.ru>\n"
"Language-Team: Belarusian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2021-12-16 08:32+0000\n"
"X-Generator: Launchpad (build cd8f08e7e7c160b1710e2cad6ba032fb74527860)\n"
"Language: be\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || n%10>=5 && n%10<=9 || n%100>=11 && n%100<=14 ? 2 : 3);\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-Language: be\n"
"X-Crowdin-File: /main/jammy/en_GB/po_apport-be.po\n"
"X-Crowdin-File-ID: 41\n"

#: ../debian/tmp/usr/share/apport/kernel_oops.py:29 ../data/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr "Сістэма можа стаць нестабільнай, магчыма спатрэбіцца перазагрузка."

#: ../gtk/apport-gtk.ui.h:1 ../debian/tmp/usr/share/apport/apport-kde.py:469
#: ../debian/tmp/usr/share/apport/apport-kde.py:504
#: ../debian/tmp/usr/share/apport/apport-kde.py:524
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1 ../kde/apport-kde.py:469
#: ../kde/apport-kde.py:504 ../kde/apport-kde.py:524
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Скасаваць"

#: ../gtk/apport-gtk.ui.h:3 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3
msgid "OK"
msgstr "Добра"

#: ../gtk/apport-gtk.ui.h:4 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Справаздача аб непаладцы"

#: ../gtk/apport-gtk.ui.h:5 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>Выбачайце, паўстала ўнутраная памылка.</b></big>"

#: ../gtk/apport-gtk.ui.h:6 ../bin/apport-cli.py:194 ../gtk/apport-gtk.py:181
#: ../debian/tmp/usr/share/apport/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/bin/apport-cli.py:194 ../kde/apport-kde.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.py:181
msgid "Send problem report to the developers?"
msgstr "Даслаць распрацоўшчыкам паведамленне аб праблеме?"

#: ../gtk/apport-gtk.ui.h:7 ../gtk/apport-gtk.py:297
#: ../debian/tmp/usr/share/apport/apport-kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7 ../kde/apport-kde.py:241
#: ../debian/tmp/usr/share/apport/apport-gtk.py:297
msgid "If you notice further problems, try restarting the computer."
msgstr "Калі праблема з'явіцца зноў, паспрабуйце перазагрузіць кампутар."

#: ../gtk/apport-gtk.ui.h:8 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../gtk/apport-gtk.ui.h:9 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "Ігнараваць далейшыя збоі ў гэтай версіі праграмы"

#: ../gtk/apport-gtk.ui.h:10 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../gtk/apport-gtk.ui.h:11 ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:575
#: ../debian/tmp/usr/share/apport/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11 ../kde/apport-kde.py:292
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:575
msgid "Show Details"
msgstr "Паказаць падрабязнасці"

#: ../gtk/apport-gtk.ui.h:12 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_Лакальная праверка"

#: ../gtk/apport-gtk.ui.h:13 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../gtk/apport-gtk.ui.h:14 ../gtk/apport-gtk.py:188
#: ../debian/tmp/usr/share/apport/apport-kde.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../kde/apport-kde.py:194
#: ../debian/tmp/usr/share/apport/apport-gtk.py:188
msgid "Send"
msgstr "Даслаць"

#: ../gtk/apport-gtk.ui.h:15 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>Збор інфармацыі аб няспраўнасці</b></big>"

#: ../gtk/apport-gtk.ui.h:16 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16
msgid "Information is being collected that may help the developers fix the problem you report."
msgstr "Адбываецца збор інфармацыі, якая можа дапамагчы распрацоўшчыкам выправіць гэтую памылку."

#: ../gtk/apport-gtk.ui.h:17 ../bin/apport-cli.py:267
#: ../debian/tmp/usr/share/apport/apport-kde.py:435
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../debian/tmp/usr/bin/apport-cli.py:267 ../kde/apport-kde.py:435
msgid "Uploading problem information"
msgstr "Перадача інфармацыі аб непаладцы"

#: ../gtk/apport-gtk.ui.h:18 ../debian/tmp/usr/share/apport/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Перадача звестак аб няспраўнасці</b></big>"

#: ../gtk/apport-gtk.ui.h:19 ../debian/tmp/usr/share/apport/apport-kde.py:436
#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:19 ../kde/apport-kde.py:436
msgid "The collected information is being sent to the bug tracking system. This might take a few minutes."
msgstr "Сабраныя дадзеныя перасылаюцца ў сістэму ўліку памылак. Гэта можа заняць некалькі хвілін."

#: ../bin/apport-retrace.py:34 ../debian/tmp/usr/bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "Не дадаваць новыя трасіроўкі ў справаздачу, а адсылаць на стандартны вывад."

#: ../bin/apport-retrace.py:36 ../debian/tmp/usr/bin/apport-retrace.py:36
msgid "Start an interactive gdb session with the report's core dump (-o ignored; does not rewrite report)"
msgstr "Запусціць інтэрактыўны сеанс gdb з дампам ядра са справаздачы (-o ігнаруецца; справаздача не перазапісваецца)"

#: ../bin/apport-retrace.py:38 ../debian/tmp/usr/bin/apport-retrace.py:38
msgid "Write modified report to given file instead of changing the original report"
msgstr "Захаваць змененую справаздачу ў файл замест змены арыгінальнай справаздачы"

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "Выдаліць дамп ядра са справаздачы пасля ўзнаўлення трасіроўкі стэка"

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Замяніць CoreFile у справаздачы"

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Замяніць ExecutablePath у справаздачы"

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Замяніць ProcMaps у справаздачы"

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Нанава пабудаваць інфармацыю аб пакетах у справаздачы"

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid "Build a temporary sandbox and download/install the necessary packages and debug symbols in there; without this option it assumes that the necessary packages and debug symbols are already installed in the system. The argument points to the packaging system configuration base directory; if you specify \"system\", it will use the system configuration files, but will then only be able to retrace crashes that happened on the currently running release."
msgstr "Стварыць часавае асяроддзе, затым загрузіць / ўсталяваць у яе неабходныя пакеты і адладкавыя сімвалы; без гэтага параметра прадугледжваецца, што неабходныя пакеты і адладкавыя сімвалы ў сістэме ўжо ўсталяваныя. Аргумент паказвае на базавую тэчку канфігурацыі сістэмы пакетаў; калі Вы паказалі \"system\", будуць выкарыстоўвацца сістэмныя файлы канфігурацыі, але толькі ў выпадку выяўлення аварыйных сітуацый, якія адбыліся ў выпуску сістэмы, які працуе ў дадзены момант."

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid "Build another temporary sandbox for installing gdb and its dependencies using the same release as the report rather than whatever version of gdb you have installed."
msgstr ""

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid "Report download/install progress when installing packages into sandbox"
msgstr "Паведамляць аб ходзе выканання загрузкі / ўсталёўкі пакетаў у часовае асяроддзе"

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "Дадаваць часовыя пазнакі да паведамленняў у часопісе, для групавых аперацый"

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid "Create and use third-party repositories from origins specified in reports"
msgstr "Стварэнне і выкарыстанне іншых сховішчаў на аснове зыходных, указаных у справаздачах"

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "Тэчка для захавання пакетаў, загружаных у часовае асяроддзе"

#: ../bin/apport-retrace.py:63 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid "Directory for unpacked packages. Future runs will assume that any already downloaded package is also extracted to this sandbox."
msgstr "Дырэкторыя для распакавання пакетаў. Пры наступных запусках ўсё ўжо загружаны пакеты будуць распакоўваць ў гэта ізаляванае асяроддзе."

#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-valgrind.py:66
#: ../debian/tmp/usr/bin/apport-retrace.py:65 ../bin/apport-valgrind.py:66
msgid "Install an extra package into the sandbox (can be specified multiple times)"
msgstr "Усталяваць у часовае асяроддзе дадатковы пакет (можа задавацца некалькі разоў)"

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid "Path to a file with the crash database authentication information. This is used when specifying a crash ID to upload the retraced stack traces (only if neither -g, -o, nor -s are specified)"
msgstr "Шлях да файла з інфармацыяй аб праверцы сапраўднасці базы збояў. Выкарыстоўваецца пры ўказанні ID збою для адпраўкі трасіровак стэка (толькі калі -g, -o ці -s не пазначаныя)"

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid "Display retraced stack traces and ask for confirmation before sending them to the crash database."
msgstr "Адлюстраваць трасіроўкі і запытаць пацверджанне перад іх адпраўкай у базу дадзеных збояў."

#: ../bin/apport-retrace.py:71 ../debian/tmp/usr/bin/apport-retrace.py:71
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr "Шлях да дублюючай базы дадзеных sqlite (па змаўчанні: без праверкі дублікатаў)"

#: ../bin/apport-retrace.py:73 ../debian/tmp/usr/bin/apport-retrace.py:73
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../bin/apport-retrace.py:82 ../debian/tmp/usr/bin/apport-retrace.py:82
msgid "You cannot use -C without -S. Stopping."
msgstr "Нельга выкарыстоўваць -C без -S. Прыпынак."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:115 ../debian/tmp/usr/bin/apport-retrace.py:115
msgid "OK to send these as attachments? [y/n]"
msgstr "Адправіць гэтыя дастасаванні? [y/n]"

#: ../kde/apport-kde.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Паведаміць аб праблеме..."

#: ../kde/apport-kde.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Паведаміць аб недапрацоўцы распрацоўшчыкам"

#: ../bin/apport-cli.py:80 ../debian/tmp/usr/bin/apport-cli.py:80
msgid "Press any key to continue..."
msgstr "Каб працягнуць, націсніце любую клавішу ..."

#: ../bin/apport-cli.py:87 ../debian/tmp/usr/bin/apport-cli.py:87
msgid "What would you like to do? Your options are:"
msgstr "Што вы жадаеце зрабіць? Магчымыя варыянты:"

#: ../bin/apport-cli.py:100 ../debian/tmp/usr/bin/apport-cli.py:100
#, python-format
msgid "Please choose (%s):"
msgstr "Калі ласка выберыце (%s):"

#: ../bin/apport-cli.py:164 ../debian/tmp/usr/bin/apport-cli.py:164
#, python-format
msgid "(%i bytes)"
msgstr "(%i байт)"

#: ../bin/apport-cli.py:166 ../gtk/apport-gtk.py:146
#: ../debian/tmp/usr/share/apport/apport-kde.py:363
#: ../debian/tmp/usr/bin/apport-cli.py:166 ../kde/apport-kde.py:363
#: ../debian/tmp/usr/share/apport/apport-gtk.py:146
msgid "(binary data)"
msgstr "(двайковыя дадзеныя)"

#: ../bin/apport-cli.py:195 ../debian/tmp/usr/bin/apport-cli.py:195
msgid "After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr "Пасля таго, як справаздача будзе дасланая, запоўніце\n"
"форму ў акне браўзэра , што адчынілася аўтаматычна."

#: ../bin/apport-cli.py:198 ../debian/tmp/usr/bin/apport-cli.py:198
#, python-format
msgid "&Send report (%s)"
msgstr "&Даслаць паведамленне (%s)"

#: ../bin/apport-cli.py:202 ../debian/tmp/usr/bin/apport-cli.py:202
msgid "&Examine locally"
msgstr "&Локальна перевірка"

#: ../bin/apport-cli.py:206 ../debian/tmp/usr/bin/apport-cli.py:206
msgid "&View report"
msgstr "&Паказаць справаздачу"

#: ../bin/apport-cli.py:207 ../debian/tmp/usr/bin/apport-cli.py:207
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "&Захаваць файл справаздачы для наступнай адпраўкі альбо капіявання куды-небудзь"

#: ../bin/apport-cli.py:208 ../debian/tmp/usr/bin/apport-cli.py:208
msgid "Cancel and &ignore future crashes of this program version"
msgstr "Адмяніць і &ігнараваць будучыя збоі ў гэтай версіі праграмы"

#: ../bin/apport-cli.py:210 ../bin/apport-cli.py:287 ../bin/apport-cli.py:319
#: ../bin/apport-cli.py:340 ../debian/tmp/usr/bin/apport-cli.py:210
#: ../debian/tmp/usr/bin/apport-cli.py:287
#: ../debian/tmp/usr/bin/apport-cli.py:319
#: ../debian/tmp/usr/bin/apport-cli.py:340
msgid "&Cancel"
msgstr "&Скасаваць"

#: ../bin/apport-cli.py:238 ../debian/tmp/usr/bin/apport-cli.py:238
msgid "Problem report file:"
msgstr "Файл справаздачы аб праблеме:"

#: ../bin/apport-cli.py:244 ../bin/apport-cli.py:249
#: ../debian/tmp/usr/bin/apport-cli.py:244
#: ../debian/tmp/usr/bin/apport-cli.py:249
msgid "&Confirm"
msgstr "&Пацвердзіць"

#: ../bin/apport-cli.py:248 ../debian/tmp/usr/bin/apport-cli.py:248
#, python-format
msgid "Error: %s"
msgstr "Памылка: %s"

#: ../bin/apport-cli.py:254 ../debian/tmp/usr/share/apport/apport-kde.py:407
#: ../debian/tmp/usr/bin/apport-cli.py:254 ../kde/apport-kde.py:407
msgid "Collecting problem information"
msgstr "Збор інфармацыі аб праблеме"

#: ../bin/apport-cli.py:255 ../debian/tmp/usr/bin/apport-cli.py:255
msgid "The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr "Сабраная інфармацыя можа быць накіравана распрацоўшчыкам для\n"
"паляпшэння дастасавання. Гэта можа заняць некалькі хвілін."

#: ../bin/apport-cli.py:268 ../debian/tmp/usr/bin/apport-cli.py:268
msgid "The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr "Сабраная інфармацыя накіроўваецца да сістэмы адсочвання памылак.\n"
"Гэта можа заняць некалькі хвілін."

#: ../bin/apport-cli.py:318 ../debian/tmp/usr/bin/apport-cli.py:318
msgid "&Done"
msgstr "&Зроблена"

#: ../bin/apport-cli.py:324 ../debian/tmp/usr/bin/apport-cli.py:324
msgid "none"
msgstr "нічога"

#: ../bin/apport-cli.py:325 ../debian/tmp/usr/bin/apport-cli.py:325
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Абрана: %s. Некалькі варыянтаў:"

#: ../bin/apport-cli.py:341 ../debian/tmp/usr/bin/apport-cli.py:341
msgid "Choices:"
msgstr "Выбар:"

#: ../bin/apport-cli.py:355 ../debian/tmp/usr/bin/apport-cli.py:355
msgid "Path to file (Enter to cancel):"
msgstr "Шлях да файла (Enter — адмена):"

#: ../bin/apport-cli.py:361 ../debian/tmp/usr/bin/apport-cli.py:361
msgid "File does not exist."
msgstr "Файл не існуе."

#: ../bin/apport-cli.py:363 ../debian/tmp/usr/bin/apport-cli.py:363
msgid "This is a directory."
msgstr "Гэта - дырэкторыя."

#: ../bin/apport-cli.py:369 ../debian/tmp/usr/bin/apport-cli.py:369
msgid "To continue, you must visit the following URL:"
msgstr "Каб працягнуць, Вы павінны наведаць наступны адрас:"

#: ../bin/apport-cli.py:371 ../debian/tmp/usr/bin/apport-cli.py:371
msgid "You can launch a browser now, or copy this URL into a browser on another computer."
msgstr "Зараз Вы можаце адкрыць браўзар ці скапіяваць URL у браўзар на іншы кампутар."

#: ../bin/apport-cli.py:373 ../debian/tmp/usr/bin/apport-cli.py:373
msgid "Launch a browser now"
msgstr "Запусціць браўзар"

#: ../bin/apport-cli.py:388 ../debian/tmp/usr/bin/apport-cli.py:388
msgid "No pending crash reports. Try --help for more information."
msgstr "Няма чакаючых паведамленьняў аб збоях. Паспрабуйце ключ --help."

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:200
#: ../data/general-hooks/ubuntu.py:200
msgid "An Ubuntu package has a file conflict with a package that is not a genuine Ubuntu package."
msgstr "Пакет Ubuntu канфліктуе з пакетам, які не з'яўляецца сапраўдным пакетам Ubuntu."

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:208
#: ../data/general-hooks/ubuntu.py:208
msgid "You have already encountered this package installation failure."
msgstr "Памылка з усталёўкай гэтага пакета ўжо адбывалася."

#: ../debian/tmp/usr/share/apport/general-hooks/ubuntu.py:224
#: ../data/general-hooks/ubuntu.py:224
msgid "Your system was initially configured with grub version 2, but you have removed it from your system in favor of grub 1 without configuring it.  To ensure your bootloader configuration is updated whenever a new kernel is available, open a terminal and run:\n\n"
"      sudo apt-get install grub-pc\n"
msgstr "Першапачаткова сістэма была настроена на выкарыстанне загрузчыка GRUB версіі 2, але быў заменены на GRUB 1 і не настроена. Каб пераканацца ў працаздольнасці загрузніка з новымі параметрамі, адкрыйце тэрмінал і выканайце каманду:\n\n"
"      sudo apt-get install grub-pc\n"

#: ../debian/tmp/usr/bin/apport-valgrind.py:37 ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Глядзіце падрабязнасці ў старонках man"

#: ../debian/tmp/usr/bin/apport-valgrind.py:43 ../bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "вызначце імя log файлу valgrind"

#: ../debian/tmp/usr/bin/apport-valgrind.py:46 ../bin/apport-valgrind.py:46
msgid "reuse a previously created sandbox dir (SDIR) or, if it does not exist, create it"
msgstr "выкарыстоўваць раней створаны каталог пясочніцы (SDIR) або стварыць яго калі яго не існуе"

#: ../debian/tmp/usr/bin/apport-valgrind.py:50 ../bin/apport-valgrind.py:50
msgid "do  not  create  or reuse a sandbox directory for additional debug symbols but rely only on installed debug symbols."
msgstr "не ствараць і не выкарыстоўваць каталог пясочніцы для дадатковых сімвалаў адладкі, а спадзявацца толькі на устаноўленыя сімвалы адладкі."

#: ../debian/tmp/usr/bin/apport-valgrind.py:54 ../bin/apport-valgrind.py:54
msgid "reuse a previously created cache dir (CDIR) or, if it does not exist, create it"
msgstr "выкарыстоўваць раней створаны каталог кэша (CDIR) або стварыць яго калі яго не існуе"

#: ../debian/tmp/usr/bin/apport-valgrind.py:58 ../bin/apport-valgrind.py:58
msgid "report download/install progress when installing packages into sandbox"
msgstr "паказваць прагрэс загрузкі/ўстаноўкі пры ўсталёўцы пакетаў у пясочніцу"

#: ../debian/tmp/usr/bin/apport-valgrind.py:62 ../bin/apport-valgrind.py:62
msgid "the executable that is run under valgrind's memcheck tool  for memory leak detection"
msgstr "выкананы файл, які запускаецца пад кантролем valgrind memcheck для вызначэння уцечак памяці"

#: ../debian/tmp/usr/bin/apport-valgrind.py:97 ../bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Памылка: %s - не выканальны файл. Прыпынак."

#: ../gtk/apport-gtk.py:161 ../debian/tmp/usr/share/apport/apport-gtk.py:161
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "Выбачайце, прылада %s нечакана прыпынілася."

#: ../gtk/apport-gtk.py:164 ../debian/tmp/usr/share/apport/apport-gtk.py:164
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "Выбачайце, %s нечакана зачынілася."

#: ../gtk/apport-gtk.py:169 ../debian/tmp/usr/share/apport/apport-kde.py:200
#: ../debian/tmp/usr/share/apport/apport-kde.py:238 ../kde/apport-kde.py:200
#: ../kde/apport-kde.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:169
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "Прабачце, у %s адбылася ўнутраная памылка."

#: ../gtk/apport-gtk.py:216 ../debian/tmp/usr/share/apport/apport-kde.py:231
#: ../debian/tmp/usr/share/apport/apport-kde.py:244 ../kde/apport-kde.py:231
#: ../kde/apport-kde.py:244 ../debian/tmp/usr/share/apport/apport-gtk.py:216
msgid "Continue"
msgstr "Працягнуць"

#: ../gtk/apport-gtk.py:239 ../debian/tmp/usr/share/apport/apport-gtk.py:239
#, python-format
msgid "The application %s has stopped responding."
msgstr "Дадатак %s перастаў адказваць."

#: ../gtk/apport-gtk.py:243 ../debian/tmp/usr/share/apport/apport-gtk.py:243
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Праграма \"%s\" перастала адказваць."

#: ../gtk/apport-gtk.py:259 ../debian/tmp/usr/share/apport/apport-kde.py:208
#: ../kde/apport-kde.py:208 ../debian/tmp/usr/share/apport/apport-gtk.py:259
#, python-format
msgid "Package: %s"
msgstr "Пакет: %s"

#: ../gtk/apport-gtk.py:265 ../debian/tmp/usr/share/apport/apport-kde.py:214
#: ../kde/apport-kde.py:214 ../debian/tmp/usr/share/apport/apport-gtk.py:265
msgid "Sorry, a problem occurred while installing software."
msgstr "Прабачце, пры ўсталяванні адбылася памылка."

#: ../gtk/apport-gtk.py:274 ../gtk/apport-gtk.py:289
#: ../debian/tmp/usr/share/apport/apport-kde.py:220 ../kde/apport-kde.py:220
#: ../debian/tmp/usr/share/apport/apport-gtk.py:274
#: ../debian/tmp/usr/share/apport/apport-gtk.py:289
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "У дадатку %s адбылася ўнутраная памылка."

#: ../gtk/apport-gtk.py:277 ../debian/tmp/usr/share/apport/apport-kde.py:223
#: ../kde/apport-kde.py:223 ../debian/tmp/usr/share/apport/apport-gtk.py:277
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "Дастасаванне %s нечакана зачынілася."

#: ../gtk/apport-gtk.py:299 ../debian/tmp/usr/share/apport/apport-kde.py:245
#: ../kde/apport-kde.py:245 ../debian/tmp/usr/share/apport/apport-gtk.py:299
msgid "Ignore future problems of this type"
msgstr "Ігнараваць такія праблемы ў будучыні"

#: ../gtk/apport-gtk.py:579 ../debian/tmp/usr/share/apport/apport-kde.py:289
#: ../kde/apport-kde.py:289 ../debian/tmp/usr/share/apport/apport-gtk.py:579
msgid "Hide Details"
msgstr "Схаваць падрабязнасці"

#: ../debian/tmp/usr/share/apport/apport-kde.py:234 ../kde/apport-kde.py:234
msgid "Leave Closed"
msgstr "Пакінуць зачыненым"

#: ../debian/tmp/usr/share/apport/apport-kde.py:235
#: ../debian/tmp/usr/share/apport/apport-kde.py:381 ../kde/apport-kde.py:235
#: ../kde/apport-kde.py:381
msgid "Relaunch"
msgstr "Перазапусціць"

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Username:"
msgstr "Імя карыстальніка:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:316 ../kde/apport-kde.py:316
msgid "Password:"
msgstr "Пароль:"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406 ../kde/apport-kde.py:406
msgid "Collecting Problem Information"
msgstr "Збор інфармацыі аб праблеме"

#: ../debian/tmp/usr/share/apport/apport-kde.py:408 ../kde/apport-kde.py:408
msgid "The collected information can be sent to the developers to improve the application. This might take a few minutes."
msgstr "Сабраную інфармацыю можна даслаць распрацоўшчыкам, каб палепшыць прыкладанне. Гэта можа заняць некалькі хвілін."

#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../kde/apport-kde.py:434
msgid "Uploading Problem Information"
msgstr "Перадача інфармацыі аб непаладцы"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:139
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:139
#: ../apport/ui.py:139
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:139
msgid "This package does not seem to be installed correctly"
msgstr "Падобна на тое, што гэты пакет усталяваны неправільна"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:144
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:144
#: ../apport/ui.py:144
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:144
#, python-format
msgid "This does not seem to be an official %s package. Please retry after updating the indexes of available packages, if that does not work then remove related third party packages and try again."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:166
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:166
#: ../apport/ui.py:166
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:166
#, python-format
msgid "You have some obsolete package versions installed. Please upgrade the following packages and check if the problem still occurs:\n\n"
"%s"
msgstr "У Вашай сістэме ўсталяваныя састарэўшыя версіі некаторых пакетаў. Абнавіце наступныя пакеты і праверце, ці засталася праблема:\n\n"
"%s"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:303
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:303
#: ../apport/ui.py:303
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:303
msgid "unknown program"
msgstr "невядомая праграма"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:304
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:304
#: ../apport/ui.py:304
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:304
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "Прабачце, праграма «%s» аварыйна завяршыла сваю работу"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1459
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1459
#: ../apport/ui.py:306 ../apport/ui.py:1459
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:306
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1459
#, python-format
msgid "Problem in %s"
msgstr "Праблема ў %s"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:307
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:307
#: ../apport/ui.py:307
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:307
msgid "Your computer does not have enough free memory to automatically analyze the problem and send a report to the developers."
msgstr "На Вашым кампутары недастаткова вольнай памяці для таго, каб аўтаматычна прааналізаваць няспраўнасць і даслаць справаздачу распрацоўшчыкам."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:370
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:519
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:522
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:727
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1264
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1431
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1435
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:370
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:519
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:522
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:727
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1264
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1431
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1435
#: ../apport/ui.py:362 ../apport/ui.py:370 ../apport/ui.py:519
#: ../apport/ui.py:522 ../apport/ui.py:727 ../apport/ui.py:1264
#: ../apport/ui.py:1431 ../apport/ui.py:1435
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:362
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:370
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:519
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:522
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:727
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1264
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1431
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1435
msgid "Invalid problem report"
msgstr "Няправільная справаздача аб памылцы"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:363
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:363
#: ../apport/ui.py:363
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:363
msgid "You are not allowed to access this problem report."
msgstr "У Вас не хапае правоў, каб паведамляць аб праблемах."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:366
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:366
#: ../apport/ui.py:366
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:366
msgid "Error"
msgstr "Памылка"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:367
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:367
#: ../apport/ui.py:367
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:367
msgid "There is not enough disk space available to process this report."
msgstr "Недастаткова месца на дыску для апрацоўкі дадзенай справаздачы."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:403
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:403
#: ../apport/ui.py:403
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:403
msgid "No PID specified"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:404
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:404
#: ../apport/ui.py:404
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:404
msgid "You need to specify a PID. See --help for more information."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:411
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:500
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:411
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:500
#: ../apport/ui.py:411 ../apport/ui.py:500
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:411
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:500
msgid "Invalid PID"
msgstr "Памылковы PID"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:412
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:412
#: ../apport/ui.py:412
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:412
msgid "The specified process ID does not exist."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:415
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:415
#: ../apport/ui.py:415
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:415
msgid "Not your PID"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:416
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:416
#: ../apport/ui.py:416
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:416
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:467
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:467
#: ../apport/ui.py:467
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:467
msgid "No package specified"
msgstr "Не пазначаны пакет"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:468
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:468
#: ../apport/ui.py:468
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:468
msgid "You need to specify a package or a PID. See --help for more information."
msgstr "Неабходна пазначыць пакет альбо PID. Запусціце праграму з параметрам --help каб атрымаць дадатковую інфармацыю."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:497
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:497
#: ../apport/ui.py:497
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:497
msgid "Permission denied"
msgstr "Доступ забаронены"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:498
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:498
#: ../apport/ui.py:498
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:498
msgid "The specified process does not belong to you. Please run this program as the process owner or as root."
msgstr "Пазначаны працэс запушчэны іншым карыстальнікам. Запусціце дадзеную праграму з правамі ўладальніка працэса альбо адміністратара сістэмы."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:501
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:501
#: ../apport/ui.py:501
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:501
msgid "The specified process ID does not belong to a program."
msgstr "Пазначаны PID належыць іншаму працэсу."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:520
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:520
#: ../apport/ui.py:520
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:520
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "Сімптаматычны скрыпт %s ня можа вызначыць закрануты пакет"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:523
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:523
#: ../apport/ui.py:523
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:523
#, python-format
msgid "Package %s does not exist"
msgstr "Пакет %s не існуе"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:739
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:744
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:739
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:744
#: ../apport/ui.py:552 ../apport/ui.py:739 ../apport/ui.py:744
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:552
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:739
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:744
msgid "Cannot create report"
msgstr "Нельга стварыць справаздачу"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:567
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:613
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:629
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:567
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:613
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:629
#: ../apport/ui.py:567 ../apport/ui.py:613 ../apport/ui.py:629
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:567
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:613
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:629
msgid "Updating problem report"
msgstr "Абнаўленне справаздачы аб праблеме"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:568
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:568
#: ../apport/ui.py:568
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:568
msgid "You are not the reporter or subscriber of this problem report, or the report is a duplicate or already closed.\n\n"
"Please create a new report using \"apport-bug\"."
msgstr "Вы не з'яўляецеся аўтарам альбо атрымальнікам гэтай справаздачы аб праблеме, магчыма яна ўжо існуе ці была зачыненая."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:577
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:577
#: ../apport/ui.py:577
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:577
msgid "You are not the reporter of this problem report. It is much easier to mark a bug as a duplicate of another than to move your comments and attachments to a new bug.\n\n"
"Subsequently, we recommend that you file a new bug report using \"apport-bug\" and make a comment in this bug about the one you file.\n\n"
"Do you really want to proceed?"
msgstr "Вы не з'яўляецеся стваральнікам дадзенай справаздачы. Нашмат прасцей, адзначыць памылку што яна ўжо існуе, чым ствараць свае каментары і ўкладаць іх у новую памылку\n\n"
"Пасля, мы рэкамендуем Вам падаць новае паведамленне аб памылцы выкарыстання \"памылка apport\", і зрабіць заўвагу аб гэтай памылцы ў тым жа файле.\n\n"
"Вы сапраўды хочаце працягнуць?"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:614
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:630
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:614
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:630
#: ../apport/ui.py:614 ../apport/ui.py:630
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:614
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:630
msgid "No additional information collected."
msgstr "Не сабрана ніякай дадатковай інфармацыі."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:681
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:681
#: ../apport/ui.py:681
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:681
msgid "What kind of problem do you want to report?"
msgstr "Пра які тып праблемы Вы хочаце паведаміць?"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:698
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:698
#: ../apport/ui.py:698
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:698
msgid "Unknown symptom"
msgstr "Невядомы сімптом"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:699
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:699
#: ../apport/ui.py:699
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:699
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Сімптом  \"%s\" невядомы."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:730
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:730
msgid "After closing this message please click on an application window to report a problem about it."
msgstr "Пасля закрыцця гэтага паведамлення, калі ласка, націсніце на вакно прыкладання, каб паведаміць аб праблеме."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:740
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:745
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:740
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:745
#: ../apport/ui.py:740 ../apport/ui.py:745
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:740
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:745
msgid "xprop failed to determine process ID of the window"
msgstr "xprop не ўдалося вызначыць ID працэсу акна"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:759
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:759
#: ../apport/ui.py:759
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:759
msgid "%prog <report number>"
msgstr "%prog <нумар справаздачы>"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:761
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:761
#: ../apport/ui.py:761
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:761
msgid "Specify package name."
msgstr "Пазначце імя пакета."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:763
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:815
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:763
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:815
#: ../apport/ui.py:763 ../apport/ui.py:815
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:763
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:815
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "Дадаць дадатковы тэг да справаздачы. Можа быць паказаны некалькі разоў."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:794
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:794
#: ../apport/ui.py:794
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:794
msgid "%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr "%prog [параметры] [прыкмета|pid|пакет|шлях да праграмы|.apport/.crash файл]"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:797
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:797
#: ../apport/ui.py:797
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:797
msgid "Start in bug filing mode. Requires --package and an optional --pid, or just a --pid. If neither is given, display a list of known symptoms. (Implied if a single argument is given.)"
msgstr "Запуск у рэжыме адпраўкі справаздачы аб памылцы. Патрабуе параметр --package і неабавязковы --pid, або толькі --pid. Калі параметры не перададзеныя, адлюстроўвае спіс вядомых сімптомаў. (Ужываецца, калі перададзены адзіны параметр.)"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:799
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:799
#: ../apport/ui.py:799
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:799
msgid "Click a window as a target for filing a problem report."
msgstr "Цокніце па намечаным акне каб запоўніць справаздачу аб праблеме."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:801
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:801
#: ../apport/ui.py:801
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:801
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "Запусціць у рэжыме абнаўлення памылкі. Можа прымаць дадатковы ключ - package."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:803
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:803
#: ../apport/ui.py:803
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:803
msgid "File a bug report about a symptom. (Implied if symptom name is given as only argument.)"
msgstr "Адправіць справаздачу аб памылцы з сімптомам. (Ужываецца, калі назва сімптома перададзена ў якасці адзінага параметра.)"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:805
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:805
#: ../apport/ui.py:805
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:805
msgid "Specify package name in --file-bug mode. This is optional if a --pid is specified. (Implied if package name is given as only argument.)"
msgstr "Пазначыць імя пакета ў рэжыме --file-bug. Неабавязкова, калі пазначаны --pid. (Ужываецца, калі імя пакета перададзена ў якасці адзінага праметра.)"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:807
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:807
#: ../apport/ui.py:807
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:807
msgid "Specify a running program in --file-bug mode. If this is specified, the bug report will contain more information.  (Implied if pid is given as only argument.)"
msgstr "Пазначце запушчаную праграму ў рэжыме - file-bug. У гэтым выпадку справаздача аб памылцы будзе ўтрымліваць больш інфармацыі. (Маецца на ўвазе, што пазначаны адзіны аргумент - pid.)"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:809
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:809
#: ../apport/ui.py:809
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:809
msgid "The provided pid is a hanging application."
msgstr "Згаданы ідэнтыфікатар належыць працэсу, які не адказвае."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:811
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:811
#: ../apport/ui.py:811
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:811
#, python-format
msgid "Report the crash from given .apport or .crash file instead of the pending ones in %s. (Implied if file is given as only argument.)"
msgstr "Адправіць дадзеныя аб збоі з азначанага файла .apport або .crash замест ччакаемых у %s. (Ужываецца, калі файл перададзены ў якасці адзінага параметра.)"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:813
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:813
#: ../apport/ui.py:813
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:813
msgid "In bug filing mode, save the collected information into a file instead of reporting it. This file can then be reported later on from a different machine."
msgstr "У рэжыме збору справаздачы аб памылках, сабраная інфармацыя захоўваецца ў файле замест яе адпраўкі. Гэты файл можна будзе адправіць пазней, ці з іншага кампутара."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:817
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:817
#: ../apport/ui.py:817
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:817
msgid "Print the Apport version number."
msgstr "Раздрукаваць нумар версіі Apport ."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:968
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:968
#: ../apport/ui.py:968
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:968
msgid "This will launch apport-retrace in a terminal window to examine the crash."
msgstr "Будзе ажыццёўлены запуск «apport-retrace» у акне тэрміналу для праверкі аварыйнага завяршэння працы."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:969
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:969
#: ../apport/ui.py:969
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:969
msgid "Run gdb session"
msgstr "Запусціць сеанс gdb"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:970
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:970
#: ../apport/ui.py:970
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:970
msgid "Run gdb session without downloading debug symbols"
msgstr "Запусціць сеанс gdb, абыходзячы загрузкі адладкавых сімвалаў"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:972
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:972
#: ../apport/ui.py:972
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:972
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Абнавіць %s з поўным адсочваннем сімвалічнага стэку"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1008
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1008
#: ../apport/ui.py:1008
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1008
msgid "Can't remember send report status settings"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1009
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1009
#: ../apport/ui.py:1009
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1009
msgid "Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1068
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1078
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1068
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1078
#: ../apport/ui.py:1068 ../apport/ui.py:1078
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1068
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1078
msgid "This problem report applies to a program which is not installed any more."
msgstr "Дадзеная справаздача адносіцца да праграмы, якая не ўсталявана."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1093
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1093
#: ../apport/ui.py:1093
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1093
#, python-format
msgid "The problem happened with the program %s which changed since the crash occurred."
msgstr "Праблема ў праграме %s, да якой былі ўнесены змены з моманту аварыйнага завяршэння яе работы."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1140
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1221
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1437
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1140
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1221
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1437
#: ../apport/ui.py:1140 ../apport/ui.py:1221 ../apport/ui.py:1437
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1140
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1221
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1437
msgid "This problem report is damaged and cannot be processed."
msgstr "Дадзеная справаздача аб непаладцы пашкоджана і не можа апрацоўвацца."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1145
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1145
#: ../apport/ui.py:1145
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1145
msgid "This report is about a package that is not installed."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1149
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1149
#: ../apport/ui.py:1149
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1149
msgid "An error occurred while attempting to process this problem report:"
msgstr "Адбылася памылка пры спробе апрацоўкі справаздачы:"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1159
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1159
#: ../apport/ui.py:1159
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1159
msgid "You have two versions of this application installed, which one do you want to report a bug against?"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1160
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1160
#: ../apport/ui.py:1160
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1160
#, python-format
msgid "%s snap"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1161
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1161
#: ../apport/ui.py:1161
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1161
#, python-format
msgid "%s deb package"
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1194
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1194
#: ../apport/ui.py:1194
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1194
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1196
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1196
#: ../apport/ui.py:1196
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1196
#, python-format
msgid "%s is provided by a snap published by %s. No contact address has been provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1265
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1265
#: ../apport/ui.py:1265
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1265
msgid "Could not determine the package or source package name."
msgstr "Немагчыма вызначыць імя пакету альбо крыніцы."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1283
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1283
#: ../apport/ui.py:1283
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1283
msgid "Unable to start web browser"
msgstr "Не атрымалася запусціць вэб-браўзэр"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1284
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1284
#: ../apport/ui.py:1284
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1284
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Немагчыма запусціць вэб-браўзэр, каб адчыніць %s."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1385
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1385
#: ../apport/ui.py:1385
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1385
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr "Калі ласка, увядзіце інфармацыю аб уліковым запісы для %s  сістэмы сачэння за памылкамі"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1397
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1397
#: ../apport/ui.py:1397
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1397
msgid "Network problem"
msgstr "Праблема з сеткай"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1399
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1399
#: ../apport/ui.py:1399
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1399
msgid "Cannot connect to crash database, please check your Internet connection."
msgstr "Не атрымоўваецца падлучыцца да базы дадзеных па збоях, калі ласка, праверце падлучэнне да Інтэрнэту."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1426
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1426
#: ../apport/ui.py:1426
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1426
msgid "Memory exhaustion"
msgstr "Нястача памяці"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1427
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1427
#: ../apport/ui.py:1427
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1427
msgid "Your system does not have enough memory to process this crash report."
msgstr "У сістэме недастаткова памяці для апрацоўкі дадзенай справаздачы аб памылцы."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1462
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1462
#: ../apport/ui.py:1462
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1462
#, python-format
msgid "The problem cannot be reported:\n\n"
"%s"
msgstr "Немагчыма паведаміць аб праблеме:\n\n"
"%s"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1518
#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1525
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1518
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1525
#: ../apport/ui.py:1518 ../apport/ui.py:1525
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1518
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1525
msgid "Problem already known"
msgstr "Праблема ўжо вядомая"

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1519
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1519
#: ../apport/ui.py:1519
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1519
msgid "This problem was already reported in the bug report displayed in the web browser. Please check if you can add any further information that might be helpful for the developers."
msgstr "Аб дадзенай няспраўнасці ўжо вядома. Існуючая справаздача аб ёй адкрыта ў Вашым браўзэры. Калі ласка, праверце, ці можаце Вы дадаць да яе карысную інфармацыю, якая магла бы дапамагчы распрацоўшчыкам."

#: ../debian/tmp/usr/lib/python3.10/dist-packages/apport/ui.py:1526
#: ../debian/tmp/usr/lib/python3.9/dist-packages/apport/ui.py:1526
#: ../apport/ui.py:1526
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1526
msgid "This problem was already reported to developers. Thank you!"
msgstr "Аб гэтай праблеме распрацоўнікам ужо вядома. Дзякуй!"

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Выкарыстанне: %s <справаздача> <тэчка прызначэння>"

#: ../bin/apport-unpack.py:42 ../debian/tmp/usr/bin/apport-unpack.py:42
msgid "Destination directory exists and is not empty."
msgstr "Тэчка прызначэння існуе і яна не пустая."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
#: ../data/apportcheckresume.py:67
msgid "This occurred during a previous suspend, and prevented the system from resuming properly."
msgstr "Гэта адбылося падчас папярэдняга сеансу прыпынення працы і прывяло да немагчымасці належнага аднаўлення працы сістэмы."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
#: ../data/apportcheckresume.py:69
msgid "This occurred during a previous hibernation, and prevented the system from resuming properly."
msgstr "Гэта адбылося падчас папярэдняга сеансу ўсыплення і прывяло да немагчымасці належнага аднаўлення працы сістэмы."

#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
#: ../data/apportcheckresume.py:74
msgid "The resume processing hung very near the end and will have appeared to have completed normally."
msgstr "Адбылася памылка ў працэсе стварэння справаздачы, бо сам працэс завіс перад сваім завяршэннем; для нармальнага завяршэння ён павінен быў з'явіцца."

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Сабраць сістэмную інфармацыю"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid "Authentication is required to collect system information for this problem report"
msgstr "Трэба даць права, каб сабраць патрэбныя дадзеныя для справаздачнасці гэтай праблемы"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Справаздачы аб сістэмных памылках"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr "Калі ласка, увядзіце пароль для доступу да справаздач пра памылкі ў сістэмных праграмах"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Файл справаздачы Apport"

